### ISSUE TITLE
Connection to HAP

### ISSUE THREAD

**Issue by legotheboss** [KhaosT/HAP-NodeJS#100]
I have multiple devices that are paired to my HAP setup. On iOS 9 beta 3, only 1 device can connect to the HAP server at a time. System logs don't show any errors and HAP doesn't show any connection attempt either.

**Comment by KhaosT** [comment]
That's strange, are you using latest commit?

**Comment by legotheboss** [comment]
@KhaosT It fixed itself after an update to iOS 9 b4. Looks like something in beta 3 was messing up. After I upgraded both my devices to b4, the issue disappeared.

**Comment by KhaosT** [comment]
nice to know :)
