### ISSUE TITLE
add humidity and temperature sensor services

### ISSUE THREAD

**Issue by justme-1968** [KhaosT/HAP-NodeJS#101]
please add the following two services to types.js:

exports.HUMIDITY_SENSOR_STYPE = stPre + "82" + stPost;
exports.TEMPERATURE_SENSOR_STYPE = stPre + "8A" + stPost;

thanks
  andre

**Comment by KhaosT** [comment]
Can you send a pull request?

Best Wishes,
Tian Zhang
