### ISSUE TITLE
rename window characteristics

### ISSUE THREAD

**Issue by justme-1968** [KhaosT/HAP-NodeJS#109]
the three characteristics WINDOW_COVERING_TARGET_POSITION_CTYPE, WINDOW_COVERING_CURRENT_POSITION_CTYPE and WINDOW_COVERING_OPERATION_STATE_CTYPE should probable renamed to just WINDOW_... (without the COVERING_) as these are also used by the window service class to open and close windows.

i'dont know if they are already used and it would be a problem for backwards compatibility.

the window service type would be: exports.WINDOW_STYPE = stPre + "8B" + stPost;

**Comment by nfarina** [comment]
This should be closed by #110 (all known services/characteristics are extracted from HomeKit Simulator and provided in HomeKitTypes.js).
