### ISSUE TITLE
bignum.cc Error Cannot open include file: 'openssl/bn.h'

### ISSUE THREAD

**Issue by nzhome** [KhaosT/HAP-NodeJS#112]
..\bignum.cc(9): fatal error C1083: Cannot open include file: 'openssl/bn.h': No such file or directory [C:\Program Files\nodejs\node_modules\homebridge-master\node_modules\HAP-NodeJS\node_modules\srp\node_modules\bignum\build\bignum.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Windows_NT 6.1.7600
gyp ERR! command "node" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "build"
gyp ERR! cwd C:\Program Files\nodejs\node_modules\homebridge-master\node_modules\HAP-NodeJS\node_modules\srp\node_modules\bignum
gyp ERR! node -v v0.12.7

**Comment by KhaosT** [comment]
SRP module requires OpenSSL and I don't think your Windows has that... Please make sure you installed OpenSSL dev and build again. (I never tried to build/use this project on Windows so I'm not sure if it will work or not...)

**Comment by nzhome** [comment]
solved. thanks.  https://github.com/justmoon/node-bignum/issues/32
