### ISSUE TITLE
Node 4.0.0 compatibility

### ISSUE THREAD

**Issue by volschin** [KhaosT/HAP-NodeJS#129]
At the moment HAP-NodeJS doesn't build with node v4.0.0 on the raspberry pi.

Problematic modules seem to be begnum, ed25519 and curve25519.

**Comment by volschin** [comment]
I have submitted pull requests for 
- node-srp regarding bignum
- curve25519 regarding nan v2 changes.

ed25519 I have no fix for yet. Also nan v2 topic but a little bit more complex.

**Comment by volschin** [comment]
Updated dependencies for the already submitted PRs.
```json
  "dependencies": {
    "curve25519": "git://github.com/thejh/node-curve25519#274b3aa",
    "debug": "^2.2.0",
    "ed25519": "git://github.com/dazoe/ed25519",
    "mdns": "^2.2.10",
    "node-persist": "0.0.3",
    "srp": "git://github.com/KhaosT/node-srp#e4165e3"
  },
```

**Comment by volschin** [comment]
ed25519 got a PR we can test.
But the maintainer of curve25519 says he is not working with nodejs and the repository is abandoned.
@KhaosT He suggests using libsodium instead. Other way you could fork and integrate my changes.

**Comment by KhaosT** [comment]
@volschin There were some issues with libsodium last time when I try to integrate it with the project. I forked your curve25519 repo and updated the dependency of the project (Thanks ^^). For ed25519, if they didn't merge the PR by the end of this week, I'll try to fork and apply the PR.

**Comment by volschin** [comment]
This one builds fine with node 4.0
```json
  "dependencies": {
    "curve25519": "git://github.com/volschin/node-curve25519",
    "debug": "^2.2.0",
    "ed25519": "git://github.com/KenanSulayman/ed25519.git",
    "mdns": "^2.2.10",
    "node-persist": "0.0.3",
    "srp": "git://github.com/KhaosT/node-srp"
  },
```

Not tested yet, I don't know if the changes are backward compatible.

**Comment by cflurin** [comment]
Trying to install node 4.0.0 on a RPi 2 (4.1.6-v7+ #810) I've missing 2 files:
```
node -v
node: /usr/lib/arm-linux-gnueabihf/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by node)
node: /lib/arm-linux-gnueabihf/libc.so.6: version `GLIBC_2.16' not found (required by node)
```
I also upgraded GCC according to [ http://node-arm.herokuapp.com/  Option 1 ] without success.
Any idea?

**Comment by dannybloe** [comment]
I had exactly the same errors with my RPi B+ when I tried to install latest node through apt-get install node. I spent a couple of hours trying to fix this but I didn't succeed. Then I installed an old node using apt-get install nodejs, then installed an old npm (sudo apt-get install npm) and 'n' (npm install -g n) and then used n to get to the latest node (sudo n stable).

**Comment by volschin** [comment]
You cannot use a rasbian Standard package, because there isn't one. It seems you need to update to jessie before installing node 4.0

**Comment by cflurin** [comment]
@dannybloe: I've downloaded and installed v0.12.6.
@volschin: Just now I prefer to use the official Raspbian Wheezy.

I'll upgrade later to 4.0.0.

**Comment by cflurin** [comment]
@nfarina: there'll be troubles with node 4.0.0 installing homebridge on a new RPi according to the wiki. See the post above.

**Comment by nfarina** [comment]
@cflurin Will following the wiki instructions get you a version of Node (4.0.0) that doesn't work?

**Comment by cflurin** [comment]
@nfarina: that's right! I had to uninstall node v4.0.0 and install v0.12.6.

**Comment by nfarina** [comment]
Damn. Added a note to the wiki for now.

**Comment by cflurin** [comment]
Thanks, I also got the new node v4.0.0 installed on a old RPi with:
```
sudo apt-get dist-upgrade
```
```

**Comment by KhaosT** [comment]
@volschin now the master can build and run on Node 4.0.0

**Comment by luxus** [comment]
does homebridge need some changes in there source? i can't install it at the moment :( errors about curve25519 and ed25519

**Comment by volschin** [comment]
curve25519 and ed25519 are fixed. You probably don't have the most recent version.

**Comment by nfarina** [comment]
Need to bump the version of HAP-NodeJS in Homebridge's `package.json`. Working on that now

**Comment by luxus** [comment]
try to compile with the version at this moment

**Comment by volschin** [comment]
It makes no sense to discuss homebridge issues in this HAP-NodeJS issue that is closed now.
