### ISSUE TITLE
Cannot find module 'srp'

### ISSUE THREAD

**Issue by mvahanen** [KhaosT/HAP-NodeJS#130]
Hi,

I'm trying to run node Core.js but its not work. Here is screenshot.
I have node -v 0.10.25 and npm -v 1.3.10

![untitled](https://cloud.githubusercontent.com/assets/10205046/9903917/86f39d5e-5c82-11e5-9225-d04065b1f5df.png)

**Comment by snowdd1** [comment]
Did you try an `npm update` to install the dependencies?
And your node version seems rather old.

**Comment by mvahanen** [comment]
I change git:// to https:// on package.json and now i can install srp. I also update node.

**Comment by Lightsonplease** [comment]
I've **exactly** the same error, but the solution "npm update" will not solve the error. What exactly did you change Ghost? 

Thanks for any comment!
