### ISSUE TITLE
Siri: Blinds?

### ISSUE THREAD

**Issue by snowdd1** [KhaosT/HAP-NodeJS#136]
Did anyone get Siri to recognize the WindowCovering service type? I can control it via EVE, but Siri's giving me the bird all the time, and in all languages I tried:

English - US: "Close the blinds" - "I wasn't able to find any devices this time"
German: "Schließe die Jalousien im Arbeitszimmer" - "Ich kann keine Jalousien im Bereich Arbeitszimmer finden"

Was anybody more successful in that?

**Comment by justme-1968** [comment]
ah... i thought it was only a problem in german. siri even recognizes the german 'rolladen' and then answers it can not find any 'jalousien'. so it recognizes what is meant. i have even opened a developer bug report with apple but got no feedback at all :)

very strange.

**Comment by firsttris** [comment]
same problem here

**Comment by cflurin** [comment]
There is a workaround using scenes in EVE.
Define a scene like the build in one "Good morning" and set the window covering position to 0 or what you like. "Hey Siri, good morning" will set the position and answer "Your wish is my command. And Io, Good morning!"

**Comment by snowdd1** [comment]
Cool, but has its draw backs: I just tried and Siri said: (translated) "good morning? It's 9:47pm!"

**Comment by firsttris** [comment]
try to make a custom scene like "jalousien runter"(german). worked for me ;)

**Comment by cflurin** [comment]
@snowdd1: Sorry it should be "Hey Siri, set good morning" or you can define a new scene.

**Comment by snowdd1** [comment]
Still quite uncomfortable for about 20 blinds, at least if I want to control them separately. Otherwise I could have used a switch-like scene set mechanism in my home server.

I think Apple will fix that as soon as the first MFI manufacturer comes with the first certified blinds controller.

**Comment by cflurin** [comment]
My blinds are controlled by several conditions and time-settings. In the morning I have rarely to talk to Siri, probably Siri wouldn't unterstand me anyway :smile:

**Comment by snowdd1** [comment]
That is true for my home as well, but I have some blinds left that I control by wall mounted switch right now. It would have been nice to be able to control all of them by Siri and not having workarounds for up/down or percentages. 

No changes with 9.0.1 which I updated to just an hour ago.

**Comment by lilalinux** [comment]
Thank you! At least there is a workaround for the shutters.

BTW: Does anoybody else have the problem, that all accessory is grayed out every few hours/days and have to be re-paired?

**Comment by KhaosT** [comment]
@lilalinux I never see something like that... My bridge has been running fine for at least 6 weeks. What's the platform you're running the bridge?

**Comment by lilalinux** [comment]
Linux infrastructure 3.19.0-28-generic #30-Ubuntu SMP Mon Aug 31 15:52:51 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
The symptom is the same as #52 
I'm using it together with https://github.com/htreu/OpenHAB-HomeKit-Bridge
It worked fine a few days now, but today I created rooms and scenes and some hours later it broke.
The server is still fine, if I unpair, I can re-pair and it works again. I guess it's an iOS issue.

**Comment by KhaosT** [comment]
@lilalinux under that circumstance, does reboot iOS device fix the issue?

**Comment by lilalinux** [comment]
Unfortunately not. The frustrating thing is, that it alway happens, after the time comsuming configuring of rooms and scenes. The last days it worked I had 1 scene and 0 rooms. Today I added all rooms and 10 scenes (for the blinds)

**Comment by KhaosT** [comment]
@lilalinux That's so strange, next time when this happens, can you try to grab HomeKit logs from iOS device? For how to get logs from iOS device, you can follow instruction at [here](https://www.chromium.org/developers/how-tos/retrieving-crash-reports-on-ios). HomeKit log located under ./Diagnostics/HomeKit...

**Comment by lilalinux** [comment]
BTW: also my Properties.app crashes a lot since iOS9

**Comment by desvdp** [comment]
@lilalinux  I had a similar issue where the devices would grey out after a limited time (hours .. day). Since then I replaced my switch with a real dump one, the issue is gone now. Our guess is it has to do with the mdns broadcast packages not being sent around as they should. I'm not 100% sure this is the root cause, but it's worth looking at it... 

see: https://github.com/nfarina/homebridge/issues/11

**Comment by lilalinux** [comment]
I see. So you think it would be more related to https://github.com/htreu/OpenHAB-HomeKit-Bridge than HAP-NodeJS or iOS?

**Comment by desvdp** [comment]
@lilalinux actually I believe that project is a fork of HAP-Nodejs, so that's one and the same or at least similar. If (and I say if) it is related to mdns it has possibly has to do with your network infrastructure not being able broadcast the mdns packets reliably, not as such with HAP or iOS itself...

**Comment by lilalinux** [comment]
I can see the Bridge still in e.g. NetExplorer for iOS

**Comment by lilalinux** [comment]
This time, a restart of the bridge worked without deleting/repairing.

**Comment by snowdd1** [comment]
This deviated somewhat from the original topic...
