### ISSUE TITLE
HAP tunneling

### ISSUE THREAD

**Issue by snowdd1** [KhaosT/HAP-NodeJS#137]
Did anyone have a glimpse of the HAP tunneling specs?
I am wondering when Apple TV tunnel ceases working, which I heard it did never reliably.

**Comment by KhaosT** [comment]
HAP Tunneling for BLE is an accessory side protocol enhancement, it has nothing to do with Apple TV… Do you mean Remote Access via Apple TV?

**Comment by snowdd1** [comment]
You're right, I meant remote access.
I assume that with the tunneling feature, the accessories have to keep an "outside line" open all the time, and so enabling iCloud to contact them. Other than that I would not understand how iCloud would be able to pass the firewalls (or at least the NAT of the routers most of us have)

**Comment by snowdd1** [comment]
But I did not mean the tunnel for BLE, but the outside tunnel for remote access that was mentioned in the Session 210 of this summer's WWDC: https://developer.apple.com/videos/wwdc/2015/?id=210 rather at the end.

**Comment by luxus** [comment]
i watched the video as well and was wondering if homebridge/HAP-NodeJS will support the iCloud remote access

**Comment by KhaosT** [comment]
Aha, you mean the Remote Access via iCloud... That feature requires having a MFi chip which I believe most of people using this project won't have access to so this project won't support that feature.

**Comment by luxus** [comment]
just one last question.. from my understanding.. if i have one device with a mfi chip my will make homebridge available in the outside world as well?

**Comment by KhaosT** [comment]
@luxus There are extra things that accessory needs to do to support HAP over iCloud, but yes, it's possible for homebridge to support that.
