### ISSUE TITLE
How to add outlet and switch accessories

### ISSUE THREAD

**Issue by gjniewenhuijse** [KhaosT/HAP-NodeJS#143]
I see different examples in the accessories dir, but how to add an outlet and a switch?

**Comment by cflurin** [comment]
Hi,
For Homebridge - which is based on HAP-NodeJS-  there are several examples [here](https://github.com/cflurin/homebridge-shims)

**Comment by snowdd1** [comment]
For [homebridge](https://Github.com/nfarina/homebridge) there are even some wiki pages available.
You should check whether the accessories you have are already covered by an available shim for homebridge. You probably won't have to invent the wheel again.
