### ISSUE TITLE
Problem With NPM on Windows 10

### ISSUE THREAD

**Issue by Tetragramato** [KhaosT/HAP-NodeJS#146]
Hi, i try to install the module from Node JS 4 on Windows 10, and get following error : 
Failed at the curve25519@1.1.0 install script 'node-gyp rebuild'.

I followed instructions from node-gyp (have Python 2.7.3) and install it without success.

I saw some people with same problems (see the nfarina Homebridge project), without resolution.

Do you have some ideas ?

Thanks a lot.

Here part of the install log : 

1704 info ed25519@0.0.3 Failed to exec install script
1705 verbose unsafe-perm in lifecycle true
1706 verbose unlock done using C:\Users\tetragramato\AppData\Roaming\npm-cache\_locks\ed25519-8badc943ed317dd1.lock for D:\developpement\node_modules\hap-nodejs\node_modules\ed25519
1707 info mdns@2.2.10 Failed to exec install script
1708 verbose unsafe-perm in lifecycle true
1709 verbose unlock done using C:\Users\tetragramato\AppData\Roaming\npm-cache\_locks\mdns-0b6a45879afe0439.lock for D:\developpement\node_modules\hap-nodejs\node_modules\mdns
1710 info bignum@0.11.0 Failed to exec install script
1711 verbose unlock done using C:\Users\tetragramato\AppData\Roaming\npm-cache\_locks\bignum-c272c3e0c7b85cba.lock for D:\developpement\node_modules\hap-nodejs\node_modules\srp\node_modules\bignum
1712 verbose about to build D:\developpement\node_modules\hap-nodejs\node_modules\srp
1713 verbose unlock done using C:\Users\tetragramato\AppData\Roaming\npm-cache\_locks\srp-7e7b3154dfc378b4.lock for D:\developpement\node_modules\hap-nodejs\node_modules\srp
1714 verbose about to build D:\developpement\node_modules\hap-nodejs
1715 verbose unlock done using C:\Users\tetragramato\AppData\Roaming\npm-cache\_locks\hap-nodejs-ffc805aaf5475105.lock for D:\developpement\node_modules\hap-nodejs
1716 verbose stack Error: curve25519@1.1.0 install: `node-gyp rebuild`
1716 verbose stack Exit status 1
1716 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:214:16)
1716 verbose stack     at emitTwo (events.js:87:13)
1716 verbose stack     at EventEmitter.emit (events.js:172:7)
1716 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
1716 verbose stack     at emitTwo (events.js:87:13)
1716 verbose stack     at ChildProcess.emit (events.js:172:7)
1716 verbose stack     at maybeClose (internal/child_process.js:818:16)
1716 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
1717 verbose pkgid curve25519@1.1.0
1718 verbose cwd D:\developpement
1719 error Windows_NT 10.0.10240
1720 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "HAP-NodeJS"
1721 error node v4.1.2
1722 error npm  v2.14.4
1723 error code ELIFECYCLE
1724 error curve25519@1.1.0 install: `node-gyp rebuild`
1724 error Exit status 1
1725 error Failed at the curve25519@1.1.0 install script 'node-gyp rebuild'.
1725 error This is most likely a problem with the curve25519 package,
1725 error not with npm itself.
1725 error Tell the author that this fails on your system:
1725 error     node-gyp rebuild
1725 error You can get their info via:
1725 error     npm owner ls curve25519
1725 error There is likely additional logging output above.
1726 verbose exit [ 1, true ]
1727 verbose unbuild node_modules\hap-nodejs\node_modules\curve25519
1728 info preuninstall curve25519@1.1.0
1729 info uninstall curve25519@1.1.0
1730 verbose unbuild rmStuff curve25519@1.1.0 from D:\developpement\node_modules
1731 verbose unbuild rmStuff in D:\developpement\node_modules\hap-nodejs\node_modules
1732 info postuninstall curve25519@1.1.0
1733 silly gentlyRm D:\developpement\node_modules\hap-nodejs\node_modules\curve25519 is being purged from base D:\developpement
1734 verbose gentlyRm don't care about contents; nuking D:\developpement\node_modules\hap-nodejs\node_modules\curve25519
1735 silly vacuum-fs purging D:\developpement\node_modules\hap-nodejs\node_modules\curve25519
1736 silly vacuum-fs quitting because other entries in D:\developpement\node_modules\hap-nodejs\node_modules
1737 verbose unbuild node_modules\hap-nodejs\node_modules\ed25519
1738 info preuninstall ed25519@0.0.3
1739 info uninstall ed25519@0.0.3
1740 verbose unbuild rmStuff ed25519@0.0.3 from D:\developpement\node_modules
1741 verbose unbuild rmStuff in D:\developpement\node_modules\hap-nodejs\node_modules
1742 info postuninstall ed25519@0.0.3
1743 silly gentlyRm D:\developpement\node_modules\hap-nodejs\node_modules\ed25519 is being purged from base D:\developpement
1744 verbose gentlyRm don't care about contents; nuking D:\developpement\node_modules\hap-nodejs\node_modules\ed25519
1745 silly vacuum-fs purging D:\developpement\node_modules\hap-nodejs\node_modules\ed25519
1746 silly vacuum-fs quitting because other entries in D:\developpement\node_modules\hap-nodejs\node_modules
1747 verbose unbuild node_modules\hap-nodejs\node_modules\mdns
1748 info preuninstall mdns@2.2.10
1749 info uninstall mdns@2.2.10
1750 verbose unbuild rmStuff mdns@2.2.10 from D:\developpement\node_modules
1751 verbose unbuild rmStuff in D:\developpement\node_modules\hap-nodejs\node_modules
1752 info postuninstall mdns@2.2.10
1753 silly gentlyRm D:\developpement\node_modules\hap-nodejs\node_modules\mdns is being purged from base D:\developpement
1754 verbose gentlyRm don't care about contents; nuking D:\developpement\node_modules\hap-nodejs\node_modules\mdns
1755 silly vacuum-fs purging D:\developpement\node_modules\hap-nodejs\node_modules\mdns
1756 silly vacuum-fs quitting because other entries in D:\developpement\node_modules\hap-nodejs\node_modules
1757 verbose unbuild node_modules\hap-nodejs\node_modules\srp\node_modules\bignum
1758 info preuninstall bignum@0.11.0
1759 info uninstall bignum@0.11.0
1760 verbose unbuild rmStuff bignum@0.11.0 from D:\developpement\node_modules
1761 verbose unbuild rmStuff in D:\developpement\node_modules\hap-nodejs\node_modules\srp\node_modules
1762 info postuninstall bignum@0.11.0
1763 silly gentlyRm D:\developpement\node_modules\hap-nodejs\node_modules\srp\node_modules\bignum is being purged from base D:\developpement
1764 verbose gentlyRm don't care about contents; nuking D:\developpement\node_modules\hap-nodejs\node_modules\srp\node_modules\bignum
1765 silly vacuum-fs purging D:\developpement\node_modules\hap-nodejs\node_modules\srp\node_modules\bignum
1766 silly vacuum-fs removing D:\developpement\node_modules\hap-nodejs\node_modules\srp\node_modules
1767 silly vacuum-fs quitting because other entries in D:\developpement\node_modules\hap-nodejs\node_modules\srp
1768 verbose unbuild node_modules\hap-nodejs\node_modules\srp
1769 info preuninstall srp@0.2.0
1770 info uninstall srp@0.2.0
1771 verbose unbuild rmStuff srp@0.2.0 from D:\developpement\node_modules
1772 verbose unbuild rmStuff in D:\developpement\node_modules\hap-nodejs\node_modules
1773 info postuninstall srp@0.2.0
1774 silly gentlyRm D:\developpement\node_modules\hap-nodejs\node_modules\srp is being purged from base D:\developpement
1775 verbose gentlyRm don't care about contents; nuking D:\developpement\node_modules\hap-nodejs\node_modules\srp
1776 silly vacuum-fs purging D:\developpement\node_modules\hap-nodejs\node_modules\srp
1777 silly vacuum-fs quitting because other entries in D:\developpement\node_modules\hap-nodejs\node_modules
1778 verbose unbuild node_modules\hap-nodejs
1779 info preuninstall hap-nodejs@0.0.2
1780 info uninstall hap-nodejs@0.0.2
1781 verbose unbuild rmStuff hap-nodejs@0.0.2 from D:\developpement\node_modules
1782 info postuninstall hap-nodejs@0.0.2
1783 silly gentlyRm D:\developpement\node_modules\hap-nodejs is being purged from base D:\developpement
1784 verbose gentlyRm don't care about contents; nuking D:\developpement\node_modules\hap-nodejs
1785 silly vacuum-fs purging D:\developpement\node_modules\hap-nodejs
1786 silly vacuum-fs removing D:\developpement\node_modules
1787 silly vacuum-fs finished vacuuming up to D:\developpement

**Comment by KhaosT** [comment]
@Tetragramato someone figured out [a way](https://github.com/nfarina/homebridge/wiki/Install-homebridge-on-Windows) to install this on Windows Machine
