### ISSUE TITLE
Characteristic.CurrentTemperature and negative values

### ISSUE THREAD

**Issue by stipus** [KhaosT/HAP-NodeJS#147]
In gen/HomeKitTypes.js the CurrentTemperature characteristic is defined as:

Characteristic.CurrentTemperature = function() {
  Characteristic.call(this, 'Current Temperature', '00000011-0000-1000-8000-0026BB765291');
  this.setProps({
    format: Characteristic.Formats.FLOAT,
    unit: Characteristic.Units.CELSIUS,
    maxValue: 100,
    minValue: 0,
    minStep: 0.1,
    perms: [Characteristic.Perms.READ, Characteristic.Perms.NOTIFY]
  });
  this.value = this.getDefaultValue();
};

I have been working on a Homebridge platform that supports temperature sensors, and I found the temperature always read 0.0°C in HomeKit applications when it's a negative temperature.

Negative temperatures in celsius are very common, especially in winter.

I changed the minValue to -100 in HomeKitTypes.h and then it worked !

Characteristic.CurrentTemperature = function() {
  Characteristic.call(this, 'Current Temperature', '00000011-0000-1000-8000-0026BB765291');
  this.setProps({
    format: Characteristic.Formats.FLOAT,
    unit: Characteristic.Units.CELSIUS,
    maxValue: 100,
    minValue: -100,
    minStep: 0.1,
    perms: [Characteristic.Perms.READ, Characteristic.Perms.NOTIFY]
  });
  this.value = this.getDefaultValue();
};

**Comment by KhaosT** [comment]
@stipus Application should override minValue if the value it tries to display is lower than default minValue. The current min/maxValue are generated from Apple's HomeKit Accessory Simulator.

**Comment by stipus** [comment]
OK I understand. I'm going to search how to override minValue from the Homebridge platform.

**Comment by KhaosT** [comment]
@stipus just do a ``characteristic.minValue = targetMinValue`` and it should work :)

**Comment by stipus** [comment]
Thanks a lot for your fast answers :)
Best regards,
stipus

**Comment by andig** [comment]
@stipus do you have an example how to do this dynamically from inside a plugin when it encounters min/max values being exceedee?

**Comment by stipus** [comment]
I did what KhaosT explained during accessory creation. No problem since then.
Best regards,
stipus

**Comment by NorthernMan54** [comment]
After watching this discussion I made this change to my plugin homebridge-dht and homebridge-mcuiot, and it works fine.  I even did a test run in the freezer with one sensor.  I added the min and max as part of defining the accessory.

                this.temperatureService = new Service.TemperatureSensor(this.name);
                this.temperatureService
                    .getCharacteristic(Characteristic.CurrentTemperature)
                    .setProps({
                        minValue: -100,
                        maxValue: 100
                    })
                    .on('get', this.getTemperature.bind(this));

**Comment by Kosta-Github** [comment]
After the switch to `TypeScript` the method signature for `setProps()` needs to change from:
```
  setProps = (props: CharacteristicProps) => { ... }
```
to
```
  setProps = (props: Partial<CharacteristicProps>) => { ... }
```
since you just want to override some `props` and don't want to be required to pass in all `props`, right?
