### ISSUE TITLE
Accessories can be found only once during Add-procedure (Core.js)

### ISSUE THREAD

**Issue by futuretec** [KhaosT/HAP-NodeJS#150]
Hey there,

I experienced some unreliability issues while using 2 GarageDoorOpener accessories with Core.js

Unfortunately once the accessories were added (e.g. to one device via HMCatalog), it can't be found by any other device anymore. Controls work fine and reliable on this one device.
Only help --> remove the "persist" directory and clear the HomeKit data from the device.

Interesting thing is e.g. if you configure the accessories on two iPhones simultaneously it works. But if you try to add another "consumer" to this a minute later -> no accessories appear in the menu.

(I tested this behavior several times)
Any thoughts on this?

**Comment by KhaosT** [comment]
@futuretec this is designed by HomeKit due to security reason. To give access accessory to another user, please share the home to the other account if you want to use those accessories with multiple users.

**Comment by futuretec** [comment]
@KhaosT 
thanks for the reply.
In that case I don't understand how it is even possible to add the accessories on multiple devices without using the "share home" functionality.
But thanks anyway - I will try to add the devices on one iPhone and share it with other users.
