### ISSUE TITLE
Question: can characteristics be triggered by code?

### ISSUE THREAD

**Issue by GorkaMM** [KhaosT/HAP-NodeJS#151]
Hello KhaosT,

First of all, thank you for this great implementation of HAP. I'm using it in my Raspberry Pi and I wanted to use, apart from HomeKit with Siri, a bluetooth device to detect when I'm home or I leave to turn lights on or off, but for this I would have to trigger state changes by a NodeJS app and I can't figure out the way to do it. Should I implement a HomeKit client and make it trigger changes through the normal HTTP API or could I use any of your functions reliably?

Thank you a lot!

**Comment by KhaosT** [comment]
@GorkaMM HomeKit in iOS 9 introduces Event Trigger which supports setting CLBeaconRegion as event. If you can configure your bluetooth device to act as iBeacon, then you can setup an event trigger to turn on/off the lights when you enter/leave the region.

**Comment by GorkaMM** [comment]
That's great! Thank you, @KhaosT, I'll try with it.
By the way, in case I want to do more complex things, do you know if there's a way to trigger any characteristic change programatically?

Thank you a lot!

**Comment by KhaosT** [comment]
You mean on the accessory side? You can have the accessory to host a HTTP server and invoke characteristic set value in request handler.

**Comment by GorkaMM** [comment]
Yes, I mean having another node script running in the same machine as the HomeKit accessory that is able to change the state of characteristics as Siri would do, for example, so I could perform these state changes by code, preferably using a more simple solution than the HTTP API of HAP.

Is there simple solution of doing this without implementing a complete HomeKit client in Node to talk to the API?

Thank you a lot!

**Comment by KhaosT** [comment]
@GorkaMM I mean you can use [net](https://nodejs.org/api/net.html) library to create a simple socket server and accept command on the local machine to modify the characteristic without using HomeKit API at all.

**Comment by GorkaMM** [comment]
Implementing it inside the accesory (Light accesory, Fan accesory...) itself you mean? Sounds very good! I'm gonna try it.

Thank you!
