### ISSUE TITLE
Cannot use different pin code

### ISSUE THREAD

**Issue by michbeck100** [KhaosT/HAP-NodeJS#156]
It seems that it's not possible to change the default pin code 031-45-154. I tried different values like 123-45-678, but when i try to pair my iOS device it says, that the pin code is wrong. 
I did change the pin code in BridgedCore.js (line 36). Am i missing something?

**Comment by KhaosT** [comment]
@michbeck100 HomeKit has its own security measurement which prevents accessory to use pin code like 123-45-678, 111-11-111 ... those pin code will be rejected by iOS.

**Comment by michbeck100** [comment]
Is there any algorithm to create valid pincodes? I seems there is no documentation for this "feature".

**Comment by 00lex** [comment]
@michbeck100 
I ran into the same issue. 
change the pin, cpy or delete `/pimatic-app/hap-database` and restart pimatic.
