### ISSUE TITLE
Change unit for Characteristic.CurrentTemperature

### ISSUE THREAD

**Issue by bahlo** [KhaosT/HAP-NodeJS#159]
Hey guys. 

I'm writing a plugin for [homebridge](https://github.com/nfarina/homebridge) and I want to change the unit for the `Characteristic.CurrentTemperature` to fahrenheit, but I can't get it to work.

What I've tried:
```js
var service = new homebridge.hap.Service.TemperatureSensor("Some sensor");
var c = service.getCharacteristic(Characteristic.CurrentTemperature)
  .on('get', this.getState.bind(this));

c.setProps({ unit: Characteristic.Units.FAHRENHEIT });
```

When I'm logging `c`, I get the correct unit in `props`:
```js
Characteristic {
  displayName: 'Current Temperature',
  UUID: '00000011-0000-1000-8000-0026BB765291',
  iid: null,
  value: 0,
  props:
   { format: 'float',
     unit: 'fahrenheit',
     minValue: 0,
     maxValue: 100,
     minStep: 0.1,
     perms: [ 'pr', 'ev' ] },
  _events: { change: [Function: bound ], get: [Function: bound ] },
  _eventsCount: 2 }
```

But in HomeKit, it still get's shown as °C.

What am I doing wrong? Thanks in advance :+1:

**Comment by snowdd1** [comment]
Are you going to tell homekit that the values you are going to send and to receive are in fahrenheit? Then your approach should work. Your plugin can sent values in fahrenheit and will receive values in F.

If you want to see values in your homekit app in fahrenheit, then you should change it in the app's settings. E.g. Elagto EVE: Go to iOS Settings, EVE, Units: Temperature: Fahrenheit.
Done.

However, some guys think Apple is metric by heart and is converting your Fahrenheit values to Celsius back and forth, with rounding in between, making flat fahrenheits coming back as crooked values... :smile:

**Comment by bahlo** [comment]
Thank you for your (fast) answer. 

So if I'm understanding you correctly, `unit` only determines the unit of data sent to and from services should be?

**Comment by snowdd1** [comment]
AFAIK. I can change displayed units in the EVE app regardless what the device is talking.

**Comment by snowdd1** [comment]
BTW why would you want to have Fahrenheit living in Germany???

**Comment by bahlo** [comment]
I got an email regarding [homebridge-temperature-file](https://github.com/bahlo/homebridge-temperature-file) to support fahrenheit so wanted to add an option. :grin:

Thanks for your help! :ok_hand:

**Comment by snowdd1** [comment]
@bahlo
I am not so convinced of my first statement any more as in the discussions in homebridge slack team chat @khaost stated that the communication between devices and HomeKit always has to be in Celsius.

**Comment by snowdd1** [comment]
And he confirmed that. Fahrenheit will be removed from repo.

**Comment by travisemery34** [comment]
I wanted to do the same thing, and after reading Apple's documentation I see there is metadata support for fahrenheit units. Perhaps they've recently added this support. 

I am referencing this page: https://developer.apple.com/documentation/homekit/hmcharacteristicmetadataunitsfahrenheit
