### ISSUE TITLE
Security System 

### ISSUE THREAD

**Issue by Mittech** [KhaosT/HAP-NodeJS#162]
Hello,

I have my Raspberry Pi controlling my lights. HomeKit can also control security systems. Is there a way to add like a security device or system to HAP-NodeJS?

**Comment by KhaosT** [comment]
You can create an accessory with Security System service and implement logic in your accessory. https://github.com/KhaosT/HAP-NodeJS/blob/master/lib/gen/HomeKitTypes.js#L1689

**Comment by Mittech** [comment]
Oh, thank you!
