### ISSUE TITLE
package.json: Fixed node-persist to ver 0.0.3

### ISSUE THREAD

**Issue by snowdd1** [KhaosT/HAP-NodeJS#163]
Hi @KhaosT is there a reason why hap-nodejs is fixed to that very version of node-persist? I am getting warnings with each `npm update` because @nfarina homebridge is using a different version (I think it's 0.0.6) - the actual version on github is 0.0.9 anyhow.

Any objections to changing that to ^0.0.3 which would cover 0.0.0 to 0.0.9 ?

Regards

**Comment by KhaosT** [comment]
I believe 0.0.3 is the latest version when I initially wrote this. I'll try to update it to a newer version later today.

**Comment by KhaosT** [comment]
Done, e2129b237015c174c91809db5c04ff7d20e63544 addressed the issue.
