### ISSUE TITLE
How can we configure the GPIO pins to be used for the HAP-NodeJS

### ISSUE THREAD

**Issue by jayzy** [KhaosT/HAP-NodeJS#168]
How can we configure the GPIO pins to be used for the HAP-NodeJS in Raspberry Pi? I don't see it anywhere

**Comment by WoodySlum** [comment]
You can create a php script which calls your GPIO pin.
Then, create an accessory in HAP which call the php script.

Here is an example of an accessory (just a part of the accessory) :
```
var jardin = {
  powerOn: false,
  brightness: 100, // percentage
  
  setPowerOn: function(on) { 
    console.log("Turning the light %s!", on ? "on" : "off");
    jardin.powerOn = on;
    var status = "off";
    if (on) {status = "on"};
    var req = new XMLHttpRequest();  
  
      req.open('GET', 'http://127.0.0.1/path/to/my/site/myscript.php?name=jardin&status='+status, true);
    
    req.onload = function(e) {
        //console.log(selectedDevice+' set to '+on);
    };
    req.send(null);
  },
  setBrightness: function(brightness) {
    console.log("Setting light brightness to %s", brightness);
    jardin.brightness = brightness;
  },
  identify: function() {
    console.log("Identify the light!");
  }
}
```

**Comment by jayzy** [comment]
I was following this video https://www.youtube.com/watch?v=lG5oE-Xrtu0 but I got the updated HAP-NodeJS instead of using that. Still I can't find how he manage to use the GPIO pins in the raspberry pi to the relay. And can you give a sample php script cause not sure what you meant by that. Thanks

**Comment by jayzy** [comment]
Nevermind, I just used Python instead of PHP
