### ISSUE TITLE
Where is the accessories status save at? What folder or what file?

### ISSUE THREAD

**Issue by jayzy** [KhaosT/HAP-NodeJS#169]
Where is the accessories status save at? What folder or what file? I'm planning to have a website that shows up current status of my app and also allow to change the status through the site.

**Comment by KhaosT** [comment]
the accessory status is only saved in memory and not persist in any other ways. If you plan to do so, you'll need to design a way to interact accessory with web.

**Comment by jayzy** [comment]
Thanks :)
