### ISSUE TITLE
Alex Skalozub research copy

### ISSUE THREAD

**Issue by kiler129** [KhaosT/HAP-NodeJS#172]
I was wondering if anyone can share Alex research content? I think https://cryptobin.org is a safe place to store it.

**Comment by KhaosT** [comment]
I'm afraid you have to ask Alex for that... I don't have the right to redistribute his research.

**Comment by electronicsguy** [comment]
@KhaosT Wouldn't you code be built on it? How is it that Apple took down his research info from github but not your project. (I love your work, don't take me wrong :) )
