### ISSUE TITLE
Incorrect accessory setup code.

### ISSUE THREAD

**Issue by Techchunky** [KhaosT/HAP-NodeJS#180]
When entering the 8 digit code for my accessory it tells me: Incorrect accessory setup code.

I am sure the pin is right I checked it 10 times. I even change the pin for my accessory but that did not help.

This is what I get from debug BUT I am using the right password! 

  EventedHTTPServer Server listening on port 51826 +0ms
  EventedHTTPServer Server listening on port 51827 +118ms
  EventedHTTPServer Server listening on port 51828 +68ms
  EventedHTTPServer Server listening on port 51829 +45ms
  EventedHTTPServer [192.168.2.9] New connection from client +5s
  EventedHTTPServer [192.168.2.9] HTTP server listening on port 54826 +24ms
  EventedHTTPServer [192.168.2.9] HTTP request: /identify +201ms
  HAPServer [1A:2B:3C:4D:5E:FF] HAP Request: POST /identify +8ms
  Accessory [Kleine lamp1] Identification request +64ms
  Accessory [Kleine lamp1] Identification request ignored; no listeners to 'identify' event +2ms
  HAPServer [1A:2B:3C:4D:5E:FF] Identification success +6ms
  EventedHTTPServer [192.168.2.9] HTTP Repsonse is finished +55ms
  EventedHTTPServer [192.168.2.9] HTTP request: /pair-setup +14s
  HAPServer [1A:2B:3C:4D:5E:FF] HAP Request: POST /pair-setup +4ms
  HAPServer [1A:2B:3C:4D:5E:FF] Pair step 1/5 +34ms
  EventedHTTPServer [192.168.2.9] HTTP Repsonse is finished +217ms
  EventedHTTPServer [192.168.2.9] HTTP request: /pair-setup +8s
  HAPServer [1A:2B:3C:4D:5E:FF] HAP Request: POST /pair-setup +4ms
  HAPServer [1A:2B:3C:4D:5E:FF] Pair step 2/5 +14ms
  HAPServer [1A:2B:3C:4D:5E:FF] Error while checking pincode: client did not use the same password +172ms
  EventedHTTPServer [192.168.2.9] HTTP Repsonse is finished +12ms

<img width="238" alt="screen shot 2015-12-14 at 00 15 52" src="https://cloud.githubusercontent.com/assets/14234528/11770138/deafb2f2-a1f7-11e5-9f4d-8d8ae39e0088.png">

**Comment by KhaosT** [comment]
Strange... You're sure that you entered the password "03145154" (no dash) on the iOS side?

**Comment by Techchunky** [comment]
Yes, like I said: I checked it multiple times.

**Comment by KhaosT** [comment]
That's strange, what's the iOS version and what platform and OS are you running the server?

**Comment by Techchunky** [comment]
I have IOS 9.2 I use a raspberry pi model B+ and run it on wheezy @KhaosT

**Comment by KhaosT** [comment]
@Techchunky can you try to remove ./persist and then re-try the pairing process? I'm not sure what goes wrong there but there might be a tiny chance the key pair the server generated might be corrupted

**Comment by Techchunky** [comment]
@KhaosT Nope, still not working :(

**Comment by Techchunky** [comment]
Did you find a fix for this? @KhaosT

**Comment by KhaosT** [comment]
@Techchunky I can't reproduce the problem with my Raspberry Pi and so far you're the only person that encountered this issue... I'm not sure what I can do at this stage.

**Comment by Techchunky** [comment]
Reinstalled via NPM and not via GIT clone fixed alot of bugs!!
