### ISSUE TITLE
Raspberry Pi discovery broken 

### ISSUE THREAD

**Issue by AdySan** [KhaosT/HAP-NodeJS#181]
![image](https://cloud.githubusercontent.com/assets/744810/11770809/8b661450-a1bc-11e5-809c-945e30fdabac.png)

Everything was working fine this morning. Sometime today I deleted by Home and tried to add it again but Node Bridge was not discoverable. Looks like my Raspberry Pi has two IP addresses for some reason. Can this interfere with discovery?

My Phone updated to iOS 9.2 overnight, thats probably broke discovery somehow for me. Anyone facing similar issues?

**Comment by KhaosT** [comment]
@AdySan the IP doesn't matter, Bonjour can handle that. In your case, you need to delete ./persist and restart the server. HomeKit will not show user accessories that has already been paired and from the screenshot, the accessory itself is advertising as "paired"

**Comment by AdySan** [comment]
@KhaosT Bingo! 谢谢你
