### ISSUE TITLE
Siri Issues.

### ISSUE THREAD

**Issue by amz4u2nv** [KhaosT/HAP-NodeJS#183]
I've created an accessory - types.SWITCH_STYPE

So bascially the request goes on to call a bash script.
However, if I say "Turn on Sleep mode" - 
I get the following response from Siri -
"Hmm, I couldn't get a response from your devices this time"
It was working fine on the weekend, and also still works if I do it manually through mytouchhome app.

I've deleted the persist files and reset the homekit settings on the ios device, etc.. still no luck

Any ideas,

// HomeKit types required
var types = require("./types.js")
var exports = module.exports = {};

var execute = function(accessory,characteristic,value)
{
  console.log("executed accessory: " + accessory + ", and characteristic: " + characteristic + ", with value: " +  value + ".");
  var request = require("request");
  var object = "sleep";
    if (value == true)
      var method = 'ON';
    else
      var method = 'OFF';
 console.log("http://xxxxxx:1111/sleep_mode.php?method="+method);
    request("http://xxxxxxx:1111/sleep_mode.php?method="+method, function(error, response, body) {
      console.log(body);
    });

}

exports.accessory = {
  displayName: "Sleep",
  username: "1A:2C:2D:3D:2E:CF",
  pincode: "031-45-154",
  services: [{
    sType: types.ACCESSORY_INFORMATION_STYPE,
    characteristics: [{
    	cType: types.NAME_CTYPE,
    	onUpdate: null,
    	perms: ["pr"],
		format: "string",
		initialValue: "Sleep",
		supportEvents: false,
		supportBonjour: false,
		manfDescription: "Bla",
		designedMaxLength: 255
    },{
    	cType: types.MANUFACTURER_CTYPE,
    	onUpdate: null,
    	perms: ["pr"],
		format: "string",
		initialValue: "HomeEasy",
		supportEvents: false,
		supportBonjour: false,
		manfDescription: "Bla",
		designedMaxLength: 255
    },{
    	cType: types.MODEL_CTYPE,
    	onUpdate: null,
    	perms: ["pr"],
		format: "string",
		initialValue: "Rev-1",
		supportEvents: false,
		supportBonjour: false,
		manfDescription: "Bla",
		designedMaxLength: 255
    },{
    	cType: types.SERIAL_NUMBER_CTYPE,
    	onUpdate: null,
    	perms: ["pr"],
		format: "string",
		initialValue: "A3S2NASF99EW",
		supportEvents: false,
		supportBonjour: false,
		manfDescription: "Bla",
		designedMaxLength: 255
    },{
    	cType: types.IDENTIFY_CTYPE,
    	onUpdate: null,
    	perms: ["pw"],
		format: "bool",
		initialValue: false,
		supportEvents: false,
		supportBonjour: false,
		manfDescription: "Identify Accessory",
		designedMaxLength: 1
    }]
  },{
    sType: types.SWITCH_STYPE,
    characteristics: [{
    	cType: types.NAME_CTYPE,
    	onUpdate: null,
    	perms: ["pr"],
		format: "string",
		initialValue: "Sleep Mode",
		supportEvents: false,
		supportBonjour: false,
		manfDescription: "Bla",
		designedMaxLength: 255
    },{
    	cType: types.POWER_STATE_CTYPE,
    	onUpdate: function(value) { console.log("Change:",value); execute("Test Accessory 1", "sleep service", value); },
    	perms: ["pw","pr","ev"],
		format: "bool",
		initialValue: false,
		supportEvents: false,
		supportBonjour: false,
		manfDescription: "Turn On Sleep Mode",
		designedMaxLength: 1
    }
    ]
  }]
}

**Comment by amz4u2nv** [comment]
Can anyone suggest anything that might be causing my issue.

Thanks

**Comment by Techchunky** [comment]
Which homekit app are you using? @amz4u2nv

**Comment by amz4u2nv** [comment]
Mytouchhome

**Comment by Techchunky** [comment]
Try downloading "Idevices" from the App Store. This app allows you to add scenes. E.X add a scene that says "Open the door". When you say "Open the door" to siri, that scene will be played. You can tell the scene to turn on a light. @amz4u2nv

**Comment by amz4u2nv** [comment]
Scenes worked as a workaround.
Thanks
