### ISSUE TITLE
When creating second light accessory, first and second Lights doesn't show up 

### ISSUE THREAD

**Issue by Techchunky** [KhaosT/HAP-NodeJS#185]
Hi So the default Light_accessory is just working. when I create a new one I cannot see the second one when searching for a product  sometimes  the first one doesn't work anymore. I copied the file from the first one, and changed the name of the light and light.username: 
@KhaosT 

var Accessory = require('../').Accessory;
var Service = require('../').Service;
var Characteristic = require('../').Characteristic;
var uuid = require('../').uuid;
var PythonShell = require('python-shell');

// here's a fake hardware device that we'll expose to HomeKit
var FAKETL_LIGHT = {
  powerOn: false,
  brightness: 100, // percentage

  setPowerOn: function(on) {
    console.log("Turning the light %s!", on ? "on" : "off");
    FAKETL_LIGHT.powerOn = on;

        if(on){

              PythonShell.run('../../lighton.py', function (err) {
                        if (err) throw err;
                                console.log('finished ON');
                });

        }else{

                PythonShell.run('../../lightoff.py', function (err) {
                        if (err) throw err;
                                console.log('finished OFF');
                });

        }
  },
  setBrightness: function(brightness) {
    console.log("Setting light brightness to %s", brightness);
    FAKETL_LIGHT.brightness = brightness;
  },
  identify: function() {
    console.log("Identify the light!");
  }
}

// Generate a consistent UUID for our light Accessory that will remain the same even when
// restarting our server. We use the `uuid.generate` helper function to create a deterministic
// UUID based on an arbitrary "namespace" and the word "light".
var lightUUID = uuid.generate('hap-nodejs:accessories:light');

// This is the Accessory that we'll return to HAP-NodeJS that represents our fake light.

var light = exports.accessory = new Accessory('Light tl', lightUUID);

// Add properties for publishing (in case we're using Core.js and not BridgedCore.js)
light.username = "QK:2D:3E:4F:5G:HH";
light.pincode = "031-45-154";

// set some basic properties (these values are arbitrary and setting them is optional)
light
  .getService(Service.AccessoryInformation)
  .setCharacteristic(Characteristic.Manufacturer, "Oltica")
  .setCharacteristic(Characteristic.Model, "Rev-1")
  .setCharacteristic(Characteristic.SerialNumber, "A1S2NASF88EW");

// listen for the "identify" event for this Accessory
light.on('identify', function(paired, callback) {
  FAKETL_LIGHT.identify();
  callback(); // success
});

// Add the actual Lightbulb Service and listen for change events from iOS.
// We can see the complete list of Services and Characteristics in `lib/gen/HomeKitTypes.js`
light
  .addService(Service.Lightbulb, "grote lamp") // services exposed to the user should have "names" like "Fake Light" for us
  .getCharacteristic(Characteristic.On)
 .on('set', function(value, callback) {
    FAKETL_LIGHT.setPowerOn(value);
    callback(); // Our fake Light is synchronous - this value has been successfully set
  });

// We want to intercept requests for our current power state so we can query the hardware itself instead of
// allowing HAP-NodeJS to return the cached Characteristic.value.
light
  .getService(Service.Lightbulb)
  .getCharacteristic(Characteristic.On)
  .on('get', function(callback) {

    // this event is emitted when you ask Siri directly whether your light is on or not. you might query
    // the light hardware itself to find this out, then call the callback. But if you take longer than a
    // few seconds to respond, Siri will give up.

    var err = null; // in case there were any problems

    if (FAKETL_LIGHT.powerOn) {
      console.log("Are we on? Yes.");
      callback(err, true);
    }
    else {
      console.log("Are we on? No.");
     callback(err, false);
    }
  });

// also add an "optional" Characteristic for Brightness
light
  .getService(Service.Lightbulb)
  .addCharacteristic(Characteristic.Brightness)
  .on('get', function(callback) {
    callback(null, FAKETL_LIGHT.brightness);
  })
  .on('set', function(value, callback) {
    FAKETL_LIGHT.setBrightness(value);
    callback();
  })

**Comment by KhaosT** [comment]
Please make sure the accessory file is ended with ``_accessory.js``

**Comment by Techchunky** [comment]
It is, when starting core.js it also starts.



On 18 Dec 2015, at 07:59, Khaos Tian <notifications@github.com<mailto:notifications@github.com>> wrote:


Please make sure the accessory file is ended with _accessory.js

-

**Comment by Techchunky** [comment]
Can you make a second LIGHT accessory and check if pairing both of them works. If so, can you send me the second light_accessory.js file?. Thank you! @KhaosT

**Comment by Techchunky** [comment]
@KhaosT ?

**Comment by Techchunky** [comment]
Hope you can help me out @KhaosT

**Comment by KhaosT** [comment]
I'm not sure what you expect me to do here... the second light file will be exactly the same except the ``username``. I can only suggest you to try it again.

**Comment by AdySan** [comment]
For the new accessory, doesn't the UUID need to change?

```
// Generate a consistent UUID for our light Accessory that will remain the same even when
// restarting our server. We use the `uuid.generate` helper function to create a deterministic
// UUID based on an arbitrary "namespace" and the word "light".
var lightUUID = uuid.generate('hap-nodejs:accessories:light');
```

Change to 

```
var lightUUID = uuid.generate('hap-nodejs:accessories:SomeOtherlight');
```

**Comment by Techchunky** [comment]
@AdySan This did not help.

**Comment by Techchunky** [comment]
Fixed the problem by resetting the home configuration in settings on Iphone and deleting my home twice from the homekit app!
