### ISSUE TITLE
Adding Hue to the light accessory

### ISSUE THREAD

**Issue by AdySan** [KhaosT/HAP-NodeJS#186]
Hi @KhaosT inspired by your Christmas light, I added the Hue characteristic to the Light Accessory. 

https://github.com/AdySan/HAP-NodeJS/blob/master/accessories/AdyLight_accessory.js

I can control the Hue with this slider, but as you see below, Siri doesn't translate the color to a Hue value. Who should do this conversion? (I assume every color refers to a specific Hue value)

![img_4686](https://cloud.githubusercontent.com/assets/744810/11916823/18115938-a69e-11e5-9efd-986a884feba1.PNG)
![img_4687](https://cloud.githubusercontent.com/assets/744810/11916824/1c27c124-a69e-11e5-8424-a85c3c471469.PNG)

**Comment by KhaosT** [comment]
@AdySan Currently Siri requires all three (Hue, Saturation and Brightness) characteristics to successfully set the color. Otherwise, it will say it can't find light to blablabla...

**Comment by AdySan** [comment]
Cool got it, will try and report back tomorrow.

**Comment by AdySan** [comment]
Works great, thanks for the tip!

https://twitter.com/ady/status/679146825136259073
