### ISSUE TITLE
Can't connect accessory to multiple IOS Devices.

### ISSUE THREAD

**Issue by Techchunky** [KhaosT/HAP-NodeJS#189]
Hi I am using the latest version of IOS. 

However I am not able to connect my accessory to my iPad. Once it is connected to my iPhone, my iPad can't find the accessory.

Thanks in advance! @KhaosT

**Comment by futuretec** [comment]
Hey there,

I ran into the same issue, when I started with this project myself.
This has to do with the basic architecture of HomeKit by Apple. You only can setup your accessories once on one iOS device/home/account.
Once you configured your accessories on e.g. your iPhone, you have to "share" your home with other users (via Apple ID). If your iPad uses the same Apple ID, try to start over: remove all accessories, remove all homes, reset HomeKit in your Settings/Privacy and check that your iCloud keychain is configured properly.

Hope I could help.

**Comment by Techchunky** [comment]
When I invite someone to my Home. The person is not getting an email @futuretec

**Comment by futuretec** [comment]
@Techchunky I don't think you'll get an email.
At first you got to use a valid iCloud/Apple ID email address. Then a banner should appear on the invitee's device. If it doesn't check Settings -> HomeKit if they can accept the invite.

**Comment by AdySan** [comment]
I second that, no email, just a notification. Using the HMCatalog app in Apples examples, and works flawlessly with the latest HAP-NodeJS.

**Comment by Techchunky** [comment]
Hmm, not getting a notification.. @AdySan @futuretec

**Comment by Techchunky** [comment]
Ah it worked!! Thanks

**Comment by Techchunky** [comment]
It worked Thanks to @AdySan @futuretec

**Comment by Techchunky** [comment]
It worked Thanks to @AdySan @futuretec
