### ISSUE TITLE
Trying to make a battery powered Temperature Sensor

### ISSUE THREAD

**Issue by AdySan** [KhaosT/HAP-NodeJS#190]
In TemperatureSensor_accessory.js, if I understand correctly, the Temperature sensor has to be always available online listening for Temperature requests by the HAP-NodeJS server. 

I'm interested in making a battery powered temperature sensor, that will wake up, say every 10 minutes and make a measurement. And may be send it over to the HAP-NodeJS server via MQTT. What would be the best way to make HAP-NodeJS listen to a certain topic on MQTT and persist the last temperature reading in memory?

I can figure out the figure out the details, but there's nothing fundamentally wrong in this model, right?

**Comment by futuretec** [comment]
Hey there,

I'm not sure what you are trying to achieve here.
HAP-NodeJS is simply for providing a HomeKit-compatible server, which builds a bridge between iOS and specific devices.

I would suggest to separate your project into three logical modules:
1) battery powered temperature sensor, which publishes its read values to a MQTT broker (e.g. use an ESP8266 or Adafruit "Huzzah" for this)
2) MQTT broker (e.g. could be running aside of the HAP-NodeJS server)
3) HAP-NodeJS itself with the "TemperatureSensor_accessory.js", which requests its values from the MQTT topic.

Hope I could help.

**Comment by AdySan** [comment]
Thanks, that's exactly the setup I had in mind. I already have it working for some light accessories. I'm a little worried about my ESP8266 sensor being offline in deep sleep mode for 99% of the time. When HAP-NodeJS requests the temperature reading from the MQTT topic, is there any mechanism for the broker to buffer this value in case the temperature sensor is not available at that moment?

**Comment by futuretec** [comment]
@AdySan 
Look at the MQTT documentation for "retained messages". I think if you publish the temperature values from the ESP8266 as "retained", they will be retrievable by any new subscribing client of the topic (in your case the HAP-NodeJS accessory).
An other option would be to wake the ESP8266 and wait a specific time, until a new temperature value was submitted to the topic.

**Comment by AdySan** [comment]
Thanks, I'll take a look at that. I guess I just don't understand how exactly MQTT works. 

I can't remotely wake the ESP8266, as I understand the only way to kick it out of deep sleep is a set timer, basically the chip resets itself on wakeup.

**Comment by futuretec** [comment]
@AdySan 
Maybe you don't even need to use retained messages with MQQT.
Scenario: HAP-NodeJS + MQTT broker are up and running. HAP-NodeJS accessory subscribes to MQTT topic for temperature value. Every time a value is published (by the esp8266), it will be read by the accessory and can be saved as "state" or latest value within your implementation.
In this case it wouldn't matter if the esp8266 is in deep sleep. A new value would be submitted once it is awake again (e.g. use a defined cycle for temperature updates).
The only case you won't have a valid temperature value is, when your HAP-NodeJS server crashes and the esp8266 hasn't submitted a new value yet.

**Comment by AdySan** [comment]
Can someone help me with the NodeJS syntax here, I'm totally new to JS. All I wanna do it subscribe to the MQTT topic NurseryTemperature and whenever a message arrives I want to store that value in a global variable. If what I've done below going to work? 

```
var NurseryTemperature = "00";

// MQTT Setup
var mqtt = require('mqtt');
console.log("Connecting to MQTT broker...");
var mqtt = require('mqtt');
var options = {
  port: 1883,
  host: '192.168.1.155',
  clientId: 'AdyPi_NurseryTemperatureSensor'
};
var client = mqtt.connect(options);
console.log("Nursery Temperature Sensor Connected to MQTT broker");
client.subscribe('NurseryTemperature');
client.on('message', function(topic, message) {
  console.log(message);
  NurseryTemperature = message;
});

var Accessory = require('../').Accessory;
var Service = require('../').Service;
var Characteristic = require('../').Characteristic;
var uuid = require('../').uuid;

// here's a fake temperature sensor device that we'll expose to HomeKit
var FAKE_SENSOR = {
  currentTemperature: 50,
  getTemperature: function() { 
    console.log("Getting the current temperature!");
    // return FAKE_SENSOR.currentTemperature;
    return NurseryTemperature; 
  },
  randomizeTemperature: function() {
    // randomize temperature to a value between 0 and 100
    FAKE_SENSOR.currentTemperature = Math.round(Math.random() * 100);
  }
}
```

**Comment by AdySan** [comment]
Got this working. Thanks everyone. More details here http://adityatannu.com/blog/post/2016/01/01/WeatherBug-ESP8266-WeatherStation-with-IFTTT-and-HomeKit-support.html
