### ISSUE TITLE
What if I want to have a couple Motion Sensor in one accessory.

### ISSUE THREAD

**Issue by jayzy** [KhaosT/HAP-NodeJS#196]
What if I want to have a couple Motion Sensor in one accessory and I want to identify and set each motion sensor. How do I call that?

    alarm
      .addService(Service.MotionSensor, "Motion 1")
      .getCharacteristic(Characteristic.MotionDetected)
      .on('set', function(value, callback) {
        
        if (value == 1) {
          callback();
    
            .getService(Service.MotionSensor)
            .setCharacteristic(Characteristic.MotionDetected, 1);
        }
    	else {
          callback();
      	
            .getService(Service.MotionSensor)
            .setCharacteristic(Characteristic.MotionDetected, 0);
        }
      });

    alarm
      .addService(Service.MotionSensor, "Motion 2")
      .getCharacteristic(Characteristic.MotionDetected)
      .on('set', function(value, callback) {
        
        if (value == 1) {
          callback();
    
            .getService(Service.MotionSensor)
            .setCharacteristic(Characteristic.MotionDetected, 1);
        }
    	else {
          callback();
      	
            .getService(Service.MotionSensor)
            .setCharacteristic(Characteristic.MotionDetected, 0);
        }
      });
   alarm.getService(Service.MotionSensor)
     .getCharacteristic(Characteristic.SecuritySystemCurrentState)
     .on('get', function(callback) {
       // Should get each accessory
     });

**Comment by KhaosT** [comment]
@jayzy you can try ``.getService("Motion 2")``

**Comment by jayzy** [comment]
It's gives error duplicate on UUID

**Comment by jayzy** [comment]
Even though I don't change that but just adding two the same service. I already get the error.

**Comment by KhaosT** [comment]
Alright, in this case you'll have to provide a subtype.

```js
alarm.addService(Service.MotionSensor, "Motion 1", "M1");
alarm.addService(Service.MotionSensor, "Motion 2", "M2");
```

**Comment by jayzybriones** [comment]
Ok and when I call them? I'll use the "Motion 1" or the "M1"?

**Comment by KhaosT** [comment]
Use the name "Motion 1"

**Comment by jayzy** [comment]
Ok got it thanks :)
