### ISSUE TITLE
Siri couldn't get a response from my devices

### ISSUE THREAD

**Issue by shmuelzon** [KhaosT/HAP-NodeJS#197]
Hey,

Not really sure what's at fault here but was hoping I could get some insight.
I've created an accessory to control the water heater I've recently connected to WiFi. It's rather simple as far as coding goes:
```javascript
var Accessory = require('../').Accessory;
var Service = require('../').Service;
var Characteristic = require('../').Characteristic;
var uuid = require('../').uuid;
var request = require('request');

function httpRequest(method, payload, callback) {
  request({
    url: 'http://water-heater/relay',
    method: method,
    json: true,
    body: payload,
  }, callback);
}

var waterHeaterUUID = uuid.generate('com:shmuelzon:hap-nodejs:accessories:water-heater');
var waterHeater = exports.accessory = new Accessory('Water Heater', waterHeaterUUID);

// Add properties for publishing (in case we're using Core.js and not BridgedCore.js)
waterHeater.username = '1A:2B:3C:4D:5E:FF';
waterHeater.pincode = '031-45-154';

waterHeater
  .getService(Service.AccessoryInformation)
  .setCharacteristic(Characteristic.Manufacturer, 'Shmuelzon')
  .setCharacteristic(Characteristic.Model, 'Rev-1')
  .setCharacteristic(Characteristic.SerialNumber, '1');

waterHeater
  .addService(Service.Switch, 'Water Heater')
  .getCharacteristic(Characteristic.On)
  .on('set', function(on, callback) {
    console.log('Turning the water heater %s!', on ? 'on' : 'off');
    httpRequest('PUT', {
      state:  on ? 'on' : 'off'
    }, function (error, response, body) {
      callback(error);
    });
  });

waterHeater
  .getService(Service.Switch)
  .getCharacteristic(Characteristic.On)
  .on('get', function(callback) {
    httpRequest('GET', null, function(error, response, body) {
      var val = null;

      if (body) {
        val = body.state == 'on' ? true : false;
      }
      callback(error, val);
    })
  });
```

I'm using Apple's HMCatalog app to add HomeKit devices. Successfully paired with the Node Bridge and can see my new accessory. In the app, I can also turn it on and off without any issues.
Now, if I ask Siri to "Turn the water heater on", she will do so promptly. However, if I ask her to "Turn the water heater off" I get the following reply: "Hmm, I couldn't get a response from your devices this time".
I tried to go around it a few other ways, e.g. "Turn the water heater on", followed by "Turn it off" will work. I can also ask "Is the water heater on?" and after telling me that it's on, I can also say "Turn it off" and it does.

I've started the bridge with "DEBUG=*" and can see whenever a request is sent to the server and no log message appears when trying to turn the water heater off (when I get the "Hmm..." reply).

Like I said before, I'm not sure this is really a HAP-NodeJS issue but I have no idea what might be the problem.

Thanks!

**Comment by KhaosT** [comment]
@shmuelzon have you tried to rename ``water heater`` to something else? Maybe the ``off`` command + ``heater`` triggers Siri to match a different service...

**Comment by shmuelzon** [comment]
Sadly, you're right. I've renamed it to "Water Tank" and it seems to work fine now.
Kind of weird that the original issue was only for 'off'. Now I need to find a different name it (and I) would accept using :)

Thanks!
