### ISSUE TITLE
Garage Accessory Dissappearing

### ISSUE THREAD

**Issue by legotheboss** [KhaosT/HAP-NodeJS#198]
Hi,

I have a Node Bridge with just the Garage Door accessory that seems to disappear after 6 hours or so. I tried both Core.js and BridgedCore.js and the same result occurred. All the other accessories are still there but just Garage seems to have disappeared. Does anyone have a solution against this?

**Comment by KhaosT** [comment]
That's interesting, do you have the log from iOS when this happens?

**Comment by legotheboss** [comment]
Nope, I don't have the log. Just FYI, I am on iOS 9.3 beta 1.1.

**Comment by KhaosT** [comment]
Next time when this happens, can you get the content from 127.0.0.1:51826/accessories ?

**Comment by legotheboss** [comment]
All I am getting is 

{"error": "not found"}

**Comment by KhaosT** [comment]
are you sure you copied the url right? there is no way you get "not found" for this ...

**Comment by legotheboss** [comment]
After restarting the node, heres the output

{"accessories":[{"aid":1,"services":[{"iid":1,"type":"0000003E-0000-1000-8000-0026BB765291","characteristics":[{"iid":2,"type":"00000014-0000-1000-8000-0026BB765291","perms":["pw"],"format":"bool","description":"Identify"},{"iid":3,"type":"00000020-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"Default-Manufacturer","description":"Manufacturer"},{"iid":4,"type":"00000021-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"Default-Model","description":"Model"},{"iid":5,"type":"00000023-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"Garage Bridge","description":"Name"},{"iid":6,"type":"00000030-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"Default-SerialNumber","description":"Serial Number"}]}]},{"aid":2,"services":[{"iid":1,"type":"0000003E-0000-1000-8000-0026BB765291","characteristics":[{"iid":2,"type":"00000023-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"Garage Door Opener","description":"Name"},{"iid":3,"type":"00000020-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"Liftmaster","description":"Manufacturer"},{"iid":4,"type":"00000021-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"Rev-1","description":"Model"},{"iid":5,"type":"00000030-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"A1S2NASF88EW","description":"SN"},{"iid":6,"type":"00000014-0000-1000-8000-0026BB765291","perms":["pw"],"format":"bool","description":"Identify Accessory"}]},{"iid":7,"type":"00000041-0000-1000-8000-0026BB765291","characteristics":[{"iid":8,"type":"00000023-0000-1000-8000-0026BB765291","perms":["pr"],"format":"string","value":"Liftmaster Garage","description":"Name"},{"iid":9,"type":"0000000E-0000-1000-8000-0026BB765291","perms":["pr","ev"],"format":"int","value":1,"description":"BlaBla","maxValue":4,"minValue":0,"minStep":1},{"iid":10,"type":"00000032-0000-1000-8000-0026BB765291","perms":["pr","pw","ev"],"format":"int","value":1,"description":"BlaBla","maxValue":1,"minValue":0,"minStep":1},{"iid":11,"type":"00000024-0000-1000-8000-0026BB765291","perms":["pr","ev"],"format":"bool","value":false,"description":"BlaBla"}]},{"iid":12,"type":"00000062-0000-1000-8000-0026BB765291","characteristics":[{"iid":13,"type":"00000103-0000-1000-8000-0026BB765291","perms":["pr","ev"],"format":"uint16","value":1,"description":"Category","maxValue":65535,"minValue":1},{"iid":14,"type":"00000102-0000-1000-8000-0026BB765291","perms":["pr","ev"],"format":"string","value":"f2f312cf-a52e-4a0e-a5c7-923a4819e488","description":"Link Address"},{"iid":15,"type":"0000009C-0000-1000-8000-0026BB765291","perms":["pr","ev"],"format":"uint8","value":1,"description":"Link Quality","maxValue":3,"minValue":1},{"iid":16,"type":"00000104-0000-1000-8000-0026BB765291","perms":["pr"],"format":"uint8","value":1,"description":"Link Type","maxValue":255,"minValue":1},{"iid":17,"type":"00000063-0000-1000-8000-0026BB765291","perms":["pr","ev"],"format":"bool","value":true,"description":"Reachable"}]}]}]}

**Comment by KhaosT** [comment]
Interesting... so before restarting the node, you got ``{"error": "not found"}`` and after restart everything comes back?

**Comment by legotheboss** [comment]
yeah

**Comment by KhaosT** [comment]
@legotheboss can you share all the accessories files you got? based on your situation, it seems like one of those messed up the server maybe...

**Comment by legotheboss** [comment]
This is the main accessory file straight from the node. Sorry I had to ZIP it, github wouldn't accept the main .js file. 
[GarageDoorOpener_accessory.js.zip](https://github.com/KhaosT/HAP-NodeJS/files/96908/GarageDoorOpener_accessory.js.zip)

**Comment by KhaosT** [comment]
not really sure what happens there, it looks fine. next time when you run hap-nodejs, can you try run it with debug flag so we can get more logs and see what's wrong?

**Comment by legotheboss** [comment]
I was able to fix it just by reinstalling HAP-NodeJS, something was being funky... A reinstall has completely fixed it and haven't has an issue since :)
