### ISSUE TITLE
Add `BRIDGE` Characteristic in Accessory.js, and use it for Bridges

### ISSUE THREAD

**Issue by johannrichard** [KhaosT/HAP-NodeJS#199]
HomeKit Bridges currently carry an Accessory Category `OTHER`. However, according to the developers documentation, there is a specific type for `BRIDGE` (I suspect the constant value to be `2`) and it would be great if this was added in `Accessory.js` and then set correctly on Bridges. 

See`HMAccessoryCategoryTypes.h` in iOS SDK for details on the type value.

**Comment by KhaosT** [comment]
Done
