### ISSUE TITLE
Fan Speed?

### ISSUE THREAD

**Issue by hplato** [KhaosT/HAP-NodeJS#200]
Using this code, I can successfully turn a fan on and off, however I can't set the speed. Telling Siri to 'set the fan to low' I get

"Sorry, I wasn't able to find any devices this time"

Saying 'set the fan to off' I get

"OK, the fan is turned off"

Here's the characteristics I'm using (from the fan example accessory)

```
      services.push({
      sType: types.FAN_STYPE,
      characteristics: [{
          cType: types.NAME_CTYPE,
          onUpdate: null,
          perms: ["pr"],
          format: "string",
          initialValue: this.serviceName,
          supportEvents: false,
          supportBonjour: false,
          manfDescription: "Service Name",
          designedMaxLength: 255
      },{
       		cType: types.ROTATION_SPEED_CTYPE,
            perms: ["pw","pr","ev"],
            format: "bool",
            initialValue: 0,
            supportEvents: true,
            supportBonjour: false,
            manfDescription: "Change the speed of the fan",
            designedMaxLength: 1,
            onUpdate: function(value) {
                if (value == 0) {
                    that.setPowerState(0);
                } else if (value > 0 && value < 40) {
                    that.setBrightnessLevel("low");
                } else if (value > 40 && value < 75) {
                    that.setBrightnessLevel("med");
                } else {
                    that.setBrightnessLevel("high");
                }
            }
      },{
          cType: types.POWER_STATE_CTYPE,
          onUpdate: function(value) {
            console.log(that.name + "...changing status....");
            that.setPowerState(value);
             },
          perms: ["pw","pr","ev"],
          format: "bool",
          initialValue: false,
          supportEvents: false,
          supportBonjour: false,
          manfDescription: "Change the power state of fan",
          designedMaxLength: 1
      }]
    });    
 ```

**Comment by AdySan** [comment]
format is bool, not sure how it will accept a value. Maybe you can take some cues form the brightness setting here https://github.com/AdySan/HAP-NodeJS/blob/master/accessories/BedroomLight_accessory.js <https://github.com/AdySan/HAP-NodeJS/blob/master/accessories/BedroomLight_accessory.js>

**Comment by hplato** [comment]
I have no idea. However, for a light brightness (which works), it's also bool:

```
          cType: types.BRIGHTNESS_CTYPE,
          onUpdate: function(value) {
            console.log(that.name + "...changing brightness....");
            that.setBrightnessLevel(value);
             },
          perms: ["pw","pr","ev"],
          format: "bool",
          initialValue: 100,
          supportEvents: false,
          supportBonjour: false,
          manfDescription: "Adjust Brightness",
          designedMinValue: 0,
          designedMaxValue: 100,
          designedMinStep: 1,
          unit: "%"
```

**Comment by AdySan** [comment]
Can you change the speed using a HomeKit app which has a slider, Siri can get confused with generic names like fan.

**Comment by KhaosT** [comment]
First of all, the fan speed should be a float instead of the bool (https://github.com/KhaosT/HAP-NodeJS/blob/master/lib/gen/HomeKitTypes.js#L974). Second, Siri may not support setting a value by saying level like "low","high"...

**Comment by fahrvergnuugen** [comment]
I have success using "set the ----- to 50%" for dimmable lights. Have you tried that for the fan?

**Comment by hplato** [comment]
OK, this was totally my fault, I ended up updating the accessory in the wrong directory. So using this code, yes it does work. Saying to Siri 'Set the fan to low' Siri responds back, OK setting it to around 25.
