### ISSUE TITLE
DS18B20

### ISSUE THREAD

**Issue by Ramzes177** [KhaosT/HAP-NodeJS#208]
Hi,
How to get the value of the connected sensor DS18B20 on the bus 1-ware through puthon

**Comment by snowdd1** [comment]
hmm. 
Have you tried http://www.giyf.com/DS18B20%20python ?

**Comment by Ramzes177** [comment]
wittily )))

**Comment by legotheboss** [comment]
https://youtu.be/hVrl7FC_T2Y

This might help you @Ramzes177

**Comment by jimvanderveen** [comment]
Nice job on the YouTube tutorial, Amruth!

Sent from my iPad

On Mar 5, 2016, at 19:01, Amruth Pabba <notifications@github.com<mailto:notifications@github.com>> wrote:


https://youtu.be/hVrl7FC_T2Y

This might help you @Ramzes177<https://github.com/Ramzes177>

-

**Comment by Ramzes177** [comment]
Thank you!!! It helped

**Comment by legotheboss** [comment]
@KhaosT you can close this
