### ISSUE TITLE
How to run hap-nodejs on homebridge?

### ISSUE THREAD

**Issue by toshibochan** [KhaosT/HAP-NodeJS#209]

**Comment by KhaosT** [comment]
What do you mean...? homebridge is built on hap-nodejs ...

**Comment by toshibochan** [comment]
How to run hap-nodejs accessories on homebridge?

**Comment by KhaosT** [comment]
You can took the service creation parts in hap-nodejs accessory and create a plugin with those services.

**Comment by toshibochan** [comment]
when I run homebridge I can't run bridgedcore.js or core.js, i want use light_accessory.js and fan_accessory.js on homebridge. How I can make plugin for homebridge?

**Comment by KhaosT** [comment]
@toshibochan for how to create a plugin for homebridge, please refer to the [sample plugin](https://github.com/nfarina/homebridge/tree/master/example-plugins/homebridge-lockitron).

**Comment by toshibochan** [comment]
@ KhaosT thanks! I will try to make plugin! But I have to study a lot because I don't know nothing about codes! Lol
