### ISSUE TITLE
Add Gitter

### ISSUE THREAD

**Issue by flexzuu** [KhaosT/HAP-NodeJS#210]
Can we add a [Gitter](https://gitter.im) to this Repo?
Because many people are asking stuff on issues and its not that helpful to have usage questions in the issues. I will help to administrate if you want me to.
Someone should got through the open issues, tag them and close the irrelevant ones.

**Comment by KhaosT** [comment]
@flexzuu Not sure if Gitter is really necessary. For most of HomeKit related issues, I'd suggest people to ask in homebridge's Slack channel 😊There are lots of people in that channel can answer general questions.

**Comment by flexzuu** [comment]
@KhaosT Okay maybe we should add the info about the slack channel and [Homebridge](https://github.com/nfarina/homebridge) to the Readme. I didn't even knew that a other solution for home kit whit node existed. I currently have a working HAP running what is the difference? I am running on a Raspberry Pi btw.

**Comment by KhaosT** [comment]
@flexzuu homebridge is an abstraction built on top of hap-nodejs which allows developer to develop plugins to offer support for existing home automation products :)

**Comment by flexzuu** [comment]
@KhaosT i have a currently a plugin build on top of hap-node. You can checkout my fork. maybe i should switch to homebridge.
