### ISSUE TITLE
Disconnected after a while

### ISSUE THREAD

**Issue by kajaba** [KhaosT/HAP-NodeJS#213]
Hi there. I have a problem with bridgedcore. When I run bridgedcore.js everything is ok, my custom accessories work. After a while I get disconnected from all accessories. But when I run a scene everything works. But I can't turn on/off individual accessory. 
See the screenshots - after running bridged core and after a while 
![image](https://cloud.githubusercontent.com/assets/513122/12992416/a0f6b914-d114-11e5-9b9d-4867102b0507.png)
![image](https://cloud.githubusercontent.com/assets/513122/12992420/a86037b6-d114-11e5-99a1-c8123278ece4.png)

I don't know what might be the problem. I have fully updated all packages (raspi) and node packages
Do I need to provide more details? 

Thank you for your help

**Comment by KhaosT** [comment]
You said the scene execution works in this state?

**Comment by kajaba** [comment]
Yes. I can ask Siri and it executes all the commands and it works

**Comment by KhaosT** [comment]
that's interesting, if you reboot the node instance, does the accessory come back as reachable?

**Comment by Radstake** [comment]
@KhaosT @kajaba Hi there I have exactly the same! After the reboot they are reachable again. But all the time I can control them with Siri. Could it be the the accessory doesn't have a functie to return it's (fake) state?

**Comment by kajaba** [comment]
@KhaosT Yes, when I kill the node instance and run it again, the accessories are reconnected and on the app the switches are shown (first picture)

**Comment by kajaba** [comment]
Strange thing is tag on iPad it works ok. Same app on the iPad works. But I can't control accessorize on my iPhone. I see them disconnected in each app

**Comment by kajaba** [comment]
I think I figured it out. After one minute of not using the iPhone or iPad. It gets disconnected. By not using I mean it's in sleep mode. When I wake the phone during this one minute it's ok. But after a minute it get disconnected.

**Comment by Radstake** [comment]
Same here! Same here!

Groeten,

Erich Radstake
+31642235142

**Comment by kajaba** [comment]
@KhaosT how can I participate to resolve this issue?

**Comment by KhaosT** [comment]
I'm not really sure...It's not like the underlying physical connection is gone (since scene execution works)
Maybe try to gather logs from iOS device and see why it the reachability to false?

**Comment by KhaosT** [comment]
I think I found the issue, can you update hap-nodejs to 0.2.3 and see if the issue still occurs?

**Comment by Radstake** [comment]
Thank you! Updated half a hour again, looks promising!

**Comment by Radstake** [comment]
@KhaosT Yep, this did the trick for me, thank you so much!

**Comment by kajaba** [comment]
Works like a charm. Thank you @KhaosT for your great work to make our lives better :)

**Comment by KhaosT** [comment]
@Radstake @kajaba Sorry for the inconvenience, glad to know it works :) I'll close the issue for now. Feel free to open a new one if this occurs again.
