### ISSUE TITLE
Not an issue but what is the best way to 

### ISSUE THREAD

**Issue by Techchunky** [KhaosT/HAP-NodeJS#214]
This is not an issue, I am not sure where to ask.

What is the best way to update HAP-NodeJs from raspberry-pi without losing your accessory configs?. 

Is there also a way to control the lights, not only from IOS but also from MAC OSX?

Thanks!

**Comment by jamesabruce** [comment]
Navigate to the HAP-NodeJS directory, type "git pull". This will update core files, but won't overwrite any local copies of accessories you've made and modified (assuming you copied the original files, and didn't just modify the defaults). 

There is no HomeKit support from Mac yet. Presumably it'll arrive whenever Siri for Mac does.
