### ISSUE TITLE
No Bonjour Services on iNet app / no device recognition through Homekit apps

### ISSUE THREAD

**Issue by alext-avi** [KhaosT/HAP-NodeJS#216]
Hello,
I've been trying to determine what's going on with my setup. At this point, I have HAP-NodeJS set up trying to run the demo apps in debug. The output looks like the same output everyone else gets, which includes the warnings about libavahi. I've rebuilt a couple of times, but no luck.

The Pi is hardwired into my router, with all the other devices going over wifi. From my laptop, I can curl the accessories endpoints and get back {"status":-70401}. iNet shows the Pi, but no Bonjour services running. Conversely, my AppleTV is plugged into the router and I see it's five Bonjour services.

I'm sure there's something simple i've missed, and I've gone through updating and re-updating most of the packages.

Here's the npm version info:
{ 'hap-nodejs': '0.2.2',
  npm: '3.7.2',
  ares: '1.10.1-DEV',
  http_parser: '2.6.1',
  icu: '56.1',
  modules: '47',
  node: '5.6.0',
  openssl: '1.0.2f',
  uv: '1.8.0',
  v8: '4.6.85.31',
  zlib: '1.2.8' }

Kind of a newb on this stuff, but I've looked through just about every thread that looked remotely relevant and tried to add some tools to my toolbox to debug this and do my due diligence.

Any help is appreciated.

**Comment by alext-avi** [comment]
Looking around the codebase, I'm not sure where that status of -70401 is coming from. Is that an expected result?

**Comment by KhaosT** [comment]
Getting a response of -70401 is expected (since you don't have a secure session). On your Raspberry Pi, please make sure you installed avahi related packages.

**Comment by alext-avi** [comment]
**sudo apt-get install libavahi-compat-libdnssd-dev**
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libavahi-compat-libdnssd-dev is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

Are there other avahi libraries I should be looking for? I'll do a little research. I know the warnings complain about avahi, but it seems like that's a red herring as I see that all over the place.

**Comment by KhaosT** [comment]
libavahi-compat-libdnssd-dev should be enough. So can you see raspberry pi on your computer using bonjour browser?

**Comment by alext-avi** [comment]
Interestingly, no - at least not consistently. It was there for a moment, and when I went to expand it it disappeared. Odd. They show up on my iPhone using the iNet app for my AppleTV and TiVo, but I don't even see that on the Bonjour Browser. I don't see anything other than local services.

I went ahead and added _hap._tcp to the services plist, but that looks like it's just for naming.

I went into this expecting to need to upgrade my router, as it (according to the folks at SONOS) is at least partially responsible for intermittent pairing with my SONOS. But I'm starting to settle on the same conclusion.

**Comment by KhaosT** [comment]
@alext-avi Since bonjour works for Apple TV and TiVo, I'm not really sure if it's router's problem or bonjour related problem on RasPi. Would you mind to run this on your computer and see if iOS device can see the service?

**Comment by alext-avi** [comment]
I'll give it a shot and report back. Thanks for all the support!

**Comment by alext-avi** [comment]
Okay, I got this going in OSX El Cap. It's a macbook pro running over wifi.

Starting Core.js does not complain about libavahi, which I take as a good sign. I can now see it on the (now local) bonjour browser.  I do not see that machine at all on the iNet app, where I do see the raspberry pi (which is wired). Naturally, I don't see the devices on the Eve app.

**Comment by KhaosT** [comment]
@alext-avi just to be sure, your Mac is in the same network as other devices and there is no strange vlan there right?

**Comment by alext-avi** [comment]
All devices connected to the same router, same wifi. I'm double checking myself, but the laptop is my primary workstation from which I can ping/curl the raspberry pi, which iNet is plainly seeing. Same subnet. All three devices show up on the router's active devices list.

I think my router sucks.

**Comment by KhaosT** [comment]
If the ping works for RaspPi but bonjour doesn't work, then there might be something wrong with the router... The last thing I'd suggest you try is having iOS create a network (Personal Hotspot) and have your Mac to join that and see if Eve app can see the accessory.

**Comment by alext-avi** [comment]
Brilliant suggestion - worked like a charm. Guess it's a trip to the Apple Store for me.

You are the man, @KhaosT . 

Actiontec MI424WR-GEN2 (Verizon) is the router, for when someone else has this issue.
