### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by amz4u2nv** [KhaosT/HAP-NodeJS#222]
After an update - 
I'm getting the following errors -

Parsing accessory: UnMute_accessory.js       Parsing accessory: Upstairs_Hall_Light_accessory.js                                       /home/pi/HAP-NodeJS/lib/Advertiser.js:68         this._advertisement.updateTXTRecord(txtRecord);                                                               ^                    TypeError: undefined is not a function           at Advertiser.updateAdvertisement (/home/pi/HAP-NodeJS/lib/Advertiser.js:68:25)           at Bridge.Accessory._handlePair (/home/pi/HAP-NodeJS/lib/Accessory.js:516:20)             at HAPServer.emit (events.js:118:17)         at HAPServer._handlePairings (/home/pi/HAP-NodeJS/lib/HAPServer.js:629:10)   

Any ideas on how to resolve this.

Thanks

**Comment by KhaosT** [comment]
Please make sure you updated hap-nodejs along with underlying packages (mdns)

**Comment by amz4u2nv** [comment]
That did the trick...
sudo apt-get install libnss-mdns avahi-utils

Thanks for the quick response
