### ISSUE TITLE
Siri doesn't execute switch types

### ISSUE THREAD

**Issue by Radstake** [KhaosT/HAP-NodeJS#224]
Hi there!

First of all I really appreciate your work and support, it's amazing!

Since last (couple of) version(s), Siri won't execute my accessories of the switch type, although she says she has done so. Lightbulb still work fine. **But now the crazy part**.... In Eve all the accessories (including switch) work! So the accessories are defined correctly! And I'm sure it worked before!

My workaround for now is that I defined an automation Sequence is Eve, added a switch to it, and call the sequence from Siri.

What could be wrong?!?

**Comment by legotheboss** [comment]
Can you share your Switch accessory file?

**Comment by Radstake** [comment]
Sure; see attached file
[example.txt](https://github.com/KhaosT/HAP-NodeJS/files/364769/example.txt)
