### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by Ramzes177** [KhaosT/HAP-NodeJS#227]
When the light switch, often there Segmentation fault error
then vyvalivaetsya of debug

> 
Change: true
  EventedHTTPServer [::ffff:192.168.255.103] Muting event '3.9' notification for this connection since it originated here. +28ms
  EventedHTTPServer [::ffff:192.168.255.103] HTTP Response is finished +2ms
On Success
  EventedHTTPServer [::ffff:192.168.255.103] HTTP request: /characteristics +1s
  HAPServer [CC:22:3D:E3:CE:F6] HAP Request: PUT /characteristics +2ms
  Accessory [Node Bridge] Processing characteristic set: [{"aid":3,"iid":9,"value":false}] +2ms
  Accessory [Node Bridge] Setting Characteristic "Turn On the Light" to value false +2ms
Change: false
  EventedHTTPServer [::ffff:192.168.255.103] Muting event '3.9' notification for this connection since it originated here. +19ms
  EventedHTTPServer [::ffff:192.168.255.103] HTTP Response is finished +3ms
Off Success
  EventedHTTPServer [::ffff:192.168.255.103] HTTP request: /characteristics +1s
  HAPServer [CC:22:3D:E3:CE:F6] HAP Request: PUT /characteristics +1ms
  Accessory [Node Bridge] Processing characteristic set: [{"aid":3,"iid":9,"value":true}] +2ms
  Accessory [Node Bridge] Setting Characteristic "Turn On the Light" to value true +1ms
Change: true
  EventedHTTPServer [::ffff:192.168.255.103] Muting event '3.9' notification for this connection since it originated here. +30ms
  EventedHTTPServer [::ffff:192.168.255.103] HTTP Response is finished +1ms
Segmentation fault

> 

With what it can be connected?

**Comment by KhaosT** [comment]
Can you post the log?

**Comment by Ramzes177** [comment]
> pi@raspberrypi:~/HAP-NodeJS $ DEBUG=* node BridgedCore.js
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
HAP-NodeJS starting...
Parsing accessory: BedroomTemperatureSensor_accessory.js
Parsing accessory: KitchetTemperatureSensor_accessory.js
Parsing accessory: Light_accessory.js
Parsing accessory: Mediasana_accessory.js
Parsing accessory: RoomsTemperatureSensor_accessory.js
  EventedHTTPServer Server listening on port 51826 +0ms
  EventedHTTPServer [::ffff:192.168.255.103] New connection from client +1s
  EventedHTTPServer [::ffff:192.168.255.103] HTTP server listening on port 35340 +12ms
  EventedHTTPServer [::ffff:192.168.255.104] New connection from client +43ms
  EventedHTTPServer [::ffff:192.168.255.104] HTTP server listening on port 57978 +2ms
  EventedHTTPServer [::ffff:192.168.255.103] HTTP request: /pair-verify +890ms
  HAPServer [CC:22:3D:E3:CE:F6] HAP Request: POST /pair-verify +2ms
  HAPServer [CC:22:3D:E3:CE:F6] Pair verify step 1/2 +27ms
  EventedHTTPServer [::ffff:192.168.255.103] HTTP Response is finished +109ms
  EventedHTTPServer [::ffff:192.168.255.104] HTTP request: /pair-verify +10ms
  HAPServer [CC:22:3D:E3:CE:F6] HAP Request: POST /pair-verify +1ms
  HAPServer [CC:22:3D:E3:CE:F6] Pair verify step 1/2 +5ms
  EventedHTTPServer [::ffff:192.168.255.104] HTTP Response is finished +34ms
  EventedHTTPServer [::ffff:192.168.255.103] HTTP request: /pair-verify +36ms
  HAPServer [CC:22:3D:E3:CE:F6] HAP Request: POST /pair-verify +1ms
  HAPServer [CC:22:3D:E3:CE:F6] Pair verify step 2/2 +6ms
  HAPServer [CC:22:3D:E3:CE:F6] Client E350368D-1972-4DE8-8FA6-8677A3E505A3 verification complete +10ms
  EventedHTTPServer [::ffff:192.168.255.103] HTTP Response is finished +5ms
  EventedHTTPServer [::ffff:192.168.255.104] HTTP request: /pair-verify +3ms
  HAPServer [CC:22:3D:E3:CE:F6] HAP Request: POST /pair-verify +1ms
  HAPServer [CC:22:3D:E3:CE:F6] Pair verify step 2/2 +3ms
  HAPServer [CC:22:3D:E3:CE:F6] Client E350368D-1972-4DE8-8FA6-8677A3E505A3 verification complete +14ms
  EventedHTTPServer [::ffff:192.168.255.104] HTTP Response is finished +5ms
  EventedHTTPServer [::ffff:192.168.255.103] HTTP request: /accessories +13ms
  HAPServer [CC:22:3D:E3:CE:F6] HAP Request: GET /accessories +1ms
  EventedHTTPServer [::ffff:192.168.255.103] HTTP Response is finished +23ms
  EventedHTTPServer [::ffff:192.168.255.104] HTTP request: /accessories +88ms
  HAPServer [CC:22:3D:E3:CE:F6] HAP Request: GET /accessories +1ms
  EventedHTTPServer [::ffff:192.168.255.104] HTTP Response is finished +14ms
  EventedHTTPServer [::ffff:192.168.255.104] HTTP request: /characteristics +144ms
  HAPServer [CC:22:3D:E3:CE:F6] HAP Request: PUT /characteristics +1ms
  Accessory [Node Bridge] Processing characteristic set: [{"aid":7,"iid":10,"ev":true},{"aid":8,"iid":10,"ev":true},{"aid":3,"iid":14,"ev":true},{"aid":9,"iid":14,"ev":true},{"aid":10,"iid":10,"ev":true}] +6ms
  Accessory [Node Bridge] Registering Characteristic "Reachable" for events +5ms
  Accessory [Node Bridge] Registering Characteristic "Reachable" for events +1ms
  Accessory [Node Bridge] Registering Characteristic "Reachable" for events +1ms
  Accessory [Node Bridge] Registering Characteristic "Reachable" for events +1ms
  Accessory [Node Bridge] Registering Characteristic "Reachable" for events +1ms
  EventedHTTPServer [::ffff:192.168.255.104] HTTP Response is finished +2ms
  EventedHTTPServer [::ffff:192.168.255.103] HTTP request: /characteristics +52ms
  HAPServer [CC:22:3D:E3:CE:F6] HAP Request: PUT /characteristics +1ms
  Accessory [Node Bridge] Processing characteristic set: [{"aid":7,"iid":10,"ev":true},{"aid":8,"iid":10,"ev":true},{"aid":3,"iid":14,"ev":true},{"aid":9,"iid":14,"ev":true},{"aid":10,"iid":10,"ev":true}] +3ms
  Accessory [Node Bridge] Registering Characteristic "Reachable" for events +0ms
  Accessory [Node Bridge] Registering Characteristic "Reachable" for events +1ms
  Accessory [Node Bridge] Registering Characteristic "Reachable" for events +1ms
  Accessory [Node Bridge] Registering Characteristic "Reachable" for events +1ms
  Accessory [Node Bridge] Registering Characteristic "Reachable" for events +0ms
  EventedHTTPServer [::ffff:192.168.255.103] HTTP Response is finished +2ms
  EventedHTTPServer [::ffff:192.168.255.103] HTTP request: /characteristics +16s
  HAPServer [CC:22:3D:E3:CE:F6] HAP Request: PUT /characteristics +1ms
  Accessory [Node Bridge] Processing characteristic set: [{"aid":9,"iid":9,"ev":true}] +3ms
  Accessory [Node Bridge] Registering Characteristic "Turn On the Light" for events +1ms
  EventedHTTPServer [::ffff:192.168.255.103] HTTP Response is finished +4ms
  EventedHTTPServer [::ffff:192.168.255.103] HTTP request: /characteristics +101ms
  HAPServer [CC:22:3D:E3:CE:F6] HAP Request: PUT /characteristics +1ms
  Accessory [Node Bridge] Processing characteristic set: [{"aid":9,"iid":10,"ev":true}] +3ms
  Accessory [Node Bridge] Registering Characteristic "Doesn’t actually adjust Hue of Light" for events +1ms
  EventedHTTPServer [::ffff:192.168.255.103] HTTP Response is finished +2ms
  EventedHTTPServer [::ffff:192.168.255.103] HTTP request: /characteristics +39ms
  HAPServer [CC:22:3D:E3:CE:F6] HAP Request: PUT /characteristics +1ms
  Accessory [Node Bridge] Processing characteristic set: [{"aid":9,"iid":11,"ev":true}] +5ms
  Accessory [Node Bridge] Registering Characteristic "Doesn’t actually adjust Brightness of Light" for events +2ms
  EventedHTTPServer [::ffff:192.168.255.103] HTTP Response is finished +2ms
  EventedHTTPServer [::ffff:192.168.255.103] HTTP request: /characteristics +10ms
  HAPServer [CC:22:3D:E3:CE:F6] HAP Request: PUT /characteristics +1ms
  Accessory [Node Bridge] Processing characteristic set: [{"aid":9,"iid":12,"ev":true}] +3ms
  Accessory [Node Bridge] Registering Characteristic "Doesn’t actually adjust Saturation of Light" for events +1ms
  EventedHTTPServer [::ffff:192.168.255.103] HTTP Response is finished +2ms
  EventedHTTPServer [::ffff:192.168.255.103] HTTP request: /characteristics +15ms
  HAPServer [CC:22:3D:E3:CE:F6] HAP Request: PUT /characteristics +1ms
  Accessory [Node Bridge] Processing characteristic set: [{"aid":9,"iid":9,"ev":true}] +2ms
  Accessory [Node Bridge] Registering Characteristic "Turn On the Light" for events +2ms
  EventedHTTPServer [::ffff:192.168.255.103] HTTP Response is finished +2ms
  EventedHTTPServer [::ffff:192.168.255.103] HTTP request: /characteristics +13ms
  HAPServer [CC:22:3D:E3:CE:F6] HAP Request: PUT /characteristics +1ms
  Accessory [Node Bridge] Processing characteristic set: [{"aid":9,"iid":10,"ev":true}] +6ms
  Accessory [Node Bridge] Registering Characteristic "Doesn’t actually adjust Hue of Light" for events +1ms
  EventedHTTPServer [::ffff:192.168.255.103] HTTP Response is finished +5ms
  EventedHTTPServer [::ffff:192.168.255.103] HTTP request: /characteristics +24ms
  HAPServer [CC:22:3D:E3:CE:F6] HAP Request: PUT /characteristics +1ms
  Accessory [Node Bridge] Processing characteristic set: [{"aid":9,"iid":11,"ev":true}] +4ms
  Accessory [Node Bridge] Registering Characteristic "Doesn’t actually adjust Brightness of Light" for events +2ms
  EventedHTTPServer [::ffff:192.168.255.103] HTTP Response is finished +4ms
  EventedHTTPServer [::ffff:192.168.255.103] HTTP request: /characteristics +62ms
  HAPServer [CC:22:3D:E3:CE:F6] HAP Request: PUT /characteristics +1ms
  Accessory [Node Bridge] Processing characteristic set: [{"aid":9,"iid":12,"ev":true}] +2ms
  Accessory [Node Bridge] Registering Characteristic "Doesn’t actually adjust Saturation of Light" for events +1ms
  EventedHTTPServer [::ffff:192.168.255.103] HTTP Response is finished +2ms
  EventedHTTPServer [::ffff:192.168.255.103] HTTP request: /characteristics?id=9.8 +7ms
  HAPServer [CC:22:3D:E3:CE:F6] HAP Request: GET /characteristics?id=9.8 +1ms
  Accessory [Node Bridge] Getting value for Characteristic "Name" +11ms
  Accessory [Node Bridge] Got Characteristic "Name" value: Light Medaisana Service +3ms
  EventedHTTPServer [::ffff:192.168.255.103] HTTP Response is finished +2ms
  EventedHTTPServer [::ffff:192.168.255.103] HTTP request: /characteristics?id=9.9 +106ms
  HAPServer [CC:22:3D:E3:CE:F6] HAP Request: GET /characteristics?id=9.9 +1ms
  Accessory [Node Bridge] Getting value for Characteristic "Turn On the Light" +2ms
  Accessory [Node Bridge] Got Characteristic "Turn On the Light" value: false +1ms
  EventedHTTPServer [::ffff:192.168.255.103] HTTP Response is finished +2ms
  EventedHTTPServer [::ffff:192.168.255.103] HTTP request: /characteristics?id=9.10 +11ms
  HAPServer [CC:22:3D:E3:CE:F6] HAP Request: GET /characteristics?id=9.10 +1ms
  Accessory [Node Bridge] Getting value for Characteristic "Doesn’t actually adjust Hue of Light" +2ms
  Accessory [Node Bridge] Got Characteristic "Doesn’t actually adjust Hue of Light" value: 0 +0ms
  EventedHTTPServer [::ffff:192.168.255.103] HTTP Response is finished +2ms
  EventedHTTPServer [::ffff:192.168.255.103] HTTP request: /characteristics?id=9.11 +11ms
  HAPServer [CC:22:3D:E3:CE:F6] HAP Request: GET /characteristics?id=9.11 +1ms
  Accessory [Node Bridge] Getting value for Characteristic "Doesn’t actually adjust Brightness of Light" +4ms
  Accessory [Node Bridge] Got Characteristic "Doesn’t actually adjust Brightness of Light" value: 0 +0ms
  EventedHTTPServer [::ffff:192.168.255.103] HTTP Response is finished +2ms
  EventedHTTPServer [::ffff:192.168.255.103] HTTP request: /characteristics?id=9.12 +9ms
  HAPServer [CC:22:3D:E3:CE:F6] HAP Request: GET /characteristics?id=9.12 +1ms
  Accessory [Node Bridge] Getting value for Characteristic "Doesn’t actually adjust Saturation of Light" +2ms
  Accessory [Node Bridge] Got Characteristic "Doesn’t actually adjust Saturation of Light" value: 0 +1ms
  EventedHTTPServer [::ffff:192.168.255.103] HTTP Response is finished +1ms
  EventedHTTPServer [::ffff:192.168.255.103] HTTP request: /characteristics +13s
  HAPServer [CC:22:3D:E3:CE:F6] HAP Request: PUT /characteristics +1ms
  Accessory [Node Bridge] Processing characteristic set: [{"aid":9,"iid":9,"ev":false}] +2ms
  Accessory [Node Bridge] Unregistering Characteristic "Turn On the Light" for events +2ms
  EventedHTTPServer [::ffff:192.168.255.103] HTTP Response is finished +2ms
  EventedHTTPServer [::ffff:192.168.255.103] HTTP request: /characteristics +79ms
  HAPServer [CC:22:3D:E3:CE:F6] HAP Request: PUT /characteristics +1ms
  Accessory [Node Bridge] Processing characteristic set: [{"aid":9,"iid":10,"ev":false}] +3ms
  Accessory [Node Bridge] Unregistering Characteristic "Doesn’t actually adjust Hue of Light" for events +1ms
  EventedHTTPServer [::ffff:192.168.255.103] HTTP Response is finished +6ms
  EventedHTTPServer [::ffff:192.168.255.103] HTTP request: /characteristics +10ms
  HAPServer [CC:22:3D:E3:CE:F6] HAP Request: PUT /characteristics +1ms
  Accessory [Node Bridge] Processing characteristic set: [{"aid":9,"iid":11,"ev":false}] +6ms
  Accessory [Node Bridge] Unregistering Characteristic "Doesn’t actually adjust Brightness of Light" for events +1ms
  EventedHTTPServer [::ffff:192.168.255.103] HTTP Response is finished +2ms
  EventedHTTPServer [::ffff:192.168.255.103] HTTP request: /characteristics +19ms
  HAPServer [CC:22:3D:E3:CE:F6] HAP Request: PUT /characteristics +1ms
  Accessory [Node Bridge] Processing characteristic set: [{"aid":9,"iid":12,"ev":false}] +10ms
  Accessory [Node Bridge] Unregistering Characteristic "Doesn’t actually adjust Saturation of Light" for events +1ms
  EventedHTTPServer [::ffff:192.168.255.103] HTTP Response is finished +2ms
  EventedHTTPServer [::ffff:192.168.255.103] HTTP request: /characteristics?id=1.3 +12s
  HAPServer [CC:22:3D:E3:CE:F6] HAP Request: GET /characteristics?id=1.3 +0ms
  Accessory [Node Bridge] Getting value for Characteristic "Manufacturer" +3ms
  Accessory [Node Bridge] Got Characteristic "Manufacturer" value: Default-Manufacturer +1ms
  EventedHTTPServer [::ffff:192.168.255.103] HTTP Response is finished +3ms
  EventedHTTPServer [::ffff:192.168.255.103] HTTP request: /characteristics?id=1.4 +35ms
  HAPServer [CC:22:3D:E3:CE:F6] HAP Request: GET /characteristics?id=1.4 +1ms
  Accessory [Node Bridge] Getting value for Characteristic "Model" +17ms
  Accessory [Node Bridge] Got Characteristic "Model" value: Default-Model +1ms
  EventedHTTPServer [::ffff:192.168.255.103] HTTP Response is finished +2ms
  EventedHTTPServer [::ffff:192.168.255.103] HTTP request: /characteristics?id=1.5 +9ms
  HAPServer [CC:22:3D:E3:CE:F6] HAP Request: GET /characteristics?id=1.5 +1ms
  Accessory [Node Bridge] Getting value for Characteristic "Name" +2ms
  Accessory [Node Bridge] Got Characteristic "Name" value: Node Bridge +1ms
  EventedHTTPServer [::ffff:192.168.255.103] HTTP Response is finished +2ms
  EventedHTTPServer [::ffff:192.168.255.103] HTTP request: /characteristics?id=1.6 +8ms
  HAPServer [CC:22:3D:E3:CE:F6] HAP Request: GET /characteristics?id=1.6 +0ms
  Accessory [Node Bridge] Getting value for Characteristic "Serial Number" +2ms
  Accessory [Node Bridge] Got Characteristic "Serial Number" value: Default-SerialNumber +1ms
  EventedHTTPServer [::ffff:192.168.255.103] HTTP Response is finished +2ms
  EventedHTTPServer [::ffff:192.168.255.103] HTTP request: /characteristics +11s
  HAPServer [CC:22:3D:E3:CE:F6] HAP Request: PUT /characteristics +1ms
  Accessory [Node Bridge] Processing characteristic set: [{"aid":10,"iid":8,"ev":true}] +2ms
  Accessory [Node Bridge] Registering Characteristic "Current Temperature" for events +1ms
  EventedHTTPServer [::ffff:192.168.255.103] HTTP Response is finished +3ms
  EventedHTTPServer [::ffff:192.168.255.103] Sending HTTP event '10.8' with data: {"characteristics":[{"aid":10,"iid":8,"value":18}]} +851ms
  EventedHTTPServer [::ffff:192.168.255.103] HTTP request: /characteristics +7ms
  HAPServer [CC:22:3D:E3:CE:F6] HAP Request: PUT /characteristics +1ms
  Accessory [Node Bridge] Processing characteristic set: [{"aid":10,"iid":8,"ev":true}] +2ms
  Accessory [Node Bridge] Registering Characteristic "Current Temperature" for events +1ms
  EventedHTTPServer [::ffff:192.168.255.103] HTTP Response is finished +2ms
  EventedHTTPServer [::ffff:192.168.255.103] HTTP request: /characteristics?id=10.8 +43ms
  HAPServer [CC:22:3D:E3:CE:F6] HAP Request: GET /characteristics?id=10.8 +0ms
  Accessory [Node Bridge] Getting value for Characteristic "Current Temperature" +3ms
Получение текущей температуры!
  Accessory [Node Bridge] Got Characteristic "Current Temperature" value: 18 +839ms
  EventedHTTPServer [::ffff:192.168.255.103] HTTP Response is finished +3ms
  EventedHTTPServer [::ffff:192.168.255.103] Sending HTTP event '10.8' with data: {"characteristics":[{"aid":10,"iid":8,"value":18}]} +4s
  EventedHTTPServer [::ffff:192.168.255.103] Sending HTTP event '10.8' with data: {"characteristics":[{"aid":10,"iid":8,"value":18}]} +5s
  EventedHTTPServer [::ffff:192.168.255.103] Sending HTTP event '10.8' with data: {"characteristics":[{"aid":10,"iid":8,"value":18}]} +5s
  EventedHTTPServer [::ffff:192.168.255.103] Sending HTTP event '10.8' with data: {"characteristics":[{"aid":10,"iid":8,"value":18}]} +5s
  EventedHTTPServer [::ffff:192.168.255.103] Sending HTTP event '10.8' with data: {"characteristics":[{"aid":10,"iid":8,"value":18}]} +5s
  EventedHTTPServer [::ffff:192.168.255.103] HTTP request: /characteristics +2s
  HAPServer [CC:22:3D:E3:CE:F6] HAP Request: PUT /characteristics +1ms
  Accessory [Node Bridge] Processing characteristic set: [{"aid":10,"iid":8,"ev":false}] +12ms
  Accessory [Node Bridge] Unregistering Characteristic "Current Temperature" for events +2ms
  EventedHTTPServer [::ffff:192.168.255.103] HTTP Response is finished +6ms
  EventedHTTPServer [::ffff:192.168.255.103] HTTP request: /characteristics +5s
  HAPServer [CC:22:3D:E3:CE:F6] HAP Request: PUT /characteristics +1ms
  Accessory [Node Bridge] Processing characteristic set: [{"aid":3,"iid":9,"ev":true}] +5ms
  Accessory [Node Bridge] Registering Characteristic "Turn On the Light" for events +1ms
  EventedHTTPServer [::ffff:192.168.255.103] HTTP Response is finished +2ms
  EventedHTTPServer [::ffff:192.168.255.103] HTTP request: /characteristics +150ms
  HAPServer [CC:22:3D:E3:CE:F6] HAP Request: PUT /characteristics +1ms
  Accessory [Node Bridge] Processing characteristic set: [{"aid":3,"iid":10,"ev":true}] +2ms
  Accessory [Node Bridge] Registering Characteristic "Doesn’t actually adjust Hue of Light" for events +1ms
  EventedHTTPServer [::ffff:192.168.255.103] HTTP Response is finished +2ms
  EventedHTTPServer [::ffff:192.168.255.103] HTTP request: /characteristics +32ms
  HAPServer [CC:22:3D:E3:CE:F6] HAP Request: PUT /characteristics +1ms
  Accessory [Node Bridge] Processing characteristic set: [{"aid":3,"iid":11,"ev":true}] +7ms
  Accessory [Node Bridge] Registering Characteristic "Doesn’t actually adjust Brightness of Light" for events +11ms
  EventedHTTPServer [::ffff:192.168.255.103] HTTP Response is finished +2ms
  EventedHTTPServer [::ffff:192.168.255.103] HTTP request: /characteristics +33ms
  HAPServer [CC:22:3D:E3:CE:F6] HAP Request: PUT /characteristics +1ms
  Accessory [Node Bridge] Processing characteristic set: [{"aid":3,"iid":12,"ev":true}] +2ms
  Accessory [Node Bridge] Registering Characteristic "Doesn’t actually adjust Saturation of Light" for events +1ms
  EventedHTTPServer [::ffff:192.168.255.103] HTTP Response is finished +2ms
  EventedHTTPServer [::ffff:192.168.255.103] HTTP request: /characteristics +19ms
  HAPServer [CC:22:3D:E3:CE:F6] HAP Request: PUT /characteristics +1ms
  Accessory [Node Bridge] Processing characteristic set: [{"aid":3,"iid":9,"ev":true}] +2ms
  Accessory [Node Bridge] Registering Characteristic "Turn On the Light" for events +0ms
  EventedHTTPServer [::ffff:192.168.255.103] HTTP Response is finished +2ms
  EventedHTTPServer [::ffff:192.168.255.103] HTTP request: /characteristics +25ms
  HAPServer [CC:22:3D:E3:CE:F6] HAP Request: PUT /characteristics +1ms
  Accessory [Node Bridge] Processing characteristic set: [{"aid":3,"iid":10,"ev":true}] +2ms
  Accessory [Node Bridge] Registering Characteristic "Doesn’t actually adjust Hue of Light" for events +0ms
  EventedHTTPServer [::ffff:192.168.255.103] HTTP Response is finished +2ms
  EventedHTTPServer [::ffff:192.168.255.103] HTTP request: /characteristics +11ms
  HAPServer [CC:22:3D:E3:CE:F6] HAP Request: PUT /characteristics +0ms
  Accessory [Node Bridge] Processing characteristic set: [{"aid":3,"iid":11,"ev":true}] +2ms
  Accessory [Node Bridge] Registering Characteristic "Doesn’t actually adjust Brightness of Light" for events +1ms
  EventedHTTPServer [::ffff:192.168.255.103] HTTP Response is finished +7ms
  EventedHTTPServer [::ffff:192.168.255.103] HTTP request: /characteristics +28ms
  HAPServer [CC:22:3D:E3:CE:F6] HAP Request: PUT /characteristics +1ms
  Accessory [Node Bridge] Processing characteristic set: [{"aid":3,"iid":12,"ev":true}] +5ms
  Accessory [Node Bridge] Registering Characteristic "Doesn’t actually adjust Saturation of Light" for events +1ms
  EventedHTTPServer [::ffff:192.168.255.103] HTTP Response is finished +2ms
  EventedHTTPServer [::ffff:192.168.255.103] HTTP request: /characteristics?id=3.8 +8ms
  HAPServer [CC:22:3D:E3:CE:F6] HAP Request: GET /characteristics?id=3.8 +1ms
  Accessory [Node Bridge] Getting value for Characteristic "Name" +2ms
  Accessory [Node Bridge] Got Characteristic "Name" value: Light 1 Light Service +1ms
  EventedHTTPServer [::ffff:192.168.255.103] HTTP Response is finished +2ms
  EventedHTTPServer [::ffff:192.168.255.103] HTTP request: /characteristics?id=3.9 +8ms
  HAPServer [CC:22:3D:E3:CE:F6] HAP Request: GET /characteristics?id=3.9 +1ms
  Accessory [Node Bridge] Getting value for Characteristic "Turn On the Light" +3ms
  Accessory [Node Bridge] Got Characteristic "Turn On the Light" value: false +1ms
  EventedHTTPServer [::ffff:192.168.255.103] HTTP Response is finished +2ms
  EventedHTTPServer [::ffff:192.168.255.103] HTTP request: /characteristics?id=3.10 +8ms
  HAPServer [CC:22:3D:E3:CE:F6] HAP Request: GET /characteristics?id=3.10 +1ms
  Accessory [Node Bridge] Getting value for Characteristic "Doesn’t actually adjust Hue of Light" +3ms
  Accessory [Node Bridge] Got Characteristic "Doesn’t actually adjust Hue of Light" value: 0 +1ms
  EventedHTTPServer [::ffff:192.168.255.103] HTTP Response is finished +2ms
  EventedHTTPServer [::ffff:192.168.255.103] HTTP request: /characteristics?id=3.11 +7ms
  HAPServer [CC:22:3D:E3:CE:F6] HAP Request: GET /characteristics?id=3.11 +1ms
  Accessory [Node Bridge] Getting value for Characteristic "Doesn’t actually adjust Brightness of Light" +2ms
  Accessory [Node Bridge] Got Characteristic "Doesn’t actually adjust Brightness of Light" value: 0 +2ms
  EventedHTTPServer [::ffff:192.168.255.103] HTTP Response is finished +2ms
  EventedHTTPServer [::ffff:192.168.255.103] HTTP request: /characteristics?id=3.12 +16ms
  HAPServer [CC:22:3D:E3:CE:F6] HAP Request: GET /characteristics?id=3.12 +1ms
  Accessory [Node Bridge] Getting value for Characteristic "Doesn’t actually adjust Saturation of Light" +3ms
  Accessory [Node Bridge] Got Characteristic "Doesn’t actually adjust Saturation of Light" value: 0 +1ms
  EventedHTTPServer [::ffff:192.168.255.103] HTTP Response is finished +2ms
  EventedHTTPServer [::ffff:192.168.255.103] HTTP request: /characteristics +3s
  HAPServer [CC:22:3D:E3:CE:F6] HAP Request: PUT /characteristics +2ms
  Accessory [Node Bridge] Processing characteristic set: [{"aid":3,"iid":9,"value":true}] +2ms
  Accessory [Node Bridge] Setting Characteristic "Turn On the Light" to value true +2ms
Change: true
  EventedHTTPServer [::ffff:192.168.255.103] Muting event '3.9' notification for this connection since it originated here. +57ms
  EventedHTTPServer [::ffff:192.168.255.103] HTTP Response is finished +3ms
On Success
  EventedHTTPServer [::ffff:192.168.255.103] HTTP request: /characteristics +11s
  HAPServer [CC:22:3D:E3:CE:F6] HAP Request: PUT /characteristics +2ms
  Accessory [Node Bridge] Processing characteristic set: [{"aid":3,"iid":9,"value":false}] +3ms
  Accessory [Node Bridge] Setting Characteristic "Turn On the Light" to value false +2ms
Change: false
  EventedHTTPServer [::ffff:192.168.255.103] Muting event '3.9' notification for this connection since it originated here. +36ms
  EventedHTTPServer [::ffff:192.168.255.103] HTTP Response is finished +3ms
Off Success
  EventedHTTPServer [::ffff:192.168.255.103] HTTP request: /characteristics +3s
  HAPServer [CC:22:3D:E3:CE:F6] HAP Request: PUT /characteristics +2ms
  Accessory [Node Bridge] Processing characteristic set: [{"aid":3,"iid":9,"value":true}] +2ms
  Accessory [Node Bridge] Setting Characteristic "Turn On the Light" to value true +2ms
Change: true
  EventedHTTPServer [::ffff:192.168.255.103] Muting event '3.9' notification for this connection since it originated here. +28ms
  EventedHTTPServer [::ffff:192.168.255.103] HTTP Response is finished +2ms
On Success
  EventedHTTPServer [::ffff:192.168.255.103] HTTP request: /characteristics +1s
  HAPServer [CC:22:3D:E3:CE:F6] HAP Request: PUT /characteristics +2ms
  Accessory [Node Bridge] Processing characteristic set: [{"aid":3,"iid":9,"value":false}] +2ms
  Accessory [Node Bridge] Setting Characteristic "Turn On the Light" to value false +2ms
Change: false
  EventedHTTPServer [::ffff:192.168.255.103] Muting event '3.9' notification for this connection since it originated here. +19ms
  EventedHTTPServer [::ffff:192.168.255.103] HTTP Response is finished +3ms
Off Success
  EventedHTTPServer [::ffff:192.168.255.103] HTTP request: /characteristics +1s
  HAPServer [CC:22:3D:E3:CE:F6] HAP Request: PUT /characteristics +1ms
  Accessory [Node Bridge] Processing characteristic set: [{"aid":3,"iid":9,"value":true}] +2ms
  Accessory [Node Bridge] Setting Characteristic "Turn On the Light" to value true +1ms
Change: true
  EventedHTTPServer [::ffff:192.168.255.103] Muting event '3.9' notification for this connection since it originated here. +30ms
  EventedHTTPServer [::ffff:192.168.255.103] HTTP Response is finished +1ms
Segmentation fault

>

**Comment by KhaosT** [comment]
Not really sure... never see something like this. What's the hardware running the homebridge?

**Comment by Ramzes177** [comment]
this error after I add a temperature sensor
