### ISSUE TITLE
Evohome characteristics

### ISSUE THREAD

**Issue by luc-ass** [KhaosT/HAP-NodeJS#228]
Hey there, I just found this: 

https://gist.github.com/gomfunkel/b1a046d729757120907c

gomfunkel decoded the "evohome services" wich can be used across HomeKit and specifically in Evohomes App. Would it be reasonable to include those? I would like to use them in HomeKit and as I understand it HAP-NodeJS is the basis of Homebridge... #

**Comment by justme-1968** [comment]
i think the final format is not known at the moment

but there is already a diskussion about a possible inclusion here: https://github.com/KhaosT/HAP-NodeJS/issues/223#issuecomment-193247136

**Comment by luc-ass** [comment]
Thanks
