### ISSUE TITLE
Light disconnects after some time

### ISSUE THREAD

**Issue by MiniguyBrendan** [KhaosT/HAP-NodeJS#229]
Hi,

I have this working great for a fan in my room (hats off to you developers, really cool!) but my light disconnects after 10-30 minutes. The fan never disconnects, but the light does. I'm running on a raspberry pi. I'm using the Light_accessory.js file as a base.

Occasionally, the whole thing goes down entirely. Is there a way to check logs or do I have to run in debug mode?

Thanks.

**Comment by legotheboss** [comment]
Try clearing the persist directory and also add a cron job that stops the node and restarts every hour or two. That has solved a lot of my issues on all my nodes.

**Comment by KhaosT** [comment]
You can try to run the BridgedCore with DEBUG env var, like

DEBUG=* node BridgedCore.js

**Comment by MiniguyBrendan** [comment]
@KhaosT  Alright, I'll try to run with debug. Also I'm running Core.js instead of BridgedCore because I want separate devices. Could that also be causing problems?

@legotheboss I'd rather not have to restart node, could cause no service for a few seconds. I know it shouldn't matter but I like the idea of everything just working.

**Comment by KhaosT** [comment]
It shouldn't matter

**Comment by MiniguyBrendan** [comment]
Okay, thanks. Running with the the environment variable now.

**Comment by MiniguyBrendan** [comment]
Hmm, doesn't show any error. Just stops showing up on app, and Siri refuses to turn it on/off

**Comment by KhaosT** [comment]
Huh interesting, if that's the case, you might have to check the error log on iOS side see what's the error HomeKit produce…

**Comment by MiniguyBrendan** [comment]
Just a thought, but could the pi be losing its internet connection? No errors are produced by HMCatalog and there are no errors when I run with DEBUG=*

If the pi IS losing it's internet connection (it's connected with WiFi, so it's possible), any tips on keeping it up?

**Comment by julianvollmer** [comment]
Just another thought, are you using access points and you phone is connected to a different access point?

**Comment by MiniguyBrendan** [comment]
Good idea, but I already checked that. I do have two different networks (2.4 GHz and 5.0 GHz) but they are both connected to the 2.4 GHz network. Any other ideas?

Thanks!

**Comment by MiniguyBrendan** [comment]
UPDATE: I think I got it, but I'm not going to close until I'm sure. I was using WiFi, and it appears that power save mode was on (via 8912.conf). Disabling it seems to have fixed it!

**Comment by MiniguyBrendan** [comment]
Yup, fixed. The Pi had wifi power saving on. Thanks!
