### ISSUE TITLE
Change Default PIN?

### ISSUE THREAD

**Issue by michaeldpotter** [KhaosT/HAP-NodeJS#238]
Is there a way to change the default PIN that is used?

**Comment by KhaosT** [comment]
Change [this](https://github.com/KhaosT/HAP-NodeJS/blob/master/BridgedCore.js#L36)

**Comment by michaeldpotter** [comment]
What if I'm just running the Core.js? I don't see that parameter in that file.

**Comment by KhaosT** [comment]
@michaeldpotter depends on accessory file, like for the sample light one, it's [here](https://github.com/KhaosT/HAP-NodeJS/blob/master/accessories/Light_accessory.js#L34)

**Comment by michaeldpotter** [comment]
Ah! Dang it, now I feel foolish. Thanks for your quick response and help!
