### ISSUE TITLE
Remote Access

### ISSUE THREAD

**Issue by reejinbouk** [KhaosT/HAP-NodeJS#246]
Hi, please tell me, whats wrong?
i have apple TV 3gen, download HAP-NodeJS, and:
1. i'm start the BridgedCore
2. then pair it with iPhone via WiFi
3. then try to disable WiFi
4. then try to connect via cellular data transfer
And it's not connecting

Try the same with Homebridge - and it's working
Whats wrong in HAP?
thank You

**Comment by KhaosT** [comment]
Homebridge and HAP-NodeJS shared the same core. If homebridge works but HAP-NodeJS doesn't, it's most likely to be a problem with HomeKit. For some reasons I guess Apple TV didn't get the notification from iOS about the newly paired accessory.
