### ISSUE TITLE
Lock Accessory for Door-buzzer

### ISSUE THREAD

**Issue by svh1985** [KhaosT/HAP-NodeJS#265]
Hi,

I'm trying to modify the standard Lock Accessory to control my apartment's Door-buzzer.
I hooked up the buzz-unlock-mechanics to an Arduino, and the Arduino is hooked up to a Relay which connects 2 wires for opening the door.

In this situation the door does not have an actual Secured and Unsecured reading. Thats because once the two wires have been connected, the door can be pushed open, and when the door falls shut again, you guessed it... it's locked again.

So what I was thinking; once I've executed the unlock command, the door should unlock (UNSECURED) for 2 seconds and after those two seconds, it the lock should automatically reset it's status back to the SECURED state again.

I've tried all sorts of code modifications but I could not get it to work.

Can you please point me in the right direction?

Thank you very much!!

Cheers!

Something I've tried as an example:
```
if (value == Characteristic.LockTargetState.UNSECURED) {
      FRONT_DOOR_LOCK.unlock();
    
      // now we want to set our lock's "actual state" to be unsecured so it shows as unlocked in iOS apps
      lock
        .getService(Service.LockMechanism)
        .setCharacteristic(Characteristic.LockCurrentState, Characteristic.LockCurrentState.UNSECURED);

      FRONT_DOOR_LOCK.lock();      
      // now we want to set our lock's "actual state" to be locked so it shows as open in iOS apps
      
      lock
        .getService(Service.LockMechanism)
        .setCharacteristic(Characteristic.LockCurrentState, Characteristic.LockCurrentState.SECURED);

      callback(); // Our fake Lock is synchronous - this value has been successfully set
    }
```

**Comment by joachimvenaas** [comment]
Try this:

if (value == Characteristic.LockTargetState.UNSECURED) {
      FRONT_DOOR_LOCK.unlock();

      // now we want to set our lock's "actual state" to be unsecured so it shows as unlocked in iOS apps
      lock
        .getService(Service.LockMechanism)
        .setCharacteristic(Characteristic.LockCurrentState, Characteristic.LockCurrentState.UNSECURED);

      FRONT_DOOR_LOCK.lock();      
      // now we want to set our lock's "actual state" to be locked so it shows as open in iOS apps
setTimeout(function(){
      lock
        .getService(Service.LockMechanism)
        .setCharacteristic(Characteristic.LockCurrentState, Characteristic.LockCurrentState.SECURED);
}, 2000);

      callback(); // Our fake Lock is synchronous - this value has been successfully set
    }

**Comment by svh1985** [comment]
Hi joachimvenaas,

Thanks for your reply, I've tried your suggestion, and it works partially. The only part that doesn't work is the update back to the iPhone/HomeKit about the lock's state. Do you know how we can update the lock's state back to the iPhone?

Thanks!

**Comment by svh1985** [comment]
Update: 
The code as posted above seems to work; if I tap the unlock button on my iPhone it sends a MQTT message to the Arduino which returns a MQTT message saying that the lock is UNSECURED.
After receiving that UNSECURED message, the nodejs code performs a Lock after 2 seconds.

The thing is that the status isn't update back to the phone/HomeKit, it (weirdly enough) says "Unlocking..." even tho it actually performed the lock action. 

ps. I'm testing it on iOS 10b3 on both my iPhone 6 and my Apple TV 4

Screenshots:
![img_0640](https://cloud.githubusercontent.com/assets/5213210/17037119/b216104c-4f8f-11e6-89aa-1bef2119f8ee.jpg)
![img_0639](https://cloud.githubusercontent.com/assets/5213210/17037120/b2333852-4f8f-11e6-801d-a3c01003a0dd.jpg)

**Comment by joachimvenaas** [comment]
Hi, sorry I could not be more to help, I'm on vacation right now. But i have a simular lock back home and i want to make autolock myself

**Comment by svh1985** [comment]
No problem, maybe we can give it a try when you're back?!

Enjoy your holidays!

**Comment by joachimvenaas** [comment]
I've tried some more on this case, but no luck. I have a Yale Doorman v2 and I have feedback status, but that doesn't help. After the door has auto-locked itself and i open the Home-app the icon says "Unlocking..." like your picture. It works fine if i just use Siri: if I ask Siri "is the door locked?" after the door has locked itself she replies that the door is locked.

**Comment by marcelkordek** [comment]
Hi, this is my final Solution:
```
LockAccessory.prototype.setState = function(state, callback) {
  var lockState = (state == Characteristic.LockTargetState.SECURED) ? "lock" : "unlock";
  var update = (state == Characteristic.LockTargetState.SECURED) ? true : false;
    
  this.log("Set state to %s", lockState);

  request.get({
    url: this.url,
    qs: { option: "setState", apiKey: this.apiKey, lockid: this.lockID, delay: this.delay, state: lockState }
  }, function(err, response, body) {

    if (!err && response.statusCode == 200) {
      this.log("State change complete.");

      // we succeeded, so update the "current" state as well
      var currentState = (state == Characteristic.LockTargetState.SECURED) ?
        Characteristic.LockCurrentState.SECURED : Characteristic.LockCurrentState.UNSECURED;
              
      lockservice
        .setCharacteristic(Characteristic.LockCurrentState, currentState);
        
    if(!update){
      setTimeout(function(){
        lockservice
        .setCharacteristic(Characteristic.LockTargetState, Characteristic.LockTargetState.SECURED);
        update = true;  
      }, this.delay);
    }
        
      callback(null, state); // success
    }
    else {
      this.log("Error setting state (status code %s): %s", response.statusCode, err);
      callback(err || new Error("Error setting lock state."));
    }
  }.bind(this));
},
```

Everything works like expected. I hope this helps you further.

**Comment by benzman81** [comment]
@svh1985 did you solve the problem shown by your image where it states "Unlocking..." instead of the new state? I wrote a homebridge-plugin for the smartlock Nuki and have the same issue with the Home App in iOS 10 when I set a new value to the characteristic in the background (i.e. through a webhook ). I am asking this, because I think this might be an issue of the Home App as the Eve App works as desired. But may be I be missing something to get it work correctly in the Home App.

**Comment by KhaosT** [comment]
@benzman81 Home app will try to match current state characteristic with target state characteristic. If your plugin returns value that doesn't match, then Home app will show a transitional state "xxxing..." Please fix your plugin to return the expected value.

**Comment by benzman81** [comment]
@KhaosT I only set the Characteristic.LockCurrentState from my server receiving the webhook call. Do I need to update target state as well?

**Comment by KhaosT** [comment]
@benzman81 Yep

**Comment by benzman81** [comment]
@KhaosT could you please help me and have look at the setState method at https://github.com/benzman81/homebridge-nukiio/blob/master/index.js#L90 ? In Line 103 I want to change the lock back to secured state using setTimeout. From my understanding this will trigger the setState method again. Thats why I use the context and in line 113 i set the current state to match the target state from the setTimeout method. Now, I get notifications from "lock a is unlocked" and the a little later "lock a is locked", which is fine. But if the home app is open, I still get the "xxxing...". Any ideas?

**Comment by benzman81** [comment]
@KhaosT shame on me. I forgot to call a callback. The only thing now where I got the "xxxing" is when I want to set the current state UNKNOWN in case of an error. There is no target state I can map it to.

**Comment by sutterline** [comment]
_This code works for me, when i push button in app to unlock, after two seconds the state changes to closed._

var FAKE_LOCK = {
  locked: true,
  lock: function() { 
    console.log("Locking the lock!");
    FAKE_LOCK.locked = true;
    
    lock
        .getService(Service.LockMechanism)
        .setCharacteristic(Characteristic.LockTargetState, Characteristic.LockTargetState.SECURED);
  },
  unlock: function() { 
    console.log("Unlocking the lock!");
    cmd.run('sudo python /home/pi/HAP-NodeJS/python/cancela.py');
    FAKE_LOCK.locked = false;
  },
  identify: function() {
    console.log("Identify the lock!");
  }
}

lock
  .addService(Service.LockMechanism, "Fake Lock") // services exposed to the user should have "names" like "Fake Light" for us
  .setCharacteristic(Characteristic.LockTargetState, Characteristic.LockTargetState.SECURED)
  .getCharacteristic(Characteristic.LockTargetState)
  .on('set', function(value, callback) {
    
   if (value == Characteristic.LockTargetState.UNSECURED) {
      FAKE_LOCK.unlock();
      callback(); // Our fake Lock is synchronous - this value has been successfully set

      // now we want to set our lock's "actual state" to be unsecured so it shows as unlocked in iOS apps
      lock
        .getService(Service.LockMechanism)
        .setCharacteristic(Characteristic.LockCurrentState, Characteristic.LockCurrentState.UNSECURED);
    
    setTimeout(function(){//wait 2 seg, and call close function to target secured state
		
		FAKE_LOCK.lock();
		
	},2000);
    
    }
    else if (value == Characteristic.LockTargetState.SECURED) {
      
      callback(); // Our fake Lock is synchronous - this value has been successfully set
      
      // now we want to set our lock's "actual state" to be locked so it shows as open in iOS apps
      lock
        .getService(Service.LockMechanism)
        .setCharacteristic(Characteristic.LockCurrentState, Characteristic.LockCurrentState.SECURED);
    }
  });

**Comment by davidhusselmann** [comment]
In case this helps anyone, I have hacked my way around this by editing `LockMechanism.js` and removing the call to set `initial` to false.  This has the effect of always setting the `LockTargetState` to the real lock state, and IOS doesn't show "Locking" for me anymore if I open my lock by hand.
