### ISSUE TITLE
Returns request twice

### ISSUE THREAD

**Issue by TheNoim** [KhaosT/HAP-NodeJS#266]
Hello Guys,
I tried HAP out since yesterday, and now I have my first problem. It isn't really a bug (if any its a bug in my brain xD). First I will try to explain my problem. I have registered two lamps which triggers a http request with the node module "request". But If i open the HomeKit App he will only return one response two times. I am logging this in the console (and you can see it in the app, because If one Light is one, he will display that both Lights are on). It looks like this:
[http://imgur.com/a/m1Agy](url)

My code looks like this:
`var Accessory = require('../').Accessory;
var Service = require('../').Service;
var Characteristic = require('../').Characteristic;
var uuid = require('../').uuid;
var request = require('request');
var LICHT_DG = {
    powerOn: false,

```
setPowerOn: function (on) {
    console.log(on);
    var stat;
    if (on == 1) {
        stat = "an";
    } else {
        stat = "aus";
    }
    request('http://ip:1337/set/pw/Licht_DG=' + stat, function (error, response, body) {
        if (!error && response.statusCode == 200) {
            console.log(body);
            LICHT_DG.powerOn = on;
        }
    });

},
identify: function () {
    console.log("Identify the Licht_DG!");
}
```

};
var lightUUID = uuid.generate('hap-nodejs:accessories:light');
var light_DG = exports.accessory = new Accessory('Light_DG', lightUUID);
light_DG.username = "1C:2B:3C:4U:5E:FH";
light_DG.pincode = "031-45-154";
light_DG
    .getService(Service.AccessoryInformation)
    .setCharacteristic(Characteristic.Manufacturer, "Homematic")
    .setCharacteristic(Characteristic.Model, "No2")
    .setCharacteristic(Characteristic.SerialNumber, "A1S2NASF88QW");
light_DG.on('identify', function (paired, callback) {
    LICHT_DG.identify();
    callback();
});
light_DG
    .addService(Service.Lightbulb, "Dachboden Licht")
    .getCharacteristic(Characteristic.On)
    .on('set', function (value, callback) {
        LICHT_DG.setPowerOn(value);
        callback();
    });
var _licht_dg_function = function (cb) {
    var err = null;

```
var d = request('http://ip:1337/get/pw/Licht_DG', function (error, response, body) {
    if (!error && response.statusCode == 200) {
        console.log(body);
        var ajson = JSON.parse(body);
        cb(err, ajson.state);
    }
});
```

};
light_DG
    .getService(Service.Lightbulb)
    .getCharacteristic(Characteristic.On)
    .on('get', _licht_dg_function);

`
The code of 'Steckdose_Nils_Fenster_links' is the same. To sum up:
This Lights are registered:
Steckdose_Nils_Fenster_links & Licht_DG.
But he returns twice the response of Steckdose_Nils_Fenster_links. I think it is a simple logic error by myself but I can't find it.

Yours sincerely Nils

**Comment by joachimvenaas** [comment]
Maybe try a different UUID?

**Comment by TheNoim** [comment]
I already tried this.
In this pastbin i marked everything which is uniq for every code:
http://pastebin.com/JXq0SdCj

**Comment by TheNoim** [comment]
close
