### ISSUE TITLE
ip camera

### ISSUE THREAD

**Issue by Ramzes177** [KhaosT/HAP-NodeJS#268]
how to display image through camera ip HAP-nodejs?

**Comment by leoneleone** [comment]
Not possible until someone adds the new HomeKit Camera type with its relevant associated coding to HAP-NodeJS. 
You'll have to wait until someone has the time to do that. 
Probably have to wait until iOS 10 is released before anyone with the knowledge takes an interest 😊

**Comment by xmuskrat** [comment]
Well, that's only a couple days away now.

**Comment by RienduPre** [comment]
I would be interested to see this too

**Comment by PatchworkBoy** [comment]
Watch the IP-cam branch...  https://github.com/KhaosT/HAP-NodeJS/tree/ip-cam

**Comment by leoneleone** [comment]
@PatchworkBoy
Have you been able to add an ip camera to HomeKit using the branch above?

Any idea how I can add my camera to config.json and what parameters I would need to define?

Thanks

**Comment by PatchworkBoy** [comment]
Nope - pointless til kT says s'all there n' ready for use.

**Comment by KhaosT** [comment]
Alright, the camera support is in v0.4.0

I'll try to document things a little bit later but the general idea is for developer to copy Camera.js to their own project and modify the Camera.js to handle snapshot request and streaming request.

**Comment by leoneleone** [comment]
@KhaosT 
Thanks for the update. 
Can you please elaborate on the modifications which need to be done, etc.?
Also, do the ip camera streams have to be rtp encoded from the ip camera side, or can a developer configure a http/https video stream to work?
Some documentation would be very useful. Or at least some examples

**Comment by KhaosT** [comment]
@leoneleone you can find document at [here](https://github.com/KhaosT/HAP-NodeJS/wiki/IP-Camera). HomeKit on iOS side requires RTP stream but technically with the help of ffmpeg, HLS should also be possible.
