### ISSUE TITLE
Config for double switch

### ISSUE THREAD

**Issue by drozdz** [KhaosT/HAP-NodeJS#269]
Hello. I'm building my own smartHome. I'm using PythonShell to run python scripts, which communicate by wireless, but to the point.

I have double swich in home (like this: https://techniczny.files.wordpress.com/2013/06/garaz-wlacznik.jpg)

And I don't know how to create good light_accessory.js Can you help me ?

**Comment by drozdz** [comment]
somebody knows?

**Comment by chaeplin** [comment]
I don't know how make multiple lights with one light_accessory.js, but with multiple light_accessory.js(mqtt). Check https://github.com/chaeplin/HAP-NodeJS/tree/master/accessories

With homebridge https://github.com/chaeplin/homebridge-mqttlightbulb/blob/master/config.json

**Comment by drozdz** [comment]
Are you suggesting that I need to create double files?

**Comment by chaeplin** [comment]
@drozdz As switch has one characteristic  "this.addCharacteristic(Characteristic.On);", I think making two files with different name much easier. 
https://github.com/KhaosT/HAP-NodeJS/blob/master/lib/gen/HomeKitTypes.js#L2290-L2304

**Comment by drozdz** [comment]
Yes, this is the easiest way, but not comfortable when you need to swtich on or off two lights and switch between two other devices

**Comment by amz4u2nv** [comment]
Make a scene or call both lights in your script.. If it's via http that you switch it on or off

**Comment by drozdz** [comment]
@amz4u2nv but you know, sometimes I want to switch separately or together

**Comment by EricHigdon** [comment]
You can still switch the lights separately if you are using scenes. It sounds like you would just need one scene to turn them both on and one scene to turn them both off.

**Comment by drozdz** [comment]
OK. Sounds good. I try to do this
