### ISSUE TITLE
iCloud integration in HAP-NodeJS with MFi chip

### ISSUE THREAD

**Issue by nurulbitcanny** [KhaosT/HAP-NodeJS#270]
Hi we are working one homekit and we are registered with MFi program. We have our existing smart home hub which works with ZWave and we are using your HAP-NodeJS library to expose our existing devices through your bridge. Now we need to access it through the iCloud and defiantly we are going to use MFi chip for authentication kindly help us to integrate it with your library or kindly connect us the apple concerned person if you know.

**Comment by KhaosT** [comment]
Please contact your MFi representative for more information regarding to HAP over iCloud.
