### ISSUE TITLE
Add new command

### ISSUE THREAD

**Issue by blayote** [KhaosT/HAP-NodeJS#275]
Can I add a new command to Siri? I would like to include "opens the blinds" (window) for example. Thank you very much

**Comment by shawnlobo96** [comment]
You could just change the name of the device in the app you use. I've not used iOS 10 so I have no clue how to do the same in iOS 10 home app. ![](http://i.imgur.com/s19POjd.jpg)

**Comment by blayote** [comment]
I use Homekit and I tried to rename the service, but Siri decrile to the new service name, does nothing. What application is to capture?
Thanks for answering.

**Comment by shawnlobo96** [comment]
This application is called Eve

**Comment by blayote** [comment]
Thanks, I'll try with it to see if it works

**Comment by blayote** [comment]
Thank you very much!!!! with this application I am able to put name I want my device , homekit not allowed to do that , or at least , I do not run
