### ISSUE TITLE
Access accessories from external network

### ISSUE THREAD

**Issue by OczkoSX** [KhaosT/HAP-NodeJS#276]
Hi. Is it possible to access accessories from other network? For example i have Pi connectes to Wi-Fi and wants to control home by using lte.

**Comment by justme-1968** [comment]
you have to have a gen3 or gen4 apple tv for external access. or with ios10 an ipad.

**Comment by OczkoSX** [comment]
There is no way to not use tv/iPad?

Wysłane z iPhone'a

Dnia 25.08.2016 o godz. 11:52 justme-1968 <notifications@github.com> napisał(a):

**Comment by justme-1968** [comment]
no
