### ISSUE TITLE
IOS 10 Apple TV

### ISSUE THREAD

**Issue by Ramzes177** [KhaosT/HAP-NodeJS#280]
Hi,
After Apple TV upgrade ios 10 no longer go through the LTE data, it's like you can fix it?

**Comment by legotheboss** [comment]
Try to troubleshoot with the steps in this [link](https://support.apple.com/en-us/HT207057)...

**Comment by legotheboss** [comment]
Do you have an Apple TV 3 or Apple TV 4? Apple TV 3's Remote Access support has been discontinued with iOS 10.

**Comment by chaeplin** [comment]
I have an Apple TV 3, and Remote Access is working with IOS 10, though automation is not working.
https://9to5mac.com/2016/09/16/homekit-ios-10-remote-access-automation-apple-tv-2fa/

**Comment by legotheboss** [comment]
oh ok. If you enabled 2FA authentication and fixed your issue, request @KhaosT to close this issue...

**Comment by FradSer** [comment]
Now this issue can be closed.
