### ISSUE TITLE
Couldn't add accessories on mipsel (little-endien) openwrt

### ISSUE THREAD

**Issue by benwwchen** [KhaosT/HAP-NodeJS#284]
**Please see the update on the bottom of this post first.**

I cross compiled and got it running on my mipsel (little endien) router (running openwrt). ~~But it couldn't pair:~~
```
#DEBUG=* node BridgedCore.js
HAP-NodeJS starting...
Parsing accessory: Fan_accessory.js
Parsing accessory: GarageDoorOpener_accessory.js
Parsing accessory: Light_accessory.js
Parsing accessory: Lock_accessory.js
Parsing accessory: TemperatureSensor_accessory.js
Parsing accessory: Thermostat_accessory.js
  Accessory [Node Bridge] Creating new AccessoryInfo for our HAP server +0ms
  Accessory [Node Bridge] Creating new IdentifierCache +47ms
  EventedHTTPServer Server listening on port 51826 +225ms
  EventedHTTPServer [192.168.1.205] New connection from client +2m
  EventedHTTPServer [192.168.1.205] HTTP server listening on port 58728 +7ms
  EventedHTTPServer [192.168.1.205] HTTP request: /pair-setup +89ms
  HAPServer [CC:22:3D:E3:CE:F6] HAP Request: POST /pair-setup +3ms
  HAPServer [CC:22:3D:E3:CE:F6] Pair step 1/5 +28ms
  EventedHTTPServer [192.168.1.205] HTTP Response is finished +203ms
  EventedHTTPServer [192.168.1.205] HTTP request: /pair-setup +17s
  HAPServer [CC:22:3D:E3:CE:F6] HAP Request: POST /pair-setup +3ms
  HAPServer [CC:22:3D:E3:CE:F6] Pair step 2/5 +11ms
  HAPServer [CC:22:3D:E3:CE:F6] Error while checking pincode: client did not use the same password +541ms
  EventedHTTPServer [192.168.1.205] HTTP Response is finished +10ms
  EventedHTTPServer [192.168.1.205] HTTP request: /pair-setup +9s
  HAPServer [CC:22:3D:E3:CE:F6] HAP Request: POST /pair-setup +2ms
  HAPServer [CC:22:3D:E3:CE:F6] Pair step 1/5 +7ms
  EventedHTTPServer [192.168.1.205] HTTP Response is finished +131ms
  EventedHTTPServer [192.168.1.205] HTTP request: /pair-setup +173ms
  HAPServer [CC:22:3D:E3:CE:F6] HAP Request: POST /pair-setup +2ms
  HAPServer [CC:22:3D:E3:CE:F6] Pair step 2/5 +6ms
  HAPServer [CC:22:3D:E3:CE:F6] Error while checking pincode: client did not use the same password +639ms
  EventedHTTPServer [192.168.1.205] HTTP Response is finished +4ms
```
When I cross compiled bignum, I added the `openssl_config_path` for `mipsel` in `binding.gyp` as `elf`/ `mipsel` / `mips`. All of them can compile but none of them works (not able to pair).

By the way, the Identify action seems working fine:
```
  EventedHTTPServer [192.168.1.205] New connection from client +4s
  EventedHTTPServer [192.168.1.205] HTTP server listening on port 56276 +15ms
  EventedHTTPServer [192.168.1.205] HTTP request: /identify +99ms
  HAPServer [3C:2B:3D:E3:CE:F6] HAP Request: POST /identify +4ms
  Accessory [Node Bridge] Identification request +26ms
Node Bridge identify
  HAPServer [3C:2B:3D:E3:CE:F6] Identification success +5ms
  EventedHTTPServer [192.168.1.205] HTTP Response is finished +32ms
```

~~I also ran the tests in `node_modules/srp/test` and they all passed:~~
```
#node test_srp.js
······· ✓ OK » 7 honored (20.512s)
#node test_rfc_5054.js
········ ✓ OK » 8 honored (0.853s)
#node test_picl_vectors.js
···· ✓ OK » 4 honored (18.762s)
```
~~Does it mean that the srp module should work correctly? If so, what else could be the cause of this problem?~~
~~(Weirdly, on my Mac, where I can run HAP-NodeJS perfectly, the srp tests failed a lot:~~
```
node test_srp.js
·✗✗✗✗·✗
(details)
✗ Errored » 2 honored ∙ 5 errored
node test_rfc_5054.js
····✗··✗
(details)
✗ Errored » 6 honored ∙ 2 errored
node test_picl_vectors.js
✗✗✗✗
(details)
✗ Errored » 4 errored
```
~~I'm so confused.😖)~~

Could anyone please tell me how to debug?

**Update: just reinstall (compiled) it (with `openssl_config_path` set to `arm`) and this time it stucks at getting accessories:**
```
#DEBUG=* node BridgedCore.js
HAP-NodeJS starting...
Parsing accessory: Fan_accessory.js
Parsing accessory: GarageDoorOpener_accessory.js
Parsing accessory: Light_accessory.js
Parsing accessory: Lock_accessory.js
Parsing accessory: TemperatureSensor_accessory.js
Parsing accessory: Thermostat_accessory.js
  Accessory [Node Bridge] Creating new AccessoryInfo for our HAP server +0ms
  Accessory [Node Bridge] Creating new IdentifierCache +56ms
  EventedHTTPServer Server listening on port 51826 +295ms
  EventedHTTPServer [192.168.1.205] New connection from client +21s
  EventedHTTPServer [192.168.1.205] HTTP server listening on port 34095 +9ms
  EventedHTTPServer [192.168.1.205] HTTP request: /pair-setup +122ms
  HAPServer [C8:72:3D:E3:CE:F6] HAP Request: POST /pair-setup +4ms
  HAPServer [C8:72:3D:E3:CE:F6] Pair step 1/5 +37ms
  EventedHTTPServer [192.168.1.205] HTTP Response is finished +1s
  EventedHTTPServer [192.168.1.205] HTTP request: /pair-setup +2s
  HAPServer [C8:72:3D:E3:CE:F6] HAP Request: POST /pair-setup +4ms
  HAPServer [C8:72:3D:E3:CE:F6] Pair step 2/5 +13ms
  EventedHTTPServer [192.168.1.205] HTTP Response is finished +2s
  EventedHTTPServer [192.168.1.205] HTTP request: /pair-setup +43ms
  HAPServer [C8:72:3D:E3:CE:F6] HAP Request: POST /pair-setup +2ms
  HAPServer [C8:72:3D:E3:CE:F6] Pair step 3/5 +13ms
  HAPServer [C8:72:3D:E3:CE:F6] Pair step 4/5 +204ms
  HAPServer [C8:72:3D:E3:CE:F6] Pair step 5/5 +43ms
  Accessory [Node Bridge] Paired with client C236D52B-2996-44B5-BFD2-377238F4E1E1 +137ms
  EventedHTTPServer [192.168.1.205] HTTP Response is finished +19ms
  EventedHTTPServer [192.168.1.205] Client connection closed +118ms
  EventedHTTPServer [192.168.1.205] New connection from client +19ms
  EventedHTTPServer [192.168.1.205] HTTP server listening on port 40816 +6ms
  EventedHTTPServer [192.168.1.205] HTTP connection was closed +24ms
  EventedHTTPServer [192.168.1.205] HTTP server was closed +6ms
  EventedHTTPServer [192.168.1.205] HTTP request: /pair-verify +20ms
  HAPServer [C8:72:3D:E3:CE:F6] HAP Request: POST /pair-verify +3ms
  HAPServer [C8:72:3D:E3:CE:F6] Pair verify step 1/2 +16ms
  EventedHTTPServer [192.168.1.205] HTTP Response is finished +132ms
  EventedHTTPServer [192.168.1.205] HTTP request: /pair-verify +65ms
  HAPServer [C8:72:3D:E3:CE:F6] HAP Request: POST /pair-verify +2ms
  HAPServer [C8:72:3D:E3:CE:F6] Pair verify step 2/2 +11ms
  HAPServer [C8:72:3D:E3:CE:F6] Client C236D52B-2996-44B5-BFD2-377238F4E1E1 verification complete +64ms
  EventedHTTPServer [192.168.1.205] HTTP Response is finished +8ms
  EventedHTTPServer [192.168.1.205] HTTP request: /accessories +73ms
  HAPServer [C8:72:3D:E3:CE:F6] HAP Request: GET /accessories +3ms
  EventedHTTPServer [192.168.1.205] HTTP Response is finished +53ms
  EventedHTTPServer [192.168.1.205] Client connection closed +3s
  EventedHTTPServer [192.168.1.205] HTTP connection was closed +17ms
  EventedHTTPServer [192.168.1.205] HTTP server was closed +4ms
```
**On the phone, it said it couldn't connect:**
![img_8168](https://cloud.githubusercontent.com/assets/4254675/18617808/a9d3822a-7e0b-11e6-82c0-fe7faaf2fc81.PNG)

**The cause should be a lot different?** 
**If I run** `curl http://192.168.1.1:51826/accessories`, It logs:
```
HAPServer [C9:72:3A:E3:CE:F6] HAP Request: GET /accessories +3ms
  EventedHTTPServer [192.168.1.135] HTTP Response is finished +10ms
  EventedHTTPServer [192.168.1.135] Client connection closed +10ms
  EventedHTTPServer [192.168.1.135] HTTP connection was closed +7ms
  EventedHTTPServer [192.168.1.135] HTTP server was closed +2ms
```
**I tried logging the response of `/accessories` and it's mostly the same on the mipsel router and on the Mac where I can run it without problems. The diff result is [here](https://www.diffchecker.com/nPTTlFi8)**

**It seems that I'm getting the same problems as #177 now.**

**Comment by benwwchen** [comment]
Finally got it running and it seems working well so far. May be the reason that I **changed the node version from v0.10.40 to v0.10.26**. (I can only find these old versions and I used them because they also runs HAP-NodeJS well on macOS.)

I'll close the issue as soon as I test it for a while and no similar problems occur again.

**Comment by chrisschlitt** [comment]
Can you share your cross compiled version of hap-nodejs?

**Comment by benwwchen** [comment]
@chrisschlitt 
You can check out my blog post [here](https://blog.bencww.com/2016/11/09/DIY-a-HomeKit-Light-and-a-Sensor/) and download the binaries [here](https://blog.bencww.com/download/homekit.zip).

Although the post is written in Chinese, as soon as you understand how HAP-NodeJS works, there should be no problems just using the binaries directly. 

Just feel free to ask if you encounter any problems or need me to translate some parts of the post. I'd be glad to help.

**Comment by chrisschlitt** [comment]
Thanks a lot for the binaries and post! I'm ultimately trying to install HAP-NodeJs as a dependency for the Homebridge module. Any chance you have a cross-compiled version of that? Haha

Unfortunately I'm still having trouble installing the binaries on my device. How, generally, do I install a pre-compiled node module binary? (Do I put it in a specific directory, run a specific command, etc.).

Also, when trying to follow your tutorial on how to cross compile, I continue to run into "Illegal Instruction 4" errors. Could that be due to me trying to do this on High Sierra?

Thanks again for your help!

**Comment by benwwchen** [comment]
@chrisschlitt 
I didn't try out the Homebridge module yet. 😂 

Maybe you can try to put the entire `HAP-NodeJS` folder  in the node_modules folder and do `npm install module-1 module-2...` for the rest of the dependencies of the Homebridge (excluding HAP-NodeJS and all its dependencies). Then run it to see if it works. If that doesn't work, you can try copying all the sub-modules of HAP-NodeJS in the `node_modules` folder to Homebridge's `node_modules` folder.

However, if other dependencies of Homebridge also need to be compiled after downloading, they also need to be cross compiled.

The "Illegal Instruction 4" error may be related to the compiler/linker of the macOS. There should be fewer problems if you cross compile on Linux.

**Comment by chrisschlitt** [comment]
Again, thanks so much for your help!

I'll stick to getting hap-nodejs working before I move on to homebridge haha.

I copied/extracted the hap-nodejs folder into my node_modules folder, and was able to verify that hap-nodejs was installed by using npm to get the hap-nodejs version installed.

However now when I try to run hap-nodejs, it get the following error (dealing with the mdns dependency):
```
root@chs:/usr/lib/node_modules/hap-nodejs# node BridgedCore.js 
/usr/lib/node_modules/hap-nodejs/node_modules/mdns/lib/dns_sd.js:35
    throw ex;
    ^

Error: Error relocating /usr/lib/node_modules/hap-nodejs/node_modules/mdns/build/Release/dns_sd_bindings.node: _ZN2v86String9NewSymbolEPKci: symbol not found
    at Error (native)
    at Object.Module._extensions..node (module.js:434:18)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/lib/node_modules/hap-nodejs/node_modules/mdns/lib/dns_sd.js:24:20)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
```

I didn't find much online about this error, so I (incredibly naively/out of desperation to get this to work) just commented out the line where the exception was thrown, reran node hap-nodejs and then got this error:

```
root@chs:/usr/lib/node_modules/homebridge/bin# homebridge 
/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/node_modules/mdns/lib/io_watcher.js:3
    dns_sd.SocketWatcher : process.binding('io_watcher').IOWatcher;
                                   ^

Error: No such module: io_watcher
    at Error (native)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/node_modules/mdns/lib/io_watcher.js:3:36)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/node_modules/mdns/lib/mdns_service.js:4:17)
    at Module._compile (module.js:409:26)
```

I am assuming something is wrong with the mdns module? Any idea what's going on, or can you point me in the right direction?

**Comment by benwwchen** [comment]
@chrisschlitt 
By `node_modules` folder, I meant the one inside the HomeBridge folder (just git clone it) if you want to install HAP-NodeJS as a dependency of HomeBridge. If you just want to get HAP-NodeJS to work, you can put it wherever you want. But it's no big deal and it's not related to the error.

The error may be related to some shared libraries issues. Did you install all packages (particularly the `mdnsd` one) inside the `ipks` folder in the downloaded binary zip file `homekit.zip`?
