### ISSUE TITLE
Questions about bridge configuration and security

### ISSUE THREAD

**Issue by madcat-nl** [KhaosT/HAP-NodeJS#285]
Hi,
I love the product and i already got it beautifully working in combination with homekit/siri and a raspberry pi, but i have a few questions i could not solve.

1) How can i set the characteristics for a bridge, like manufacturer, model and serial number.
i got it working for an accessory, but something like this did not work:
 bridge.setCharacteristic(Characteristic.Manufacturer, "Raspberry pi") 
Is there an example file of a bridge which is configured correctly?

2) I would like to add some extra security on opening doors, at the moment i log all the actions into a mysql database, so i can see when a door was opened. but i would like to restrict it on request for a certain request ip range. I  install "request-ip" and "ipware" but i'm not sure where i can retrieve the 'request' from in the accessory.js.
Does anyone has fetched the request ip with HAP-NodeJS?

**Comment by KhaosT** [comment]
Setting ``bridge.setCharacteristic(Characteristic.Manufacturer, "Raspberry pi")`` should just work, not really sure why it doesn't work for you.

For request IP, technically you should be able to get it from the request at ``https://github.com/KhaosT/HAP-NodeJS/blob/master/lib/HAPServer.js#L884``
Would you mind to share why you want to restrict IP access? HomeKit itself already enforces the access using strong end-to-end encryption which should prevents unauthorized access already.

**Comment by madcat-nl** [comment]
Thanks for you reply,

I also wonder what i'm doing wrong i thought it was not supported, this is my BridgedCore.js at the moment:
var fs = require('fs');
var path = require('path');
var storage = require('node-persist');
var uuid = require('./').uuid;
var Bridge = require('./').Bridge;
var Accessory = require('./').Accessory;
var accessoryLoader = require('./lib/AccessoryLoader');
var Characteristic = require('./').Characteristic; //Added

console.log("HAP-NodeJS starting...");

// Initialize our storage system
storage.initSync();

// Start by creating our Bridge which will host all loaded Accessories
var bridge = new Bridge('RaspberryPi', uuid.generate("RaspberryPi")); //modified

bridge.setCharacteristic(Characteristic.Manufacturer, "Raspberry pi") //added
bridge.setCharacteristic(Characteristic.Model, "3 B")//added
bridge.setCharacteristic(Characteristic.SerialNumber, "001");/added

// Listen for bridge identification event
bridge.on('identify', function(paired, callback) {
  console.log("Node Bridge identify");
  callback(); // success
});

// Load up all accessories in the /accessories folder
var dir = path.join(__dirname, "accessories");
var accessories = accessoryLoader.loadDirectory(dir);

// Add them all to the bridge
accessories.forEach(function(accessory) {
  bridge.addBridgedAccessory(accessory);
});

// Publish the Bridge on the local network.
bridge.publish({
  username: "CC:22:3D:E3:CE:F6",
  port: 51826,
  pincode: "000-00-000",
  category: Accessory.Categories.BRIDGE
});

When i run it, it returns the following error:
bridge.setCharacteristic(Characteristic.Manufacturer, "Raspberry pi")
       ^

TypeError: bridge.setCharacteristic is not a function
    at Object.<anonymous> (/home/pi/HAP-NodeJS/BridgedCore.js:18:8)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:134:18)
    at node.js:962:3

i'll take a look at the HAPServer.js and see if i can cascade it to the accessory level.
because i also would like to open doors with it i would like to have a bit more control over the "keys" i'm giving out. it should only work when someone has access on my network and is added to the homekit. But there are always bugs in software so i rather would like an extra point of control on lower level just to keep hackers a bit more out :)

**Comment by KhaosT** [comment]
```js
bridge.setCharacteristic(Characteristic.Manufacturer, "Raspberry pi") //added
bridge.setCharacteristic(Characteristic.Model, "3 B")//added
bridge.setCharacteristic(Characteristic.SerialNumber, "001");/added
```
needs to be
```js
bridge.getService(Service.AccessoryInformation).setCharacteristic(Characteristic.Manufacturer, "Raspberry pi") //added
bridge.getService(Service.AccessoryInformation).setCharacteristic(Characteristic.Model, "3 B")//added
bridge.getService(Service.AccessoryInformation).setCharacteristic(Characteristic.SerialNumber, "001");/added
```

**Comment by madcat-nl** [comment]
Cool, that worked

For other who wants this, i added this to the BridgeCore.js:
var Characteristic = require('./').Characteristic;
var Service = require('./').Service;

bridge.getService(Service.AccessoryInformation)
  .setCharacteristic(Characteristic.Manufacturer, "Raspberry pi")
  .setCharacteristic(Characteristic.Model, "3 B")
  .setCharacteristic(Characteristic.SerialNumber, "001");

**Comment by madcat-nl** [comment]
about the HAPServer.js and logging and restricting ip's, the headers are for some reason not filled in, so it's not possible to see where it's coming from.
I'll solve it by restricting access via the router and hope that there is no major bug in the security in the HAPprotocol and the homekit imlementation :)

Thanks for your feedback!
