### ISSUE TITLE
Unable to start service - ReferenceError: accessoryName is not defined

### ISSUE THREAD

**Issue by bornmand** [KhaosT/HAP-NodeJS#286]
I followed the tutorials to get everything installed without any issues but I am unable to get the service started successfully. For some reason it is having problems finding the `/accessories` directory.
Here is the error I get when I run `node BridgedCore.js`.   

*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
HAP-NodeJS starting...
Parsing accessory: Fan_accessory.js
/home/pi/HAP-NodeJS/accessories/Fan_accessory.js:52
  .addService(Service.Fan, accessoryName) // services exposed to the user should have "names" like "Fake Light" for us
                       	^

ReferenceError: accessoryName is not defined
	at Object.<anonymous> (/home/pi/HAP-NodeJS/accessories/Fan_accessory.js:52:28)
	at Module._compile (module.js:556:32)
	at Object.Module._extensions..js (module.js:565:10)
	at Module.load (module.js:473:32)
	at tryModuleLoad (module.js:432:12)
	at Function.Module._load (module.js:424:3)
	at Module.require (module.js:483:17)
	at require (internal/module.js:20:19)
	at /home/pi/HAP-NodeJS/lib/AccessoryLoader.js:32:29
	at Array.forEach (native)

**Comment by KhaosT** [comment]
Sorry, please try again with commit 7b42deba8f3e7b8057390b0155782cb33272df4d
