### ISSUE TITLE
RTSP Support for Cameras?

### ISSUE THREAD

**Issue by dsully** [KhaosT/HAP-NodeJS#295]
It looks like HomeKit supports RTSP in addition to RTP. SRTP is optional.

Should Camera.js be updated to allow for an RTSP endpoint to be exposed?

**Comment by KhaosT** [comment]
RTSP is a protocol used to negotiate streaming parameters. HomeKit on iOS doesn't take in a RTSP url. The right way is for program to get the parameters from prepareStream and then negotiate with the actual camera over RTSP to have camera send the stream to iOS device.

**Comment by karacaozan** [comment]
Can you please share an example? Can we link the stream to a raspberry pi camera?

**Comment by rmarinho** [comment]
Yes take a look here...

https://github.com/KhaosT/HAP-NodeJS/issues/253#issuecomment-249992052
