### ISSUE TITLE
question: definitions for power monitoring

### ISSUE THREAD

**Issue by mrose17** [KhaosT/HAP-NodeJS#296]
hi. i'm planning to write a homebridge accessory for my neur.io power monitor.  i've attached an example of the JSON below.

do you know of any service definitions for power monitoring for use with homekit? or am i in "define your own" territory?

also (sorry for putting two topics in one issue): do you know of a good repository for user-defined service definitions. i posted something to https://homebridgeteam.slack.com/archives/hap/p1474645226000007 last week, but no one responded...

thanks!

[neur.io.txt](https://github.com/KhaosT/HAP-NodeJS/files/495636/neur.io.txt)

**Comment by justme-1968** [comment]
have a look here: https://gist.github.com/gomfunkel/b1a046d729757120907c

there are some custom characteristic uuids that you can reuse. they will be correctly displayed in eve.
eve will also display all other custom characteristics that you create.

home does not display any custom characteristics.

**Comment by mrose17** [comment]
@justme-1968 - many thanks!

it turns out that the eve app is actually my favorite homekit app, so this is a double-win!!!
