### ISSUE TITLE
Staying updated HAP

### ISSUE THREAD

**Issue by angyalZK** [KhaosT/HAP-NodeJS#298]
How can I updating my cloned git from here? I tried with "git pull", but always wants I commit or stash it.

**Comment by smith288** [comment]
Means you have outstandings code changes in your local repository.  I'd suggest learning more about git source control as this type of question isnt related to HAP-NodeJS.

**Comment by amz4u2nv** [comment]
Whilst in the subject of updates innocence that when i did an update in the past my iOS devices wouldn't pick up my homekit devices and I would have to delete my HomeKit settings and start again. Is there a way to save my scenes so I don't have to redo my scenes. Is simple as copying .persist files as a backup
