### ISSUE TITLE
HeatingState, CoolingState, CurrentTemp, TargetTemp

### ISSUE THREAD

**Issue by thechrisreese** [KhaosT/HAP-NodeJS#299]
For devices that work in F rather than C to accurately set certain temperatures (such as 79 degrees) then CurrentTemp, TargetTemp, HeatingState, and CoolingState needs to move in increments smaller than .1

I have tested at .0001 and everything works well. Hopefully someone can make that change to hap-node.js.

**Comment by KhaosT** [comment]
@thechrisreese HomeKit expects value in Celsius and should respect the step value reported by metadata. By adding arbitrary small numbers after the value can potentially causing HomeKit to block the accessory. I'm afraid this area will be kept as is of right now.
