### ISSUE TITLE
Doorbell support?

### ISSUE THREAD

**Issue by lukeredpath** [KhaosT/HAP-NodeJS#303]
I know #253 has been closed - did support for the new doorbell accessory type make it into HAP-NodeJS? I'm using Homebridge to bridge my Domoticz server to HomeKit and have my 433mhz doorbell hooked up to Domoticz. Currently I have to rely on IFTTT and Domoticz scripting to get notifications when the bell is rung (with a noticeable delay) - it would be great to be able to expose this to HomeKit and use that to get notifications over the local network.

**Comment by smith288** [comment]
[Looks like it to me.](https://github.com/KhaosT/HAP-NodeJS/blob/64fa27a0a557f5f7d0f4bbd6ea3cc9106eb3446c/lib/gen/HomeKitTypes.js#L2326)

**Comment by KhaosT** [comment]
The service info is there…

**Comment by lukeredpath** [comment]
Thanks, I couldn't find it. I'll see if this is in Homebridge already and see if I can get it working.

**Comment by KhaosT** [comment]
@lukeredpath https://github.com/KhaosT/HAP-NodeJS/blob/master/lib/gen/HomeKitTypes.js#L2329
