### ISSUE TITLE
Randomly fired Homekit actions.

### ISSUE THREAD

**Issue by MichMich** [KhaosT/HAP-NodeJS#304]
I use [homekit2mqtt](https://github.com/hobbyquaker/homekit2mqtt) (which uses HAP-NodeJS) to control my self built electric curtains. It works perfect, but sometimes my curtains randomly open. I checked the debug info, and it doesn't say anything strange: it really looks like it really receives an open command from HAP-NodeJS:

    hap set Curtain 1 TargetPosition 100

It seems like HAP-NodeJS fires false Homekit actions. Any idea where to look for any clues or solutions?

@hobbyquaker, creator of homekit2mqtt, suggested to check of there were any others using HAP-NodeJS users with the same issue: https://github.com/hobbyquaker/homekit2mqtt/issues/12

**Comment by MichMich** [comment]
So, I probably found the issue. Which is 100% my fault: I was running the application on two different machines at the same time (by mistake). Homekit probably switches between the two different instances from time to time. I shut down one of the two instances, and will check if this solved the issue ... If not, I'll reopen the issue. Thanks!

**Comment by KhaosT** [comment]
Yeah, if this still occurs, I'd encourage you try to run the program with ``DEBUG=* node xxx`` to get all debug outputs so we can figure out if the command is originated from iOS device or from hap-nodejs internals.

**Comment by MichMich** [comment]
Will do! Thanks!
