### ISSUE TITLE
How to set "No Response" on Lightbulb accessory?

### ISSUE THREAD

**Issue by ArnieX** [KhaosT/HAP-NodeJS#306]
Hi @KhaosT,

could you please point me in right direction? I'm looking for characteristic of lightbulb accessory to show **no response** when it is in fact offline, for example when someone flip the physical switch off. This is right now working with Philips Hue lightbulbs and the new HomeKit bridge. So I was curious how to accomplish the same with my DIY approach with ESP8266 too. I can for example ping the device to get the current status and if the ping is unsuccessful then set the characteristic to no response, but I can't find such characteristic.

Thank you a lot in advance.

**Comment by sembsa** [comment]
Maybe you can change Lightbulb file, maybe add new function ping() if not to connect RPi to ESP to set status.

**Comment by ArnieX** [comment]
@sembsa I do not know what are you talking about ;). I know how to get status of ESP that is not a problem. What I don't know how to set characteristic, like for example characteristic On:true/false, Brightness:0-100, etc. there should be one to set no response. Otherwise I do not know how eg Philips Hue does set this for their lights.

**Comment by cflurin** [comment]
@ArnieX:
Take a look at the new homebridge-mqtt version on GitHub:
https://github.com/cflurin/homebridge-mqtt

**Comment by akshaysmurthy** [comment]
@ArnieX Were you able to figure that out?

**Comment by ArnieX** [comment]
Well yes @cflurin made it possible in his homebridge-mqtt plugin.

**Comment by akshaysmurthy** [comment]
Right thanks. Just in case anyone stumbles upon this, the first argument for the `callback` function is `error`. So, just setting it to anything other than `null` or `undefined` should do the trick.

Sample:

`callback('No Response);`

**Comment by ArnieX** [comment]
Great, that is good to know for others. Thanks for sharing.
