### ISSUE TITLE
Creating Outdoor Blinds Accessory

### ISSUE THREAD

**Issue by peadard** [KhaosT/HAP-NodeJS#31]
Hi guys.
I have been trying to create an accessory called Outdoor Blinds.
I have successfully created and added it by modifying the Garage door Opener accessory.
However... the commands such as Open the outdoor blinds and close the outdoor blinds do not work. 
I get "it looks like you do not have an app called outdoor blinds"
the only command that works for me is "Open the garage door and Close the garage door" this is a bit of an issue because I have a garage door that I plan to add.
I know this is the accessory that is being called because the output correctly prints "Sent close to Outdoor Blinds"
The code that i have used is below:

// HomeKit types required
var types = require("./types.js")
var exports = module.exports = {};
var nc = require("node-cat");
var host = "xxx.xx.xx.xxx";
var port = "xxxx";

var types = require("./types.js")
var exports = module.exports = {};

var execute = function(accessory,characteristic,value){ console.log("executed accessory: " + accessory + ", and characteristic: " + characteristic + ", with value: " +  value + "."); }

exports.accessory = {
  displayName: "Outdoor Blinds",
  username: "3C:51:3D:EE:5E:DB",
  pincode: "031-45-154",
  services: [{
    sType: types.ACCESSORY_INFORMATION_STYPE, 
    characteristics: [{
    	cType: types.NAME_CTYPE, 
    	onUpdate: null,
    	perms: ["pr"],
		format: "string",
		initialValue: "OutDoor Blinds Opener",
		supportEvents: false,
		supportBonjour: false,
		manfDescription: "Name of the accessory",
		designedMaxLength: 255    
    },{
    	cType: types.MANUFACTURER_CTYPE, 
    	onUpdate: null,
    	perms: ["pr"],
		format: "string",
		initialValue: "Oltica",
		supportEvents: false,
		supportBonjour: false,
		manfDescription: "Manufacturer",
		designedMaxLength: 255    
    },{
    	cType: types.MODEL_CTYPE,
    	onUpdate: null,
    	perms: ["pr"],
		format: "string",
		initialValue: "Rev-1",
		supportEvents: false,
		supportBonjour: false,
		manfDescription: "Model",
		designedMaxLength: 255    
    },{
    	cType: types.SERIAL_NUMBER_CTYPE, 
    	onUpdate: null,
    	perms: ["pr"],
		format: "string",
		initialValue: "OutdoorBlinds",
		supportEvents: false,
		supportBonjour: false,
		manfDescription: "SN",
		designedMaxLength: 255    
    },{
    	cType: types.IDENTIFY_CTYPE, 
    	onUpdate: null,
    	perms: ["pw"],
		format: "bool",
		initialValue: false,
		supportEvents: false,
		supportBonjour: false,
		manfDescription: "Identify Accessory",
		designedMaxLength: 1    
    }]
  },{
    sType: types.GARAGE_DOOR_OPENER_STYPE, 
    characteristics: [{
    	cType: types.NAME_CTYPE,
    	onUpdate: null,
    	perms: ["pr"],
		format: "string",
		initialValue: "Outdoor Blinds Control",
		supportEvents: false,
		supportBonjour: false,
		manfDescription: "Name of service",
		designedMaxLength: 255   
    },{
    	cType: types.CURRENT_DOOR_STATE_CTYPE,
    	onUpdate: function(value) { console.log("Change:",value); execute("Garage Door", "Current State", value); },
    	perms: ["pr","ev"],
		format: "int",
		initialValue: 0,
		supportEvents: false,
		supportBonjour: false,
		manfDescription: "BlaBla",
		designedMinValue: 0,
		designedMaxValue: 4,
		designedMinStep: 1,
		designedMaxLength: 1    
    },{
    	cType: types.TARGET_DOORSTATE_CTYPE,
    	//onUpdate: function(value) { console.log("Change:",value); execute("Outdoor blinds", "Target State", value); },

	onUpdate: function(value) { console.log("Change:",value); var client = nc.createClient(host, port);client.start(
	function(client /* the tcp client returned by net.connect */, rl /* readline instance */, stdin, stdout)

{

 if (value === 0) {
        client.write("09tn01800BC^");
    stdout.write("Sent Open to Outdoor Blinds.");
	 client.end();
    }
 if (value === 1) {
        client.write("09tn01800BC^");
    stdout.write("Sent Close to Outdoor Blinds.");
	 client.end();
    }})
 },
    	perms: ["pr","pw","ev"],
		format: "int",
		initialValue: 0,
		supportEvents: false,
		supportBonjour: false,
		manfDescription: "BlaBla",
		designedMinValue: 0,
		designedMaxValue: 1,
		designedMinStep: 1,
		designedMaxLength: 1    
    },{
    	cType: types.OBSTRUCTION_DETECTED_CTYPE,
    	onUpdate: function(value) { console.log("Change:",value); execute("Garage Door", "Obstruction Detected", value); },
    	perms: ["pr","ev"],
		format: "bool",
		initialValue: false,
		supportEvents: false,
		supportBonjour: false,
		manfDescription: "BlaBla",
    }]
  }]
}

Does anybody have any idea how i might move forward with this??
As far as I know there is no generic door opener service.
Thanks guys.

**Comment by KhaosT** [comment]
@peadard As I stated in issue #15, Siri seems having issue controlling individual accessory by its name. If you have time, it would be great to file a bug report on [bugreport.apple.com](http://bugreport.apple.com).
