### ISSUE TITLE
Create CONTACT SENSOR accessory

### ISSUE THREAD

**Issue by madcat-nl** [KhaosT/HAP-NodeJS#312]
Hi,

I would like to create contact sensor type accessory for a door.
it should only report if the door is open or closed because it's not possible to open the door via a motor.

I tried to start from the lock accessory but after a few changes it still looks like a lock.
how can i change this?

never mind, i had to use:

door
  .getService(Service.Door)
  .getCharacteristic(Characteristic.CurrentPosition)

**Comment by finalhawk90** [comment]
Could you please post the code you use. Trying to get a gpio contact Sensor exposed in HomeKit but can’t find anything that runs on hap-node js
