### ISSUE TITLE
HAP-NodeJS on startup Raspberry pi 3

### ISSUE THREAD

**Issue by Maxmudjon** [KhaosT/HAP-NodeJS#318]
Help please
not working on startup HAP-NodeJS

**Comment by theopoon** [comment]
You got to send some info for people to help you, what problem do you have?

**Comment by Maxmudjon** [comment]
Hap-nodejs does not start when you reboot.

**Comment by Maxmudjon** [comment]
after reboot raspberry pi 3 does not start HAP-NodeJS. In the /etc/init.d script he added.

**Comment by TheNoim** [comment]
Normaly HAP dose not add any startup script. Maybe you could sent the startup script. But i think this is not a problem of hap.

**Comment by Maxmudjon** [comment]
#! /bin/sh
# /etc/init.d/noip 

### BEGIN INIT INFO
# Provides:          noip
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Simple script to start a program at boot
# Description:       A simple script from www.stuffaboutcode.com which will start / stop a program a boot / shutdown.
### END INIT INFO

# If you want a command to always run, put it here

# Carry out specific functions when asked to by the system
case "$1" in
  start)
    echo "Starting Core,js"
    # run application you want to start
    node /home/pi/HAP-NodeJS/Core.js
    ;;
  stop)
    echo "Stopping Core.js"
    # kill application you want to stop
    killall Core.js
    ;;
  *)
    echo "Usage: /etc/init.d/noip {start|stop}"
    exit 1
    ;;
esac

exit 0

**Comment by Maxmudjon** [comment]
#! /bin/sh
# /etc/init.d/Core

### BEGIN INIT INFO
# Provides:          Core
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Simple script to start a program at boot
# Description:       A simple script from www.stuffaboutcode.com which will start / stop a program a boot / shutdown.
### END INIT INFO

# If you want a command to always run, put it here

# Carry out specific functions when asked to by the system
case "$1" in
  start)
    echo "Starting Core"
    # run application you want to start
    node /home/pi/HAP-NodeJS/Core.js
    ;;
  stop)
    echo "Stopping Core"
    # kill application you want to stop
    killall Core.js
    ;;
  *)
    echo "Usage: /etc/init.d/Core {start|stop}"
    exit 1
    ;;
esac

exit 0

**Comment by todro** [comment]
As Raspian is Debian based and the latest Debian version "Jessie" switched from the old sysvinit to systemd, you might check first which raspian/debian version you have. If it's Jessie-based, your old old init.d scripts will not run unless sysvinit is installed as a "bridge" to the old init.d world.

So you might search in google for jessie and systemd to get an idea how system start is handled in the new version, searching for raspbian debian jessie systemd will give you lot's of information about this topic and even some example scripts, or you might check this link: 

https://www.raspberrypi.org/forums/viewtopic.php?f=66&t=122207

**Comment by legotheboss** [comment]
@Maxmudjon If you followed the QuickPi tutorials, here is the updated guide: 
https://github.com/legotheboss/YouTube-files/wiki/(RPi)-Start-HAP-on-Reboot

**Comment by Maxmudjon** [comment]
QuickPI hi how are you. I solved the problem differently added to rc.local 'sudo sh /home/pi/start.sh' and start.sh 'sudo node /home/pi/HAP-NodeJS/Core.js' or 'BridgedCore.js'

**Comment by gjouanjean** [comment]
Hello ! 

I have follow guide @legotheboss : https://github.com/legotheboss/YouTube-files/wiki/(RPi)-Start-HAP-on-Reboot and i have a problem when i reboot my pi.

My accessories doesn't works in homekit, to run Core.js i need to : 
run : forever stopall
then i run Core.js and CameraCore.js and it's work.

@Maxmudjon how do you create your start.sh ?

Thank you

**Comment by legotheboss** [comment]
@gjouanjean This is what i suggest, change the username parameter in Core and CameraCore. Then you need to reconnect both nodes with your phone. This should be a one-time process.

**Comment by gjouanjean** [comment]
Thanks @legothe.boss how can i change the username parameter in Core and CameraCore ? i'm sorry i d'ont understand

**Comment by legotheboss** [comment]
@gjouanjean 
So if you open BridgedCore.js with nano, you should be able to see this at the bottom of the file:

````
bridge.publish({
  username: "CC:22:3D:E3:CE:F6",
  port: 51826,
  pincode: "031-45-154",
  category: Accessory.Categories.BRIDGE
});
````
Change the variable called username. I would just suggest change one number to another.

Now, open CameraCore.js with nano and go to the bottom of the file.

````
cameraAccessory.publish({
  username: "EC:22:3D:D3:CE:CE",
  port: 51062,
  pincode: "031-45-154",
  category: Accessory.Categories.CAMERA
}, true);
````

Just like before, change one character or number so it is different than before.

Hope this helps!

**Comment by gjouanjean** [comment]
@legotheboss Thank you very much, but it doesn't work, i have the same problem :/

**Comment by legotheboss** [comment]
@gjouanjean did you enable wait for network during boot on raspi-config?

**Comment by gjouanjean** [comment]
@legotheboss Yes it's enable, i check this many time.
