### ISSUE TITLE
Update Characteristic

### ISSUE THREAD

**Issue by Be2daErtin** [KhaosT/HAP-NodeJS#319]
Hi,

I need help please.

I want to update the characteristic of an accessory. When I print to console I get this:

console.log(accessories[0]);

> Accessory {
>   displayName: 'Kitchen Light',
>   UUID: 'b9a6b2ff-c36f-4484-b8ac-5d6b26094bfd',
>   aid: null,
>   _isBridge: false,
>   bridged: true,
>   bridgedAccessories: [],
>   services: 
>    [ Service {
>        displayName: undefined,
>        UUID: '0000003E-0000-1000-8000-0026BB765291',
>        subtype: undefined,
>        iid: null,
>        characteristics: [Object],
>        optionalCharacteristics: [Object],
>        _events: [Object],
>        _eventsCount: 1 },
>      Service {
>        displayName: 'Kitchen Light',
>        UUID: '00000043-0000-1000-8000-0026BB765291',
>        subtype: undefined,
>        iid: null,
>        characteristics: [Object],
>        optionalCharacteristics: [Object],
>        _events: [Object],
>        _eventsCount: 1 } ],
>   deviceid: 3,
>   _events: 
>    { identify: [Function],
>      'service-characteristic-change': [Function: bound ] },
>   _eventsCount: 2 }

**Comment by Be2daErtin** [comment]
I just want to update the value stored and push that back to the phone....

**Comment by KhaosT** [comment]
on the Characteristic object there is an updateValue function to do this.
