### ISSUE TITLE
Wall switch on off with MQTT

### ISSUE THREAD

**Issue by Maxmudjon** [KhaosT/HAP-NodeJS#321]
https://www.youtube.com/watch?v=UyCtxQwTZz0

who has received or who have .js code for HAP-NodeJS

**Comment by todro** [comment]
You can find the code here https://github.com/ItKindaWorks/ESP8266/tree/master/Home%20Automation

**Comment by Maxmudjon** [comment]
where there is no code as shown in the video

**Comment by linuxpa** [comment]
You can find the code here

https://github.com/linuxpa/MQTT-switch

**Comment by iCarl** [comment]
This one doesn't show as a button in Homekit, how do I change the UI characteristics?

**Comment by hobbyquaker** [comment]
Perhaps https://github.com/hobbyquaker/homekit2mqtt is something for you.

**Comment by cflurin** [comment]
Have a look here:
https://github.com/cflurin/homebridge-mqtt
