### ISSUE TITLE
Node 4 support

### ISSUE THREAD

**Issue by mifi** [KhaosT/HAP-NodeJS#322]
https://github.com/KhaosT/HAP-NodeJS/commit/a4067085589753198e177786b151165824c19f99

**This is a breaking change**
Buffer.alloc/from are not supported in node 4. Not supporting node 4 is a bit harsh. Node 4 is still LTS and default package manager version in many OS distros and widely used. Is it really necessary?

See issue in telldus plugin:
https://github.com/jchnlemon/homebridge-telldus/issues/27

**Comment by KhaosT** [comment]
Nodejs v7 plans to drop support for the original Buffer constructors. Because of that, I have to either migrate to "new Buffer(…)" or "Buffer.alloc"

Since Buffer constructors are marked as deprecated, I don't think it's a good idea to migrate to "new Buffer(…)" solution.

What's your proposed solution for this?

**Comment by mifi** [comment]
Maybe something like this:
https://www.npmjs.com/package/buffer-shims

**Comment by KhaosT** [comment]
I'm not sure... It feels like putting a lot of work on something just because people prefers to use a older version of software. It's not like nodejs v6 drops support for any hardware. If you really think it's worth the effort, feel free to send my a PR and I'm happy to merge it.

**Comment by mifi** [comment]
True, but it breaks npm upgrade for a lot of people. I added a PR #324 where i replaced all Buffer.alloc and Buffer.from calls with buffer-shims. It's easy to go back on this in the future. Just find-replace reverse

**Comment by KhaosT** [comment]
Thanks for the effort. v0.4.13 should work with earlier version of nodejs now.
