### ISSUE TITLE
Contact Sensor not seen as actual sensor in homekit

### ISSUE THREAD

**Issue by madcat-nl** [KhaosT/HAP-NodeJS#325]
Hi i have created a contact sensor which is kinda working but i have two issues.

In the homekit app in IOS 10, i do see it as a contact sensor and it shows the correct state.
but when i go to the automation tab, the option "A sensor detects something" is still grayed out.
i was kinda hoping that once i have one sensor in homekit i could use this.

On the background, the sensor state is read every second, but in the IOS application it's only updated when it's refreshed from the IOS app. 
Is there a way to publish the state to all devices, so i see a state change in the homescreen once a door has been opened.

Here is the code of the contact sensor i'm using

```
var Accessory = require('../').Accessory;
var Service = require('../').Service;
var Characteristic = require('../').Characteristic;
var uuid = require('../').uuid;
var wpi = require('wiring-pi');

var DeurSensorPin=22; //sensor 2 GPIO25 
var lastState=0;
// here's a door device that we'll expose to HomeKit
var DOOR = {
  open: false,
  sensor: 0,
  read: function(){
    wpi.setup('phys');
    wpi.pinMode(DeurSensorPin,wpi.INPUT)
    var DeurSensorValue = wpi.digitalRead(DeurSensorPin);
    //console.log('read sensor',DeurSensorValue);
    DOOR.sensor=DeurSensorValue;
    if(DOOR.sensor==0){
       DOOR.open=false;
       if(lastState!=false){
         console.log('door is closed');
         lastState=false;
       }
    }else{
       DOOR.open=true;
       if(lastState!=true){
       console.log('door is open');
       lastState=true;
       }
    }
  },wait: function() {
     var seconds=1;
     var waitTill = new Date(new Date().getTime() + seconds * 1000);
     while(waitTill > new Date()){}
  },
  identify: function() {
    console.log("Identify the door!");
  }
}

// Generate a consistent UUID for our Lock Accessory that will remain the same even when
// restarting our server. We use the `uuid.generate` helper function to create a deterministic
// UUID based on an arbitrary "namespace" and the word "door".
var doorUUID = uuid.generate('hap-nodejs:accessories:contactsensor');

// This is the Accessory that we'll return to HAP-NodeJS that represents our door
var door = exports.accessory = new Accessory('ContactSensor', doorUUID);

// Add properties for publishing (in case we're using Core.js and not BridgedCore.js)
door.username = "AA:BB:CC:DD:EE:01";
door.pincode = "314-00-000";

// set some basic properties (these values are arbitrary and setting them is optional)
door
  .getService(Service.AccessoryInformation)
  .setCharacteristic(Characteristic.Manufacturer, "Door Sensor")
  .setCharacteristic(Characteristic.Model, "Nemef")
  .setCharacteristic(Characteristic.SerialNumber, "1");

// listen for the "identify" event for this Accessory
door.on('identify', function(paired, callback) {
  DOOR.identify();
  callback(); // success
});

door
   .addService(Service.ContactSensor,"Binnen Deur Sensor")
   .getCharacteristic(Characteristic.ContactSensorState)
   .on('get', function(callback) {
    DOOR.read();
    // return our current value
    callback(null, DOOR.open);
});

setInterval(function() {  
  DOOR.read()
  
  // update the characteristic value so interested iOS devices can get notified
   door
    .getService(Service.ContactSensor)
    .getCharacteristic(Characteristic.ContactSensorState, DOOR.open);  
}, 1000);
```

**Comment by iCarl** [comment]
I have the same issue with a DHT-sensor

**Comment by snowdd1** [comment]
@madcat-nl 
You've forgotten to update the characteristics value with `setValue()` in your interval:
```
  // update the characteristic value so interested iOS devices can get notified
   door
    .getService(Service.ContactSensor)
    .getCharacteristic(Characteristic.ContactSensorState, DOOR.open);  
}, 1000);
```
that should be
```
  // update the characteristic value so interested iOS devices can get notified
   door
    .getService(Service.ContactSensor)
    .getCharacteristic(Characteristic.ContactSensorState)
    .setValue(DOOR.open);  
}, 1000);
```

**Comment by madcat-nl** [comment]
@snowdd1, Does that work for you?
it still does not push the change to IOS

**Comment by snowdd1** [comment]
Well I use [homebridge](https://github.com/nfarina/homebridge) as a wrapper for [my plugin](https://github.com/snowdd1/homebridge-knx), which makes some things a lot easier.  

I storing the characteristics in my own objects, but in the end I call 
[characteristic.setValue(val ? (reverse ? 0 : 1) : (reverse ? 1 : 0), undefined, 'fromKNXBus');](
https://github.com/snowdd1/homebridge-knx/blob/master/lib/knxaccess.js#L278)  
and the `reverse` thing I just need to reverse true and false in some cases. That works fine in serveral hundred installations as far as I know.

If you start hap with debug options, does it show 'register ContactSensorState for events' or similar, if you open your home app?

**Comment by linuxpa** [comment]
You must add the service when you go to query the sensor

`var DOOR = {
  open: false,
  sensor: 0,
  read: function(){
    wpi.setup('phys');
    wpi.pinMode(SensorPin,wpi.INPUT);
    var DeurSensorValue = wpi.digitalRead(SensorPin);
    //console.log('read sensor',DeurSensorValue);
    DOOR.sensor=DeurSensorValue;
    if(DOOR.sensor==0){
       DOOR.open=false;
       if(lastState!=false){
         console.log('door is closed');
         lastState=false;
         
          door
          .getService(Service.ContactSensor)
          .setCharacteristic(Characteristic.ContactSensorState, false )
       }

    }else{
       DOOR.open=true;
       if(lastState!=true){
       console.log('door is open');
       lastState=true;

         door
         .getService(Service.ContactSensor)
         .setCharacteristic(Characteristic.ContactSensorState, true )

       
       }
    }
  }, `

**Comment by linuxpa** [comment]
You must add the service when you go to query the sensor


`
var DOOR = {
  open: false,
  sensor: 0,
  read: function(){
    wpi.setup('phys');
    wpi.pinMode(SensorPin,wpi.INPUT);
   // var DeurSensorValue = wpi.digitalRead(SensorPin);
   // console.log('read sensor',DeurSensorValue);
    DOOR.sensor= wpi.digitalRead(SensorPin);
    if(DOOR.sensor==0){
       DOOR.open=false;
       if(lastState!=false){
         console.log('door is closed');
         lastState=false;
         
          door
          .getService(Service.ContactSensor)
          .setCharacteristic(Characteristic.ContactSensorState, false )
       }

    }else{
       DOOR.open=true;
       if(lastState!=true){
       console.log('door is open');
       lastState=true;

         door
         .getService(Service.ContactSensor)
         .setCharacteristic(Characteristic.ContactSensorState, true )

       
       }
    }
  }, 
`

**Comment by linuxpa** [comment]
You need to upgrade service with the value of SensorPin

`
var DOOR = {
  open: false,
  sensor: 0,
  read: function(){
    wpi.setup('phys');
    wpi.pinMode(SensorPin,wpi.INPUT);
   // var DeurSensorValue = wpi.digitalRead(SensorPin);
   // console.log('read sensor',DeurSensorValue);
    DOOR.sensor= wpi.digitalRead(SensorPin);
    if(DOOR.sensor==0){
       DOOR.open=false;
       if(lastState!=false){
         console.log('door is closed');
         lastState=false;        
          door
          .getService(Service.ContactSensor)
          .setCharacteristic(Characteristic.ContactSensorState, false )
       }
    }else{
       DOOR.open=true;
       if(lastState!=true){
       console.log('door is open');
       lastState=true;
         door
         .getService(Service.ContactSensor)
         .setCharacteristic(Characteristic.ContactSensorState, true )     
       }
    }
  },
`

**Comment by linuxpa** [comment]
You need to upgrade service with the value of SensorPin
`var DOOR = {
  open: false,
  sensor: 0,
  read: function(){
    wpi.setup('phys');
    wpi.pinMode(SensorPin,wpi.INPUT);
   // var DeurSensorValue = wpi.digitalRead(SensorPin);
   // console.log('read sensor',DeurSensorValue);
    DOOR.sensor= wpi.digitalRead(SensorPin);
    if(DOOR.sensor==0){
       DOOR.open=false;
       if(lastState!=false){
         console.log('door is closed');
         lastState=false;        
          door
          .getService(Service.ContactSensor)
          .setCharacteristic(Characteristic.ContactSensorState, false )
       }
    }else{
       DOOR.open=true;
       if(lastState!=true){
       console.log('door is open');
       lastState=true;
         door
         .getService(Service.ContactSensor)
         .setCharacteristic(Characteristic.ContactSensorState, true )     
       }
    }
  },
`

**Comment by linuxpa** [comment]
You need to upgrade service with the value of SensorPin
`//

var DOOR = {
  open: false,
  sensor: 0,
  read: function(){
    wpi.setup('phys');
    wpi.pinMode(SensorPin,wpi.INPUT);
   // var DeurSensorValue = wpi.digitalRead(SensorPin);
   // console.log('read sensor',DeurSensorValue);
    DOOR.sensor= wpi.digitalRead(SensorPin);
    if(DOOR.sensor==0){
       DOOR.open=false;
       if(lastState!=false){
         console.log('door is closed');
         lastState=false;
         
          door
          .getService(Service.ContactSensor)
          .setCharacteristic(Characteristic.ContactSensorState, false )
       }

    }else{
       DOOR.open=true;
       if(lastState!=true){
       console.log('door is open');
       lastState=true;

         door
         .getService(Service.ContactSensor)
         .setCharacteristic(Characteristic.ContactSensorState, true )

       
       }
    }
  }, `

**Comment by madcat-nl** [comment]
i have solved this issue by using "When an accessory is controled" it then is possible to connect it to for example an light. so the light is turned on when a door is opened.

The other issue is also solved, i also had a node-red instance open which was polling the sensor.
this probably had some interference.

But it still would be cool to use the "When the sensor detects something", it's grayed out for now.

I also have a humidity and temperature sensor in my bathroom, but it's not possible to use it as a sensor via homekit, other then just showing the raw data. i have used node-red to read the sensor and sends a message every minute via the MQTT, so the house ventilation will kicks in when the humidity is higher then 60%

**Comment by viictor924** [comment]
Hi @madcat-nl, I was wondering if you were ever able to figure out the "when sensor detects something" automation rule. I heard this was a new feature in iOS 11 but I wasn't able to figure it out.

I've got a temperature and humidity sensor connected to homekit but the "sensor detects something" automation is still grayed out. I was able to use the EVE app as a workaround but it would be nice if it was all done via the Home app. 

FYI, I use a dht22 sensor via homebridge using this plugin:
https://github.com/NorthernMan54/homebridge-dht

![img_0075 jpg](https://user-images.githubusercontent.com/23468631/31376990-810e19b0-ad5b-11e7-888f-e7b44c32759e.JPG)

![img_0074 jpg](https://user-images.githubusercontent.com/23468631/31376996-862e991a-ad5b-11e7-8af9-196e9a11244b.JPG)

**Comment by dezral** [comment]
As far as i know and not found in IOS you can't make an action in homekit yet with only temp sensor.. it only works with a thermostat..

**Comment by lee-pham** [comment]
@viictor924 I've been messing around with HAP-NodeJS, and @dezral is correct. A temperature sensor doesn't qualify as a sensor that can be used for automation. However, a motion sensor can be used.

![img_751b51743167-1](https://user-images.githubusercontent.com/17168754/39227393-f0b60950-481d-11e8-8ee2-f41ffb01ff27.jpeg)
