### ISSUE TITLE
MQTT Fan_accessory.js

### ISSUE THREAD

**Issue by Maxmudjon** [KhaosT/HAP-NodeJS#328]
Fan accessory for HAP-NodeJS
MQTT_Fan_accessory.txt

Fan accessory for ESP8266
Ventilator_MQTT.txt

The fan with three modes

**Comment by madcat-nl** [comment]
i'm not sure what your question is, but i use a float which results in a 0-100 scale and when it's 0-33% on low, 34-66% is medium and 67-100% is high. When you ask siri she will set it on 25,50 or 100%

**Comment by Maxmudjon** [comment]
the code for the fan with three modes

**Comment by TeraJaQ** [comment]
hi, i've made this...

`var Accessory = require('../').Accessory;
var Service = require('../').Service;
var Characteristic = require('../').Characteristic;
var uuid = require('../').uuid;
var Value;
var power=0; 
var outTopic1='HOME/Ventilatore/SetSpeed';
var outTopic2='HOME/Ventilatore/GetSpeed';
var inTopic1 = 'HOME/Ventilatore/StatusSpeed';
var inTopic2 = 'HOME/Ventilatore/Status'

// MQTT Setup
var mqtt = require('mqtt');
var options = {
  port: 1883,
  host: '127.0.0.1',
  clientId: 'Fan'
};
var client = mqtt.connect(options);
client.on('connect', function () {

 client.subscribe(inTopic1);
 client.subscribe(inTopic2);
 client.publish(outTopic2,'?');
});
client.on('message', function(topic, message) {
 if (topic == inTopic1){
   Value = parseFloat(message);
   FAKE_FAN.rSpeed = Value;
 }
 if (topic == inTopic2)
   FAKE_FAN.powerOn = parseFloat(message);
});
// here's a fake hardware device that we'll expose to HomeKit
var FAKE_FAN = {
  powerOn: false,
  rSpeed: 100,
  setPowerOn: function(on) {
    if(on){
      //put your code here to turn on the fan
      FAKE_FAN.powerOn = on;
      client.publish(outTopic1,FAKE_FAN.rSpeed.toString())
    } else{
      //put your code here to turn off the fan
      FAKE_FAN.powerOn = on;
      client.publish(outTopic1,"0")
    }
  },
  setSpeed: function(value) {
    console.log("Setting fan rSpeed to %s", value);
    FAKE_FAN.rSpeed = value;
    client.publish(outTopic1,FAKE_FAN.rSpeed.toString())
    //put your code here to set the fan to a specific value
  },
  getPower: function() {      //to restore information from mqtt when raspberry reboot
    if(this.outputLogs) 
     console.log("'%s' is %s.", this.name, this.power ? "on" : "off");
	client.publish("HOME/Ventilatore/Status/?","?");
	return FAKE_FAN.powerOn;
  },
  getSpeedStatus: function(){   //to restore information from mqtt when raspberry reboot
    client.publish(outTopic2,'?');
    return FAKE_FAN.rSpeed;
  },
  identify: function() {
    //put your code here to identify the fan
    console.log("Fan Identified!");
  }
}
// This is the Accessory that we'll return to HAP-NodeJS that represents our fake fan.
var fan = exports.accessory = new Accessory('Fan', uuid.generate('hap-nodejs:accessories:Fan'));
// Add properties for publishing (in case we're using Core.js and not BridgedCore.js)
fan.username = "1A:22:32:42:2E:FF";
fan.pincode = "031-45-154";
// set some basic properties (these values are arbitrary and setting them is optional)
fan
  .getService(Service.AccessoryInformation)
  .setCharacteristic(Characteristic.Manufacturer, "JaQ")
  .setCharacteristic(Characteristic.Model, "Rev-1")
  .setCharacteristic(Characteristic.SerialNumber, "0025");

// listen for the "identify" event for this Accessory
fan.on('identify', function(paired, callback) {
  FAKE_FAN.identify();
  callback(); // success
});
// Add the actual Fan Service and listen for change events from iOS.
// We can see the complete list of Services and Characteristics in `lib/gen/HomeKitTypes.js`
fan
  .addService(Service.Fan, "Fan") // services exposed to the user should have "names" like "Fake Light" for us
  .getCharacteristic(Characteristic.On)
  .on('set', function(value, callback) {
    FAKE_FAN.setPowerOn(value);
    if (value){
    client.publish(outTopic1,FAKE_FAN.rSpeed.toString());
    } else {
    client.publish(client.publish(outTopic1,"0"));
    }
    callback(); // Our fake Fan is synchronous - this value has been successfully set
  });
fan
  .getService(Service.Fan)
  .getCharacteristic(Characteristic.On)
  .on('get', function(callback) {
    // this event is emitted when you ask Siri directly whether your fan is on or not. you might query
    // the fan hardware itself to find this out, then call the callback. But if you take longer than a
    // few seconds to respond, Siri will give up.
client.publish("HOME/Ventilatore/Status/?","?");
    var err = null; // in case there were any problems

    if (FAKE_FAN.powerOn) {
      callback(err, true);
    }
    else {
      callback(err, false);
    }
});
// also add an "optional" Characteristic for spped
fan
  .getService(Service.Fan)
  .addCharacteristic(Characteristic.RotationSpeed)
  .on('get', function(callback) {
    callback(null, FAKE_FAN.rSpeed);
  })
  .on('set', function(Value, callback) {
    FAKE_FAN.setSpeed(Value);
    callback();
  })
  
setInterval(function(){
client.publish("HOME/Ventilatore/Status/?","?");
},60000);
`
and this is my arduino code


`#include <EEPROM.h>
#include <ESP8266WiFi.h>
#include <ESP8266mDNS.h>
#include <WiFiUdp.h>
#include <ArduinoOTA.h>
#include <PubSubClient.h>
#include "RemoteDebug.h"        //https://github.com/JoaoLopesF/RemoteDebug
RemoteDebug Debug;

#include "Adafruit_MQTT.h"
#include "Adafruit_MQTT_Client.h"

WiFiClient Ventilatore;
PubSubClient client(Ventilatore);
#define HOST_NAME "Ventilatore"

const char* ssid = "Valentina";
const char* password = "valentilla";
const char* mqtt_server = "192.168.1.123";

int softValue1 = HIGH;
int softValue2 = HIGH;
int softValue3 = HIGH;
int value = 0;
int powerstate = 0;

char msg[50];

const byte Fan1 = D5;
const byte Fan2 = D6;
const byte Fan3 = D7;

const char* outTopic1 = "HOME/Ventilatore/StatusSpeed";
const char* outTopic2 = "HOME/Ventilatore/Status";
const char* inTopic1 = "HOME/Ventilatore/SetSpeed";
const char* inTopic2 = "HOME/Ventilatore/GetSpeed";
const char* inTopic3 = "HOME/Ventilatore/Status/?";

void callback(char* topic, byte* payload, unsigned int length) {
  // Conver the incoming byte array to a string
  payload[length] = '\0'; // Null terminator used to terminate the char array
  String message = (char*)payload;

  Debug.print("Message arrived [");
  Debug.print(topic);
  Debug.print("] [");
  Debug.print(message);
  Debug.println("] ");

  if (strcmp (topic, inTopic1) == 0) {

    char receivedAll2[length];
    for (int x = 0; x < length; x++) {
      char receivedChar = (char)payload[x];
      Debug.print(receivedChar);
      receivedAll2[x] = receivedChar;
    }
    Debug.println(" ");
    value = atoi (receivedAll2);

    if (value == 0)    {
      softValue1 = HIGH;
      softValue2 = HIGH;
      softValue3 = HIGH;
      powerstate = 0;
    } else if (value > 0 && value <= 33) {
      softValue1 = LOW;
      softValue2 = HIGH;
      softValue3 = HIGH;
      powerstate = 1;
    } else if (value > 33 && value <= 66) {
      softValue1 = HIGH;
      softValue2 = LOW;
      softValue3 = HIGH;
      powerstate = 1;
    } else if (value > 66 && value <= 100) {
      softValue1 = HIGH;
      softValue2 = HIGH;
      softValue3 = LOW;
      powerstate = 1;
    }
    digitalWrite(Fan1, softValue1);
    digitalWrite(Fan2, softValue2);
    digitalWrite(Fan3, softValue3);
  }

  else if (strcmp (topic, inTopic2) == 0) {
    if (message == "?") {
      if (value != 0) {
        dtostrf(value , 0, 0, msg);
        client.publish(outTopic1, msg);
      }
    }
  }
  else if (strcmp (topic, inTopic3) == 0) {
    if (message == "?") {
      dtostrf(powerstate , 0, 0, msg);           // no value ma power state
      client.publish(outTopic2, msg);
    }
  }

  Debug.println();
}

void reconnect() {

  while (!client.connected()) {
    Debug.println("Attempting MQTT connection...");
    // Attempt to connect
    if (client.connect("Ventilatore")) {
      Debug.println("Ventilatore connected");
      // ... and subscribe to topic
      client.subscribe("HOME/Ventilatore/#");
    } else {
      Debug.print("failed, rc=");
      Debug.print(client.state());
      Debug.println(" try again in 5 second");
      // Wait 5 seconds before retrying
      delay(5000);
    }
  }
}

void setup() {
  Serial.begin(115200);
  pinMode(Fan1, OUTPUT);
  pinMode(Fan2, OUTPUT);
  pinMode(Fan3, OUTPUT);

  //digitalWrite(Fan1, softValue1);
  //digitalWrite(Fan2, softValue2);
  //digitalWrite(Fan3, softValue3);


  Debug.begin("Ventilatore"); // Initiaze the telnet server
  Debug.setSerialEnabled(true);
  Debug.setResetCmdEnabled(true); // Enable the reset command
  Debug.showTime(true); // To show time
  Debug.showProfiler(true); // To show profiler - time between messages of Debug
  // Good to "begin ...." and "end ...." messages
  ConnectWifi();
  OTA();
  client.setServer(mqtt_server, 1883);
  client.setCallback(callback);
}

void loop() {
  if (WiFi.waitForConnectResult() != WL_CONNECTED)
    ConnectWifi();
  ArduinoOTA.handle();
  if (!client.connected())
    reconnect();
  Debug.handle();
  client.loop();
  yield();
}

bool ConnectWifi() {
  WiFi.mode(WIFI_STA);
  WiFi.disconnect();
  delay(100);
  WiFi.begin(ssid, password);
}

void OTA() {
  ArduinoOTA.setPort(8266);
  ArduinoOTA.setHostname("Ventilatore");
  //ArduinoOTA.setPassword((const char *)"123");
  ArduinoOTA.onStart([]() {
    Serial.println("Start");
  });
  ArduinoOTA.onEnd([]() {
    Serial.println("\nEnd");
  });
  ArduinoOTA.onProgress([](unsigned int progress, unsigned int total) {
    Serial.printf("Progress: %u%%\r", (progress / (total / 100)));
  });
  ArduinoOTA.onError([](ota_error_t error) {
    Serial.printf("Error[%u]: ", error);
    if (error == OTA_AUTH_ERROR) Serial.println("Auth Failed");
    else if (error == OTA_BEGIN_ERROR) Serial.println("Begin Failed");
    else if (error == OTA_CONNECT_ERROR) Serial.println("Connect Failed");
    else if (error == OTA_RECEIVE_ERROR) Serial.println("Receive Failed");
    else if (error == OTA_END_ERROR) Serial.println("End Failed");
  });
  ArduinoOTA.begin();
}`
