### ISSUE TITLE
Characteristic.ChargingState.NOT_CHARGEABLE not supported anymore?

### ISSUE THREAD

**Issue by richardklose** [KhaosT/HAP-NodeJS#329]
I think that Characteristic.ChargingState.NOT_CHARGEABLE is not supported by HomeKit anymore? If i set it, the device can not be added to HomeKit any more. The native iOS Home App simply says "could not add device" with no further information.

I also could not find the value in other HomeKit documentations. e.g.:
https://developer.apple.com/reference/homekit/hmcharacteristictypechargingstate
https://developer.xamarin.com/api/type/HomeKit.HMCharacteristicValueChargingState/

**Comment by KhaosT** [comment]
It's caused by a metadata mismatch. I updated the maxValue for this characteristic and now it should work.

**Comment by richardklose** [comment]
Wow that was fast. It's working now. Keep the awesomeness going!
