### ISSUE TITLE
Elgato Avea Light Bulb

### ISSUE THREAD

**Issue by Alblahm** [KhaosT/HAP-NodeJS#330]
We have written a new accessory file to work with this bluetooth light:
https://www.elgato.com/es/avea

 It doesnt need anything more than the raspberry pi with the Hap-NodeJS installed and this accessory file:
[Luz_VerticalComedor_accessory.js.txt](https://github.com/KhaosT/HAP-NodeJS/files/586717/Luz_VerticalComedor_accessory.js.txt)

You have to paste it into the accessories folder and eliminate the ".txt" extension to make it work. Does anyone have bought this light and can make a fast check with this accessory file ?. I did, and it seems it works fine, but it would be perfect if anyone more can check it, or improve the code.

To make it work you also need to download the light lib inside the node_modules folder. 
>cd Hap-NodeJS/node_modules
>git clone https://github.com/Marmelatze/avea_node.git

And you should be able to turn on and off, or change brightness with siri.

**Comment by KhaosT** [comment]
Thanks for sharing this :)
Since this is technically not a "issue", I'll close the issue for now.
