### ISSUE TITLE
Motion Sensor from ESP8266 it is necessary to code

### ISSUE THREAD

**Issue by Maxmudjon** [KhaosT/HAP-NodeJS#334]
Please help me to write code

**Comment by oriolism** [comment]
Take a look a this: 
https://github.com/hobbyquaker/homekit2mqtt

**Comment by cflurin** [comment]
have a look at:

http://www.letscontrolit.com/wiki/index.php/ESPEasy
https://github.com/cflurin/homebridge-mqtt
https://github.com/cflurin/homebridge-mqtt/wiki/homebridge2ESP8266

**Comment by Maxmudjon** [comment]
I want to make an accessory for HAP-NodeJS
example (motionSensor_accessory.js)
