### ISSUE TITLE
Remote Access with VPN

### ISSUE THREAD

**Issue by fabsfuchs** [KhaosT/HAP-NodeJS#337]
Hello,

is it possible to access the homekit server through VPN? Normally this shouldn't be possible because Bonjour is a multicast protocol. I found some information about a "bridged-vpn" maybe with Open VPN on the raspberry?
Has anyone ever tried this approach?
For the client I want to use my iPhone.

**Comment by KhaosT** [comment]
@fabsfuchs OpenVPN with tap-style tunnel should allow Bonjour to work but iOS doesn't support that. So nope.

**Comment by llemtt** [comment]
In order to work through VPN you have to proxy Bonjour announcements locally.
Yesterday I was at a remote location with a MacBook proxying Bonjour with dns-sd -P ... and my iPhone connected home with VPN and everything was working!

In order to work with my iPhone alone I would need an app to do the dns-sd job...

**Comment by Glavin001** [comment]
@llemtt  could you describe your steps more thoroughly? I would like to create a Docker container for easily setting up a VPN server which supports remote access to HomeKit.

**Comment by llemtt** [comment]
@Glavin001 what kind of VPN is yours? is "client to net" or "net to net"?

**Comment by Glavin001** [comment]
I think "client to net" is appropriate, however I am not entirely sure. I found http://www.pivpn.io/ and will be trying this on my Raspberry Pi later next week and connect on my iPhone with `Settings -> General -> VPN --> Add configuration` in the hopes that my HomeKit devices will then be accessible remotely.

**Comment by llemtt** [comment]
"client to net" requires either:

-  another computer to proxy Bonjour announcements to your iPhone via WiFi as I did it; 
I used a Mac and run the following command:
dns-sd -P "Homebridge" _hap._tcp local. 51826 hap.local. 192.168.1.10 "md=Homebridge" "pv=1.0" "id=CC:22:3D:E3:CE:30" "c#=2" "s#=1" "ff=0" "ci=2" "sf=0"

where 192.168.1.10 is the address of your HAP accessory

- an app to proxy Bonjour announcements directly on your iPhone:
the best I have come to date is a minimal app I wrote that works 180 seconds before being "background suspended" (which kills announcements)

**Comment by Glavin001** [comment]
> another computer to proxy Bonjour announcements to your iPhone via WiFi as I did it;

Could I perform this on a Raspberry Pi? I am not sure the best way to use`dns-sd` on the pi. 

```bash
root@raspberrypi-2d773a8:/usr/src/app# dns-sd
bash: dns-sd: command not found
root@raspberrypi-2d773a8:/usr/src/app# apt-cache search dns-sd
avahi-daemon - Avahi mDNS/DNS-SD daemon
libapache2-mod-dnssd - Zeroconf support for Apache 2 via avahi
libavahi-client-dev - Development files for the Avahi client library
libavahi-client3 - Avahi client library
libavahi-core-dev - Development files for Avahi's embeddable mDNS/DNS-SD library
libavahi-core7 - Avahi's embeddable mDNS/DNS-SD library
libepc-1.0-3 - Easy Publish and Consume library - shared libraries
libepc-common - Easy Publish and Consume library - data files
libepc-dev - Easy Publish and Consume library - development files
libepc-doc - Easy Publish and Consume library - documentation
libepc-ui-1.0-3 - Easy Publish and Consume library - shared widget libraries
libepc-ui-dev - Easy Publish and Consume library - widget development files
libkdnssd4 - DNS-SD Protocol Library for the KDE Platform
mdns-scan - Scan for mDNS/DNS-SD services published on the local network
pike7.8-dnssd - DNS Service Discovery (DNS-SD) for Pike
```

> where 192.168.1.10 is the address of your HAP accessory

So each accessory (Homebridge and physical devices) would need to have a process running a respective variation of this command?

My goal would be to bundle everything (VPN, homebridge, etc) into a Docker container running on a Raspberry Pi (or similar device): https://github.com/Glavin001/resin-homebridge

**Comment by Glavin001** [comment]
I have setup my VPN on the Raspberry Pi using [pivpn](http://www.pivpn.io/).

My Homebridge config:

```javascript
# cat /data/.homebridge/config.json
{
    "bridge": {
        "name": "Homebridge - Raspberry Pi 1",
        "username": "CC:22:3D:E3:CE:30",
        "port": 51826,
        "pin": "031-45-154"
    },
    "description": "Homebridge running on Resin.io",
    "accessories": [
    // ...
    ]
}
```

The IP of the pi is `192.168.1.25`:

```bash
# ifconfig
docker0   Link encap:Ethernet  HWaddr 02:42:00:70:7b:10
          inet addr:172.17.0.1  Bcast:0.0.0.0  Mask:255.255.0.0
          inet6 addr: fe80::8d26:1c7d:e981:357d/64 Scope:Link
          UP BROADCAST MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)

eth0      Link encap:Ethernet  HWaddr b8:27:eb:25:bd:12
          inet addr:192.168.1.25  Bcast:192.168.1.255  Mask:255.255.255.0
          inet6 addr: fe80::ba27:ebff:fe25:bd12/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST DYNAMIC  MTU:1500  Metric:1
          RX packets:471290 errors:0 dropped:0 overruns:0 frame:0
          TX packets:529633 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:308881797 (294.5 MiB)  TX bytes:80013970 (76.3 MiB)

lo        Link encap:Local Loopback
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:97177 errors:0 dropped:0 overruns:0 frame:0
          TX packets:97177 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:7615709 (7.2 MiB)  TX bytes:7615709 (7.2 MiB)

resin-vpn Link encap:UNSPEC  HWaddr 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00
          inet addr:10.2.8.162  P-t-P:52.4.252.97  Mask:255.255.255.255
          UP POINTOPOINT RUNNING NOARP MULTICAST  MTU:1500  Metric:1
          RX packets:10478 errors:0 dropped:0 overruns:0 frame:0
          TX packets:10504 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:100
          RX bytes:684536 (668.4 KiB)  TX bytes:1558110 (1.4 MiB)

tun0      Link encap:UNSPEC  HWaddr 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00
          inet addr:10.8.0.1  P-t-P:10.8.0.1  Mask:255.255.255.0
          UP POINTOPOINT RUNNING NOARP MULTICAST  MTU:1500  Metric:1
          RX packets:3330 errors:0 dropped:0 overruns:0 frame:0
          TX packets:3914 errors:0 dropped:74 overruns:0 carrier:0
          collisions:0 txqueuelen:100
          RX bytes:289743 (282.9 KiB)  TX bytes:4110437 (3.9 MiB)
```

I modified your command and ran:

```bash
❯ dns-sd -P "Homebridge - Raspberry Pi 1" _hap._tcp local. 51826 hap.local. 192.168.1.25 "md=Homebridge - Raspberry Pi 1" "pv=1.0" "id=CC:22:3D:E3:CE:30" "c#=2" "s#=1" "ff=0" "ci=2" "sf=0"
Registering Service Homebridge - Raspberry Pi 1._hap._tcp.local. host hap.local. port 51826 TXT md=Homebridge\ -\ Raspberry\ Pi\ 1 pv=1.0 id=CC:22:3D:E3:CE:30 c#=2 s#=1 ff=0 ci=2 sf=0
DATE: ---Wed 01 Mar 2017---
13:48:28.962  ...STARTING...
13:48:29.873  Got a reply for record hap.local.: Name now registered and active
13:48:30.179  Got a reply for service Homebridge - Raspberry Pi 1 (2)._hap._tcp.local.: Name now registered and active
```

While connecting using OpenVPN client on iOS I am still unable to see accessories under Apple's Home or Elegato Eve app.

Any ideas?

**Comment by KhaosT** [comment]
You need OpenVPN TAP mode in order to support Bonjour over VPN. However iOS doesn't support TAP mode. That's why llemtt is using another app to re-broadcast Bonjour frames "the best I have come to date is a minimal app I wrote that works 180 seconds before being "background suspended" (which kills announcements)"

**Comment by Glavin001** [comment]
> > "client to net" requires **either**:
> 
> That's why llemtt is using another app to re-broadcast Bonjour frames "the best I have come to date is a minimal app I wrote that works 180 seconds before being "background suspended" (which kills announcements)"

Oooooh, I read it as two **alternatives** and opted for the approach without an iOS app. So both are actually required. I did try to setup TAP mode, however, as you mentioned, iOS does not support TAP mode which I learned the hard way.

Is this Bonjour re-broadcast app something you would be willing to share?

**Comment by llemtt** [comment]
You actually have two alternatives!

the first one requires another "not iOS device" connected to the same WiFi network your iPhone is connected

the second one requires the app (mine attached) on your iPhone
[BonjourProxy.zip](https://github.com/KhaosT/HAP-NodeJS/files/821379/BonjourProxy.zip)

**Comment by Glavin001** [comment]
> the first one requires another "not iOS device" connected to the same WiFi network your iPhone is connected

My current setup is something like this:

iPhone (over cellular) <--> OpenVPN Client <--> OpenVPN Server <--> Raspberry Pi (at home, running Homebridge, could run `dns-sd`?) <--> Mac (at home, could run `dns-sd`?)

I was hoping the Raspberry Pi or another computer (Mac?) could broadcast the Bonjour information from home so the iPhone (over cellular) could access Homebridge.

**Comment by llemtt** [comment]
Sorry.. actually you can't broadcast Bonjour "over" VPN to iOS!

Bonjour packets on iOS, and OS X too, are accepted only coming from "not point-to-point" network interfaces.

**Comment by Glavin001** [comment]
So this leaves the BonjourProxy app as the only option, for this case? Thanks for the info! I'll test things out this weekend.

**Comment by lorenzodroid** [comment]
I'm interested too, it works with Bonjour proxy on Rasp?

Thanks ;)

**Comment by 0xcaff** [comment]
@llemtt Do you know whether [Wide Area Bonjour](http://theriom.com/Access-your-Bonjour-printer-over-VPN-from-your-iOS-device) can be used to accomplish this?

**Comment by llemtt** [comment]
Sorry but Wide Area Bonjour doesn't work because all accessories lookups are made only on .local domain. Hap/Homekit is one of those Apple bonjour based frameworks designed to work only on the local LAN or remotely by means of his private tunnels.
