### ISSUE TITLE
Should I worry about 'This accessory is not certified.."

### ISSUE THREAD

**Issue by moonvader** [KhaosT/HAP-NodeJS#338]
I know that this question can be seen as not directly connected to HAP-NodeJS project but I still think that I can find answer here.

When I connect to any accessories that work with HAP-NodeJS and RPi - I get notification that this accessory is not certified by Apple.
My question is - can I build complex home automation solutions for HomeKit based on RPi and HAP-NodeJS or this option can be blocked by Apple at any time as this devices are not Apple certified?

**Comment by PatchworkBoy** [comment]
Who can say...? Yes, at any time Apple could release an update that locks HomeKit entirely to function only with certified devices.

HAP-NodeJS is a hack at the end of the day. Prototyping a business model with it - fine. RELYING on it? Foolish. If basing a business model on it, go down the sanctioned MFi certification route, or accept the risks.

**Comment by pieceofsummer** [comment]
You shouldn't worry too much. If they do that, their own Accessory Simulator won't work too, so it is unlikely.

**Comment by llemtt** [comment]
I'm pretty sure they'll move to MFi certified accessories as soon as they fear an actual security issue to the whole homekit/ios ecosystem. We won't see HomeKit on OSX soon either for the same reason, at least on current macs, maybe on the newest MacBooks...
