### ISSUE TITLE
Error: Could not locate the bindings file. Tried:

### ISSUE THREAD

**Issue by Techchunky** [KhaosT/HAP-NodeJS#343]
So I get the following error when running node Core.js

Error: Could not locate the bindings file. Tried:
 → /home/pi/node_modules/hap-nodejs/node_modules/curve25519-n/build/curve.node
 → /home/pi/node_modules/hap-nodejs/node_modules/curve25519-n/build/Debug/curve.node
 → /home/pi/node_modules/hap-nodejs/node_modules/curve25519-n/build/Release/curve.node
 → /home/pi/node_modules/hap-nodejs/node_modules/curve25519-n/out/Debug/curve.node
 → /home/pi/node_modules/hap-nodejs/node_modules/curve25519-n/Debug/curve.node
 → /home/pi/node_modules/hap-nodejs/node_modules/curve25519-n/out/Release/curve.node
 → /home/pi/node_modules/hap-nodejs/node_modules/curve25519-n/Release/curve.node
 → /home/pi/node_modules/hap-nodejs/node_modules/curve25519-n/build/default/curve.node
 → /home/pi/node_modules/hap-nodejs/node_modules/curve25519-n/compiled/0.10.0/linux/arm/curve.node
    at bindings (/home/pi/node_modules/hap-nodejs/node_modules/bindings/bindings.js:88:9)
    at Object.<anonymous> (/home/pi/node_modules/hap-nodejs/node_modules/curve25519-n/index.js:1:96)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/pi/node_modules/hap-nodejs/lib/util/encryption.js:3:18)
    at Module._compile (module.js:456:26)

If I do NPM rebuild I get: 

sh: 1: node-gyp: not found

npm ERR! curve25519-n@1.1.0 install: `node-gyp rebuild`
npm ERR! `sh "-c" "node-gyp rebuild"` failed with 127
npm ERR! 
npm ERR! Failed at the curve25519-n@1.1.0 install script.
npm ERR! This is most likely a problem with the curve25519-n package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls curve25519-n
npm ERR! There is likely additional logging output above.
npm ERR! 
npm ERR! System Linux 4.1.19+
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "rebuild" "--unsafe-perm"
npm ERR! cwd /home/pi/node_modules/hap-nodejs
npm ERR! node -v v0.6.19
npm ERR! npm -v 1.1.4
npm ERR! code ELIFECYCLE
npm ERR! message curve25519-n@1.1.0 install: `node-gyp rebuild`
npm ERR! message `sh "-c" "node-gyp rebuild"` failed with 127
npm ERR! errno {}
npm WARN This failure might be due to the use of legacy binary "node" 
npm WARN For further explanations, please read
npm WARN /usr/share/doc/nodejs/README.Debian
npm WARN 
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/pi/node_modules/hap-nodejs/npm-debug.log
npm not ok

**Comment by legotheboss** [comment]
Your node version is too old, try updating to a node version above 5...

**Comment by Techchunky** [comment]
Thanks, now I am getting this: Error: listen EADDRINUSE 0.0.0.0:51826 Tried to reboot etc. @legotheboss
