### ISSUE TITLE
Trying to reinstall HAP-NodeJS and can't add or see accessories 

### ISSUE THREAD

**Issue by bluntiless** [KhaosT/HAP-NodeJS#344]
![img_0398](https://cloud.githubusercontent.com/assets/1809627/20492509/e7de25ec-b00c-11e6-9e7e-2c670f13d3af.PNG)

Can you help me with with this issue? Also can you let me know what is the simplest way to update to the latest version of the server.

Kind regards 

Bluntiless

**Comment by rodorgas** [comment]
Your raspberry pi is connected to a network? WiFi or Ethernet?
Please copy the output of the command `ifconfig`

**Comment by bluntiless** [comment]
Hi Rodorgas, 
Its connected via WiFi. 
I'll try the ifconfig next

**Comment by bluntiless** [comment]
![img_0399](https://cloud.githubusercontent.com/assets/1809627/20494908/d59926c0-b016-11e6-874c-6bf4f6b568c3.PNG)
