### ISSUE TITLE
Thermostat AUTO Mode

### ISSUE THREAD

**Issue by thechrisreese** [KhaosT/HAP-NodeJS#347]
Now that home kit allows AUTO for Thermostats, is anyone able to find the MaxMax MaxMin MinMax MinMin Characteristics UUIDs? This would be very helpful to set up AUTO for Thermostats in Homebridge.

**Comment by KhaosT** [comment]
It's called Heating Threshold and Cooling Threshold

**Comment by thechrisreese** [comment]
Ok. I'm trying to make the Homebridge-Wink plugin work. I'll keep playing assuming those will work.

**Comment by thechrisreese** [comment]
Ok so with Auto, there are 6 settings - 

Current Temp
Target Temp 
Max Allowed Temp (usually 95 degrees)
Max Cooling Temp (CoolingThreshold)
Min Heating Temp (Heating Threahold)
Min Allowed Temp (usually 50 degrees)

For Auto to work, I need to be able to tell Honekit what those Max and Min allowed temps are. So far I have had no success. Not sure what's broken but can anyone help?

**Comment by KhaosT** [comment]
[Min Heating Temp](https://github.com/KhaosT/HAP-NodeJS/blob/master/lib/gen/HomeKitTypes.js#L726)
[Max Cooling Temp](https://github.com/KhaosT/HAP-NodeJS/blob/master/lib/gen/HomeKitTypes.js#L407)

Min Allowed Temp and Max Allowed Temp are set by [adjusting](https://github.com/KhaosT/HAP-NodeJS/blob/master/lib/Characteristic.js#L108) min/maxValue on characteristics.

**Comment by thechrisreese** [comment]
Ok. I know this is closed but I will have to figure out how to do this. Would you be willing to help me out with the homebridge-wink section for the themorstat Heating and Cooling thresholds? 

I can't figure out how to get it to tell HomeKit Max Allowed and Min Allowed. 

	this
		.getService(Service.Thermostat)
		.getCharacteristic(Characteristic.HeatingThresholdTemperature)
		.on('get', function (callback) {
			callback(null, that.device.last_reading.min_set_point);
		})
		.on('set', function (value, callback) {
			that.updateWinkProperty(callback, "min_set_point", value);
		});

	this
		.getService(Service.Thermostat)
		.getCharacteristic(Characteristic.CoolingThresholdTemperature)
		.on('get', function (callback) {
			callback(null, that.device.last_reading.max_set_point);
		})
		.on('set', function (value, callback) {
			that.updateWinkProperty(callback, "max_set_point", value);
		});

**Comment by thechrisreese** [comment]
![img_0512](https://cloud.githubusercontent.com/assets/20584219/20645706/1500b6fe-b41b-11e6-9831-1b3855525d81.PNG)

This is the problem. The HeatingThreshold is working but the CoolingThreshold is not. Please any help?

**Comment by nathantsmith** [comment]
Was any progress made on this front?

**Comment by thechrisreese** [comment]
Yes. 

Simple answer is that Hap-Nodejs puts Characteristic.HeatingThresholdTemperature at maxValue: 25; this caps it at 77 degrees F which causes this. 

Go to your Homebridge installation in npm and open homebridge>node_modules>hap-nodejs>lib>gen>HomekitTypes.js and scroll to around 790's and change the HeatingThresholdTemperature maxValue to 35 or higher. 

This will not persisit after updates and I know there is a way to update this with the right code but I'm not there

**Comment by profesionalTI** [comment]
I use Homekit over Node-Red, I have the following problem with Thermostat on Automatic Mode:

![img_1012](https://user-images.githubusercontent.com/8957929/34877108-5e2d5704-f783-11e7-8052-5d7b56684893.PNG)

Only show me one control, not double control how this:

![1500b6fe-b41b-11e6-9831-1b3855525d81](https://user-images.githubusercontent.com/8957929/34877150-8da2a160-f783-11e7-9246-44c92495a1e7.PNG)

Any idea?

**Comment by profesionalTI** [comment]
The thermostat service show me:
![current thermostat](https://user-images.githubusercontent.com/8957929/34902659-019c403c-f7ff-11e7-8107-44853a43b0b0.PNG)

This is my automatic mode, I don't know what happened because it will show:
![wish thermostat](https://user-images.githubusercontent.com/8957929/34902667-27a284b2-f7ff-11e7-8947-b7f87f365a3e.PNG)

Please Help  any idea?!

**Comment by thechrisreese** [comment]
Again - this is an issue with how hap-node.js reads settings and fills in honekittypes.js. I have been told that’s “not true” but when I change homekittypes.js to have accurate heatingthreshold temperatures and cooling threshold temperatures this issue disappears. Homekittypes.js is telling homekittypes that your thermostat only goes to 77 degrees mac. Same exact thing happened to me.

**Comment by profesionalTI** [comment]
Can you tell me what line of HomeKitTypes.js need to change?

**Comment by thechrisreese** [comment]
From above - 

“Go to your Homebridge installation in npm and open homebridge>node_modules>hap-nodejs>lib>gen>HomekitTypes.js and scroll to around 790's and change the HeatingThresholdTemperature maxValue to 35 or higher.”

**Comment by profesionalTI** [comment]
@thechrisreese I make the change on HomekitTypes.js in HeatingThresholdTemperature, change value to 50:

![heatingthresholdtemperature](https://user-images.githubusercontent.com/8957929/34910675-f5e133a2-f898-11e7-91ee-35374efc28ef.png)

In the same file, CoolingThresHoldTemperature was: (no make changes)

![coolingthresholdtemperature](https://user-images.githubusercontent.com/8957929/34910683-12d50e66-f899-11e7-9cb5-3c0d387e1b0d.png)

Now, I create again Thermostat Accessory, and the iPhone show me the following on Automatic Mode:

![thermostat auto mode](https://user-images.githubusercontent.com/8957929/34910687-2fc0747a-f899-11e7-985f-5015926a6181.jpeg)

Any idea?!

**Comment by thechrisreese** [comment]
Make both cooking and heating 35 or above

**Comment by profesionalTI** [comment]
I change cooling and heating to 35, and try with 45 too, but, in iPhone UI show me 38º, I search where is this value and I find on accessories/Thermostat_accessory.js (https://github.com/KhaosT/HAP-NodeJS/blob/master/accessories/Thermostat_accessory.js)


![thermo](https://user-images.githubusercontent.com/8957929/34910815-92afaee6-f89b-11e7-9442-a795801675a1.png)

**Comment by profesionalTI** [comment]
I need something on Characteristic.js? what need to change o add?

**Comment by TeraJaQ** [comment]
Check the TargetTemperature on HomekitTypes.js....

this is my MQTT thermostat accessory


var Accessory = require('../').Accessory;
var Service = require('../').Service;
var Characteristic = require('../').Characteristic;
var uuid = require('../').uuid;
var mqtt = require('mqtt');

var topicCurrentTemperature = 'HOME/Termostato/Current/Temperature';
var topicCurrentHumidity = 'HOME/Termostato/Current/Humidity';
var topicTargetTemperature = "HOME/Termostato/Target/Temperature";
var topicTargetHumidity = 'HOME/Termostato/Target/Humidity';
var topicTargetHCS = 'HOME/Termostato/Target/Hcs';
var topicCurrentHCS = 'HOME/Termostato/Current/HCS';

var Temperature = 24;
var CurrentHumidity =20;
var targetHum = 40;
var targetTemp = 25;

var state = false;

var targetHeatCoolState = 0;
var currentHCS = 0;

var vuota=0;
var vuota2 = ".";

var fs = require('fs');

var options = {
  port: 1883,
  host: '127.0.0.1',  //MQTT broker on same raspberry
  clientId: 'Termostato'
};


var client = mqtt.connect(options);

client.on('connect', function () {
 client.subscribe('HOME/Termostato/#');
 client.publish('HOME/Termostato/getall','info');
 client.publish('HOME/Termostato/getStatus/Humidity','???');
 client.publish('HOME/Termostato/getStatus/Temperature','???');
});

client.on('message', function(topic, message) {
  if(topic == topicCurrentTemperature){
    Temperature = parseFloat(message);
    fs.writeFile('logValue/RoomTemp.txt', Temperature, function (err) { //log current temp on file
     if (err) return console.log(err);
    });
  }
  else if(topic == topicCurrentHumidity){
    CurrentHumidity = parseFloat(message);
    fs.writeFile('logValue/RoomHumi.txt', CurrentHumidity, function (err) { //log current Humidity on file
     if (err) return console.log(err);
    });
  }
  else if(topic == topicCurrentHCS){
    currentHCS=parseFloat(message);
    fs.writeFile('logValue/currentHCS.txt', currentHCS, function (err) {//log current HCS on file
     if (err)
      return console.log(err);
    });
   TermostatoCasa
     .getService(Service.Thermostat)
     .setCharacteristic(Characteristic.CurrentHeatingCoolingState, currentHCS);

     if(currentHCS == 0){
       fs.writeFile('logValue/RoomTargetTemp.txt', vuota2, function (err) { //log target temp on file
        if (err)
         return console.log(err);
       });
     }
  }
  else if (topic == "HOME/Termostato/RecoveryTemperature"){
	targetTemp=parseFloat(message);
  }
  else if (topic == "HOME/Termostato/RecoveryHumidity"){
    targetHum=parseFloat(message);
  }
  else if (topic == "HOME/Termostato/RecoveryTargetHCS"){
    targetHeatCoolState=parseFloat(message);
  }
});

var TERMOSTATO_CASA = {
//number: paramsObject.id,
  current_temperature: Temperature, // celsius
  target_temperature: targetTemp,   // celsius
  current_relative_humidity: CurrentHumidity,    /
  target_humidity: targetHum,
  temperature_scale: Characteristic.TemperatureDisplayUnits.CELSIUS,

  setTemperature: function(tmp) {
    if(tmp != targetTemp){
      TERMOSTATO_CASA.target_temperature = tmp;
      targetTemp = tmp;
      client.publish(topicTargetTemperature, targetTemp.toString());
	if(currentHCS==1){
	 fs.writeFile('logValue/RoomTargetTemp.txt', targetTemp, function (err) { //log taget temp on file
	 if (err) return console.log(err);});
	}
	 else {
	  fs.writeFile('logValue/RoomTargetTemp.txt', vuota2, function (err) { //log targe temp on file
	   if (err) return console.log(err);});
	 }
    }
  },
  setHumidity: function(hum){
    if(hum != targetHum){
     TERMOSTATO_CASA.target_humidity = hum;
     targetHumi = hum;
     client.publish(topicTargetHumidity, targetHumi.toString());
    }
  },
  setTargetHeatingCoolingState: function(state) {
    TERMOSTATO_CASA.target_heating_cooling_state = state;
    targetHeatCoolState = state;
    client.publish("HOME/Termostato/Target/Hcs", targetHeatCoolState.toString());
  }
}

var TermostatoCasaUUID = uuid.generate('"hap-nodejs:accessories:TermostatoCasa');

var name = "Termostato Casa"

var TermostatoCasa = exports.accessory = new Accessory(name, TermostatoCasaUUID);

// Add properties for publishing (in case we're using Core.js and not BridgedCore.js)
TermostatoCasa.username = "1A:AA:3C:4D:5E:AF";
TermostatoCasa.pincode = "031-45-154";

TermostatoCasa
  .getService(Service.AccessoryInformation)
  .setCharacteristic(Characteristic.Manufacturer, "JaQ")
  .setCharacteristic(Characteristic.Model, "ESP-Termostat")
  .setCharacteristic(Characteristic.SerialNumber, "0001");

TermostatoCasa
  .addService(Service.Thermostat, name); // services exposed to the user should have "names"
// add required Characteristics

// current temperature
TermostatoCasa
  .getService(Service.Thermostat)
  .getCharacteristic(Characteristic.CurrentTemperature)
  .on('get', function(callback) {
    TERMOSTATO_CASA.current_temperature = Temperature;
    callback(null, TERMOSTATO_CASA.current_temperature);
  });
// current relative humidity
TermostatoCasa
  .getService(Service.Thermostat)
  .getCharacteristic(Characteristic.CurrentRelativeHumidity)
  .on('get', function(callback) {
    TERMOSTATO_CASA.CurrentHumidity = CurrentHumidity;
    callback(null, TERMOSTATO_CASA.CurrentHumidity);
  });

// target temperature
TermostatoCasa
  .getService(Service.Thermostat)
  .getCharacteristic(Characteristic.TargetTemperature)
  .on('get', function(callback) {
    TERMOSTATO_CASA.target_temperature = targetTemp;
    callback(null, TERMOSTATO_CASA.target_temperature);
  })
  .on('set', function(value, callback) {
    TERMOSTATO_CASA.setTemperature(value);
    callback();
  });

// target humidity
TermostatoCasa
  .getService(Service.Thermostat)
  .getCharacteristic(Characteristic.TargetRelativeHumidity)
  .on('get', function(callback) {
    TERMOSTATO_CASA.target_humidity = targetHum;
    callback(null, TERMOSTATO_CASA.target_humidity);
  })
  .on('set', function(value, callback) {
    TERMOSTATO_CASA.setHumidity(value);
    callback();
  });
// current heating cooling state
TermostatoCasa
  .getService(Service.Thermostat)
  .getCharacteristic(Characteristic.CurrentHeatingCoolingState)
  .on('get', function(callback) {
    TERMOSTATO_CASA.current_heating_cooling_state = currentHCS;
    callback(null, TERMOSTATO_CASA.current_heating_cooling_state);
  });

// target heating cooling state
TermostatoCasa
  .getService(Service.Thermostat)
  .getCharacteristic(Characteristic.TargetHeatingCoolingState)
  .on('get', function(callback) {
    TERMOSTATO_CASA.target_heating_cooling_state = targetHeatCoolState;
    callback(null, TERMOSTATO_CASA.target_heating_cooling_state);
  })
  .on('set', function(value, callback) {
    console.log(value);
    TERMOSTATO_CASA.setTargetHeatingCoolingState(value);
    callback();
  });

// display units (Termostato only has read)
TermostatoCasa
  .getService(Service.Thermostat)
  .getCharacteristic(Characteristic.TemperatureDisplayUnits)
  .on('get', function(callback) {
    callback(null, TERMOSTATO_CASA.display_units);
  });

  setInterval(function(){
  client.publish('HOME/Termostato/getStatus/Temperature','???');
  client.publish('HOME/Termostato/getStatus/Humidity','???');
  TermostatoCasa
    .getService(Service.Thermostat)
    .setCharacteristic(Characteristic.CurrentTemperature, Temperature);
  TermostatoCasa
    .getService(Service.Thermostat)
    .setCharacteristic(Characteristic.CurrentRelativeHumidity, CurrentHumidity);
   TermostatoCasa
    .getService(Service.Thermostat)
    .setCharacteristic(Characteristic.TargetTemperature, targetTemp);
}, 10000);
