### ISSUE TITLE
Error on accessory file

### ISSUE THREAD

**Issue by legotheboss** [KhaosT/HAP-NodeJS#349]
Created a motion sensor accessory. [Here](https://gist.github.com/legotheboss/b92ffd29495109a5c409c638307aa00f) is the file. Been running into this error: 

````
Parsing accessory: MotionSensor_accessory.js
/home/pi/HAP-Camera/lib/Accessory.js:128
    if (existing.UUID === service.UUID) {
                                 ^

TypeError: Cannot read property 'UUID' of undefined
    at Accessory.addService (/home/pi/HAP-Camera/lib/Accessory.js:128:34)
    at Object.<anonymous> (/home/pi/HAP-Camera/accessories/MotionSensor_accessory.js:45:4)
````

Anyone know how to fix this?

**Comment by KhaosT** [comment]
It's [``Service.MotionSensor``](https://github.com/KhaosT/HAP-NodeJS/blob/master/lib/gen/HomeKitTypes.js#L2543) instead of [``Service.motionSensor``](https://gist.github.com/legotheboss/b92ffd29495109a5c409c638307aa00f#file-motionsensor_accessory-js-L45). Case sensitive.
