### ISSUE TITLE
push a message to the HAP-Server and update the characteristics of an accessory

### ISSUE THREAD

**Issue by firsttris** [KhaosT/HAP-NodeJS#35]
Hey KhaosT,

is it possible to send a msg to the HAP-Server to modify the value of a characteristic of an accessory?

my homematic equipment is able to send notifications when its state changes (e.g. light on/off, thermostat value change..)

If i read the value with my iOS app -  valueForUpdate() in 
https://github.com/KhaosT/HAP-NodeJS/blob/master/Characteristic.js#L95
is called.

So i could for example add a "onRead()" method similar to "onUpdate()" method in an accessory like you did it here: 
https://github.com/KhaosT/HAP-NodeJS/blob/master/Characteristic.js#L34

but i think it´s a bad practice to do something like a sync http call in my imaginary onRead() method.
(because i would need to wait for the answer)

would be nicer if i could push a message to the HAP-Server and update the characteristics of an accessory.

i would appreciate your thoughts

best regards
tristan

**Comment by KhaosT** [comment]
@firsttris You can modify https://github.com/KhaosT/HAP-NodeJS/blob/master/Core.js#L58 and find a way to get back the characteristic object. And in your implementation, when you get the value change update from your accessory, you can call `characteristic.updateValue(#Value, undefined)` to push the update to iOS devices.

**Comment by firsttris** [comment]
thanks for you input....

i think i have a quite good idea how to achieve this.... i will report back.

**Comment by firsttris** [comment]
Hey ;) just want to add..

i think we can already very easily do that by using the HAP-HTTP Server:
https://github.com/KhaosT/HAP-NodeJS/blob/master/Server.js

there are methods defined for everything...

you can for example easily ask for all accessories using http-get in your browser:
http://<upofhapserver>:51827/accessories

from there i get all params to call http-put on 
http://<upofhapserver>:51827/characteristics

which calls:
https://github.com/KhaosT/HAP-NodeJS/blob/master/AccessoryController.js#L48
which calls:
https://github.com/KhaosT/HAP-NodeJS/blob/master/Characteristic.js#L30
which calls:
https://github.com/KhaosT/HAP-NodeJS/blob/master/Characteristic.js#L76

which pushes the msg to iOS. (as you said)

every cool.

regards
Tristan
