### ISSUE TITLE
Accessory "withdraw" function needed

### ISSUE THREAD

**Issue by mschm** [KhaosT/HAP-NodeJS#351]
Hi,

as mentioned in https://github.com/mschm/node-red-contrib-homekit/issues/5 some kind of _withdraw()_-function as an opposite to the _publish()_-function is necessary to deallocate an accessory without having to terminate the program.

Current workaround: `accessory._advertiser.stopAdvertising();`

**Comment by KhaosT** [comment]
Try v0.4.16? There is now a Accessory.destory() method you can use.
