### ISSUE TITLE
ESP8266 - MQTT - RGB

### ISSUE THREAD

**Issue by Ramzes177** [KhaosT/HAP-NodeJS#352]
Hi,
Help to make the management of the RGB using MQTT on ESP8266

**Comment by Maxmudjon** [comment]
https://github.com/ItKindaWorks/ESP8266/tree/master/Home%20Automation/Part%207
https://github.com/ItKindaWorks/ESP8266/tree/master/Home%20Automation/Part%206

**Comment by Maxmudjon** [comment]
https://youtu.be/u_bH7e-OgQo?list=PL-VRW4ibM-f07ac4kScayqjbvaZQqYMf2
https://youtu.be/4jq-FLmUCP8?list=PL-VRW4ibM-f07ac4kScayqjbvaZQqYMf2
