### ISSUE TITLE
BatteryLevel for Homebridge?

### ISSUE THREAD

**Issue by andig** [KhaosT/HAP-NodeJS#354]
I'm developing https://github.com/andig/homebridge-fritz for FritzBox SmartHome accessories. Several users have reporting that `BatteryLevel` is reported as 0 by various apps.

I'm wondering is there's any chance that something is wrong with the `BatteryLevel` definition in HomeKitTypes? Or better- is there perhaps any pointer to a working implementation of `BatteryLevel`?

**Comment by andig** [comment]
Got it. `BatteryLevel` needs to be returned as number, not a string. JS type coercion is not helping here. Wondering if it would make sense to check/ convert types in this library or in homebridge?

**Comment by OczkoSX** [comment]
Have u tried using parseInt()?

**Comment by andig** [comment]
I have and its fine. Still wondering if this error should be caught by the library?

**Comment by KhaosT** [comment]
I always hope to add those to the library level. Sadly I don’t have too much time to work on this...

Best Wishes,
Tian

**Comment by OczkoSX** [comment]
It shouldnt be so hard. Maybe ill take a look on it
