### ISSUE TITLE
How to add an IP Camera Accessory?

### ISSUE THREAD

**Issue by rodorgas** [KhaosT/HAP-NodeJS#355]
I'm trying to add a Foscam FI9805W IP Camera to be accessible via HomeKit. I tried to follow the instructions in https://github.com/KhaosT/HAP-NodeJS/wiki/IP-Camera but the doc is a bit unclear to me.

My camera is accessible via VLC by connecting to the url `rtsp://admin:admin1@192.168.1.20:88/videoMain`. However, after setting this code in CameraCore.js (I've found it in [this PR](https://github.com/KhaosT/HAP-NodeJS/pull/288/files)), the camera in Home app keeps loading forever.
```
var cameraSource = new Camera([{
    uri: 'rtsp://admin:admin1@192.168.1.20:88/videoMain',
    width: 1280,
    height: 720,
    fps: 30
}]);
```
Print of Home app that keeps loading forever: https://imgur.com/a/CmW1b
Server log if useful: https://gist.github.com/rodorgas/b1c7e9c2754cfd6078ebfb5106d77320

Am I missing something?

**Comment by legotheboss** [comment]
What hardware are you running homebridge on?

**Comment by rodorgas** [comment]
These tests were done on my MacBook, but I'm using HAP-NodeJS, not homebridge.

**Comment by KhaosT** [comment]
I don't understand why you're trying to init a camera object with parameters. That class does not take in parameters at all. The example Camera class is designed to work with Mac's iSight camera not for arbitrary RTSP streams. If you want to use a RTSP stream, try create your own camera source and change that.

**Comment by Maxmudjon** [comment]
![photo1204279221268145](https://cloud.githubusercontent.com/assets/23142922/20863116/c0480bb2-b9e2-11e6-806c-4e871d0481f0.jpg)
You do not know what the problem is

**Comment by KhaosT** [comment]
@Maxmudjon I have no idea. It could be ffmpeg or the steam or iOS itself.

**Comment by Maxmudjon** [comment]
@legotheboss  Your plugin also does not work with h264_omx

**Comment by rodorgas** [comment]
Sorry, I thought there was support to RTSP streams. I managed to get it working using [Homebridge](https://github.com/nfarina/homebridge) and [homebridge-foscam-ng](https://github.com/planetbeing/homebridge-foscam-ng)
Thanks for the help!

**Comment by Maxmudjon** [comment]
@rodorgas you have not checked out the video goes on smoothly homebridge-foscam-ng

**Comment by rodorgas** [comment]
I've checked and the video goes on smoothly.

**Comment by Maxmudjon** [comment]
a camera and a system ?

**Comment by rodorgas** [comment]
Sorry what do you mean? If another accessory connected works well with a camera? I tested the camera alone in homebridge, but I have other accessories in HAP-NodeJS and it's fine.

**Comment by Maxmudjon** [comment]
I mean you have a system Raspberri PI 3 Jasse

**Comment by rodorgas** [comment]
Yeah it's fine also on the Raspberry

**Comment by Maxmudjon** [comment]
I'm checking
