### ISSUE TITLE
Automation not working

### ISSUE THREAD

**Issue by Shifter147** [KhaosT/HAP-NodeJS#357]
Hello all! 

First I would like to thanks KhaosT for the awesome work!! I recently discovered this and like it a lot. 
My programming skills are bad, but im learning fast. 

I got the HAP-NodeJS running and added some accessories and they work fine! 
I have my iPad setup for remote access and automation.

My problem: when I make an automation (for example: switch on all lights every day @ 19:15) this simply doesn't work.. The time passes and nothing happens.

Can someone please tell me if they encounter this problem and most important, how to fix it. 
I have searched this issues and googled a lot, but i can't find someone with the similar problem.

**Comment by KhaosT** [comment]
Can you try to create a automation based on accessory state and see if changing state triggers the automation?

**Comment by Shifter147** [comment]
Thanks for your quick reply. 

I created an automation based on the following: 
if outlet test is switch ON -> all lights go on. 

(it took about 20 sec) but this works. 

The automation based on time still doesn't work.

**Comment by KhaosT** [comment]
Interesting, have you tried delete existing time based automation and create a new one?

Best Wishes,
Tian Zhang

**Comment by Shifter147** [comment]
I removed the time based automation and added a new one. The newly added now works based on time. 

Weird...

**Comment by KhaosT** [comment]
^^ good to know
