### ISSUE TITLE
Problems with code, only one accessory being showed.

### ISSUE THREAD

**Issue by OczkoSX** [KhaosT/HAP-NodeJS#358]
Hi. I have some problems with this code: http://pastebin.com/GsjdSSY4
Home app shows only 'light99'. What's wrong? Console logs look fine:
Parsing accessory: esp8266_1_accessory.js
ESP8266_1: successfully loaded 'light0'
ESP8266_1: successfully loaded 'light1'
ESP8266_1: successfully loaded 'light2'
...
ESP8266_1: successfully loaded 'light97'
ESP8266_1: successfully loaded 'light98'
ESP8266_1: successfully loaded 'light99'

Thanks in advance!

**Comment by KhaosT** [comment]
Where did you publish the accessory?

**Comment by OczkoSX** [comment]
What do you mean by that? It's inside esp8266_1_accessory.js file, I use BridgedCore

**Comment by KhaosT** [comment]
Can you post the entire ``BridgedCore.js`` then?

**Comment by OczkoSX** [comment]
I didn't change anything there. Here's whole esp8266_1_accessory.js file: http://pastebin.com/810SgPV1

**Comment by OczkoSX** [comment]
So how can I fix the code?

**Comment by KhaosT** [comment]
instead of using BridgedCore.js and accessory to ``accessories/``, make a copy of BridgedCore.js and edit it directly. For how to do this, please read the documentations.

**Comment by OczkoSX** [comment]
Okay. I've tried maaaany things and it's still not working. That's my recent code: http://pastebin.com/mqdM6wWJ

I called it `esp8266_1_accfactory.js`. 

I save every `Accessory` object into an array, and then export it (I'm beginner in NodeJS and I have never used modules before, so sorry for mistakes). There are no errors in console, everything should be working fine, but bridge is not visible in Home app. What's wrong? Sorry for bothering you

**Comment by OczkoSX** [comment]
And just to add - I've done no changes to project files.

**Comment by KhaosT** [comment]
You need to modify BridgeCore instead of your accessory file. There is nothing you can do by changing accessory file to achieve the things you want to do. [Here](https://dl.dropbox.com/s/qed6rqqlbhfxwaw/oczkocore.js) is what you should do to the BridgeCore.js

**Comment by OczkoSX** [comment]
Ah, it will make code much less readable what I am trying to avoid. Can't this: https://github.com/KhaosT/HAP-NodeJS/blob/master/lib/AccessoryLoader.js#L36
solve the problem? When should we use it?

**Comment by KhaosT** [comment]
I didn't know we still have that 😛 It exists for some legacy stuff. I'm afraid that I will not be able to offer any support on using that one.

**Comment by OczkoSX** [comment]
Ohh, I see. Could you take a look on it? Won't it make the stuff? From what I see, it should do what I want (it joins array of objects from *_accfactory.js file to accessories array - it does the same what https://github.com/KhaosT/HAP-NodeJS/blob/master/lib/AccessoryLoader.js#L29 does, but for multiple objects). There are no errors, but bridge is not visible in application. How can I check, whether it loads the accessories successfully?

**Comment by OczkoSX** [comment]
Is bridge not visible when there are no accessories?

**Comment by KhaosT** [comment]
@OczkoSX bridge itself should always visible.

**Comment by OczkoSX** [comment]
It seems working. Above code was fine, I had to change bridge username (phone won't detect it?) and It started working! Thanks for your help, cya
