### ISSUE TITLE
Difference between switches

### ISSUE THREAD

**Issue by OczkoSX** [KhaosT/HAP-NodeJS#359]
Hi. What's the difference between following switches?

Stateful Programmable Switch
Stateless Programmable Switch
Switch

Thanks in advance

**Comment by KhaosT** [comment]
[Stateful Programmable Switch](https://images-na.ssl-images-amazon.com/images/I/51Vkz2rwsmL._AC_UL320_SR294,320_.jpg)
[Stateless Programmable Switch](http://www2.meethue.com/en-us/productdetail/philips-hue-tap-switch)
[Switch](http://www.electrical-online.com/wp-content/uploads/2010/09/light-switch.jpg)

Basically something like above.

**Comment by OczkoSX** [comment]
Stateless is just a button? What's the difference between Switch and Stateful Programmable Switch? I don't get it from pics.

**Comment by KhaosT** [comment]
The main difference between ``Stateful Programmable Switch`` and ``Switch`` is whether or not it physically controls something. ``Stateless Programmable Switch`` is like a remote you can press button to send event, but the button itself doesn't preserve state

**Comment by OczkoSX** [comment]
Which one of these physically controls sth? Can Stateless one be held to make an action for longer period of time?

**Comment by KhaosT** [comment]
Which one of these physically controls sth? -> Switch
I mean you can implement that with 3 states (not pressed, pressed, long pressed) and then have different trigger for it.

**Comment by OczkoSX** [comment]
Okay. I think I've got it. Thanks!

ps. Could you take a look on my other issue?
