### ISSUE TITLE
How do Programmable Switch Events work?

### ISSUE THREAD

**Issue by dunklesToast** [KhaosT/HAP-NodeJS#360]
Hey,

I just want to create a Doorbell Accessory but I cant get the Programmable Switch Event become working.
I know that this has to be 0 or 1 (for pressed and normal?) but I dont know how to add this to the Service.

For testing I am trying it like
`    .setCharacteristic(Characteristic.ProgrammableSwitchEvent, 1);`

But I am getting

```
/home/pi/HAP-NodeJS/lib/Service.js:147
  this.getCharacteristic(name).setValue(value);
                              ^
TypeError: Cannot read property 'setValue' of undefined
```
Anyone know how to make the doorbell working?

-dunklesToast

**Comment by snowdd1** [comment]
Your error message just means that the method invoked returned undefined. So `name` seems not to be a valid value for `getCharacteristic`. 
Has nothing to do with doorbell service.
