### ISSUE TITLE
iPhone keeps requesting PIN while accessory's disappear.

### ISSUE THREAD

**Issue by 128keaton** [KhaosT/HAP-NodeJS#37]
Hi, I have HAP-NodeJS running on a Raspberry Pi, nothing more, nothing less, stock accessories. Anyway, I go to pair them with my iPhone (6, 8.1) and it just keeps asking for the PIN for the accessory and doesn't ever connect.
Here is a video with the issue highlighted:
https://www.youtube.com/watch?v=C-OwA6WUmnQ&feature=youtube_gdata_player
And logs from the RasPi:
![screen shot 2015-02-11 at 10 49 50 pm](https://cloud.githubusercontent.com/assets/1402918/6162017/977aace0-b240-11e4-93bd-1054324e136a.png)

**Comment by KhaosT** [comment]
You entered the wrong PIN for accessories. The default PIN is 031-45-154.
