### ISSUE TITLE
Doorbell listed but not supported yet?

### ISSUE THREAD

**Issue by brownad** [KhaosT/HAP-NodeJS#376]
Hi

HAP API lists doorbell as a component however in HomeKit it's listed as not supported. Is that correct?

**Comment by KhaosT** [comment]
Home app does not support doorbell. HomeKit does.

**Comment by mrose17** [comment]
@brownad - see https://github.com/homespun/homebridge-platform-ring-video-doorbell/issues/3#issuecomment-271400713

**Comment by brownad** [comment]
👍
