### ISSUE TITLE
Compile errors during npm rebuild

### ISSUE THREAD

**Issue by AndyQ** [KhaosT/HAP-NodeJS#38]
I've followed the instructions on the Wiki to build this on my Raspberry Pi, however when running npm rebuild. I get the below compile errors.

Probably something really obvious I've not done but I have no idea now.

Any ideas?

-----------------
> curve25519@1.0.0 install /home/pi/homekit/HAP-NodeJS/node_modules/curve25519
> node-gyp rebuild

child_process: customFds option is deprecated, use stdio instead.
make: Entering directory '/home/pi/homekit/HAP-NodeJS/node_modules/curve25519/build'
  CXX(target) Release/obj.target/curve/node_curve.o
../node_curve.cc:13:37: error: ‘Arguments’ does not name a type
../node_curve.cc:13:46: error: ISO C++ forbids declaration of ‘parameter’ with no type [-fpermissive]
../node_curve.cc:16:37: error: ‘Arguments’ does not name a type
../node_curve.cc:16:48: error: ISO C++ forbids declaration of ‘args’ with no type [-fpermissive]
/home/pi/.node-gyp/0.12.0/deps/v8/include/v8.h: In function ‘v8::Handle<v8::Value> DoCurve(const int&)’:
/home/pi/.node-gyp/0.12.0/deps/v8/include/v8.h:816:13: error: ‘v8::HandleScope::HandleScope()’ is protected
../node_curve.cc:17:15: error: within this context
../node_curve.cc:19:12: error: request for member ‘Length’ in ‘args’, which is of non-class type ‘const int’
../node_curve.cc:20:44: error: ‘New’ is not a member of ‘v8::String’
../node_curve.cc:20:63: error: ‘ThrowException’ was not declared in this scope
../node_curve.cc:22:61: error: invalid types ‘const int[int]’ for array subscript
../node_curve.cc:23:61: error: invalid types ‘const int[int]’ for array subscript
../node_curve.cc:24:61: error: invalid types ‘const int[int]’ for array subscript
../node_curve.cc:26:20: error: too few arguments to function ‘v8::Handle<v8::Primitive> v8::Undefined(v8::Isolate*)’
/home/pi/.node-gyp/0.12.0/deps/v8/include/v8.h:305:28: note: declared here
/home/pi/.node-gyp/0.12.0/deps/v8/include/v8.h: In function ‘void init(v8::Handle<v8::Object>)’:
/home/pi/.node-gyp/0.12.0/deps/v8/include/v8.h:816:13: error: ‘v8::HandleScope::HandleScope()’ is protected
../node_curve.cc:30:15: error: within this context
../node_curve.cc:31:43: error: no matching function for call to ‘NODE_SET_METHOD(v8::Handle<v8::Object>&, const char [6], v8::Handle<v8::Value> (&)(const int&))’
../node_curve.cc:31:43: note: candidate is:
/home/pi/.node-gyp/0.12.0/src/node.h:228:13: note: template<class TypeName> void node::NODE_SET_METHOD(const TypeName&, const char*, v8::FunctionCallback)
curve.target.mk:81: recipe for target 'Release/obj.target/curve/node_curve.o' failed
make: *** [Release/obj.target/curve/node_curve.o] Error 1
make: Leaving directory '/home/pi/homekit/HAP-NodeJS/node_modules/curve25519/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2

**Comment by KhaosT** [comment]
@AndyQ Can you try node 0.10.35/36 instead of node 0.12? There are several API changes in 0.12 which I believe breaks the compiling.

**Comment by AndyQ** [comment]
That did the trick - Thanks!  All up and running nicely!
