### ISSUE TITLE
why logos when adding accessories not shown

### ISSUE THREAD

**Issue by Maxmudjon** [KhaosT/HAP-NodeJS#380]
![img_0023](https://cloud.githubusercontent.com/assets/23142922/21795180/26206aae-d722-11e6-9de5-226120f897c3.PNG)

**Comment by KhaosT** [comment]
I'm not sure I understand. Do you mean why those accessories in the scanner don't have a type icon? If that's what you mean, you need to provide a type when publishing the accessory. See [here](https://github.com/KhaosT/HAP-NodeJS/blob/master/lib/Accessory.js#L420).

**Comment by Maxmudjon** [comment]
in Homekit Simulator icon shows. And on HAP-NodejS icon does not show

**Comment by Maxmudjon** [comment]
what you can do help

**Comment by Maxmudjon** [comment]
![photo1204279221268234](https://cloud.githubusercontent.com/assets/23142922/21962059/e9f426f0-db3c-11e6-8761-f54645610036.jpg)

**Comment by Maxmudjon** [comment]
installed latest HAP-NodeJS
version - 0.4.21

**Comment by KhaosT** [comment]
I thought I'm already really clear. Accessory publisher needs to provide the category in order for Home app to show a type icon.

**Comment by Maxmudjon** [comment]
I must point?

**Comment by Maxmudjon** [comment]
and how it makes no in-HAP NodejS?

**Comment by Maxmudjon** [comment]
fan.Category = "FAN";
fan.category = "FAN";
fan.type = "Accessory.Categories.OTHER";
fan.Categories = "FAN"

as I have to write ?

**Comment by Maxmudjon** [comment]
[why](https://github.com/KhaosT/HAP-NodeJS/blob/master/lib/Accessory.js#L437)

**Comment by KhaosT** [comment]
I'm sorry but I can't understand your reply. By default I don't want to assume the category of the accessory it's being exposed, so I picked the "Other" category as the default value. If you have other options, you can choose and override the value in accessory.publish.

**Comment by Maxmudjon** [comment]
how to export category type in the accessory file ?

**Comment by KhaosT** [comment]
That's currently not supported. You can probably add [a property](https://github.com/KhaosT/HAP-NodeJS/blob/master/accessories/Fan_accessory.js#L35) on the accessory object call it ``category`` and then modify the [``Core.js``](https://github.com/KhaosT/HAP-NodeJS/blob/master/Core.js#L35) to publish with the category from accessory object.

**Comment by Maxmudjon** [comment]
please write file to me

**Comment by Maxmudjon** [comment]
how to write please help

**Comment by Maxmudjon** [comment]
i found.
![photo1204279221268235](https://cloud.githubusercontent.com/assets/23142922/21975077/67a4ee40-dbec-11e6-88b5-185b1686d4fb.jpg)

**Comment by Maxmudjon** [comment]
in file Core.js - add 

port: targetPort++,
    username: accessory.username,
    pincode: accessory.pincode,
    category: accessory.category //This This This <<<<<<<<<<<<<<<<

in file XXXXXXXX_accessory.js (expamle fan_accessory.js)

    fan.category = Accessory.Categories.FAN; 

if you accessory is SWITCH

 switch.category = Accessory.Category.SWITCH: 

and other too ...

**Comment by Hekami** [comment]
sir,
I am new in this Field.I am trying to add fan_accessory.js .but it is not running.please help me.

**Comment by n0rt0nthec4t** [comment]
Just stumbled across this and seems to make sense. Would it be possible to change Core.js code from  (lines 34-40)
  **accessory.publish({
    port: targetPort++,
    // @ts-ignore
    username: accessory.username,
    // @ts-ignore
    pincode: accessory.pincode
  });**

to:
  accessory.publish({
    port: targetPort++,
    // @ts-ignore
    username: accessory.username,
    // @ts-ignore
    pincode: accessory.pincode,
    **// @ts-ignore
    category: accessory.category**
  });

That way, we can define the category in our accessory file as to what type it might be and we dont set the category, it'll default to OTHER as it does now
