### ISSUE TITLE
code with mqtt not working properly

### ISSUE THREAD

**Issue by jat80** [KhaosT/HAP-NodeJS#381]
Hi there,

I’ve setup a homekit fan accessory using a raspberry pi, HAP-NodeJS, MQTT and a sonoff.

It works fine but the one problem i’ve got with it is the status on the home app not showing correctly. When I turn the fan accessory ON the status in the home app my iOS device is correct and shows it’s ON.

BUT if I leave it on for a while then go back into the home app is shows it’s OFF even though the accessory is still ON???

I switch it ON then OFF again and it turns OFF.

I used this code here for the .js file.

https://github.com/jat80/ESP8266/blob/master/Home%20Automation/Part%208/relayLight_accessory.js

But modified a few lines to make it look like a fan accessory.
I don’t really have any experience with javascript (or coding in general for that matter) so don’t know if there is something else in the code that could be the problem with the status not showing correctly.

Any help would be appreciated.

Thanks!

**Comment by jat80** [comment]
Any help would really be appreciated.  Thanks.

**Comment by KhaosT** [comment]
The ``currentState `` at [here](https://github.com/jat80/ESP8266/blob/master/Home%20Automation/Part%208/relayLight_accessory.js#L83) is not the same one referred at [here](https://github.com/jat80/ESP8266/blob/master/Home%20Automation/Part%208/relayLight_accessory.js#L68). This will result every time when the update timer fired, it send a 0 to HomeKit causing it to show off.

**Comment by Maxmudjon** [comment]
why Service is Fan ??

**Comment by jat80** [comment]
Thanks so much KhaosT.  I'll change lightAction.currentState to this.currentState.  I'm new to all this and never coded before but since you have highlighted the fact and explained it, it makes perfect sense to me now.

**Comment by jat80** [comment]
Mazmudjon - I changed the service to fan so it would come up as a fan accessory in the  home app.  The original code was from a simple relay light which I wanted to use to turn a fan on and off.

**Comment by jat80** [comment]
ok, I changed the above and now getting this:

Parsing accessory: fan_accessory.js
updated status to: true
/home/pi/HAP-NodeJS/accessories/fan_accessory.js:65
      console.log("Setting new outlet state: " + newState.toString());
                                                         ^

TypeError: Cannot read property 'toString' of undefined
    at Object.lightAction.setState (/home/pi/HAP-NodeJS/accessories/fan_accessory.js:65:58)
    at null.<anonymous> (/home/pi/HAP-NodeJS/accessories/fan_accessory.js:49:17)
    at emitMany (events.js:108:13)
    at emit (events.js:182:7)
    at Characteristic.setValue (/home/pi/HAP-NodeJS/lib/Characteristic.js:155:10)
    at Service.setCharacteristic (/home/pi/HAP-NodeJS/lib/Service.js:147:32)
    at null._repeat (/home/pi/HAP-NodeJS/accessories/fan_accessory.js:83:6)
    at wrapper [as _onTimeout] (timers.js:264:19)
    at Timer.listOnTimeout (timers.js:92:15)

**Comment by jat80** [comment]
I'm wondering if I just scrap this code and use the default fan code and add mqtt to it. But unsure how to even do that??

**Comment by jat80** [comment]
If someone could show me that would be awesome.  
I'm wondering if my arduino code I flashed to the sonoff could be part of the issue as well?  I wouldn't think so but put it out there.  I used this code to flash the sonoff with:

https://github.com/SuperHouse/BasicOTARelay/blob/master/BasicOTARelay.ino

**Comment by KhaosT** [comment]
@jat80 try this? https://gist.github.com/KhaosT/f312675e7a67662f40b8f68dda54c5a9

**Comment by jat80** [comment]
Thanks @KhaosT

Trying it out now.  Will leave the fan on for a while and see if the iOS status stays on.

**Comment by jat80** [comment]
@KhaosT.  It didn't work. It's changed back to off even though it's still on. 

I'm pretty sure this only leaves the code on the sonoff/esp8266 as the problem.

**Comment by KhaosT** [comment]
are you controlling the fan only though the iOS device or are you also controlling it using an OOB mechanism? like physical switch?

**Comment by jat80** [comment]
@KhaosT I'm using a sonoff (esp8266) via mqtt to control it. There is no physical switch.  The code is just to turn the relay on the sonoff on and off. 

The code I used on the sonoff is mentioned above.  I think that is the problem not the accessory code itself maybe.

**Comment by jat80** [comment]
@KhaosT - This is the code thats on the sonoff.

https://github.com/SuperHouse/BasicOTARelay/blob/master/BasicOTARelay.ino

**Comment by jat80** [comment]
@KhaosT ok I have now tried different .ino codes to flash the sonoff with and all end up with the same thing.  It works for a while (10-20mins) but then the status shows as off even the accessory is still on.  No external buttons to control it.

I'm completely stumped now.  

Is there  anyway to debug this and actually see what's happening on the server side so we can see why the accessory it showing the wrong status?

A bit more info about my setup incase that may help:

I'm running HAP-NodeJS on a raspberry pi 3 - I installed it using @legotheboss youtube tutorial.
I don't know what version HAP-NodeJS is currently running but i've done an apt-get update and upgrade today and that didn't help anything.

**Comment by Maxmudjon** [comment]
Accessory fan works through the MQTT ?

**Comment by danielsen2009** [comment]
I have a working example for a fan accessory, it uses homebridge, homebridge-mqtt and mosquitto for the broker. https://github.com/danielsen2009/homebridge-mqtt-acessories/blob/Master/Fan/Fan.ino

**Comment by jat80** [comment]
@danielsen2009 i'm not using homebridge but thanks all the same.

**Comment by jat80** [comment]
Ok thanks to @legotheboss we have found the issue with this problem.   Along with the above sonoff/esp8266 accessories I had two other accessories which were sensors (motion sensor and temperature sensor) which used wiringpi with the setup.  As you can see from this issue below:

https://github.com/WiringPi/WiringPi-Python/issues/21

This was causing issues with the incorrect state for the sonoff/esp8266 accessories.  Deleting those accessories on the pi and unplugging them from the gpio's fixed the issue.

Have to shout to @ItKindaWorks and @KhaosT as well for their help too even though the issue was not a problem with any of their code.  Appreciate everyones time.

JT.
