### ISSUE TITLE
Multiple Lights - Raspberry and GPIO

### ISSUE THREAD

**Issue by akiyamaerik** [KhaosT/HAP-NodeJS#386]
Hello @KhaosT and everyone!

First of all, congrats on the job for making HAP-NodeJS. It's marvelous! Your contribution to Home Automation is certainly accounted for every person that searched for "homekit and raspberry" on Google.

So, I've been sniffing around for a few weeks, and I'm new to JavaScript programming. I'm having some issues, so I can't quite make the setup work at home.

Here's the scenario:

I have one relay board with two relays plugged in the Raspberry's GPIO.  I cannot duplicate the light. One light works fine but I've tried cloning the accessory and changing the username and pincode, but it doesn't work.

So, I used @legotheboss implementation of python codes to access the GPIO. As you can see in the code below, the state "on" points to a python code, and "off" state points to another
Running the scripts manually, Both of them work, but on the "Home" app on my iPhone, I can't detect the second light.

I am using the following code:

[Light_accessoryImproved.js](https://github.com/akiyamaerik/HAP-NodeJS/blob/master/Light_accessoryImproved.js)

Am I doing something foolish? Can you please help me?

My intention is to make possible turn on 4 Lights via the HomeKit..

Thanks in advance!!

Erik

**Comment by akiyamaerik** [comment]
Anyone? Help?

**Comment by snowdd1** [comment]
If you're new to JavaScript I would recommend using Homebridge (https://github.com/nfarina/homebridge) which is a framework for plugins based on hap-nodejs.   
The authors of both collaborate on both projekts.  
There are several plugins for GPIO switching available, plus hundreds for other hardware and software.

But to your question: Did you actually **add the accessory** to Homekit? Or are you using *bridgedcore.js* ?

**Comment by akiyamaerik** [comment]
Hello @snowdd1 , I am currently using the Core.js file.

As a matter of fact, I think the Homebridge recognized somewhat the accessory. But failed to trigger it. 

Following a solution provided by @KhaosT in one of the issues, I have changed the pin code and username, but I have no idea if I need to do something else to make it work.

**Comment by jat80** [comment]
@akiyamaerik - I think you may have the accessory files named incorrectly.  

They should be: 
Light1_accessory.js
Light2_accessory.js

you can basically name it anything you want but it must end with _accessory.js

I followed @legotheboss youtube relay light tutorial as well and created my own python scripts to work with each light to turn them on and off using a raspberry pi zero and they work fine.

Let me know how you get on.

**Comment by akiyamaerik** [comment]
Oh, I see @jat80.

Ok, I will try to do this as soon as I get back home.

Thanks for the advice!!

**Comment by jat80** [comment]
@akiyamaerik no problem.  If you need any further assistance let me know.  I'll try and help as best I can.  :)
