### ISSUE TITLE
Service.Speaker saying 'Not Supported' in the Home app

### ISSUE THREAD

**Issue by tijlvanvliet** [KhaosT/HAP-NodeJS#389]
I am trying a build an accessory with the service type Speaker. But when I add in in the 'Home' app it stays 'successfully added', but when I go to the accessory it says 'Not supported'.

Did i miss a Characteristic

This is my code:

`speaker
  .addService(Service.Speaker, "Speaker1") // services exposed to the user should have "names" like "Fake Light" for us
  .getCharacteristic(Characteristic.Mute)
  .on('set', function(value, callback) {
    SPEAKER.setVolume(value);
    callback(); // Our fake Outlet is synchronous - this value has been successfully set
  })
  .on('get', function(callback) {
    var err = null; // in case there were any problems
    callback(err, false);
  });

speaker
      .getService(Service.Speaker) // services exposed to the user should have "names" like "Fake Light" for us
      .addCharacteristic(Characteristic.On)
      .on('set', function(value, callback) {
        SPEAKER.setVolume(10);
        callback(); // Our fake Outlet is synchronous - this value has been successfully set
      })
      .on('get', function(callback) {
        var err = null; // in case there were any problems
        callback(err, true);
      });

speaker
    .getService(Service.Speaker) // services exposed to the user should have "names" like "Fake Light" for us
    .addCharacteristic(Characteristic.Volume)
    .on('set', function(value, callback) {
      SPEAKER.setVolume(value);
      callback(); // Our fake Outlet is synchronous - this value has been successfully set
    })
    .on('get', function(callback) {
      var err = null; // in case there were any problems
      callback(err, SPEAKER.volume);
    });`

**Comment by Maxmudjon** [comment]
speaker service don't supported in homekit !

**Comment by KhaosT** [comment]
Home app itself doesn't currently support the new Speaker service as of iOS 10.2.
