### ISSUE TITLE
npm rebuild fails 

### ISSUE THREAD

**Issue by jojiabraham** [KhaosT/HAP-NodeJS#39]
npm rebuild fails with curve 

> curve25519@1.0.0 install /home/pi/HAP-NodeJS/node_modules/curve25519
> node-gyp rebuild

child_process: customFds option is deprecated, use stdio instead.
make: Entering directory '/home/pi/HAP-NodeJS/node_modules/curve25519/build'
  CXX(target) Release/obj.target/curve/node_curve.o
../node_curve.cc:13:37: error: ‘Arguments’ does not name a type
../node_curve.cc:13:46: error: ISO C++ forbids declaration of ‘parameter’ with no type [-fpermissive]
../node_curve.cc:16:37: error: ‘Arguments’ does not name a type
../node_curve.cc:16:48: error: ISO C++ forbids declaration of ‘args’ with no type [-fpermissive]
/home/pi/.node-gyp/0.12.0/deps/v8/include/v8.h: In function ‘v8::Handle<v8::Value> DoCurve(const int&)’:
/home/pi/.node-gyp/0.12.0/deps/v8/include/v8.h:816:13: error: ‘v8::HandleScope::HandleScope()’ is protected
../node_curve.cc:17:15: error: within this context
../node_curve.cc:19:12: error: request for member ‘Length’ in ‘args’, which is of non-class type ‘const int’
../node_curve.cc:20:44: error: ‘New’ is not a member of ‘v8::String’
../node_curve.cc:20:63: error: ‘ThrowException’ was not declared in this scope
../node_curve.cc:22:61: error: invalid types ‘const int[int]’ for array subscript
../node_curve.cc:23:61: error: invalid types ‘const int[int]’ for array subscript
../node_curve.cc:24:61: error: invalid types ‘const int[int]’ for array subscript
../node_curve.cc:26:20: error: too few arguments to function ‘v8::Handle<v8::Primitive> v8::Undefined(v8::Isolate*)’
/home/pi/.node-gyp/0.12.0/deps/v8/include/v8.h:305:28: note: declared here
/home/pi/.node-gyp/0.12.0/deps/v8/include/v8.h: In function ‘void init(v8::Handle<v8::Object>)’:
/home/pi/.node-gyp/0.12.0/deps/v8/include/v8.h:816:13: error: ‘v8::HandleScope::HandleScope()’ is protected
../node_curve.cc:30:15: error: within this context
../node_curve.cc:31:43: error: no matching function for call to ‘NODE_SET_METHOD(v8::Handle<v8::Object>&, const char [6], v8::Handle<v8::Value> (&)(const int&))’
../node_curve.cc:31:43: note: candidate is:
/home/pi/.node-gyp/0.12.0/src/node.h:228:13: note: template<class TypeName> void node::NODE_SET_METHOD(const TypeName&, const char*, v8::FunctionCallback)
curve.target.mk:81: recipe for target 'Release/obj.target/curve/node_curve.o' failed
make: *** [Release/obj.target/curve/node_curve.o] Error 1
make: Leaving directory '/home/pi/HAP-NodeJS/node_modules/curve25519/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1067:12)
gyp ERR! System Linux 3.18.7+
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/pi/HAP-NodeJS/node_modules/curve25519
gyp ERR! node -v v0.12.0
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok 

npm ERR! Linux 3.18.7+
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "rebuild"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE
npm ERR! curve25519@1.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the curve25519@1.0.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the curve25519 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls curve25519
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/pi/HAP-NodeJS/npm-debug.log

**Comment by KhaosT** [comment]
Please use NodeJS 0.10.35/36 instead of 0.12.x There are several API changes in 0.12 which I breaks the build.
