### ISSUE TITLE
How to see log ?

### ISSUE THREAD

**Issue by Maxmudjon** [KhaosT/HAP-NodeJS#392]
I can see the log for 1 day ?

**Comment by Maxmudjon** [comment]
HAP-NodeJS itself stops
I want to see this log

**Comment by legotheboss** [comment]
Are you running node with forever?

**Comment by snowdd1** [comment]
@Maxmudjon    
Some more information please!  
- What system your on  
- How did you start HAP-NodeJS? (Exact command line or script)  

Otherwise no one will be able to help you!

**Comment by Maxmudjon** [comment]
no problems
