### ISSUE TITLE
what is needed to test this out

### ISSUE THREAD

**Issue by snizzleorg** [KhaosT/HAP-NodeJS#40]
do I get this right that I can just run this on any computer and then issue commands to it through siri?

**Comment by nathreed** [comment]
You need to have the HomeKitDemo app installed on your phone. This requires an apple developer account ($99/yr) and a Mac. Then you need to add your own code to control whatever accessories you want to control. Then you can use Siri to control the stuff.

**Comment by firstchair** [comment]
He is going to launch the app in the appstore right?

**Comment by nathreed** [comment]
No, I don't believe there are plans for that. In its current state it's far from App Store-ready (although functionally complete) and I don't think apple will allow a generic HomeKit browser into the App Store. Apparently there are methods of running the app with a jailbroken iPhone and no dev account, but I'm not familiar with those.

**Comment by micpura** [comment]
I believe if you go in Xcode and turn off code signing... You can still install on your own phone without paying

**Comment by nathreed** [comment]
I don't think iOS allows non code-signed apps to run.

**Comment by KhaosT** [comment]
Yeah, a HomeKit app is required to setup the accessory and after that you can initiate command from Siri. When HomeKit officially launched, you'll be able to find different HomeKit app on the App Store which you can download for free. However, as of today I'm not sure when will manufacturers release their HomeKit apps on App Store.

Thanks for your interests, Hope this answers your question :)

**Comment by fritz-fritz** [comment]
@snizzleorg @micpura
The [methods I have tried](http://www.sysrage.net/guides/ios-programming/building-and-running-ios-applications-without-a-paid-developer-license) to use the HomeKitDemo or Apple's [HomeKit Catalog](https://developer.apple.com/library/ios/samplecode/HomeKitCatalog/Introduction/Intro.html) allow me to build and sign it but without the HomeKit Entitlements (from having a Developer Account) the app crashes on launch. At least thats what I think not sure if thats the problem.

However, I am not experienced with building apps for iPhone so perhaps I am doing something wrong. As I am using a jailbroken phone, theoretically this should work... maybe if someone built the app and provided a download link more people could try this project.
