### ISSUE TITLE
Amazon Echo support?

### ISSUE THREAD

**Issue by jat80** [KhaosT/HAP-NodeJS#403]
Can this work with an amazon echo at all?

**Comment by MystK** [comment]
What are you expecting to be able to do with Amazon Echo?

**Comment by NorthernMan54** [comment]
FYI - I have created a separate version of homebridge and hap-nodejs which includes support for Amazon echo control of lights, switches and outlets.

ie Alexa, turn on the front porch lights

If your interested, take a look at this https://github.com/NorthernMan54/homebridge-alexa
