### ISSUE TITLE
Below-Zero for Setpoint / Temperature Breaks Thermostat

### ISSUE THREAD

**Issue by drewcovi** [KhaosT/HAP-NodeJS#406]
I'll see if I can dig up some examples in a bit, but on iOS 10.3 I'm seeing that returning any values below 0 for either setpoint, or current temperature causes the device to show as "Not Responding"

**Comment by snowdd1** [comment]
So you assume that the mechanism for setting valid minimum and maximum values has changed with 10.3?

**Comment by drewcovi** [comment]
@snowdd1 perhaps yes, although im admittedly fairly green at this level, just sorting out how to resolve this in homebridge, so it might be there too...

**Comment by snowdd1** [comment]
If you haven't set the minimum value to below zero, then it is default behavior. Apple (in California) never assumed temperatures to drop below 0 degrees Celsius.

**Comment by snowdd1** [comment]
And if the minimum is still set to 0 Celsius, the temperature must not report below that, otherwise HomeKit bans the accessory as non compliant.

**Comment by drewcovi** [comment]
Yep! turns out I just have to set the minimum as others have: https://github.com/KhaosT/HAP-NodeJS/issues/147

All good here. thanks!
