### ISSUE TITLE
Are all services listed in HomeKitTypes.js supported?

### ISSUE THREAD

**Issue by gvuyk** [KhaosT/HAP-NodeJS#407]
Tried to add an Humidifier accessory with `service.HumidifierDehumidifier` but Home app says "This accessory is not currently supported by the Home app".
This is on iOS 10.2.1

**Comment by KhaosT** [comment]
Home app doesn't support ALL service profiles defined by Apple. (I know this sounds ridiculous but this is the sad situation we are at now ¯\_(ツ)_/¯)
