### ISSUE TITLE
BridgingState Service

### ISSUE THREAD

**Issue by ebaauw** [KhaosT/HAP-NodeJS#408]
I recently noticed that each accessory I expose through my homebridge platform plugins contains a `BridgingState` service, in addition to the `AccessoryInformation` service and service(s) I created myself.  It's kind of hidden: neither the iOS built-in Home app nor Eve show this service, but Matthias' Home app does (when viewing the accessory under Home), as does HMCatalog.  This service seems to be added by HAP-NodeJS in `addBridgeAccessory()`.

I have some questions about this:

1. Has this service been added recently?  Or did I just not notice it earlier?
2. Why do I need this service?  The (also bridged) accessories exposed by the Philips Hue bridge don't contain this service.
3. Is there a way to prevent this service from being created, or alternatively, to remove this service?  Reason I'm asking: my HomeKit configuration has become too large for iCloud syncing and I'm looking for ways to save space (obviously without losing functionality).

Thanks,
Erik.

**Comment by KhaosT** [comment]
1. This service was discovered in iOS 9.3 which allows bridge to provide extra information about a bridged accessory to HomeKit. HAP-NodeJS has been adding that service to bridged accessories for a while already.
2. The service allows bridge to report category, reachability of a bridged accessory. My guess is that Apple hasn't officially publish this service to manufacturer so they can't use it.
3. No. Are you sure you are having sync problem because the home data blob is too large? 1MB is a lot for home data...

**Comment by ebaauw** [comment]
Thanks @KhaosT 

3. I wouldn't know how to measure it, so I cannot be sure, but I do have circumstantial evidence: My "production" Home has 113 accesories, 14 rooms, 9 groups, 14 scenes, 8 rules.  I use a "test" Home on the same iCloud account when developing/testing my plugins with a difference instance of homebridge.  When that instance provides more than a dozen accessories, iCloud sync stalls: changes to the HomeKit configuration are only visible on the device where you made them.  When I change the test homekit configuration, reducing the number of accessories, HomeKit sync resumes.  I regularly delete and re-create the test Home, hoping that cleans up any mess I make during testing.

Breakdown of the accesories:
- Philips Hue gen2 bridge bridging 39 lights;
- Homebridge with homebridge-hue plugin, bridging 75 accessories (lights, switches, sensors);
- Homebridge with homebridge-zp pluging, bridging 4 sonos zones;
- 2x Elgato Eve Energy

I could use a different iCloud account for testing, but I only have one AppleTV and one iPad, so I wouldn't be able to test rules.
I pretty much installed smart lights and Hue motion sensors throughout my home, so I don't expect the Hue environment to grow.  However, after winning the lottery ;-), I want to install a smart thermostat, with smart radiotor valves (honeywell or tado or something like that), a couple of door sensors, and maybe a smart lock. Enough to hit the limit, I'm afraid.

**Comment by ebaauw** [comment]
Sorry to bumb this, @KhaosT, but I think we're really running into the CKRecord limit.  The `BridgingState` service isn't mentioned in the HAP spec, nor are any of its characteristics...

**Comment by KhaosT** [comment]
Yeah, I believe this service is removed from iOS 10.2 and HomeKit no longer use any information provided by this service. I think I will make changes to hap-nodejs to no longer automatically add this service to bridged accessories.

**Comment by KhaosT** [comment]
But I may not be able to push changes until this weekend... Internet connection at Yellowstone is terrible 😝

**Comment by ebaauw** [comment]
No problem, and many thanks.  I hope you enjoy Yellowstone despite the lousy internet connection.

**Comment by KhaosT** [comment]
Should be addressed with v0.4.26

**Comment by ebaauw** [comment]
Thanks, Tian!
