### ISSUE TITLE
HAP-NodeJS keeps crashing

### ISSUE THREAD

**Issue by Supersimo88** [KhaosT/HAP-NodeJS#413]
I have a problem, HAPNodeJs start without problems at boot* after a few hours crashes, if I try to relaunch Core.js seems to start with no problems but the accessories already associated with still do not respond, the only way is to restart the raspberry and It seems to fix this for another couple of hours except the return of the problem agin a couple hours later.
I have a raspberry pi B (1) with a more than adequate power supply, also because the same setup worked for months without any problem, then after a node update began to appear similar problems, then I formatted everything and reinstalled from scratch to solve, but at the fifth installation from scratch I am again with HAPNodeJs that crashes.

node v 4.2.1
HAPNodeJs git cloned yesterday

*on crontab "@reboot screen -dm -S HAP-iPool sudo node /home/pi/HAP-NodeJS/Core.js"

**Comment by Supersimo88** [comment]
It seems to have managed to partly solve the problem by installing forever and launch Core.js with sudo start forever /home/pi/HAP-NodeJS/BridgedCore.js in /etc/rc.local
But now I find myself with another issue which I think is related to the above.

If I activated a device, a light for example, the application home shows it as active, but after some time is shown as inactive, so if I want to turn it off before I have to wake up, which of course does not do anything because it already is, and turn it off at this point works, the same problem with a temperature sensor which shows 0 °.

It seems as if HAP-NodeJS crashes the same but with forver remains active, however, resetting the status of my accessories.

I tried to use BridgedCore.js hoping to have different results, but nothing has changed.

**Comment by KhaosT** [comment]
I think you need to post crash log and figure out why it's crashing instead of having it relaunch every time it crashes.

**Comment by Supersimo88** [comment]
Can you please help me? don't know how to get crash log

**Comment by KhaosT** [comment]
You can try to forward the log to a file and post the content of that file to here.

**Comment by Supersimo88** [comment]
something like this?
sudo DEBUG=* node /home/pi/HAP-NodeJS/BridgedCore.js >> hap.log 2>&1

**Comment by KhaosT** [comment]
That should work

**Comment by Supersimo88** [comment]
[hap.log.txt](https://github.com/KhaosT/HAP-NodeJS/files/790142/hap.log.txt)
Here is the debug log, seams to be somthing with wiringpi

**Comment by KhaosT** [comment]
Looks like your modification has some issue. Please see http://raspberrypi.stackexchange.com/questions/41740/wiringpisetup-mmap-pads-failed-cannot-allocate-memory and https://github.com/momenso/node-dht-sensor/issues/6
