### ISSUE TITLE
RGB Led Strip how to connect to GPIO ?

### ISSUE THREAD

**Issue by Maxmudjon** [KhaosT/HAP-NodeJS#415]
i can connect rgb led strip to Raspberry Pi GPIO ?

**Comment by Korcsog** [comment]
Yes. Why not? 
At the moment, i'm using an ESP8266 to control 10 meter RGB LED strip (WS2812B) via HAP-NodeJS.

**Comment by rahulmr999** [comment]
I have a setup using the ESp8266 ,MQTT communication .If you use the WS2812 RGB ,then you can make use of the Neopixel library for the ESP8266. ESP8266 can communicate to the RasPi through the MQTT server which is hosted in the RasPi. I am using that setup and it can remotely change HSL values of the light and select different colours .

**Comment by Supersimo88** [comment]
take a look here [http://supersimo88.altervista.org/homekit-philips-hue-clone-with-standard-non-addressable-rgb-strip-and-esp8266/](url)
