### ISSUE TITLE
missing modules

### ISSUE THREAD

**Issue by RikyTres** [KhaosT/HAP-NodeJS#417]
I can read this in the wiki [Installing page](https://github.com/KhaosT/HAP-NodeJS/wiki/Installing):

> It will probably give you errors about missing modules. Install these using npm install <module name>, replacing <module name> with the name of the module it is missing. After installing the module it wanted, run npm rebuild and try to run the server again with node Core.js. Repeat installing missing modules until the server launches with no errors. HAP-NodeJS is now all set up.

Why these modules are not installed by `npm install`? It should be simple put these dependecies in the `package.json`.

**Comment by snowdd1** [comment]
I think that wiki article isn't that current.

**Comment by RikyTres** [comment]
Here some logs and code to explain better this issue:

When i run `node Core.js `
I got this output:
```
module.js:472
    throw err;
    ^

Error: Cannot find module '../build/Release/dns_sd_bindings'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/opt/HAP-NodeJS/node_modules/mdns/lib/dns_sd.js:32:22)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
```

I realize here that `dns_sd_bindings` is not a package installable through npm.

How can I resolve this issue?

**Comment by snowdd1** [comment]
`cd` into the hap-nodeJS installation directory and issue an `npm install`  
That should reinstall all packages, and also compile all native language dependencies you are missing now.

**Comment by snowdd1** [comment]
You probably made the mistake to install hap-nodeJS globally, that might make installing somewhat more complicated.

**Comment by RikyTres** [comment]
I run `npm install` from the hap-nodeJS installation directory as well the first time, but I delete `node_modules` dir and run again the `npm install`.

This time I got some error. (first time I didn't noticed any errors)
```
> mdns@2.3.3 install /opt/HAP-NodeJS/node_modules/mdns
> node-gyp rebuild

make: Entering directory '/opt/HAP-NodeJS/node_modules/mdns/build'
  CXX(target) Release/obj.target/dns_sd_bindings/src/dns_sd.o
In file included from ../src/dns_sd.cpp:1:0:
../src/mdns.hpp:32:20: fatal error: dns_sd.h: No such file or directory
 #include <dns_sd.h>
                    ^
compilation terminated.
make: *** [dns_sd_bindings.target.mk:149: Release/obj.target/dns_sd_bindings/src/dns_sd.o] Error 1
make: Leaving directory '/opt/HAP-NodeJS/node_modules/mdns/build'
```

I see that on Ubuntu this is solved by `sudo apt-get install libavahi-compat-libdnssd-dev` but what about Arch? witch package I need to install?
(Google can't help me)

**Comment by RikyTres** [comment]
Ok, I search deep inside debian package website and try to search each term that looks important.
So I found `avahi` pacman package (avahi-0.6.32-3). that is "Service Discovery for Linux using mDNS/DNS-SD -- compatible with Bonjour".

Is it what we are looking for?

I run `sudo pacman -Ss avahi` and npm install procedure goes well and no error occurred. 

Anyway... I try to run `node Core.js` and I see this:
```
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
HAP-NodeJS starting...
/opt/HAP-NodeJS/node_modules/mdns/lib/advertisement.js:56
  dns_sd.DNSServiceRegister(self.serviceRef, flags, ifaceIdx, name,
         ^

Error: dns service error: unknown
    at new Advertisement (/opt/HAP-NodeJS/node_modules/mdns/lib/advertisement.js:56:10)
    at Object.create [as createAdvertisement] (/opt/HAP-NodeJS/node_modules/mdns/lib/advertisement.js:64:10)
    at Advertiser.startAdvertising (/opt/HAP-NodeJS/lib/Advertiser.js:43:30)
    at Accessory._onListening (/opt/HAP-NodeJS/lib/Accessory.js:549:20)
    at emitOne (events.js:96:13)
    at HAPServer.emit (events.js:189:7)
    at HAPServer._onListening (/opt/HAP-NodeJS/lib/HAPServer.js:190:8)
    at emitOne (events.js:96:13)
    at EventedHTTPServer.emit (events.js:189:7)
    at EventedHTTPServer.<anonymous> (/opt/HAP-NodeJS/lib/util/eventedhttp.js:65:10)
```

**Comment by RikyTres** [comment]
Problem solved:
`avahi` in not the only pakage required. We need `nss-mdns` too.

After this installation reboot is needed to make all run without errors.

And then we can run avahi daemon with `sudo avahi-daemon`.
Now we can run `node Core.js` and have fun with HAP-nodeJS.
