### ISSUE TITLE
BCM 2835

### ISSUE THREAD

**Issue by Azza1979** [KhaosT/HAP-NodeJS#419]
I have just installed a fresh os on my Rpi3 and its now PIXEL, now when i run node Core.js i get this 

root@raspberrypi:/home/pi/HAP-NodeJS# node Core.js
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
HAP-NodeJS starting...
Unable to determine hardware version. I see: Hardware	: BCM2835
,
 - expecting BCM2708 or BCM2709. Please report this to projects@drogon.net
root@raspberrypi:/home/pi/HAP-NodeJS# 

Any advice Cheers

**Comment by snowdd1** [comment]
You are using any GPIO plugins or such?

**Comment by Azza1979** [comment]
Im trying to use this https://github.com/legotheboss/YouTube-files/tree/master/Garage%20Solution

**Comment by legotheboss** [comment]
exit root and try running node again @Azza1979

**Comment by Azza1979** [comment]
@legotheboss got it thanks.
