### ISSUE TITLE
Failed to start Core.js on Intel Edison

### ISSUE THREAD

**Issue by PeijunZhao** [KhaosT/HAP-NodeJS#42]
Failed to start this app on Intel Edison. See logs below. Any pre-configuration needed on Intel Edison? 
root@edison:~/.node_app_slot# node Core.js
/home/root/.node_app_slot/node_modules/mdns/lib/dns_sd.js:35
    throw ex;
          ^
Error: /home/root/.node_app_slot/node_modules/mdns/build/Release/dns_sd_bindings.node: invalid ELF header
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/root/.node_app_slot/node_modules/mdns/lib/dns_sd.js:24:20)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
root@edison:~/.node_app_slot# 

Thanks.

**Comment by KhaosT** [comment]
@PeijunZhao Please make sure you rebuild the modules before running.

**Comment by PeijunZhao** [comment]
Thanks @KhaosT . Core.js is started after a npm rebuild. But the iPhone can not find any new accessories using the home kit app. What should I do for next step? 
  Intel edison log as follows: 
root@edison:~/.node_app_slot# node ./Core.js 
HAP-NodeJS starting...
Cannot find secret key, creating One...
TCP server accepting connection on port: 51826
HAP Server is listening
Cannot find secret key, creating One...
TCP server accepting connection on port: 51828
HAP Server is listening
Cannot find secret key, creating One...
TCP server accepting connection on port: 51832
HAP Server is listening
Cannot find secret key, creating One...
TCP server accepting connection on port: 51838
HAP Server is listening
Cannot find secret key, creating One...
TCP server accepting connection on port: 51846
HAP Server is listening

**Comment by KhaosT** [comment]
@PeijunZhao are you sure your iPhone and the Edison are in same network?

**Comment by PeijunZhao** [comment]
@KhaosT Yes, iPhone and edison are in the same network. And iPhone can find devices from  apple's HomeKit Accessory Simulator which is running on mac. 

What to debug next?

**Comment by KhaosT** [comment]
@PeijunZhao Can you try to run [this](https://itunes.apple.com/us/app/inet-network-toolbox/id340793353?mt=8) on your phone and see if it can discover your Edison over Bonjour?

**Comment by PeijunZhao** [comment]
Bonjour Services is not detected on Edison. Screenshot is attached. Can you tell me  How to enable the bonjour and  What to do next?
![img_0907](https://cloud.githubusercontent.com/assets/11224758/6410823/619cb66c-bead-11e4-90d5-e07924e56c53.PNG)

**Comment by KhaosT** [comment]
@PeijunZhao I'm not sure about this... Please make sure Avahi is being installed correctly and your are running the latest OS Release on Edison.

**Comment by PeijunZhao** [comment]
@KhaosT Thanks. I will verify Avahi on edison and keep you updated.

**Comment by PeijunZhao** [comment]
@KhaosT After power off / on , Bonjour services are detected and Home kit devices are discovered. 
Screenshots are attached. 
![img_0909](https://cloud.githubusercontent.com/assets/11224758/6411071/aed1d5f0-beaf-11e4-9172-8210faa8c34b.PNG)
![img_0908](https://cloud.githubusercontent.com/assets/11224758/6411072/af5c2d7c-beaf-11e4-9264-a4b922b2e4d7.PNG)


Thanks very much !
