### ISSUE TITLE
Control an accessory

### ISSUE THREAD

**Issue by robgarrett** [KhaosT/HAP-NodeJS#422]
I'm wondering if this has been asked before... Rather than setting up a server for an IOS device to find as a homekit accessory, is it possible to connect to an existing homekit accessory in the home using HAP? Essentially, I want to use HAP-NodeJS as a client on a raspberry pi to connect to a given device in my iCloud home and change the status (ie, lock or unlock a door).

The device I'm interested in controlling is a Schlage Sense. I tried going the BLE route, using the NodeJS BLE libs, but without knowing Apple's encryption I've not figured out how to communicate with the device. Figured I could emulate what an IOS app does when it controls a pair device in the home.

Is this at all possible without using XCode API?

Thanks,

R

**Comment by KhaosT** [comment]
No, for remote access you need to use Apple TV or iPad.

**Comment by ooii** [comment]
May be that' a too old video but during 2015 WWDC, it was mentioned that we don't need an Apple TV anymore for remote access and that it can be achieved through iCloud (see [this video](https://developer.apple.com/videos/play/wwdc2015/210/) at 30:50). Is that part of the video deprecated?

**Comment by snowdd1** [comment]
If your hap-nodejs hardware has a genuine Apple MFI encryption chip (and the corresponding code to run it) that might even work. Otherwise ...

**Comment by ooii** [comment]
But what about an official HomeKit accessory (Philips Hue). I don't think you can control it through HomeKit if no hub remains at home. No?

**Comment by echamberlain** [comment]
If it is a WiFi accessory, but a BLE accessory would have no way to connect to iCloud without going through a gateway.  Functionality the AppleTV provides.

Eric Chamberlain

**Comment by ooii** [comment]
That makes sense.
Thanks.
