### ISSUE TITLE
FEATURE REQUEST: Battery Level

### ISSUE THREAD

**Issue by ryanmaxwell** [KhaosT/HAP-NodeJS#425]
iOS 10.3 adds support for monitoring battery levels on devices. Can we add support to this project so our third-party devices can report their battery levels if appropriate?

**Comment by KhaosT** [comment]
There is already a battery service you can use.

**Comment by justme-1968** [comment]
works since forever. but it depends on the app if this characteristic is displayed. for example eve has changed from displaying always to displaying only for battery low. it looks like home is ignoring this characteristic.

**Comment by ryanmaxwell** [comment]
@KhaosT fantastic i'll close this
