### ISSUE TITLE
error on curve25519 rebuild

### ISSUE THREAD

**Issue by micpura** [KhaosT/HAP-NodeJS#43]
I followed the install instructions, but it fails at nody-gyp rebuild.
any idea how to fix?

**Comment by PeijunZhao** [comment]
Rebuild may take several minutes. Wait until it finish.


发自我的 iPhone

**Comment by KhaosT** [comment]
@micpura What's the error? Can you post the log?

**Comment by micpura** [comment]
see below...

SCREEN DUMP
----------------------------------------------------
gyp ERR! stack Error: EACCES, unlink 'build'
gyp ERR! stack     at Error (native)
gyp ERR! System Linux 3.18.7-v7+
gyp ERR! command "node" 

"/usr/local/lib/node_modules/npm/node_modules/node-

gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/pi/HAP-NodeJS/node_modules/ed25519
gyp ERR! node -v v0.12.0
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok

npm ERR! Linux 3.18.7-v7+
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" 

"rebuild"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE
npm ERR! ed25519@0.0.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ed25519@0.0.2 install script 'node-gyp 

rebuild'.
npm ERR! This is most likely a problem with the ed25519 

package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls ed25519
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support 

request:
npm ERR!     /home/pi/HAP-NodeJS/npm-debug.log
-----------------------------------------------------------
NPM-DEBUG
-----------------------------------------------------------
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 

'rebuild' ]
2 info using npm@2.5.1
3 info using node@v0.12.0
4 info readInstalled object
5 verbose rebuild path, id [ '/home/pi/HAP-

NodeJS/node_modules/ed25519', 'ed25519@0.0.2' ]
6 verbose rebuild path, id [ '/home/pi/HAP-

NodeJS/node_modules/mdns', 'mdns@2.2.0' ]
7 verbose rebuild path, id [ '/home/pi/HAP-

NodeJS/node_modules/node-hkdf',
7 verbose rebuild   'node-hkdf@0.0.1' ]
8 verbose rebuild path, id [ '/home/pi/HAP-

NodeJS/node_modules/node-hkdf/node_modules/vows',
8 verbose rebuild   'vows@0.5.13' ]
9 verbose rebuild path, id [ '/home/pi/HAP-

NodeJS/node_modules/node-

hkdf/node_modules/vows/node_modules/eyes',
9 verbose rebuild   'eyes@0.1.8' ]
10 verbose rebuild path, id [ '/home/pi/HAP-

NodeJS/node_modules/node-persist',
10 verbose rebuild   'node-persist@0.0.2' ]
11 verbose rebuild path, id [ '/home/pi/HAP-

NodeJS/node_modules/node-persist/node_modules/mkdirp',
11 verbose rebuild   'mkdirp@0.3.5' ]
12 verbose rebuild path, id [ '/home/pi/HAP-

NodeJS/node_modules/node-persist/node_modules/underscore',
12 verbose rebuild   'underscore@1.4.4' ]
13 verbose rebuild path, id [ '/home/pi/HAP-

NodeJS/node_modules/node-persist/node_modules/sugar',
13 verbose rebuild   'sugar@1.3.9' ]
14 verbose rebuild path, id [ '/home/pi/HAP-

NodeJS/node_modules/srp', 'srp@0.2.0' ]
15 verbose rebuild path, id [ '/home/pi/HAP-

NodeJS/node_modules/srp/node_modules/bignum',
15 verbose rebuild   'bignum@0.6.1' ]
16 silly rebuild set [ '/home/pi/HAP-

NodeJS/node_modules/ed25519',
16 silly rebuild set   '/home/pi/HAP-

NodeJS/node_modules/mdns',
16 silly rebuild set   '/home/pi/HAP-

NodeJS/node_modules/node-hkdf',
16 silly rebuild set   '/home/pi/HAP-

NodeJS/node_modules/node-hkdf/node_modules/vows',
16 silly rebuild set   '/home/pi/HAP-

NodeJS/node_modules/node-

hkdf/node_modules/vows/node_modules/eyes',
16 silly rebuild set   '/home/pi/HAP-

NodeJS/node_modules/node-persist',
16 silly rebuild set   '/home/pi/HAP-

NodeJS/node_modules/node-persist/node_modules/mkdirp',
16 silly rebuild set   '/home/pi/HAP-

NodeJS/node_modules/node-persist/node_modules/underscore',
16 silly rebuild set   '/home/pi/HAP-

NodeJS/node_modules/node-persist/node_modules/sugar',
16 silly rebuild set   '/home/pi/HAP-

NodeJS/node_modules/srp',
16 silly rebuild set   '/home/pi/HAP-

NodeJS/node_modules/srp/node_modules/bignum' ]
17 info build /home/pi/HAP-NodeJS/node_modules/ed25519
18 info preinstall ed25519@0.0.2
19 verbose linkStuff [ false, false, false, '/home/pi/HAP-

NodeJS/node_modules' ]
20 info linkStuff ed25519@0.0.2
21 verbose linkBins ed25519@0.0.2
22 verbose linkMans ed25519@0.0.2
23 verbose rebuildBundles ed25519@0.0.2
24 info install ed25519@0.0.2
25 verbose unsafe-perm in lifecycle false
26 info ed25519@0.0.2 Failed to exec install script
27 verbose stack Error: ed25519@0.0.2 install: `node-gyp 

rebuild`
27 verbose stack Exit status 1
27 verbose stack     at EventEmitter.<anonymous> 

(/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:213:1

6)
27 verbose stack     at EventEmitter.emit (events.js:110:17)
27 verbose stack     at ChildProcess.<anonymous> 

(/usr/local/lib/node_modules/npm/lib/utils/spawn.js:14:12)
27 verbose stack     at ChildProcess.emit (events.js:110:17)
27 verbose stack     at maybeClose (child_process.js:1008:16)
27 verbose stack     at Process.ChildProcess._handle.onexit 

(child_process.js:1080:5)
28 verbose pkgid ed25519@0.0.2
29 verbose cwd /home/pi/HAP-NodeJS
30 error Linux 3.18.7-v7+
31 error argv "/usr/local/bin/node" "/usr/local/bin/npm" 

"rebuild"
32 error node v0.12.0
33 error npm  v2.5.1
34 error code ELIFECYCLE
35 error ed25519@0.0.2 install: `node-gyp rebuild`
35 error Exit status 1
36 error Failed at the ed25519@0.0.2 install script 'node-gyp 

rebuild'.
36 error This is most likely a problem with the ed25519 

package,
36 error not with npm itself.
36 error Tell the author that this fails on your system:
36 error     node-gyp rebuild
36 error You can get their info via:
36 error     npm owner ls ed25519
36 error There is likely additional logging output above.
37 verbose exit [ 1, true ]

**Comment by KhaosT** [comment]
Please use NodeJS 0.10.35/36 instead of 0.12.x There are several API changes in 0.12 which I breaks the build.

**Comment by micpura** [comment]
Thanks...
