### ISSUE TITLE
Video Doorbell support - question

### ISSUE THREAD

**Issue by brownad** [KhaosT/HAP-NodeJS#431]
With video doorbell in HomeKit simulator is there anything comparable to create the same service composite of services: ip cam, doorbell, motion sensor? But something that will work eg doorbell does not work as a service on its own

**Comment by KhaosT** [comment]
Doesn't [Doorbell](https://github.com/KhaosT/HAP-NodeJS/blob/master/lib/gen/HomeKitTypes.js#L2681) service match your need?

**Comment by brownad** [comment]
Nope, that service doesn't really work with notifications - stopped working as a supported plugin a few months ago, needs to be part of a composite

I have a doorbird device which exposes all apis; for ip cam (rtsp stream), a doorbell, motion sensor and lock opening control (also night vision) it fits with the new video doorbell but I haven't seen this created as a service yet.

Would you consider the video doorbell as a type in the service library as seen in the HomeKit sim or doesn't fit?

I'm already combing plugins to provide the same thing but it's not as tight as the working one with supported doorbell service - had to use a motion service for the doorbell activation.

Also I don't benefit from two way intercom which you get with the new service.

**Comment by KhaosT** [comment]
@brownad the components are already implemented [here](https://github.com/KhaosT/HAP-NodeJS/wiki/IP-Camera). For support for specific accessory, you will have to do add support using those components.

**Comment by Maxmudjon** [comment]
how to create _accessory.js for doorbell ?

**Comment by brownad** [comment]
Doorbell doesn't work for anyone that I've seen so not sure combing all of the implemented services works just yet - might be missing something ?

**Comment by KhaosT** [comment]
@brownad Are you sure you implemented doorbell correctly? When someone press the doorbell, HomeKit expects accessory to send a `ProgrammableSwitchEvent` with value 0. Make sure you call the `setValue` or `updateValue` on the characteristic.

**Comment by brownad** [comment]
Yes I had it working for quite a while until iOS changed the rules it stopped working 

Others reported the same

**Comment by KhaosT** [comment]
"until iOS changed the rules it stopped working", do you remember when is that? I can't remember this from happening and as long as simulator's doorbell works, doorbell service should still work here.

**Comment by brownad** [comment]
Approx February

**Comment by brownad** [comment]
If you create a simple doorbell device it will show up as 'not supported' in iOS home app

**Comment by KhaosT** [comment]
Then I don't think it's related to iOS changes. iOS 10.2 was released on December 12, 2016 and iOS 10.3 was released on March 27, 2017. In between there is no way for Apple to change behavior of HomeKit.

For your "not supported" problem, Home app always show that if that's the only service an accessory has. If you add another service (err ... like a motion sensor service), that "not supported" tile should disappear. And here I think Home app did a terrible job showing that. Doorbell notification is displayed by HomeKit, not Home app. So even in case Home app shows "not supported", HomeKit should still show notification if a doorbell event happens.

**Comment by Maxmudjon** [comment]
i can create _accessory.js for doorbell ?

**Comment by KhaosT** [comment]
@Maxmudjon you can. Read the documentation [here](https://github.com/KhaosT/HAP-NodeJS/wiki/IP-Camera).

**Comment by Maxmudjon** [comment]
I do not know English well and it's difficult for me to create an accessory doorbell. Except the doorbell, all the accessories I created))

**Comment by KhaosT** [comment]
@Maxmudjon then what are you trying to do... I already pointed out all the resources you need to solve your problem, I can't write code for you.

**Comment by Maxmudjon** [comment]
FAN, GARAGE_DOOR_OPENER, LIGHTBULB, DOOR_LOCK, OUTLET, SWITCH, THERMOSTAT, SENSORS, ALARM_SYSTEM, DOOR, WINDOW, WINDOW_COVERING, PROGRAMMABLE_SWITCH

**Comment by Maxmudjon** [comment]
I already created these accessories

**Comment by Maxmudjon** [comment]
Only the doorbell is left

**Comment by brownad** [comment]
Ok makes sense what you said about combing with motion sensor, think it has same limitations in simulator. Thanks 

Was approx about feb give or take a month but it was something that worked for a while then just stopped

**Comment by brownad** [comment]
Likely the doorbell was introduced before camera now it assumes to be a composite service with an ip camera thus a video doorbell is achieved. Standalone it won't work. Which has stumped a few people along the way...

I guess this can be done as you say combine and make it happen.

Thanks again please close the query 👍

**Comment by brownad** [comment]
@KhaosT does the update to include VIDEO_DOORBELL mean anything or just additive for the lib?

https://github.com/KhaosT/HAP-NodeJS/blob/d808656e29390f6934c36bd9b51d1338e63b4597/lib/Accessory.js

**Comment by KhaosT** [comment]
@brownad This is just for category, Home app uses that to display icon for unpaired accessory.

**Comment by brownad** [comment]
Cool. thanks @KhaosT  👍

**Comment by Maxmudjon** [comment]
Finally I created an accessory video doorbell, yeahh))

**Comment by Maxmudjon** [comment]
![photo_2017-04-20_06-56-46](https://cloud.githubusercontent.com/assets/23142922/25209776/97d02bea-2596-11e7-96b4-27a01a7466d0.jpg)

**Comment by brownad** [comment]
Awesome !!!!!
