### ISSUE TITLE
Doorbell

### ISSUE THREAD

**Issue by Wertok07** [KhaosT/HAP-NodeJS#433]
Can someone share the file with doorbell accessorie

**Comment by brownad** [comment]
Here's a good example

https://github.com/Samfox2/homebridge-doorbell

But it won't work unless you add the service to another device e.g. An IP camera.

It needs to be an additive device not a 'doorbell' on its own... used to work no longer works standalone

**Comment by Wertok07** [comment]
I saw this, but how do I make an accessory based on this example. I read in this file https://github.com/KhaosT/HAP-NodeJS/blob/master/lib/gen/HomeKitTypes.js
About services and characteristics but i do not know what is the pattern of making accessories.

Thanks for helping me!

**Comment by brownad** [comment]
Try the example noted, but it won't do what you are expecting...

what do you want to achieve?  and what hardware do you have that you want to wire up to home bridge?

**Comment by Maxmudjon** [comment]
Finally I created an accessory video doorbell, yeahh))

![photo_2017-04-20_06-56-46](https://cloud.githubusercontent.com/assets/23142922/25209822/c99633b8-2596-11e7-9b1b-952b0531d888.jpg)

**Comment by Maxmudjon** [comment]
Video Doorbell with lock mechanism 

![domofon iphone](https://cloud.githubusercontent.com/assets/23142922/25210736/c5f10ca2-259a-11e7-980e-52ae1b4641d7.jpg)

**Comment by brownad** [comment]
Do you have the example code somewhere to look at?

**Comment by Wertok07** [comment]
Do you use ffmpeg or avconv?
Which camera you use?

**Comment by Maxmudjon** [comment]
@brownad write @mail adress

**Comment by Maxmudjon** [comment]
@Wertok07 ffmpeg

**Comment by Wertok07** [comment]
I have Hikvision camera but is not working with ffmpeg and avconv has bad quality. Can you send me example code of doorbell_accessories? My mail adress: wojtek.ok@wp.pl
Thanks!

**Comment by brownad** [comment]
adrian-brown@mail.com

Thanks man 👍

**Comment by rajkowski** [comment]
Cool! Would like to see! programmer@cloud99.pro
Currently have an Elk 930 doorbell sensor and ip cam

**Comment by brownad** [comment]
Might be a good idea to just commit a sanitised example to GH...

**Comment by california444** [comment]
I'm also very interested how you made it work...
Thanks!

**Comment by brownad** [comment]
Celebrity now 😀

**Comment by Maxmudjon** [comment]
Who wrote the mail I sent

**Comment by california444** [comment]
California444@gmail.com
Thx!

**Comment by brownad** [comment]
Any chance you post this in GH?

**Comment by Maxmudjon** [comment]
No, I will not

**Comment by brownad** [comment]
I trashed the mail as it seemed suspicious especially after what you wrote on that case that's a shame

**Comment by Maxmudjon** [comment]
@brownad Why shame? I just do not know to use GH !

**Comment by Maxmudjon** [comment]
https://github.com/Maxmudjon/HAP-NodeJS-accessories

**Comment by brownad** [comment]
Very cool

Thanks man 😀
