### ISSUE TITLE
WindowCovering Service

### ISSUE THREAD

**Issue by kajaba** [KhaosT/HAP-NodeJS#449]
Do you know if WindowCovering service is implemented in iOS?
I tried to make an interface in HAP but the accessorry doesnt show up in choose accessory screen.
Made few accessories myself so I know how to make them in HAP

**Comment by michaelkroll** [comment]
Could you share those accessories as templates for others?
Do you have. window blind accessory created or is this what you are looking for? I want to ceare such an accessory as well. Maybe we can collaborate.

**Comment by kajaba** [comment]
I am using teptron move blinds. They are using CSR bluetooth mesh.
My accessory looks like this (its work in progress):
`var Accessory = require('../').Accessory;
var Service = require('../').Service;
var Characteristic = require('../').Characteristic;
var uuid = require('../').uuid;
var exec = require('child_process').exec;
var ServiceName="MoveBlinds1";

var sensorUUID = uuid.generate('hap-nodejs:accessories:move1');
var move1 = exports.accessory = new Accessory('Move Blinds 1', sensorUUID);

move1.username = "FA:34:CC:5A:13:2B";
move1.pincode = "031-45-154";

move1.getService(Service.AccessoryInformation)
.setCharacteristic(Characteristic.Manufacturer, "Teptron")
.setCharacteristic(Characteristic.Model, "Move")
.setCharacteristic(Characteristic.SerialNumber, "Move-ID1");

move1.on('identify', function(paired, callback) {
  callback();
});

move1.addService(Service.WindowCovering,ServiceName)
  .getCharacteristic(Characteristic.CurrentPosition)
  .on('set', function(callback) {
    // return our current value
    callback(null, MOVE_BLINDS.getPosition());
  });

move1.getService(Service.WindowCovering)
  .getCharacteristic(Characteristic.PositionState)
  .on('get',function(callback){
 
  });

move1.getService(Service.WindowCovering)
  .getCharacteristic(Characteristic.TargetPosition)
  .on('set',function(val, callback){
    //MOVE_BLINDS.setPosition(val,callback);
  });

`

**Comment by kajaba** [comment]
Iam such a dumbass. I named the js file Move_accessorry.js instead of Move_accessory.js
Sorry for posting this issue. Closing

**Comment by bluntiless** [comment]
Hi kajaba, I was wondering if you had actually got this working with HAP-NodeJS and how you paired the Teptron Move with HAP-NodeJS. I have managed to install your code and it is showing up in the Home app on iOS. I also have the Teptron move and want Siri to control my blinds. Thanks in advance!

**Comment by kajaba** [comment]
Hi bluntiless. My code is just a template, but I do have an implementation based on [csrmesh](https://github.com/nkaminski/csrmesh). The implementation doesnt work correctly and I didnt have time to investigate it further.
