### ISSUE TITLE
Thermostat accessory!

### ISSUE THREAD

**Issue by yoojuaan** [KhaosT/HAP-NodeJS#453]
Hi! I'm looking for some thermostat_accessory.js example working throw mqtt, to start with it. I hope someone helps me! I'm so sorry for my English! Thanks so much.

**Comment by matbor** [comment]
Here you go. 

https://gist.github.com/matbor/c61560746c9c38d751070311ed338c18

**Comment by yoojuaan** [comment]
Hi @matbor ! That is not what I'm looking for. I need a Thermostat accessory ( something like this http://cdn2.hubspot.net/hub/400849/file-2027987282-gif/thermostat.gif), where you can select the temperature that you want, and switch on/off the heater. The item you are referring to, is just a temperature sensor, that can only read temperatures but it can't handle a heater. Thank you!

**Comment by brownad** [comment]
What brand are you looking to build for here?  Is there something you had in mind?

You wanted a thermostat that was correct before but you meant a thermostat controller for heating not a temp sensor right?

Plenty of examples in npm already e.g. Homebridge  Nest, Evohome...

**Comment by yoojuaan** [comment]
Hi @brownad! Yes, you are right. It is a home-made thermostat controller, it's mqtt based and I want to connect it with HomeKit. Thank you!

**Comment by oddwires** [comment]
Is this any use ? [radiator.js](https://github.com/oddwires/alarm-system/blob/8af531d394e517fce5af8f6b505bf828a1a0a240/ConfigFiles/Generic_Radiator.js). It's not mqtt based, but does combine thermostat and switch functionality.

My installer passes it through the SED editor to customise it. So the initial parameters ( Parm1, Parm2 etc ) dont appear in the final version as they get changed to meaningful strings.

**Comment by yoojuaan** [comment]
Hi @oddwires thank you, that is something like I'm looking for, but I already created one by myself, I'm sharing with all you my accessory. I hope that helps someone. Thank you so much for your help!
[Termostato_accessory.txt](https://github.com/KhaosT/HAP-NodeJS/files/1128707/Termostato_accessory.txt)

Only yo need to change the extension of the file from .txt to .js, and modify the variables on the file, like host, topic, and other that you need!.
