### ISSUE TITLE
New Speaker Accessory Type

### ISSUE THREAD

**Issue by Grayson3197** [KhaosT/HAP-NodeJS#456]
When will you be adding support for the newly released "Speaker" accessory, if at all?

**Comment by rpavez** [comment]
It should be pretty straightforward to implement based on the specs detailed on HomeKit Accessory Protocol Specification (non-commercial version)* https://developer.apple.com/homekit/specification/ Chapter 9.29 Speaker

**Comment by KhaosT** [comment]
The "Speaker" announced in WWDC is powered by AirPlay 2 protocol, which has nothing to do with HAP itself. The speaker in the spec is referring to the speaker used in IP Camera, which Home app doesn't support controlling directly (without the camera part).

For AirPlay 2 protocol, there isn't a lot detail on what exactly it is and is not going to be implemented in this project.

**Comment by djiwondee** [comment]
Based on the WWDC2018 session 231
![image](https://user-images.githubusercontent.com/37173958/55741592-f27fca00-5a2d-11e9-8f57-d4848d1071bb.png)
it could be assumed speaker could be used universally:
![image](https://user-images.githubusercontent.com/37173958/55741548-d11ede00-5a2d-11e9-94cb-8f7005d3132f.png)
