### ISSUE TITLE
Stateless Programmable Switch no longer works on node v8.x

### ISSUE THREAD

**Issue by ebaauw** [KhaosT/HAP-NodeJS#464]
I looks like the triggering of the `Stateful Programmable Switch` through it's `Input Event` is broken under node v8.x, see https://github.com/ebaauw/homebridge-hue/issues/125.  One of my users experienced this on his Raspberry.  Reinstalling node v7.x solved it.

I reproduced the issue under macOS 10.12.5, using node v8.1.2 and v8.1.3.  Installing node v8 over a working installation/configuration and re-installing home bridge (to force the compilation of dsn-sd agains the new node version) breaks the programmable switch.  After re-installing node v6.11.0 (and npm and homebridge to re-compile the dns-sd stuff), the switch works again.

I have no idea what could be causing this, or even where to start looking.  Any help is greatly appreciated.

**Comment by KhaosT** [comment]
Might be related to this? 

https://github.com/nfarina/homebridge/issues/1353#event-1138717098

**Comment by ebaauw** [comment]
Thanks, Tian.  It might be, I'll try the HomeKit debug profile this weekend.

**Comment by ebaauw** [comment]
I got the debug profile working, but homed is generating dozens of messages per second.  I think I better setup a test Home with just one or two accessories.

**Comment by KhaosT** [comment]
You can filter those messages to only leave what you care. Normally I
filter those by category, choose "doesn't contain"

**Comment by ebaauw** [comment]
Yes, it's the same issue, not limited to the `Input Event`.  In the log of `DEBUG=* homebridge -D` I see
```
  EventedHTTPServer [::ffff:192.168.xxx.xxx] HTTP connection was closed +1s
  EventedHTTPServer [::ffff:192.168.xxx.xxx] HTTP server was closed +1ms
  EventedHTTPServer [::ffff:192.168.xxx.xxx] Client connection closed +0ms
```

When I refresh the screen in Eve, the connection is re-estabished, and a press on the Hue dimmer switch is actually registered by HomeKit, but after a few seconds, the same messages appear and the connection is lost again.

I'll close this issue in favour of nfarina/homebridge#1353.

**Comment by KhaosT** [comment]
This should be addressed with 0.4.27

I don't know why but Node.js introduced a different property that will close inactive connections. See [here](https://nodejs.org/api/http.html#http_server_keepalivetimeout)

**Comment by ebaauw** [comment]
Thanks once again, Tian!

Guess I will need to use keepAliveTimeout in my homebridge-zp plugin as well.  It uses `http` to create a server where it receives the notifications from the Sonos speakers.

**Comment by KhaosT** [comment]
@ebaauw depends on how the client create the connection. There is a [bug](https://github.com/nodejs/node/issues/13391) that causes http server to ignore `Connection: keep-alive` in the request. If your client does include that when starting HTTP request, once the bug being fixed it should no longer be needed.
