### ISSUE TITLE
Yosemite DNS service error

### ISSUE THREAD

**Issue by jeffhuys** [KhaosT/HAP-NodeJS#47]
I've followed the steps in Readme.md, but after running `node Core.js` I get the following error:

    > $ node Core.js
    HAP-NodeJS starting...
    TCP server accepting connection on port: 51826
    HAP Server is listening
    TCP server accepting connection on port: 51828
    HAP Server is listening
    TCP server accepting connection on port: 51832
    HAP Server is listening
    TCP server accepting connection on port: 51838
    HAP Server is listening
    TCP server accepting connection on port: 51846
    HAP Server is listening

    events.js:72
            throw er; // Unhandled 'error' event
                  ^
    Error: dns service error: unknown
        at Advertisement.on_service_registered (/Users/jeffhuijsmans/Development/HAP-NodeJS/node_modules/mdns/lib/advertisement.js:42:24)
        at SocketWatcher.MDNSService.self.watcher.callback (/Users/jeffhuijsmans/Development/HAP-NodeJS/node_modules/mdns/lib/mdns_service.js:18:40)

Are there some extra steps to take on OS X?

**Comment by KhaosT** [comment]
@jeffhuys there is no extra steps needed for OS X Yosemite... Your npm rebuild didn't give you any error output?

**Comment by jeffhuys** [comment]
No, not a single error was given. It still won't boot even with one accesory. My firewall is turned off. 



—

**Comment by KhaosT** [comment]
@jeffhuys you didn't modify your discoveryd right?

**Comment by jeffhuys** [comment]
Now that you mention that name... How would I check? I remember something about that, because it was clogging my already laggy school network (5000 pc's at once being discovered)...



—

**Comment by KhaosT** [comment]
@jeffhuys can you first try to run this in terminal and check if your are using discoveryd? "ps ax|grep discoveryd"

**Comment by jeffhuys** [comment]
I will do that as soon as I reach my laptop again. I will also check my history|grep discoveryd.

Already thanks for the fast response! This could very well be the solution. 



—

**Comment by jeffhuys** [comment]
Output of `ps ax | grep discoveryd`

      > $ ps ax | grep discoveryd
         54   ??  Ss     0:00.94 /usr/libexec/discoveryd --udsocket standard --loglevel Basic --logclass Everything --logto asl
        243   ??  Ss     0:00.01 /usr/libexec/discoveryd_helper --loglevel Detailed --logclass Everything --logto asl

**Comment by KhaosT** [comment]
That looks right to me, not sure why this happens. Can you post the system log from console when this issue happens?

**Comment by jeffhuys** [comment]
The moment I run Core.js this error pops up in the console:

`28/03/15 09:04:24,475 discoveryd[54]: Basic DNSResolver  Return Code is 9 and we are treating it as an error!`

**Comment by jeffhuys** [comment]
I've set the log level to Everything, this is the output:

http://pastebin.com/TXZcXnDV

**Comment by KhaosT** [comment]
@jeffhuys can you try to replace Advertiser.js with contents from here? https://gist.github.com/KhaosT/d1f617230f619bf64e71

**Comment by jeffhuys** [comment]
That seems to have done the trick, weirdly enough (as the only difference is a try/catch, right?). At least it doesn't give me any errors.

    > $ node Core.js
    HAP-NodeJS starting...
    TCP server accepting connection on port: 51826
    HAP Server is listening

I don't have a Dev account yet to try it out, unfortunately.
Is there anything else you need me to try?

**Comment by KhaosT** [comment]
@jeffhuys That's so strange... the try/catch suppose to get detailed error instead of solving the problem ... but anyway it magically works I guess? If you have Xcode, you can try to run a HomeKit app in simulator and see if this thing actually works for you :)
