### ISSUE TITLE
anyone have windowcovering accessory example??

### ISSUE THREAD

**Issue by lisergio** [KhaosT/HAP-NodeJS#473]
Hi!
I look for a example to make an accessory for my HomeKit server, but I did not find any....
Does anyone have an example?
thanks!!!

**Comment by Yub0** [comment]
Hi,
I'm looking for the same accessory too

Thanks

**Comment by lisergio** [comment]
I'm working in a blind accessory, 
I have managed to send the position of the blind to a esp8266 to set between 0 and 100, but the accessory appears as not connected.
If you adjust the value it sends, but I do not get the accessory to remain connected to the server.
I do some more testing and I put here the code in case anyone can help.
