### ISSUE TITLE
Push characteristics update to iOS device

### ISSUE THREAD

**Issue by htreu** [KhaosT/HAP-NodeJS#48]
Hi,

is there a way to push change of state outside of HAP to iOS? I try to control accessories provided by openHAB (a home automation gateway) where the state of an accessory can change without HAP´s notice. Even if I listen on the changes from outside in HAP-NodeJS I can't get the update pushed to iOS.

Thanks and kudos for both, HAP-NodeJS and HomeKitDemo.

Cheers,
henning

**Comment by KhaosT** [comment]
@htreu check Thermostat_Logical.js:134 basically you need to find a way to get the characteristic object and call updateValue() on the object when a change outside the HAP happens.
