### ISSUE TITLE
Raspbian - no camera image 

### ISSUE THREAD

**Issue by gyurobenjamin** [KhaosT/HAP-NodeJS#480]
Trying to access my Raspberry onboard camera via Homekit.
My setup:
Raspberry Pi Zero W
Kuman Camera Module

Tried my cemra with raspistill, and I got the photo, so this part seems fine.
Also I tried to access my camera with motionEye, I can add the camera but no image.

**Comment by pdlove** [comment]
This should be fully resolved with the latest updates.

**Comment by gyurobenjamin** [comment]
Which last update? Yesterday I tried again from the beginning, and worked. In this case I used the full raspbian OS instead of the lite. Maybe it was the problem.
