### ISSUE TITLE
Discussion of unexpected Issues

### ISSUE THREAD

**Issue by pdlove** [KhaosT/HAP-NodeJS#486]
Some services have optional Characteristics that no longer exist. We've allowed compatibility with older versions by creating it in the bridge file and then making the get procedure add the Characteristic to mimic
 the old behavior.

The new issue is that some optional Characteristics are now required... Namely the FirmwareRevision characteristic.
This is causing  the addCharacteristic call to fail for many plugins. I'm hesitant to make the addCharacteristic get an existing if there is a duplicate. In all of my plugins I created a function "addOrGetCharacteristic" and the same for services. Should we just make the add and get functions identical and interchangeable where they get the existing or add a new as applicable?
Or does anyone else have any ideas on how to resolve this now and next time?

**Comment by NorthernMan54** [comment]
Here's my 2 cents as a small time plugin developer.  I think that this should be approached in a way to avoid breaking as many of the existing plugins as possible.  There are now hundreds of plugins, each with various levels of support around them, and if this is a breaking change it will leave an eco system with plugins in a potentially unknown state.  So my vote is to follow your thoughts below, and modify addCharacteristic to check for existing characteristics first, and only add if it doesn't exist.   At the same time, add some logging to indicate that the addCharacteristic for this characteristic is no longer required. 

This is similar to the removal of reachability recently.

**Comment by pdlove** [comment]
Thanks for the confirmation. 
We had talked a bit in the PR about what needed to stay for backwards capability before making the recent changes. I didn't consider what would occur from the change in the Required/Optional Characteristics as long as they existed in the files. I'll get the solution in place tonight along with some of the good ideas that have been posted for additional validation. I'm hopeful nothing new comes up.

**Comment by pdlove** [comment]
I have a concern. 
First, I add a characteristic and add an event for "get" to call a function.
Then I add the characteristic again and add the event again.
Will the event fire the event for both of the functions?
If so how does Siri react?
I'm going to test this to make sure it won't be an issue, but if anyone knows the answer and/or solution, please let me know.

**Comment by pdlove** [comment]
I ended up doing a one-off for this because of the danger of not adding when asked to add. This is in #489
