### ISSUE TITLE
Characteristic.prototype.validateValue - Sending values with extra decimals with CurrentTemperature

### ISSUE THREAD

**Issue by NorthernMan54** [KhaosT/HAP-NodeJS#487]
I was testing one of my plugins that returns current temperature, and found that the values being sent to home kit have extra decimals

My device is returning 22.9 to HAP-NodeJS, and HAP-Node is sending 22.900000000000006

From debug

  MCUIOT Callback Temp 22.9 +1ms
  Accessory [Bart] Got Characteristic "Current Temperature" value: 22.900000000000006 +1s

If I get some time later, I may dig into this further.

From a priority view, this is a priority 2 and doesn't seem to cause any issues.

**Comment by NorthernMan54** [comment]
And am testing a second plug, homebridge-dht and have this error

/Users/sgracey/Code/HAP-NodeJS/lib/Characteristic.js:225
      if (myString.length>maxLength) myString = myString.substring(0,maxLength); //Truncate strings that are too long
                  ^

TypeError: Cannot read property 'length' of undefined

And after looking at my plugin code, I was setting using an undefined value for the string.  I fixed the plugin to resolve.

**Comment by pdlove** [comment]
On the string, I'm adding validation to make sure that a string has been passed.
On your first item, I'd originally worked that out by using decimal.js but someone had sent me something that worked better... Looks like it didn't work better.

**Comment by pdlove** [comment]
@NorthernMan54  what version of node have you tested on? I'm not getting 22.9 to return as anything other than 22.9 when I run it through validation. I'm going to try and drop down to 6.11.2 for further testing.

**Comment by NorthernMan54** [comment]
@pdlove I'm on OSX 6.10.2, and am upgrading to 6.11.2 to see if that resolves the issue.

**Comment by NorthernMan54** [comment]
@pdlove I upgraded to 6.11.2, and the same issue.  I added a bunch of logging into the problematic routine, and found that it doesn't like negative values.  As I live in the great white north, we regularly get negative temperatures, so in my plugin I have changed the min for the current temperature characteristic to -100.  I know it doesn't get that cold here, but who knows.

When current temperature runs thru the validation logic, minValue_resolved gets set to -100 which breaks this line in Characteristics.js

      var valueDiffFromMin_scaled = ((newValue-minValue_resolved)*Math.pow(10,stepDecimals));

Which returns 1226 for 22.6 when the minValue_resolved is -100.  If minValue_resolved is 0, 226 is returned.

**Comment by pdlove** [comment]
Are you sure it's breaking? I just ran it through with the same logic and the final result is the same for me. I'm about to have my fork fixed using decimal.js and will let you know so you can test.
Do you use slack? That might help test quickly.

**Comment by pdlove** [comment]
@NorthernMan54 Can you please try the code on my fork and make sure it works for you? I'm not seeing any issues with it but want to make sure someone else is working with it as well before I submit the PR.

**Comment by pdlove** [comment]
These are all corrected in #489

**Comment by NorthernMan54** [comment]
@pdlove

I can try this tonight, in about 7 hours

Tks

**Comment by NorthernMan54** [comment]
@pdlove I tested your branch, and this works.  Success
