### ISSUE TITLE
this.eventOnlyCharacteristic no longer set for ProgrammableSwitchEvent

### ISSUE THREAD

**Issue by ebaauw** [KhaosT/HAP-NodeJS#488]
As of 30f0aadc1613863e1590a6132484da92e617e385 `this.eventOnlyCharacteristic` is no longer set to `true` for `Characteristic.ProgrammableSwitchEvent`.  Because of this, `Characteristic.setValue()` and `Characteristic.updateValue()` no longer issue an event when the same button is pressed twice.

We patched `lib/gen/HomeKitTypes.js` manually to include this setting.  I guess it needs to be set in `lib/gen/HomeKitTypes-Bridge.js` now, so `HomeKitTypes.js` can continue be generated.

**Comment by pdlove** [comment]
This is corrected in #489
