### ISSUE TITLE
Airport extreme bonjour problem

### ISSUE THREAD

**Issue by rooi** [KhaosT/HAP-NodeJS#49]
Hi KHaosT,

Great updates to the HAP-NodeJS!
I have one question you could perhaps help me with. Recently I experience bonjour problems with my router (airport extreme) when using the HAP-NodeJS and other bonjour services (vnc, https, etc.). What happens is that bonjour services are not published correctly (disappear in Bonjour Browser or cannot be " unfolded" using the > button).
Do you have any idea on what causes this problem? Is there a way to debug my router (already factory reseted)? Is it simply up for an replacement, or could there something be caused by HAP-NodeJS or other services of mine (no recent changes).

Hopefully you can give me you first thought. I posted this as an issue for the case someone else experiences the same and can lookup the solution.

Thanks!

Roy

**Comment by KhaosT** [comment]
@rooi I'm not sure about this topic, maybe you can check with avahi community (if you are using Linux) and see if they can come up a solution for you :)

**Comment by rooi** [comment]
Thanks KhaosT,

Strange problem indeed. I'm running HAP-NodeJS on mac os x by the way, but I understand that you do not know what could cause it. I'll look around on other places and if I find something, I'll post it here.

**Comment by KhaosT** [comment]
@rooi BTW you can try to update the mdns module and see if that solves issue (npm update mdns)
