### ISSUE TITLE
Asking Siri for a status, doesn't do anything on the server

### ISSUE THREAD

**Issue by patricks** [KhaosT/HAP-NodeJS#50]
Hi,

I have setup HAP-NodeJS on a Raspberry Pi and also written a simple iOS HomeKit enabled app. I have connected the iOS app with the GarageDoorOpener. 

If I tell Siri to open / close the garage, everything works fine. But if I ask about the door status, I always get an wrong answer.

Does anybody have an idea whats wrong? Do I need to set anything else?
Normally CURRENT_DOOR_STATE_CTYPE should be called on the server or?

**Comment by KhaosT** [comment]
@patricks when you say "get a wrong answer", do you mean the Siri reports current door state but the answer is different from what it suppose to be or do you mean Siri reports something not related to the door state at all?

**Comment by patricks** [comment]
Sorry for not exactly telling you what happened. I got the wrong state. Siri always thinks the door is open.

**Comment by KhaosT** [comment]
@patricks did you remember to update the current door state when the target door state changes?

**Comment by patricks** [comment]
If the state changes it remembers the state for a few minutes, after that it is wrong "up" again.

**Comment by KhaosT** [comment]
@patricks Siri will query the state on the server, what I can suggest you do is to intercept the return of responseCharacteristic part under Server.js and check if the server returns the right state... If server returns the right state but Siri tells the wrong one, you may need to file a bug with Apple at bugreport.apple.com against [HomeKit][Siri].
