### ISSUE TITLE
Service.HeaterCooler does not support 'TargetTemperature'

### ISSUE THREAD

**Issue by nitaybz** [KhaosT/HAP-NodeJS#500]
Hi,

I'm trying to build a plugin with the HeaterCooler Service since it's supported by iOS 11.
the problem I have is that I can't add 'TargetTemperature' characteristic which is quite essential for Air Conditioner control plugin. 
I'm getting this error:
```
/usr/local/lib/node_modules/homebridge-tado-ac/index.js:129
        .setProps({
        ^

TypeError: Cannot read property 'setProps' of undefined
    at TadoAccessory.getServices (/usr/local/lib/node_modules/homebridge-tado-ac/index.js:129:9)
    at Server._createAccessory (/usr/local/lib/node_modules/homebridge/lib/server.js:378:36)
    at Server._loadAccessories (/usr/local/lib/node_modules/homebridge/lib/server.js:266:26)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:81:38)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:40:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
```
line 129 is:
`this.service.getCharacteristic(Characteristic.TargetTemperature).setProps({ `

any plans on solving that?

Much appreciated! 👍

**Comment by nitaybz** [comment]
@KhaosT Please Help!

**Comment by pdlove** [comment]
@nitaybz Where are you seeing the HeaterCooler service as available?

**Comment by pdlove** [comment]
@nitaybz You should use the provided CoolingThresholdTemperature and HeatingThresholdTemperature or simply use the Thermostat Service.

You should be able to use this.service.addCharacteristic(Characteristic.TargetTemperature) but IOS works better if you use the supported Services with only the Supported Characteristics already on them as required or optional.

**Comment by nitaybz** [comment]
Thanks @pdlove 
I'm using that in homebridge... and I really can't add Characteristic.TargetTemperature to the HeaterCooler Service.
The reason I want to use this service instead of the the thermostat is because I want to use the SwingMode and RotationSpeed characteristics.

I'm looking at homekit docs, and I can see the targetTemperature under AirConditioner, which means it is native for this service:
[https://developer.apple.com/documentation/homekit/hmaccessorycategorytypeairconditioner](https://developer.apple.com/documentation/homekit/hmaccessorycategorytypeairconditioner)
am I reading it wrong?

**Comment by KhaosT** [comment]
@nitaybz Yeah you are reading it wrong... Please see the spec (https://developer.apple.com//homekit/specification/) on what characteristics should be used with each service.

**Comment by nitaybz** [comment]
I don't see Heater Cooler in these docs... but anyway thanks a lot for your help!
I used CoolingThresholdTemperature and HeatingThresholdTemperature creating [Homebridge Tado AC plugin](https://github.com/nitaybz/homebridge-tado-ac).
