### ISSUE TITLE
Question: Where is Sprinkler and Faucet?

### ISSUE THREAD

**Issue by dkrizic** [KhaosT/HAP-NodeJS#504]
On the WWDC, Apple was talking about new devices in HomeKit: Sprinkler and Faucet. Looking into Xcode 9, the documentation and the current Homebridge Accessory Simulator I don't find any single reference for those device types. 

Looks like HomeKit in iOS 11 does not include those two devices yet. It might be that it comes via update.

Did I miss something?

**Comment by KhaosT** [comment]
No you did not miss anything. It’s nowhere in current iOS 11.

**Comment by pdlove** [comment]
I will watch for changes as updates are released so that we can get them into the list as soon as possible. At this point, Apple still doesn’t have Color Temperature on lightbulb in the simulator so i don’t think the simulator really has everything in it.

**Comment by dkrizic** [comment]
Just to clarify: We talk about this, right?

`➜  Headers pwd
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/System/Library/Frameworks/HomeKit.framework/Headers
➜  Headers grep -i sprinkler *.h
`

**Comment by pdlove** [comment]
It is pulled from “/Applications/HomeKit Accessory Simulator.app/Contents/Frameworks/HAPAccessoryKit.framework/Versions/A/Resources/default.metadata.plist”
You can see in the import.js file how that process works.

**Comment by dkrizic** [comment]
The release notes of watchOS mentions sprinklers and faucets, so I assume that iOS 11.2 and current Xcode now contain everything:

http://www.idownloadblog.com/2017/12/05/watchos-4-2-release-notes/

**Comment by echamberlain** [comment]
Yes, faucet, shower head, and sprinkler were added in iOS 11.2.

**Comment by pdlove** [comment]
I still don't see them in the HAP Simulator I just downloaded nor do I see them in the Specifications. If anyone has the UUID for the services and associated Characteristics then it would be awesome so we could get them added.

**Comment by dkrizic** [comment]
There is still no HomeKit Simulator for Xcode 9.2... Waiting....

**Comment by dkrizic** [comment]
In den Release Notes zu watchOS 4.2 findet man

> Adds support for HomeKit sprinklers and faucets in Home

http://www.idownloadblog.com/2017/12/05/watchos-4-2-release-notes/

**Comment by dkrizic** [comment]
Wahrscheinlich ist das nur ein Schalter, der anders aussieht, aber ich habe Hoffnung, dass da mehr Intelligenz dahinter ist. So eine Steuerung einer Bewässerungsanlage kann sehr komplex sein. Zur Zeit sind das bei mir stupide Timer.

**Comment by pdlove** [comment]
I managed to find the files in the IOS image for the HomeKit information. I've updated the devices on my fork and will test with them in the next week or two prior to merging with HAP-NodeJS. Anyone who wants to try it out, feel tree to grab HomeKitTypes.js from my fork. If anyone else can confirm they are working them I'll get it merged in.

**Comment by simont77** [comment]
Could you tell us which are the files in the iOS image? Thanks

**Comment by pdlove** [comment]
The xml file I'm getting the information from in IOS is /System/Library/PrivateFrameworks/HomeKitDaemon.framework/plain-metadata.config
I updated the import.js file to process this format but the resulting HomeKitTypes.js file has too many differences in naming convention to use the file generated from the xml. I'm going to see if it's as simple as setting up aliases to be able to switch to using it for the imports. At the very least it allows us to find the major differences. I think that to get the most accurate and current information we really need to use a combination of the two files.

**Comment by simont77** [comment]
Thanks. I will have a look at the file.

**Comment by simont77** [comment]
I’ve found this pages on Apple website that may help understanding how to use these new Services and Characteristics
https://developer.apple.com/documentation/homekit/hmcharacteristicvalueprogrammode
https://developer.apple.com/documentation/homekit/hmcharacteristicvaluevalvetype

**Comment by simont77** [comment]
I played a bit with the new services and characteristics tweaking Homekit Accessory Simulator. Irrigation and Valve Services are correctly recognised by Home.app (did not try Faucet which seemed more limited, only open-close). Irrigation seems more oriented to automatic irrigation system and is similar to a sensor (only read is allowed). Valve is more flexible, you can read and write status, set a time duration, read remaining time. Unfortunately none of them is recognised by Elgato Eve.app up to now (I guess that they are waiting for the release of their Eve Acqua device).

**Comment by dkrizic** [comment]
I just looked on developer.apple.com. There is still no new version of HomeKit Accessory Simulator that contains Sprinkler and Faucet. How did you tweak HomeKit Accessory Simulator to show the new devices.

This irrigation logic sounds interesting. This is exactly what I am looking for. Currently I have three valves for irrigation that are normal switches. The possibility to control timings can only be done using automation.

**Comment by simont77** [comment]
You should manually modify the plist file inside HAP framework inside Homekit Assessory Simulator adding Services and Characteristics found by pdlove.

**Comment by Maxmudjon** [comment]
![photo_2018-01-14_02-27-38](https://user-images.githubusercontent.com/23142922/34910228-82c7af56-f8d2-11e7-8036-980768a5f4fd.jpg)

**Comment by leoneleone** [comment]
@Maxmudjon 
How did you get the speaker to show up in the Home.app? Is the speaker supported by the native app? What version of iOS are you running? 😊

**Comment by leoneleone** [comment]
@pdlove 
Will you be looking at the new iOS 11.3 beta 1 for changes/additions to the HomeKit protocol?
I’m specifically interested in Speaker.Service and any new Services and/or Characteristics regarding HomePod and tv as Devices/Accessories in the Home app, and perhaps how HomeKit handles AirPlay2. 

https://youtu.be/S5aK45slcYY

It appears that once an tv running tvOS 11.3 is assigned to a HomeKit Room, it then becomes an accessory in HomeKit which can be “played” (audio ON/OFF) (Play/Stop). These could be new Characteristics or a utilisation of already existing ones. 

I’m very excited to see how AirPlay2 can be controlled from within the HomeKit ecosystem and the native Home app! 🤓

**Comment by KhaosT** [comment]
Sprinkler and Faucet has been added. Home app's media accessory (HomePod, Apple TV, AirPlay 2 devices) support is not using HomeKit Accessory Protocol, there is simply no services/characteristics you can create to just have your HAP accessory to show up as a "speaker" in Home app. To have Home app recognize a device as a "speaker", you need to implement AirPlay 2 protocol instead of HAP.

The existing `Speaker` and `Microphone` services defined in HAP is only for IP Camera. It has nothing to do with iOS 11's Whole House Audio.

**Comment by pdlove** [comment]
On the Speaker service I'd like to point out that the only change in IOS 11.3 is the inclusion of an "Active" optional characteristic. If you're excited about airplay and what it means for your speakers... look to some of the airplay-specific projects on github. As KhaosT said, Airplay is a totally different thing than HomeKit and Apple is marketing AirPlay 2 as HomeKit compatible only because they're trying to build up the HomeKit ecosystem. I think the reality is that it's only exposed to HomeKit through iCloud. I'm looking to see if there is a cheaper AirPlay 2 device or emulator to play with so I can really understand it. If anyone wants to give me a HomePod then I'd be happy to gut out it's secrets. :)

**Comment by theo-69** [comment]
hi is there a way to show the percentage the valve is open below the icon like `CurrentLevel`
