### ISSUE TITLE
Setting the type of a switch?

### ISSUE THREAD

**Issue by jeffreylanters** [KhaosT/HAP-NodeJS#507]
Hey! The HomeKit app on your iOS device allows you to change the type of an switch to a "switch", "light" or "fan". Is there a way to pre-set this in HAP? Thanks in advance!

![img_4299](https://user-images.githubusercontent.com/3404617/30787563-e2083632-a18b-11e7-902f-b68a4e03f787.jpg)

**Comment by KhaosT** [comment]
Nope

**Comment by jeffreylanters** [comment]
Thanks for your answer. Is this not possible in general, or just not supported by HAP-NodeJS?

**Comment by KhaosT** [comment]
I mean the "associated service type" is a property on home data which only iOS device can control. However, if you are a switch and you already know what kind of thing you're connected to, why don't you just use that service type instead of a generic switch in this case?

**Comment by jeffreylanters** [comment]
I'm going to do that, just have to refactor some code to prevert copying and pasting whole classed. Thank you very much for your help and this package, I absolutely love it! It is controlling more than 30 lights and devices around my house and works perfect! 👍
