### ISSUE TITLE
Error while installing on rPI2

### ISSUE THREAD

**Issue by a-i-ks** [KhaosT/HAP-NodeJS#51]
Hello, 
I get this error when I try to install node-gyp on my rPI2. Hope anyone could help me. 

sudo npm install -g node-gyp
abort: m??$0??0????%:????:??$

==== Stack trace ============================================

Security context: 0x4f334659 <JS Object>#0#
    1: _parse(aka parse) [/usr/local/lib/node_modules/npm/node_modules/tar/lib/extended-header.js:~61] (this=0x39984c45 <an ExtendedHeader>#1#,c=0x3998a4f5 <a Buffer>#2#)
    2: emit [events.js:95] (this=0x39984c45 <an ExtendedHeader>#1#,type=0x56f14839 <String[4]: data>)
    3: arguments adaptor frame: 2->1
    4: _read [/usr/local/lib/node_modules/npm/node_modules/tar/lib/entry.js:111] (this=0x39984c45 <an ExtendedHeader>#1#)
    8: _read [native v8natives.js:1594] (this=0x39984c45 <an ExtendedHeader>#1#)
    9: write [/usr/local/lib/node_modules/npm/node_modules/tar/lib/entry.js:68] (this=0x39984c45 <an ExtendedHeader>#1#,c=0x3998a4f5 <a Buffer>#2#)
   10: _process [/usr/local/lib/node_modules/npm/node_modules/tar/lib/parse.js:105] (this=0x39914d6d <an Extract>#3#,c=0x3998a47d <a Buffer>#4#)
   11: /* anonymous */ [/usr/local/lib/node_modules/npm/node_modules/tar/lib/parse.js:47] (this=0x39914de5 <a BlockStream>#5#,c=0x3998a47d <a Buffer>#4#)
   12: emit [events.js:95] (this=0x39914de5 <a BlockStream>#5#,type=0x56f14839 <String[4]: data>)
   13: arguments adaptor frame: 2->1
   14: _emitChunk [/usr/local/lib/node_modules/npm/node_modules/block-stream/block-stream.js:145] (this=0x39914de5 <a BlockStream>#5#,flush=0x4f308091 <undefined>)
   15: arguments adaptor frame: 0->1
   16: resume [/usr/local/lib/node_modules/npm/node_modules/block-stream/block-stream.js:~55] (this=0x39914de5 <a BlockStream>#5#)
   17: arguments adaptor frame: 1->0
   18: resume [/usr/local/lib/node_modules/npm/node_modules/fstream/lib/reader.js:~251] (this=0x39914d6d <an Extract>#3#,who=0x4f308091 <undefined>)
   19: arguments adaptor frame: 0->1
   20: /* anonymous */ [/usr/local/lib/node_modules/npm/node_modules/tar/lib/extract.js:57] (this=0x39914f6d <a DirWriter>#6#)
   21: emit [events.js:92] (this=0x39914f6d <a DirWriter>#6#,type=0x35efd1a9 <String[5]: ready>)
   22: /* anonymous */ [/usr/local/lib/node_modules/npm/node_modules/fstream/lib/dir-writer.js:39] (this=0x4f334701 <JS Global Object>#7#,er=0x4f308081 <null>)
   23: arguments adaptor frame: 2->1
   24: /* anonymous */ [/usr/local/lib/node_modules/npm/node_modules/mkdirp/index.js:29] (this=0x4f334701 <JS Global Object>#7#,er=0x4f308081 <null>)
   26: oncomplete [fs.js:108] (this=0x3995a521 <an Object>#8#)
   27: arguments adaptor frame: 1->0

==== Details ================================================

[1]: _parse(aka parse) [/usr/local/lib/node_modules/npm/node_modules/tar/lib/extended-header.js:~61] (this=0x39984c45 <an ExtendedHeader>#1#,c=0x3998a4f5 <a Buffer>#2#) {
  // stack-allocated locals
  var i = 260
  var l = 410
  var b = 67
  var val = 0x3998b399 <String[4]: File>
  // expression stack (top to bottom)
  [05] : 0
  [04] : 2086534
--------- s o u r c e   c o d e ---------
function parse(c) {?  if ........
......
.....

**Comment by KhaosT** [comment]
@a-i-ks What's the version of nodejs and npm are you using?

**Comment by a-i-ks** [comment]
I had installed the latest version of nodejs accidentally. Then tried to uninstall nodejs again, by deleting all files of nodejs manually. After that I installed node_0.10.36_armhf.deb.

pi@raspberrypi ~ $ node -v
v0.10.36
pi@raspberrypi ~ $ npm -v
1.4.28

**Comment by KhaosT** [comment]
@a-i-ks you shouldn't need to install the extra node-gyp manually. npm bundled its own copy of node-gyp. Can you try skip that step and just do npm rebuild and see if that works?

**Comment by bjtitus** [comment]
@a-i-ks I found that the pre-built version of node that you installed didn't work for me. Try compiling yourself: http://www.armhf.com/node-js-for-the-beaglebone-black/ but replacing with the 0.10.36 version of Node. That seemed to work fine for me.

**Comment by a-i-ks** [comment]
@KhaosT  I tried to skip the node-gyp installation step and just do npm rebuild. Unfortunately I ran into this error, when I execute "sudo npm rebuild".
pi@raspberrypi ~/HAP-NodeJS $ npm rebuild
 
> curve25519@1.0.0 install /home/pi/HAP-NodeJS/node_modules/curve25519
> node-gyp rebuild
 
gyp ERR! clean error
gyp ERR! stack Error: EACCES, unlink 'build'
gyp ERR! System Linux 3.18.10v7-aufs
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/pi/HAP-NodeJS/node_modules/curve25519
gyp ERR! node -v v0.10.36
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok
 
npm ERR! curve25519@1.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
....http://pastebin.com/sK1J2pxn

@bjtitus Thanks for your suggestion. I compiled the source code of Node 0.10.36 and installed it as described in the instruction. But after I execute the command 'sudo npm rebuild' in the HAP-NodeJS folder I get the same error message (see above).

Thank you for your help.

**Comment by KhaosT** [comment]
@a-i-ks "stack Error: EACCES", are you sure you have write access to that folder?

**Comment by a-i-ks** [comment]
@KhaosT 
when I execute "ls -l" I get the following output for the HAP-NodeJS folder
drwxr-xr-x  5 root root     4096 Apr  6 19:52 HAP-NodeJS
Shouldn't I have write permission in any case, when I execute the command 'sudo npm rebuild' (because of sudo)? KhaosT I can give you SSH remote access to my PI, if it would help to figure out, what's wrong.? It would be so good to have an HomeKit Accessory Server running.

**Comment by KhaosT** [comment]
@a-i-ks you didn't use sudo ... "pi@raspberrypi ~/HAP-NodeJS $ npm rebuild"

**Comment by a-i-ks** [comment]
Ah true. However, I just tried it with sudo. Same issue :(

**Comment by KhaosT** [comment]
@a-i-ks If you are comfortable to email me a temp account, I'll see what I can do.
