### ISSUE TITLE
iOS 8.3 not working. 

### ISSUE THREAD

**Issue by tommyd75** [KhaosT/HAP-NodeJS#52]
Hey guys I've had this working fine for a few months but I upgraded to 8.3 this week and my homekit devices are all greyed out in the iPhone. I tried restarting both iPhone and the server but no dice. 
Is anyone using it with latest iOS update?
Incidentally the iPhone does see the simulator app on my Mac just fine. I can see the devices on my network with bonjour browser so I know they are there. Any suggestions?

**Comment by albeebe** [comment]
I just upgraded to 8.3 and its not working for me.  Whenever I try and add an accessory im getting "Accessory out of compliance"

**Comment by tommyd75** [comment]
I think we will probably have to upgrade something on the server side maybe?

**Comment by KhaosT** [comment]
I guess so, will take a look later tonight :)

Best Wishes,
Tian Zhang

**Comment by KhaosT** [comment]
@tommyd75 @albeebe are you two using a commit at least after 3d2d62eabb2f28ff21e195d3b44120ee2b4108ee? I tried with latest commit and iOS 8.3 and it works for me.

**Comment by albeebe** [comment]
@KhaosT I apologize, i just synched the current code in the repo, and everything is working. My bad.

**Comment by tommyd75** [comment]
@KhaosT I apologize as well, how do I update to the latest build?

**Comment by KhaosT** [comment]
@tommyd75 git pull?
