### ISSUE TITLE
Air quality sensor detailed PM 2.5 data

### ISSUE THREAD

**Issue by roswennen** [KhaosT/HAP-NodeJS#532]
I have an issue when through the nodered homekit node the PM 2.5 value is submitted for AirQualitySensor service.

When submitting PM2_5Density I get an error like the below.  So it looks like something is wrong when the characteristics are checked before written. Something is telling node red the characteristic should be PM2.5 instead of PM2_5 while it should.  Reason for assuming so is when submitting PM2.5 I get the error message "TypeError: Cannot read property 'setValue' of undefined"

Error message I get when submitting PM2_5
Characteristic PM2_5Density cannot be written.
Try one of these: Name, AirQuality, StatusActive, StatusFault, StatusTampered, StatusLowBattery, Name, OzoneDensity, NitrogenDioxideDensity, SulphurDioxideDensity, PM2.5Density, PM10Density, VOCDensity, CarbonMonoxideLevel, CarbonDioxideLevel

**Comment by ebaauw** [comment]
Try `Characteristic[‘PM2.5Density’]`

**Comment by roswennen** [comment]
I did that's when I receive the error "TypeError: Cannot read property 'setValue' of undefined"

**Comment by KhaosT** [comment]
It's `PM2_5Density`, where do you set that message (Characteristic PM2_5Density cannot be written.)?

**Comment by roswennen** [comment]
I do that in the nodered Homekit node
https://github.com/mschm/node-red-contrib-homekit
I submit a json to the node with service AirQualitySensor.  The json has the value {"PM2_5Density":###} with ### the value.  

And when the node is {"PM2_5Density":####} I get the characteristic cannot be written error, when I send  {"PM2.5Density":####} I get the error "TypeError: Cannot read property 'setValue' of undefined"

So get an error either way

**Comment by KhaosT** [comment]
Can you try `PositionState` with node red? I think the developer flipped the write-only logic on the accessory side...

**Comment by roswennen** [comment]
Not sure I understand what you mean with trying PositionState

but when I submit  {"PM10Density":####} and {"CarbonDioxideLevel":####}  for example those work perfect and appear in details of the homekit accessory in the apple app.

**Comment by KhaosT** [comment]
Okay, it's not about logic being flipped but instead the developer is using a different way to construct key which breaks when there is a "_" in the Characteristic. Please let the developer fix that in node-red-contrib-homekit.

**Comment by piejanssens** [comment]
@KhaosT Why would https://github.com/mschm/node-red-contrib-homekit/blob/master/homekit.js#L139 break using "_" in the Characteristic?

**Comment by KhaosT** [comment]
It is "or", `indexOf` will return `-1` when it can't find anything. And the condition checks whether or not the sum of two indexes is larger than -2, so as long as there is either `pr` or `ev`, it should be true.

**Comment by KhaosT** [comment]
The issue here is `var cKey = characteristic.displayName.replace(/ /g, '')`, which replaces space with nothing, and for the generated characteristic, it doesn't match the actual key.

**Comment by piejanssens** [comment]
@KhaosT There is no space in `PM2_5Density`, right? 😛

**Comment by KhaosT** [comment]
He is using "displayName" of characteristic which is "PM 2.5 Density" I believe?

**Comment by piejanssens** [comment]
Thanks for pointing that out! How nasty... 😄  I'll work on a fix.
@roswennen You can close this one, it's purely node-red-contrib-homekit related.

**Comment by roswennen** [comment]
OK, will close this one then.  Thanks

**Comment by piejanssens** [comment]
@KhaosT In some places I see you use Characteristic.Name, but it's not a property of the Characteristic class, is the Name property accessible from the event context?

**Comment by piejanssens** [comment]
@KhaosT My fix patch for node-red-contrib-homekit will replace '.' by '_', but for a more robust solution I suggest you add the actual 'name' in addition to the 'displayName' to the properties of the Characteristic (and the event contexts).

**Comment by slasherLee** [comment]
혹시 사용하시는 측정소가 어디신가요? 제가 pm25를 나오는 측정소를 찾아보려했는데 잘 안나오네요.
