### ISSUE TITLE
Q: HAP Light Brightness behavior

### ISSUE THREAD

**Issue by aboulfad** [KhaosT/HAP-NodeJS#533]
Hello,
setting brightness for a Light_accessory through iOS Home app, generates two characteristic set messages "Brightness" and "On" as seen in log... Is it possible to remove/discard the second characteristic set message "On" which I think is not needed as the brightness value can fully control the accessory. Thank you!

```
  EventedHTTPServer [::ffff:iPhone] HTTP request: /characteristics +2s
  HAPServer [FA:3C:ED:5A:1A:1A] HAP Request: PUT /characteristics +3ms
  Accessory [Office Light] Processing characteristic set: [{"aid":1,"iid":11,"value":0},{"aid":1,"iid":10,"value":0}] +6ms
  >>>>Accessory [Office Light] Setting Characteristic "Brightness" to value 0 +3ms
  EventedHTTPServer [::ffff:appleTV] Sending HTTP event '1.11' with data: {"characteristics":[{"aid":1,"iid":11,"value":0}]} +5ms
  EventedHTTPServer [::ffff:iPhone] Muting event '1.11' notification for this connection since it originated here. +9ms
  >>>>Accessory [Office Light] Setting Characteristic "On" to value 0 +3ms
  EventedHTTPServer [::ffff:appleTV] Sending HTTP event '1.10' with data: {"characteristics":[{"aid":1,"iid":10,"value":false}]} +7ms
  EventedHTTPServer [::ffff:iPhone] Muting event '1.10' notification for this connection since it originated here. +8ms
  EventedHTTPServer [::ffff:iPhone] HTTP Response is finished +5ms
```

**Comment by ebaauw** [comment]
This is a feature of the Home app.  It makes sort of sense, as you cannot change the brightness of a light which is off.  The Philips Hue bridge won’t turn on a light when only setting brightness.

**Comment by aboulfad** [comment]
Thank you for the reply. Understood, i asked because I’ve been having some difficulty to code the MQTT callback event handler to deal with both following actions: 

1. User triggers a brightness action by using the slider (brightness set followed by “ON” set msg)
2. User triggers a light switch action by tapping the icon (“ON” set msg)

When the user initiates  action 1, I need to handle the case where the MQTT callback receives two messages and somehow  ignore the following “ON=1” message else light is fully turned on after being dimmed. The brightness set is always received first followed by the “ON” set.

AND I need to handle the event based on action 2 where the “ON” set message is received. I know this is simple, but it’s like a puzzle and I’ve been agonizing over it for a day.

**Comment by ebaauw** [comment]
You’ll probably need to collect all changes to a single light and combine that into a single request.  See https://github.com/nfarina/homebridge/issues/1455.

**Comment by aboulfad** [comment]
Interesting read, i am a novice to all this,  so queuing all settings events to that single light into a single request would help based on the timer value of 20ms, which assumes that all light settings events happen within that short period of time?

I did use MQTT fx and noticed that the different set messages are within ms or even us of each other so based on that I could also easily check for elapsed time and use that in my logic. Which is faster for my simple mind that digesting your code :)

**Comment by ebaauw** [comment]
> so queuing all settings events to that single light into a single request would help based on the timer value of 20ms, which assumes that all light settings characteristic events happen within that short period of time?

HomeKit (the Home app) actually sends a single message to homebridge containing multiple characteristics (run `DEBUG=* homebridge -D` to see these messages).  The 20ms is just compute time for homebridge, breaking up this message into multiple `set` events, one for each characteristic.

Here's an example log switching on a light (_Living Room 1_) from the Home app.  The lights is connected to deCONZ and exposed to HomeKit by my homebridge-hue plugin:
```
  EventedHTTPServer [::ffff:192.168.xxx.xxx] HTTP request: /characteristics +17s
  HAPServer [CC:22:3D:E3:CE:30] HAP Request: PUT /characteristics +0ms
  Accessory [Homebridge - mbpr] Processing characteristic set: [{"aid":161,"iid":11,"value":45},{"aid":161,"iid":10,"value":1}] +0ms
  Accessory [Homebridge - mbpr] Setting Characteristic "Brightness" to value 45 +0ms
[2017-12-16 12:48:56] [Hue] Living Room 1: homekit brightness changed from 0% to 45%
  EventedHTTPServer [::ffff:192.168.xxx.xxx] Muting event '161.11' notification for this connection since it originated here. +1ms
  Accessory [Homebridge - mbpr] Setting Characteristic "On" to value 1 +0ms
[2017-12-16 12:48:56] [Hue] Living Room 1: homekit power changed from 0 to 1
  EventedHTTPServer [::ffff:192.168.xxx.xxx] Muting event '161.10' notification for this connection since it originated here. +0ms
  EventedHTTPServer [::ffff:192.168.xxx.xxx] HTTP Response is finished +0ms
[2017-12-16 12:48:56] [Hue] pi2: gateway request 14: put /lights/221/state {"bri":114,"on":true}
[2017-12-16 12:48:56] [Hue] Living Room 1: state changed event
[2017-12-16 12:48:56] [Hue] Living Room 1: event: light on changed from false to true
[2017-12-16 12:48:56] [Hue] pi2: gateway request 14: ok
[2017-12-16 12:48:56] [Hue] Living Room 1: state changed event
```
The `aid` (accessory ID) and `iid` (identifier ID) are shortcuts for the accessory, service, and characteristic UUIDs, see `~.homebridge/persist/IdentifierCache.xxxxxxxxxxxx.json` (the `x`s are the MAC address from `bridge.username` in config.json).  Apparently, _Living Room 1_ has `aid` 161.  You see that home issues a single PUT call setting Brightness (`iid` 11) and On (`iid` 10).  homebridge breaks up this request into two `set` events, which homebridge-hue receives separately.  homebridge-hue combines the two events into a single PUT request to deCONZ.  deCONZ sends two notifications back to homebridge-hue, that the state has changed (still on deCONZ's backlog to combine that into a single event).  The first notification actually arrives before the PUT request has returned (the joy of asynchronous processing...).

**Comment by aboulfad** [comment]
Thanks, i got the detailed msgs  from my log above, so either I would have to implement a similar logic as yours where the multiple sets from HAP-node are combined into a single PUT or fiddle around my “cluge” using timing... this is not simple... FYI, you reference Homebridge but I am using HAP-node which Homebridge uses I think, maybe it’s time to switch.

**Comment by aboulfad** [comment]
Ok implemented the time stamp method. Knowing that the different characteristic set messages are being received in the esp code within 10-150ms of each other, I only execute the subsequent set “ON” msg if the time difference > 150ms which assumes no human will tap the light icon within that small time. Very inelegant solution but it works.

The elegant solution is what @ebaauw posted but that will require me time to understand many more things!
