### ISSUE TITLE
Using QR code and the not certified notes in Homebridge

### ISSUE THREAD

**Issue by volschin** [KhaosT/HAP-NodeJS#536]
Using the QR code for pairing homebridge in the Home app every device has the annoying note not being certified and not working properly. With pairing by pin code this does not happen.

Is it possible to generate a QR code that complies in a way to prevent the annoying note?

**Comment by KhaosT** [comment]
Pin code also gives you not certified warning.

**Comment by volschin** [comment]
Thats interesting. My production homebridge does not have this problem. But it has been paired a long time ago.

**Comment by KhaosT** [comment]
If you paired with it before iOS 11 and then upgraded to iOS 11, you won't see those information since HomeKit doesn't know whether or not the accessory is certified and by default HomeKit assume it's certified.
