### ISSUE TITLE
REST component

### ISSUE THREAD

**Issue by trusk89** [KhaosT/HAP-NodeJS#54]
Hello,

I was wondering if you have any plans for implementing a rest module in your project. I don't know if you know about OpenHAB, it's a home automation project, which has an open restful api. 

You can check out a demo installation by doing a get on http://demo.openhab.org:8080/rest/items. 
I like you project a lot, but I have no experience with Node.js, and barely any experience with jscript, otherwise I would have written it myself.

**Comment by KhaosT** [comment]
@trusk89 you may want to check the forks of this project, I believe a few of them support OpenHAB.

**Comment by trusk89** [comment]
@KhaosT I'll do that, thanks!
