### ISSUE TITLE
How to detect if a characteristic is subscribed?

### ISSUE THREAD

**Issue by grover** [KhaosT/HAP-NodeJS#540]
Hi,

I'm using HAP-NodeJS through homebridge and am not sure where to file this issue... Anyways, I'm the author of [homebridge-ranger](https://github.com/grover/homebridge-ranger) - a range extender for HomeKit Bluetooth Accessories.

One of the issues I currently face is that some bluetooth accessories are very chatty if I unconditionally  subscribe all characteristics.  This in turn causes BLE connections to stay open, longer than necessary and in some instances the BLE accessory will not stop with the notifications.

The proper solution would be to know, for each characteristic, when and if a controller has subscribed it on the IP side.

Is there a solution for this today that I couldn't see from the code? Is this something that is desired from a contribution point of view? I can't imagine that I'm the only one that needs this when interfacing with third party devices/services.

Thanks!

**Comment by grover** [comment]
Thanks for merging the pull requests.

Out of curiosity: how is the release process between this and homebridge? Are you taking care of it or do I need to create a separate issue in @nfarina‘s homebridge?

**Comment by KhaosT** [comment]
I already changed dependency version on homebridge.

**Comment by grover** [comment]
Just verified. Homebridge 0.4.35 contains the changes.

Thank you!
