### ISSUE TITLE
setupURI

### ISSUE THREAD

**Issue by n0rt0nthec4t** [KhaosT/HAP-NodeJS#541]
I'm trying to use the setURI function to display the setup barcode when my accessory starts. Have the following code

var awningUUID = uuid.generate('hap-nodejs:accessories:awning_' + FAKE_AWNING.name);
var awningAccessory = exports.accessory = new Accessory(FAKE_AWNING.name, awningUUID);

// Add properties for publishing (in case we're using Core.js and not BridgedCore.js)
awningAccessory.username = FAKE_AWNING.username;
awningAccessory.pincode = FAKE_AWNING.pincode;

// set some basic properties (these values are arbitrary and setting them is optional)
awningAccessory
        .getService(Service.AccessoryInformation)
        .setCharacteristic(Characteristic.Manufacturer, FAKE_AWNING.manufacturer)
        .setCharacteristic(Characteristic.Model, FAKE_AWNING.model)
        .setCharacteristic(Characteristic.SerialNumber, FAKE_AWNING.serialnumber)

//console.log(qrcode.generate('X-HM://001408XXE7G16'));

console.log('%s', awningAccessory.setupURI());

When I run as "node Core.js" I get the following error

HAP-NodeJS starting...
/home/pi/HAP-NodeJS/lib/Accessory.js:369
  var setupCode = parseInt(this._accessoryInfo.pincode.replace(/-/g, ''), 10);
                                               ^

TypeError: Cannot read property 'pincode' of undefined
    at Accessory.setupURI (/home/pi/HAP-NodeJS/lib/Accessory.js:369:48)
    at Object.<anonymous> (/home/pi/HAP-NodeJS/accessories/WindowCovering_accessory.js:76:35)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at /home/pi/HAP-NodeJS/lib/AccessoryLoader.js:33:29

**Comment by KhaosT** [comment]
That function only works after publish

**Comment by n0rt0nthec4t** [comment]
Ah ok.. thanks.. got it work with the following

awningAccessory.publish({username:FAKE_AWNING.username, pincode:FAKE_AWNING.pincode, category:Accessory.Categories.WINDOW_COVERING}, false);
console.log("Setup Code");
qrcode.generate(awningAccessory.setupURI(),{small: true});
