### ISSUE TITLE
Cameracore.js not working

### ISSUE THREAD

**Issue by adityasravya** [KhaosT/HAP-NodeJS#548]
Camercore.js is not responding.
I can find the accessory in my iphone. But when i click on it, raspberry pi console shows that camera not responding. I found that camera is working with other applications. But says cannot find camera in Node.js

**Comment by KhaosT** [comment]
That one is more of an example instead of an actual function thing. You need you implement your own logic on how to provide the video feed.

**Comment by adityasravya** [comment]
Ah! Ok, since i was using all of your code and everything works flawless. I thought this is also the same works out of the box. I will try and let you know if i have any questions. Thanks.
