### ISSUE TITLE
Faucet and sprinkler service(valveType)

### ISSUE THREAD

**Issue by tomdrumdrum** [KhaosT/HAP-NodeJS#552]
was someone able to change the values ​​for valvetype. i want irrigation and i am not able, it always gives me the genericvalve no matter what value i give to the characteristic.valvetype. Other people have succeeded?

**Comment by nicolarampini** [comment]
What service type are you using?

**Comment by tomdrumdrum** [comment]
I am using valve service. I want to control each valve of my irrigation system... So I use valve service... it works but I would have preferred to have the icon of the sprinkler instead of the general valve.. i tried to use irrigation.system service too  but I was not able to turn on and off my valve. ( I am a beginner in writting plugin maybe the problem is on my side) ... thank you

**Comment by nicolarampini** [comment]
I also tried using valve service but i was not able to get it working. Can you please post your code?
