### ISSUE TITLE
Multiple Lights In One Room

### ISSUE THREAD

**Issue by Dageezah** [KhaosT/HAP-NodeJS#56]
I have wall lights and ceiling lights - but when I create two .js accessories files WallLight_accessory.js and CeilingLight_accessory.js the HAP server always turns on the Wall Light no matter what I say. Does anyone know if this is a bug or my stupidity?

**Comment by KhaosT** [comment]
@Dageezah As of iOS 8.3, Siri still doesn't support controlling accessory by its name. Please file a bug with Apple against [HomeKit][Siri]. More details can be found at [here](https://github.com/KhaosT/HAP-NodeJS/issues/15).
