### ISSUE TITLE
expose way to use HeatingCoolingState for single-mode systems

### ISSUE THREAD

**Issue by chrisjshull** [KhaosT/HAP-NodeJS#560]
e.g. away to have a heater-only with temperature settings (where Home won't show auto or cooling modes)

**Comment by KhaosT** [comment]
Create a TargetHeatingCoolingState characteristic and call `characteristic.setProps({validValues: [Characteristic.TargetHeatingCoolingState.OFF, Characteristic.TargetHeatingCoolingState.HEAT]})`

**Comment by chrisjshull** [comment]
oh, cool!

**Comment by n0rt0nthec4t** [comment]
Look back at this old issue, wonder if there is a dynamic way to perform this and have it reflected in HomeKit ie: can make the mode settings for a thermostat change
