### ISSUE TITLE
Library for new types for HomeKit.

### ISSUE THREAD

**Issue by sprut666666** [KhaosT/HAP-NodeJS#564]
Hello dear developer community. Let's clean up the new types of Apple HomeKit. While Apple has forgotten about our needs, everyone adds their services and characteristics as he wants. At the same time, in every project or even a Apple HomeKit-Ready device - completely different data types and storage locations can be used - for the same kinds of data. As a result, it can not be controlled. Please let's stick to a single standard until Apple remembers us.
Please add a link to the [new-types-for-homekit](https://github.com/sprut666666/new-types-for-homekit) in the readme.
Now I have created an application using exclusive types for Apple TV in plans to develop it and add support for ipad and iphone. [HomeCenter for HomeKit](https://itunes.apple.com/ru/app/homecenter-for-homekit/id1329662539?mt=8)
![1](https://user-images.githubusercontent.com/24498195/37143224-8ff53018-22cb-11e8-9caa-7235b62f4d81.jpg)

**Comment by Maxwell70** [comment]
Super idea!!!!

**Comment by Sapadi** [comment]
👍 +1

**Comment by justme-1968** [comment]
please take these: https://gist.github.com/gomfunkel/b1a046d729757120907c into account to avoid duplicates and have at least some app compatibility.

also here: https://github.com/ebaauw/homebridge-hue/wiki/Characteristics are some more characteristics documented.

**Comment by sprut666666** [comment]
@justme-1968 thanks,
I initially wanted to use the current developments, but I realized that this is pointless.
If you study the use of eve in plug-ins you will see different keys for different types of data + there is no official documentation on this issue, moreover koogeek uses its service and characteristics to store PowerMeter - not compatible with eve. And so do all the manufacturers HomeKit
Look at how many changes there were in trying to guess... https://gist.github.com/gomfunkel/b1a046d729757120907c/revisions

I was also afraid of duplicating the keys - that's why we chose this way.
The principles of Apple were taken as the basis of the library.
**XXXXXXXX-0000-1000-8000-0026BB765291 - Standard apple key for services and characteristics**

We use
**XXXXXXXX-0000-2000-8000-0026BB765291 - For services**
**XXXXXXXX-000C-2000-8000-0026BB765291 - For characteristics**

Let's develop and expand this library.

I want to make a common standard for new types for Homekit and provide its support in the application, and make the best application for iOS)))

**Comment by permadm** [comment]
Perfecto

**Comment by justme-1968** [comment]
yes. the existing characteristics in eve are not documented and for the more complicated ones like the history are very hard to use.

but the simple ones like Voltage or Power should be reused instead of creating new ones.

eve can handle these even if they are in a different service class. that is what your app should also do.

and i don't see why the PowerMeter Voltage is different from the eve Voltage and why you can't reuse them.

**Comment by Anzic23** [comment]
👍

**Comment by KhaosT** [comment]
Feel free to submit a PR and I can merge it.

**Comment by sprut666666** [comment]
@justme-1968 app support eve & new lib new-types-for-homekit
I've been thinking about this for a long time, but there are a lot of manufacturers and everyone has their own keys =( https://homekitty.world/explore?category=Outlets
Why not use https://www.koogeek.com by default ? Or any other ?
@KhaosT Thanks )

**Comment by simont77** [comment]
Eve is recognized as one of the best free HomeKit app, able also to deal with any unsupported accessory. Many plugins already emulate Eve’s services and characteristics. Honestly, I’ve never heard of homegeek. I agree with @justme-1968 that compatibility with Eve should be kept.

**Comment by sprut666666** [comment]
@simont77 Cheap HomeKit device https://koogeek.ru.aliexpress.com/store/2930044
Watt - float https://github.com/simont77/fakegato-history/wiki/Services-and-characteristics-for-Elgato-Eve-devices
Watt - UInt16 https://gist.github.com/gomfunkel/b1a046d729757120907c
I saw more Watt - UInt32

airpressure
const ATMOSPHERIC_PRESSURE_STYPE_ID = "B77831FD-D66A-46A4-B66D-FD7EE8DFE3CE"; - google not found
const ATMOSPHERIC_PRESSURE_CTYPE_ID = "E863F10F-079E-48FF-8F27-9C2605A29F52"; - eve
https://github.com/planetk/homebridge-netatmo/blob/master/service/weatherstation-airpressure-legacy.js

This is all very very bad =( 

Initially I thought I would rely on elgato, but I could not. I'll think about how it will be possible to combine ....

**Comment by ebaauw** [comment]
I agree with @simont77 and @justme-1968 that compatibility with the Eve app is a must.  I find they don't just support custom services and characteristics defined by Elgato themselves, but also defined by other manufacturers, see also #223.  Eve seems very forgiving in the data types used: INTxx, UINTxx, or FLOAT.

> This is all very very bad =(

@sprut666666, Please explain why adding yet another type isn't?

**Comment by simont77** [comment]
> Cheap HomeKit device https://koogeek.ru.aliexpress.com/store/2930044
I thought you were speaking of a software. As a plugin developer I would like to have my services and characteristics to be recognized by an app, and as I said, if we really have to choose a standard for hap-nodejs (have we?), I would go for Eve: it is a very good application, it’s free, support not only Elgato custom UUID, but also other vendor’s and even some from homebridge community. I understand that others may prefer another app, and so I’m not sure hap-nodejs should stick with anyone other than the Apple standard one, buy why should I ever use an UUID that no app recognizes?

**Comment by mrose17** [comment]
you'll also find a bunch of things defined here: https://github.com/homespun/HAP-NodeJS

**Comment by justme-1968** [comment]
eve is currently one arguably the best and most flexible app. if your aim is to be better than eve the first step ist to be at least as good as eve. that means support everything that eve does and then some.

if there is more than one standard, the correct way of handling this is to support all of them or at least the most common one(s). but not to invent another.

a good app will handle a characteristic regardless of the datatype. that is one of the great things about homekit. you can have one and the same characteristic and depending on your device you can use different datatypes and ranges.

i have written the fhem-homebridge plugin and it uses the apple and eve characteristics by default but there is not a single characteristic or datatype hardcoded. it is completely configurable, uses introspection to use new characteristics and allows changing the datatype if needed and even create a custom characteristic on the fly. if you really want to create the best app you have to support at least this flexibility. eve can handle all this.

**Comment by pdlove** [comment]
My biggest problem with eve is the lack of decent presentation for the built-in HomeKit services. It's the biggest problem with the entire HomeKit platform.
That said, I don't know the best way to handle this. Ultimately it sounds like what everyone is talking about here is a way to map the built-in HomeKit types to the Eve-specific types or vice versa. The issue becomes that you only want to present them in the format the specific app expects because the display does strange things with unknown services depending on which app you are using.

**Comment by mrose17** [comment]
@pdlove - that's rather odd! my view of the eve app is that it does the *best* job of handling the built-in homekit services. that's one of the reasons that i like it so much!
