### ISSUE TITLE
Bug or by design? CoolingThresholdTemperature / HeatingThresholdTemperature  .on('set', ...) event issue

### ISSUE THREAD

**Issue by jvmahon** [KhaosT/HAP-NodeJS#568]
I'm trying to use the CoolingThresholdTemperature / HeatingThresholdTemperature characteristics to support "Auto" mode in a thermostat plugin.  I'm having an issue with generated events.

Both of these characteristics generate a .on('change', ....) event when the Home app. is used to alter the thresholds, but neither generates an   .on('set', ...) event.  Is this by design?  I would have expected the 'set' event to also be generated when changes are made on the Home app.

However, the .on('set' ...) event does seem to generate if you use .setValue directly on the Characteristic. This seems an odd inconsistency between TargetTemperature (which generstes .on('set' ...) events when you adjust the temperature slider on the Home app, and these related thresholds which don't generate 'set' when you adjust the slider on the Home app.

As a practical matter, I can probably just use the 'change' event for what I need, but this had me stuck for quite a while figuring out what was wrong and I was hoping to understand (i) is this a bug?, (ii) is it by design; or (iii) did I just do something wrong and  others have been able to use these characteristic with .on('set' ...).

#

**Comment by KhaosT** [comment]
You should get a `set` event on characteristic. Can you post your code here?

**Comment by jvmahon** [comment]
In the "this is odd" category, took the code from my homebridge project, refashioned it into a simpler Accessory that could run with node Core, and its now generating the 'set' event as I would have expected. This suggest the problem is somewhere within my code. I'm going to close this comment for now while I try some more debugging on my own. I'll re-open again if I think  a problem remains. Thanks.
