### ISSUE TITLE
Reading the Current Device Name?

### ISSUE THREAD

**Issue by jvmahon** [KhaosT/HAP-NodeJS#573]
I can't figure out which characteristic is used to read the current name of a device - i.e., the name after the user changes it at the iOS device. 
 
I was guessing it would be the Service.AccessoryInformation variable and using getCharacteristic(Characteristic.Name).value to read the Name, but that doesn't seem to be it.  Any ideas?

**Comment by ebaauw** [comment]
Afaik that name is available over the HomeKit (app) API, not over HAP.

**Comment by n0rt0nthec4t** [comment]
Wondering if this is similar to what I'm trying to get. If the user changes the "service name" in Home, can you get "on change" event to get this new name?

**Comment by jvmahon** [comment]
@n0rt0nthec4t - From everything I could determine, you do not get notice of a changed name with the 'on change" event (in fact, I couldn't find any mechanism to get it through hap-nodejs).

**Comment by n0rt0nthec4t** [comment]
ah bugger :-(
