### ISSUE TITLE
Embedded binary's bundle identifier is not prefixed with the parent app's bundle identifier.

### ISSUE THREAD

**Issue by suhajdab** [KhaosT/HAP-NodeJS#58]
The wiki does not mention changing the embedded bundle identifier and I couldn't figure out how to do so.

Embedded Binary Bundle Identifier:	org.oltica.HomeKitDemo.watchkitextension
Parent App Bundle Identifier:		com.mycompany.HomeKitDemo

**Comment by suhajdab** [comment]
Found a tip about changing the BundleID in the extension's info.plist to what I needed, but still get the same error.

**Comment by KhaosT** [comment]
Please make sure you change all three targets' Bundle Identifier to match the same prefix.
![screen shot 2015-04-27 at 8 52 23 am](https://cloud.githubusercontent.com/assets/1725664/7351564/c26b92a2-ecba-11e4-8c5e-35900c8bd572.png)

**Comment by suhajdab** [comment]
A find and replace did the trick.
