### ISSUE TITLE
Difference between the "active" and "on" characteristics

### ISSUE THREAD

**Issue by Wertok07** [KhaosT/HAP-NodeJS#581]
Hello,

What is the difference between the "active" and "on" characteristics?
I understand that "on" determines whether the device state "0" and "1" and can be controlled from the level of the app on the device, and "activ" does the same but it is impossible to change the state from the device level?

**Comment by pdlove** [comment]
Active is something that's pushed from the device to indicate detection of something or that it is in motion.
On is a toggle able item where you can tell a device it is on or it can say it is.
For example... I have a power outlet. I can turn it on or off but it only shows active it it has current flowing through it... so active is somewhat independent of on/off.
In short... switches use on and sensor use active.

**Comment by jvmahon** [comment]
@Wertok07. This thread may be of help to you. https://github.com/nfarina/homebridge/issues/1707 which explains some implementation work I did for valves and explains a bit about the Active and InUse (as well as SetDuration and RemainingDuration).
