### ISSUE TITLE
Agnostic button, how to ?

### ISSUE THREAD

**Issue by leRenart** [KhaosT/HAP-NodeJS#587]
Hi, I'm playing with `node-red` + `node-red-contrib-homekit-bridged` with great fun, so first of all I want to thank you for this beautiful project.

I've read about the differences between `switch` and `statelessProgrammableSwitch` but none of them works in my case, I suppose I'm missing something because my need is very basic. 

I have some remote controlled outlets with two remotes. I would like to use one of them with Siri, telling to turn ON/OFF the lights. 

![img_2321](https://user-images.githubusercontent.com/1085151/40372490-17c0cc24-5de5-11e8-9ade-b3a828002fd9.jpg)

I would like HomeKit to be absolutely agnostic about the light states. 

As you can see remotes are two, so even if the lightbulb or switch state are `ON` inside HomeKit, that could be false (someone could have triggered the other switch). And beside it, the fact to be, for instance `ON` in HomeKit means that a switch can't be turned `ON` again without turning it `Off` before, HomeKit won't let you do it. 

`statelessProgrammableSwitch` could have been the solution, but: 
     1. it needs a Hub 
    2. it changes the states of `switch`es, which brings me back to the first problem, the `switch` state isn't stateless. 

Any ideas ?

**Comment by ebaauw** [comment]
You need to decide what you want expose to HomeKit:
1. the stateful outlets (as Outlet or Lightbulb); or
2. the stateless remote switches (as Stateless Programmable Switch).

With 1 you could tell Siri to switch on the lights, with 2, you could use the remotes to control HomeKit accessories, if you have a HomeKit hub.

In both cases, you’d need some hardware that talks the same protocol as the remotes and outlets, and you’d need a homebridge plugin that transalates this protocol to HomeKit.

**Comment by leRenart** [comment]
Thanks @ebaauw, I think I need something like a [push button](https://github.com/KhaosT/HAP-NodeJS/issues/134#issuecomment-141088986). I need to better grasp on how it works, I'm able to setup one in node-red and to show it into my hub (iPad) but then I'm stuck. A switch state can be modified in HomeKit app (ON/Off), a SPS can't (or, I'm unable to). Any example is appreciated.

**Comment by ebaauw** [comment]
A push button (stateless programmable switch) is an input-only device, just like the physical remote.  It’s used to control _other_ HomeKit devices, it cannot be controlled itself from HomeKit (nor by Siri).

If you want to provide a _virtual_ push button to a HomeKit app, you’d need to create a write-only custom characteristic, like _Identify_.  Unfortunately, neither Apple’s Home app nor Siri support custom characteristics.  The only thing you can do is create a regular _Switch_ service, and automatically reset the _On_ chacteristic to false, say 500ms after it’s been pressed.

**Comment by leRenart** [comment]
> The only thing you can do is create a regular Switch service, and automatically reset the On chacteristic to false, say 500ms after it’s been pressed.

Unfortunately that doesn't solve the problem, defining it back to Off means that I can only turn it on, which is not what I want as I could turn the same switch off (for instance) multiple times in a row. 

Thanks for the SPS explanation, it makes sense now.

**Comment by NorthernMan54** [comment]
Just to add a bit more to this, Siri doesn’t check the switch state before sending a command, so you can ask Siri to turn on a lamp this is already on etc.

**Comment by ebaauw** [comment]
> Unfortunately that doesn't solve the problem, defining it back to Off means that I can only turn it on, which is not what I want as I could turn the same switch off (for instance) multiple times in a row.

You’d create two of these: one for On and one for Off.

**Comment by leRenart** [comment]
One year and a half later I've found an easy way to use both remote control and HomeKit, I've published a repository with some [instructions](https://gitlab.com/daniele.tabanella/rcswitch-to-homekit).

**Comment by Shaquu** [comment]
@leRenart maybe you could do it with latest node-red-contrib-homekit-bridged?
I would suggest it if you are using node-red anyway.

**Comment by leRenart** [comment]
@Shaquu yeah I'm using it, maybe not the latest version, I'll take a look and update the doc
