### ISSUE TITLE
Can't see accessories from RPi2

### ISSUE THREAD

**Issue by edc1591** [KhaosT/HAP-NodeJS#59]
Whenever I start the server on my Raspberry Pi 2, I can't see the accessories on my iPhone. I checked with iNet and the bonjour services are being advertised. When I run the app from my Mac everything works fine.

This is the output when I run it on the RPi:

	TCP server accepting connection on port: 51882
	HAP Server is listening
	New Session 54272
	Server Connection Established 39805
	Start Verify M1
	Verify M1 Finished
	New Session 54273
	New Session 54274
	New Session 54275
	Server Connection Established 57741
	Server Connection Established 57283
	New Session 54277
	New Session 54276
	Start Verify M1
	Verify M1 Finished
	Server Connection Established 33816
	Start Verify M1
	Verify M1 Finished
	Server Connection Established 46079
	Server Connection Established 38845
	Start Verify M1
	Verify M1 Finished
	Client Disconnected
	Start Verify M1
	Verify M1 Finished
	Start Verify M1
	Verify M1 Finished
	Client Disconnected
	Client Disconnected
	Client Disconnected
	Server Disconnected
	Server Disconnected
	Server Disconnected
	Server Disconnected
	Client Disconnected
	Client Disconnected
	Server Disconnected
	Server Disconnected
	New Session 54271
	Server Connection Established 58561
	Start Verify M1
	Verify M1 Finished
	Client Disconnected
	Server Disconnected

**Comment by KhaosT** [comment]
@edc1591 are you using the latest commit from repo on your RPi2 ?

**Comment by edc1591** [comment]
Yes, I'm up to date with master.

**Comment by KhaosT** [comment]
Can you try to remove ./persist on RPi2 and reset HomeKit database on iOS and see if that works? From the log it seems pair verify failed.

**Comment by edc1591** [comment]
Oh cool, that seems to have fixed it. What exactly went wrong? What caused this to happen?

**Comment by KhaosT** [comment]
HomeKit uses Accessory ID to distinguish accessories. I assume that you used same ID on both RPi and Mac but only Mac has the valid pairing information... So when HomeKit on iOS found the accessory published on RPi, it will think it's the same accessory as on Mac so instead of asking you pair a new accessory, it will try to connect using shared key from Mac ...

**Comment by edc1591** [comment]
Ah, that makes sense. Thanks for the quick reply!
