### ISSUE TITLE
BTLE support?

### ISSUE THREAD

**Issue by lukehoersten** [KhaosT/HAP-NodeJS#608]
Is it possible to use BTLE instead of WiFi with HAP-Nodejs? Is this even something at the level of this project or at another level? I’m using a Rpi-zw.

**Comment by AMoo-Miki** [comment]
In your code, you can make connection to your device in any way you want and that your device supports. You use HAP-NodeJS in your code to connect to Homekit.

For example, in [Lock_accessory.js](https://github.com/KhaosT/HAP-NodeJS/blob/master/accessories/Lock_accessory.js), lines 7 to 20 are how it communicates with the FAKE_LOCK; you change that piece to connect to your actual device using BLE.

**Comment by lukehoersten** [comment]
HomeKit has its own specific use of BLE and accessing the BLE device directly would still require IP for HK integration. I don’t think the HK BTE is currently supported by this package.

**Comment by lukehoersten** [comment]
In the case you described, you are using HAP over IP then connecting to another device via BTE. This is not what I’m taking about. HAP supports BTE and IP. HAP-NodeJS only supports HAP IP. Take a look at the HAP documentation for BTE.

**Comment by AMoo-Miki** [comment]
Thanks for explaining. It was my fault to assume everyone wants to use HomeKit the way I do, which is access stuff while not at home. I clearly see how valuable directly interfacing BLE with HAP could be.
