### ISSUE TITLE
Controll an A/C using IR with ESP-8266

### ISSUE THREAD

**Issue by ShonP40** [KhaosT/HAP-NodeJS#610]
Hi, I currently have an IR LED hooked up to my ESP so I can control my A/C. I am using the library IRremoteESP8266 and I can turn on or off my A/C with a URL.

How can I add this ESP to Apple HomeKit with HAP-NodeJS to controll my A/C from the Home app instead of Opening the internet?

**Comment by ShonP40** [comment]
Is there a way that the Home app will see my ESP as an Air conditioner and when I press the on button in the Home app it will open one link (http://(ESP IP address)/(On code)) and when I press the off button in the Home app it will open another link (http://(ESP IP address)/(Off code))?

**Comment by NorthernMan54** [comment]
If you look at the homebridge plugins, there are a couple of options available for controlling devices via http.  For example https://github.com/rudders/homebridge-http 

For my personal use, I wrote this plugin which uses an esp8266 based IR Blaster  https://github.com/NorthernMan54/homebridge-HTTP-IRBlaster <https://github.com/NorthernMan54/homebridge-HTTP-IRBlaster>, and it features the ability to control volume/brightness as well as on/off.

**Comment by sszczep** [comment]
You can also use one of many node packages like require/axios/superagent and send HTTP request to esp. You don’t need homebridge to do that

> Wiadomość napisana przez Northern Man <notifications@github.com> w dniu 27.09.2018, o godz. 00:44:
> 
> If you look at the homebridge plugins, there are a couple of options available for controlling devices via http. For example https://github.com/rudders/homebridge-http 
> 
> For my personal use, I wrote this plugin which uses an esp8266 based IR Blaster https://github.com/NorthernMan54/homebridge-HTTP-IRBlaster <https://github.com/NorthernMan54/homebridge-HTTP-IRBlaster>, and it features the ability to control volume/brightness as well as on/off.
> 
>

**Comment by ShonP40** [comment]
Are those plugins work with HAP-NodeJS?

**Comment by sszczep** [comment]
They work with every node app

**Comment by ShonP40** [comment]
Ok, I will try it

**Comment by ShonP40** [comment]
Can someone create a script for me that will open an URL when I click “On” or “Off” in the Home app? Please?

(Example: When I click “On” On The Home app the script will open this URL: http://(IP)/(On code), and when I click “Off” On The Home app the script will open this URL: http://(IP)/(Off Code))

**Comment by sszczep** [comment]
Listen on state change and then send post request using libraries mentioned
earlier. It's really not that hard and you should be able to do it

pt., 28 wrz 2018 o 18:37 Shon Pogorelis <notifications@github.com>
napisał(a):

**Comment by ShonP40** [comment]
But I am not a coder.

**Comment by ShonP40** [comment]
But can homebridge work alongside HAP-NodeJS?

**Comment by sszczep** [comment]
Homebridge is built on top of it

**Comment by ShonP40** [comment]
For some reason I couldn’t get homebride to install. It always gave me an error.

**Comment by sszczep** [comment]
I modified outlet accessory code for you. 
[AC_accessory.js](https://pastebin.com/szEpsNiX)

1. Save it for example as AC_accessory.js.
2. Be sure to install axios first (type in terminal):
`npm i -g axios`
3. Change esp ip address in line 55, you want it to look like:
` axios.post(`http://192.168.0.100/${ value ? "ON" : "OFF"}`)...`

I haven't tested code, no way I can do it now. It should work. Write here if you encounter any problems.

**Comment by ShonP40** [comment]
Thank you very much. I will try it soon

**Comment by ShonP40** [comment]
Thank you very much, Its working.
