### ISSUE TITLE
Some accessories are not supported

### ISSUE THREAD

**Issue by songzh96** [KhaosT/HAP-NodeJS#616]
Devices：Ipod touch.
APP: Home 
IOS Version：12.0.1
Today when I was programming, I found that some accessories were added later.
I found that some accessories are not supported on the Home APP.
Like Speaker,FilterMaintenance,DoorBell and StatelessProgrammableSwitch .

respect

**Comment by ebaauw** [comment]
This has nothing to do with HAP-NodeKS - it's a limitation of Apple's Home app.  You might want to try another HomeKit app, like Eve.

Apple's Home app only supports the `Speaker` and `DoorBell` services in a Video DoorBell accessory.

Apple's Home app does support the `StatelessProgrammableSwitch` service, but you need to expose an accessory with a single `LabelNamespace` service, and a `StatelessProgrammableSwitch` service per button.

**Comment by songzh96** [comment]
> This has nothing to do with HAP-NodeJS - it's a limitation of Apple's Home app. You might want to try another HomeKit app, like Eve.
> 
> Apple's Home app only supports the `Speaker` and `DoorBell` services in a Video DoorBell accessory.
> 
> Apple's Home app does support the `StatelessProgrammableSwitch` service, but you need to expose an accessory with a single `LabelNamespace` service, and a `StatelessProgrammableSwitch` service per button.

thank you，I will try it tomorrow.

**Comment by songzh96** [comment]
> `Speaker`

Today，I Found new Problem。
I use homebridge plugin homebridge-knx，All Accessories is can use。
but when i use homebridge-creskit，I added some accessories myself.Then I found that some home apps don't support some accessories.This is very strange
I suspect that the source file has been modified.But I can't find the location of the source file
I have been using HAP-NodeJS/lib/gen/HomeKitTypes.js To increase the accessories I need
What do you think is causing my family app not to support some accessories?

respect



My Code header
/*
https://github.com/nfarina/homebridge-legacy-plugins/blob/master/platforms/HomeSeer.js used for reference.
*/

'use strict';

var async = require('async');
var request = require("request");
var net = require('net');
var events = require('events');
var Service, Characteristic;

module.exports = function(homebridge) {
    Service = homebridge.hap.Service;
    Characteristic = homebridge.hap.Characteristic;
    homebridge.registerPlatform("homebridge-creskit", "CresKit", CresKit);
}

**Comment by songzh96** [comment]
Sorry, I found it was my spelling mistake.

respect
