### ISSUE TITLE
Raspberry Pi Garage Door Opener

### ISSUE THREAD

**Issue by legotheboss** [KhaosT/HAP-NodeJS#62]
I have made a Raspberry Pi garage opener system with this: http://www.driscocity.com/idiots-guide-to-a-raspberry-pi-garage-door-opener/. I am extremely confused how I can implement this with HAP on the existing Raspberry Pi.

**Comment by KhaosT** [comment]
@legotheboss You can modify https://github.com/KhaosT/HAP-NodeJS/blob/master/accessories/GarageDoorOpener_accessory.js#L91 and use GPIO write to physically change state of the garage door.
