### ISSUE TITLE
Create contact sensor accessory, not a door accessory

### ISSUE THREAD

**Issue by p3ntium** [KhaosT/HAP-NodeJS#624]
Hi all:
Actually, I have it configured like a door accessory, and the icon show a door, including the target state, etc
I want to create an accessory for my door as contact sensor, only to inform if the door is open or close, and showing the icon as the contact sensor, not the door icon. You can shows the example contacts icons here:
https://i.redd.it/zfrsog1k44l11.jpg

Someone has an example for this accessory type? If I use the Door service the icon always shows the complete door, not the contact sensor only.

Regards!
Fran

**Comment by ebaauw** [comment]
Afaik, you can only change this through the HomeKit API, not through HAP.  In Apple's Home app, hold the tile, choose _Settings_, and change the _Type_ (under the _Room_).

**Comment by p3ntium** [comment]
Hello:
the door element has only one icon on the Home app, and I can't change it. I think it changes by involving the Contact Sensor service, but I've pending to check....

**Comment by ebaauw** [comment]
What service are you currently exposing?  You need to expose a _Contact Sensor_ service.  Then you can change the icon in Home, between Door, Window, Garage Door Opener, Blinds, and Contact Sensor.

**Comment by p3ntium** [comment]
Ciao:
I was using the Door service. Now I changed it to a service Contact Sensor and I can change the icon to the correct one.
Thanks!
Fran
