### ISSUE TITLE
A bug of thermostat

### ISSUE THREAD

**Issue by songzh96** [KhaosT/HAP-NodeJS#628]
Hi everyone,there is my problem
When I said to siri “turn off the thermostat”,
it will switch to auto mode.

The Voice control will send 3 to TargetHeatingCoolingState。

**Comment by n0rt0nthec4t** [comment]
Have have the same issue with a project developed also. Just did a "work around" for it, but not idle.

**Comment by Fonger** [comment]
I had the same problem. This is actually a bug in Chinese Siri. If you say thermostat 「空調」 instead of 「冷氣」, it will turn off successfully.

To address this without workaround, just use newer HeaterCooler service which is introduced in iOS 11 to replace old Thermostat service.

**Comment by songzh96** [comment]
Hi @Fonger 
Thank you for your answer.I will try it.

Best Regrads
songzh
