### ISSUE TITLE
eventEnabled chararcteristics property

### ISSUE THREAD

**Issue by snowdd1** [KhaosT/HAP-NodeJS#63]
Hi KhaosT, I had a look at what comes from the iPhone app I use for testing when switching a light. The data object looks like _{"characteristics":[{"aid":1,"iid":9,"value":true}]}_  , there is no "ev":true even though the app is event-aware. Is this different with your app? I experimentally forced eventEnabled to true and it worked with this app (myTouchHome) - as I am no iOS developer etc. I am bound to available software from the store...

**Comment by KhaosT** [comment]
@snowdd1 writing characteristic won't have "ev" flag being set in message. I guess the app doesn't send enable notification command to HomeKit ?

**Comment by snowdd1** [comment]
Thanks.
When would we expect an ev flagged message? on registering a new device with a homekit app in homekit? I probably changed the "supportsEvents" option in the characteristics later. I don't have access to the app's source, I have bought it from the appsore

**Comment by KhaosT** [comment]
When developer calls -[HMCharacteristic enableNotification:completionHandler:]
