### ISSUE TITLE
Other Airquailtysensor service?

### ISSUE THREAD

**Issue by madcat-nl** [KhaosT/HAP-NodeJS#635]
Hi i have created an air quality sensor that exposes the airquality based on the AirQualitySensor type.
But because i was receiving some strange data i also bought the elgato room v2
That one exposes the air quality based on stars instead of the Characteristic.AirQuality in their app, in the homekit app it all looks the same. 

I was wondering what kind of service or characteristics it is using, does anybody know?
Is it an undocumented service/characteristic.

**Comment by ebaauw** [comment]
See https://github.com/simont77/fakegato-history/wiki/Services-and-characteristics-for-Elgato-Eve-devices.
 Not sure if the v2 Eve Room is the same, though.

**Comment by madcat-nl** [comment]
Ah thanks,so elgato has created their own standard :)
