### ISSUE TITLE
Magnetic Sensor Readout

### ISSUE THREAD

**Issue by legotheboss** [KhaosT/HAP-NodeJS#64]
I have a Raspberry Pi with HAP and use it as a Garage Door Opener. How can I use the magnetic door sensor readout to tell the garage door status? GPIO is not working on my HAP setup and I'm relying on a python script to open the garage.

**Comment by KhaosT** [comment]
@legotheboss You need to rewrite Core.js in that case. See https://github.com/KhaosT/HAP-NodeJS/blob/master/Thermostat_Logical.js for example.

**Comment by snowdd1** [comment]
@legotheboss You can also use the code from my experimental branch in my fork https://github.com/snowdd1/HAP-NodeJS-KNX/tree/experimental . The files characteristics.js and a sample GarageDoorOpener_accessory.js are modified to include a callback for an onRead triggering if Siri asks for a status.

**Comment by Kosta-Github** [comment]
@KhaosT can you pull in the changes/enhancements from @snowdd1? That would be really helpful!

**Comment by snowdd1** [comment]
@Kosta-Github in JavaScript you would usually make your accessories provide their own "events". And you can already register characteristics with events using the onRegister callback property. Doing that, the status is updated whenever your device event fires, and not only if Siri asks for a status. That means that home apps can display a proper status all the time, and you don't need to trigger an update from the homekit app or from Siri. 
You can find examples in my master branch. My KNX implementation makes use of such events. There the events are handled by the busMonitor. On startup, all KNX accessories register themselves with the busMonitor and get their status updated when their KNX addresses are updated over the bus.
In @legotheboss 's case you would need a small event handler that reads the door regularly and calls the registered callback of the accessory on status changes. 
The onRegister callbacks are already pushed to @khaosT 's master.

**Comment by legotheboss** [comment]
@KhaosT what are the min and max values in the garage opener accessory current state? It says min is 1 and max is 4, which value is open and which value is closed? I want to use the new onRead function...

**Comment by KhaosT** [comment]
Check HomeKit simulator for that.

**Comment by legotheboss** [comment]
@KhaosT I now have figured that out, how do I return the value on the Node.JS? do i just use return (value like 1,2,3,4) or is there another way?

**Comment by KhaosT** [comment]
yep, just return the value

**Comment by legotheboss** [comment]
@KhaosT @snowdd1 I have used the onRead but it does not really help. I tried changing the initial value through both onRead and onUpdate, but was unable to change the initial value

**Comment by snowdd1** [comment]
You are not supposed to updat the initial value. Just return a current value in the onRead inline function where the example garage door opener returns "nothing". The characteristics.js takes care of updating the current value within the object.

**Comment by snowdd1** [comment]
Sorry, I meant "undefined" not "nothing" in the return statement. 
Wrong language...

**Comment by legotheboss** [comment]
@snowdd1 

    cType: types.CURRENT_DOOR_STATE_CTYPE,
        onUpdate: function(value) {
                console.log("Change:",value);
                execute("Garage Door - current door state", "Current State", value);
        },
        onRead: function() {
                console.log("Read:");
                execute("Garage Door - current door state", "Current State", null);
                gpio.open(12, "input", function(err) {     
                    gpio.read(12, function(err, value) {         
                        return 1-value;
                        gpio.close(12);                     // Close pin 16
                    });
                });
                return 4;
        },


Here's my current code. I added the return 4 to show atleast get a different status. The only status that s being returned is only the initial value... What is the issue?
