### ISSUE TITLE
HomeKit TV - Beta 3

### ISSUE THREAD

**Issue by SeydX** [KhaosT/HAP-NodeJS#645]
I have noticed that the volume setting in the AppleTV interface is not working anymore in the last iOS beta version

Has apple changed something there?

**Comment by ebaauw** [comment]
I find sometimes it's sometimes working and sometimes not.

**Comment by ebaauw** [comment]
If you switch the widget to your AppleTV and then back to the _Television_ service, the volume works.

**Comment by nicoduj** [comment]
@ebaauw : Thanks for the tip on the volume issue in beta 3 , it works 👍  !

**Comment by nicoduj** [comment]
Seems to be fixed in beta4 !
