### ISSUE TITLE
Beta 3 - TV Mode - BACK button not working anymore

### ISSUE THREAD

**Issue by nicoduj** [KhaosT/HAP-NodeJS#646]
Hi, 
In beta 3, the big new back button doesn't work anymore, they might have change the enum I think 

https://github.com/nicoduj/homebridge-harmony/issues/71

**Comment by ebaauw** [comment]
Indeed, _Back_ doesn't seem to be registered and I think the _i_ key has changed: it now sends _Exit_.

**Comment by nicoduj** [comment]
Thank you @ebaauw ! I will try to bind to exit but my plugin was already binding exit command and from my quick test yesterday it wasn’t triggered also . Any idea on how to reverse engineer theses changes ?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ebaauw** [comment]
I'm afraid not.  I just look at the value reported by the RemoteKey characteristic.

**Comment by nicoduj** [comment]
ok, so In my plugin ,I confirm that when we click on big new Back button, nothing is retrieved (set on characteristic.on for Chararcteristic.RemoteKey is not called at all.
I don't receive anymore events for volume also.

**Comment by ebaauw** [comment]
Volume is a bit of a hit and miss in beta 3, see https://github.com/KhaosT/HAP-NodeJS/issues/645.

**Comment by nicoduj** [comment]
Seems to be fixed in beta4 !
