### ISSUE TITLE
Handling events outside HomeKit best practice

### ISSUE THREAD

**Issue by nicoduj** [KhaosT/HAP-NodeJS#652]
Hi,

I have a plugin for gate / garage door ( Gogogate2) , and I need advice to try to handle a particular case.

In fact. Here is the sequence :
- I open the garage door through a physical remote 
- I close it through HomeKit
- HomeKit detects first that is is now open so launch every automation associated to the open state (like switching lights on)
- it launches the closing event (and then the light switch off) 

I would like to find a way to not trigger anything in this case for the discoverer opened state . 

My plugin is using a background timer to refresh the state of the door , in order to handle automation but especially notification  linked to such events but I don’t want to do this too often . And if you open / close in a short time (below the background refresh timer threshold), then you encounter this situation .

So is there a way to update a characteristic value without HomeKit to launch associated actions ? Is there any priority in the order it checks for characteristic update ?
If anyone has an idea , you’re welcome !

https://github.com/nicoduj/homebridge-gogogate2/issues/19

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by NorthernMan54** [comment]
This is something I’m playing with that exposes all homebridge/hap-nodejs accessories to NodeRed so that you can build some incredible automations with it. The code is still pretty early in development, but allows you to control all your devices.

https://github.com/NorthernMan54/HAP-NodeRed
