### ISSUE TITLE
Receiver Service Type

### ISSUE THREAD

**Issue by Gruni22** [KhaosT/HAP-NodeJS#654]
Hi,
first of all, I want to thank you for your great work!

My questions, since iOS 12.2 there are new Service Type, and you already included the television service.
Is it also possible for you to implement the new Receiver service?
Sadly I couldn't find anything about the new characteristics (current HAP Spec not published)

Thanks a lot in advance!

**Comment by KhaosT** [comment]
There isn’t a receiver service. HomeKit Speaker/Receiver accessory is using AirPlay 2, not HAP.
