### ISSUE TITLE
Howto - Invert active state??

### ISSUE THREAD

**Issue by n0rt0nthec4t** [KhaosT/HAP-NodeJS#656]
I have a callback, which does the "on set" for the active state. What I'm trying to do, is depending on certain other conditions, not allow the active state to be set. For example, with a valve, when a user turns it on in HomeKit, you get the callback called for active state = true, but depending on the conditions, I want to not allow this to be "switched on", so return from teh callback that state was set to false, not true;

Hope this makes sense

**Comment by Shaquu** [comment]
I got similar situation.
Maybe remove current listener and and your own?

**Comment by NorthernMan54** [comment]
@n0rt0nthec4t looking at the code behind the set event, the callback only has a single parameter err.

https://github.com/KhaosT/HAP-NodeJS/blob/414cd96ca9708596b1f71304bd4e6dff5ab045fc/lib/Characteristic.js#L321

Have you looked at the HomeKit protocol specification document, to see if this use case is documented?

Have you looked at the valve service to see if it has a characteristic to indicate ‘blocked’ like a window or door?

https://github.com/KhaosT/HAP-NodeJS/blob/414cd96ca9708596b1f71304bd4e6dff5ab045fc/lib/gen/HomeKitTypes.js#L3466

One option if these don’t give the experience you are looking for, is to use the characteristic updateValue function, to tell HomeKit the actual device state after you receive the set event.

https://github.com/KhaosT/HAP-NodeJS/blob/414cd96ca9708596b1f71304bd4e6dff5ab045fc/lib/Characteristic.js#L357

**Comment by n0rt0nthec4t** [comment]
Yep, haven't found a clean way to do this. Only way I have is not to call the callback if the "blocked" state i true. HomeKIt shows the valve switch on, then reverts to it off when timeouts out

**Comment by Supereg** [comment]
The HomeKit protocol is simply not designed to do that.
Not responding at all isn't really a good solution I think.
The only possibilities you have is to either return an error or to wait some milliseconds and then send an updated value to the HomeKit controller (the old value) with the updateValue() function mentioned above.

**Comment by n0rt0nthec4t** [comment]
whats the best way to code the callback with an error? normally in teh on.set call back, I just return the last line of the function with callback();

**Comment by Supereg** [comment]
The callback for the set event expects an error object as the first argument.
If undefined the request was successful otherwise the error is forwarded to HomeKit.

You would pass an error like this: callback(new Error(„optional error messages“));

**Comment by NorthernMan54** [comment]
@Supereg @n0rt0nthec4t I think the best is to return null from the callback, the send the value using updateValue a few milliseconds later.  If you return an Error, the HomeApp will mark the device as 'Not Responding'.

Also there is an option with the Error object returned with the callback to pass back specific error messages back to HomeKit ( https://github.com/KhaosT/HAP-NodeJS/pull/539 ).  I never explored what was displayed in the Home app for each, one may offer the user experience your looking for

https://github.com/KhaosT/HAP-NodeJS/blob/414cd96ca9708596b1f71304bd4e6dff5ab045fc/lib/HAPServer.js#L143

**Comment by n0rt0nthec4t** [comment]
Hmm. been trying this, with using updatevalue, returning error, return null and none provide the required response. Leaves the valve with text "waiting" *sigh*

**Comment by NorthernMan54** [comment]
Null should just work....

**Comment by n0rt0nthec4t** [comment]
should, but doesn't...

                    this.__ValveService.getCharacteristic(Characteristic.Active).updateValue(Characteristic.Active.INACTIVE);
                   this.__ValveService.getCharacteristic(Characteristic.InUse).setValue(Characteristic.InUse.NOT_IN_USE);
this.__ValveService.getCharacteristic(Characteristic.RemainingDuration).setValue(0);
callback(null);


leaves the valve showing as on in HomeKit with text underneath as "waiting"

**Comment by NorthernMan54** [comment]
Humm, thinking both should be updateValue, but need to see it in a broader context

                this.__ValveService.getCharacteristic(Characteristic.Active).updateValue(Characteristic.Active.INACTIVE);
 this.__ValveService.getCharacteristic(Characteristic.InUse).updateValue(Characteristic.InUse.NOT_IN_USE);

**Comment by n0rt0nthec4t** [comment]
This is my full function and just tried your suggestion, but no dice

    setActiveState: function(state, callback) {
        if (switchService.getCharacteristic(Characteristic.On).value == true) {
            var openValveCount = 0;
            var maxRunningValves = 1;
            var shortestRunTimeService = null;

            if (typeof config.system.MaxRunningZones !== 'undefined' && typeof config.system.MaxRunningZones === 'number') maxRunningValves = config.system.MaxRunningZones;
            if (maxRunningValves < 1) maxRunningValves = 1;

            if (this.__ValveService.getCharacteristic(Characteristic.IsConfigured).value == Characteristic.IsConfigured.CONFIGURED) {
                if ((state == Characteristic.Active.ACTIVE) && (this.__ValveService.getCharacteristic(Characteristic.Active).value == Characteristic.Active.INACTIVE)) {
                    // Request to turn on sprinkler. We need to see how many sprinkers can be active at once, and ensure we do not exceed that amount
                    // If we need to shut a sprinker off to enabled this new one, do so to the one with the shortest run time left
                    for (var index in this.__accessory.services) {
                        if (this.__accessory.services[index].UUID == Service.Valve.UUID) {
                            var tmpValveService = this.__accessory.services[index];
                            if (tmpValveService.getCharacteristic(Characteristic.Active).value == Characteristic.Active.ACTIVE) {
                                // found another active sprinkler, so stop it if we exceed the max number of simultaneous running zones
                                openValveCount = openValveCount + 1;
                                if (shortestRunTimeService == null) {
                                    shortestRunTimeService = tmpValveService; 
                                }
                                else if (tmpValveService.getCharacteristic(Characteristic.RemainingDuration).value < shortestRunTimeService.getCharacteristic(Characteristic.RemainingDuration).value) {
                                    shortestRunTimeService = tmpValveService;
                                }
                                if (openValveCount >= maxRunningValves && shortestRunTimeService != null) {
                                    // Since we're using the setValue callback, the actual closing of the valve will happen when this function is re-enter by HomeKit
                                    shortestRunTimeService.getCharacteristic(Characteristic.Active).setValue(Characteristic.Active.INACTIVE);
                                }
                            }
                        }
                    }

                    this.openValve();
                    this.__ValveService.getCharacteristic(Characteristic.Active).updateValue(Characteristic.Active.ACTIVE);
                    this.__ValveService.getCharacteristic(Characteristic.InUse).setValue(Characteristic.InUse.IN_USE);
                    this.__ValveService.getCharacteristic(Characteristic.RemainingDuration).setValue(this.__ValveService.getCharacteristic(Characteristic.SetDuration).value);
                    this.__timerFunc = setInterval(this.runningTimer.bind(this), 100, Math.floor(Date.now() / 1000), Math.floor(Date.now() / 1000) + this.__ValveService.getCharacteristic(Characteristic.SetDuration).value);
                } else if ((state == Characteristic.Active.INACTIVE) && (this.__ValveService.getCharacteristic(Characteristic.Active).value == Characteristic.Active.ACTIVE)) {
                    clearInterval(this.__timerFunc);
                    this.closeValve();
                    this.__ValveService.getCharacteristic(Characteristic.Active).updateValue(Characteristic.Active.INACTIVE);
                    this.__ValveService.getCharacteristic(Characteristic.InUse).setValue(Characteristic.InUse.NOT_IN_USE);
                    this.__ValveService.getCharacteristic(Characteristic.RemainingDuration).setValue(0);
                }
            }
            callback();
        } else {
            // Since irrigation systen is "switched off", dont allow the valve to operate
            this.__ValveService.getCharacteristic(Characteristic.Active).updateValue(Characteristic.Active.INACTIVE);
            this.__ValveService.getCharacteristic(Characteristic.InUse).updateValue(Characteristic.InUse.NOT_IN_USE);
            this.__ValveService.getCharacteristic(Characteristic.RemainingDuration).updateValue(0);
            callback(null);
        }
    },


![Screen Shot 2019-03-21 at 10 31 45 am](https://user-images.githubusercontent.com/19759130/54725826-9d862c00-4bc4-11e9-9474-3c8cd6720cdd.png)

**Comment by Supereg** [comment]
You need definitely call the callback first before you reset the values with updateValue()
Maybe you also need to delay the updateValue a bit

**Comment by NorthernMan54** [comment]
Prior to the callback, wrap them in a setTimeout of about 50ms or so should do it

**Comment by n0rt0nthec4t** [comment]
seems not to help.. The "waiting" text appears after the delay after the callback(null)

weird

**Comment by NorthernMan54** [comment]
Are they debugging in DEBUG mode so you can see the messages to HomeKit?  May help figure it out.

**Comment by n0rt0nthec4t** [comment]
This shows when I have the system dibbled as per my code loop, the active value is getting set twice.

  Accessory [Irrigation System] Processing characteristic set: [{"aid":1,"iid":10,"value":1},{"aid":1,"iid":48,"value":1}] +7ms
  Accessory [Irrigation System] Setting Characteristic "Active" to value 1 +5ms
  EventedHTTPServer [::ffff:10.0.1.14] Sending HTTP event '1.10' with data: {"characteristics":[{"aid":1,"iid":10,"value":1}]} +7ms
  EventedHTTPServer [::ffff:10.0.1.10] Muting event '1.10' notification for this connection since it originated here. +9ms
  Accessory [Irrigation System] Setting Characteristic "Active" to value 1 +4ms
  EventedHTTPServer [::ffff:10.0.1.14] Sending HTTP event '1.48' with data: {"characteristics":[{"aid":1,"iid":48,"value":1}]} +18ms
  EventedHTTPServer [::ffff:10.0.1.10] Muting event '1.48' notification for this connection since it originated here. +10ms
  EventedHTTPServer [::ffff:10.0.1.10] HTTP Response is finished +4ms

**Comment by NorthernMan54** [comment]
This appears normal
