### ISSUE TITLE
How to keep HAP running in background

### ISSUE THREAD

**Issue by legotheboss** [KhaosT/HAP-NodeJS#66]
My HAP setup keeps stopping every few hours. I tried the startup and it isn't working either. It worked fine a few days ago... What is the solution? Heres the node-app error. 

    Node app stopped, but pid file exists

**Comment by KhaosT** [comment]
@legotheboss how did you wrapper the node server?

**Comment by legotheboss** [comment]
I just fixed it by using the
`root@GaragePi:/home/pi/HAP-NodeJS# /etc/init.d/node-app start --force`

**Comment by angyalZK** [comment]
@legotheboss how can you use the --force option at system startup (in init.d)?
