### ISSUE TITLE
Add New Programmable Switch Event Value to Stateless Programmable Switch

### ISSUE THREAD

**Issue by tai1235** [KhaosT/HAP-NodeJS#663]
I have a Xiaomi Smart button which support triple press, quadruple press and quintupe press events and I want to add these values to `ProgrammableSwitchEvent` characteristic.

I have added these lines of code to `HomeKitTypes`
```
Characteristic.ProgrammableSwitchEvent = function() {
  Characteristic.call(this, 'Programmable Switch Event', '00000073-0000-1000-8000-0026BB765291');
  this.setProps({
    format: Characteristic.Formats.UINT8,
    maxValue: 5,
    minValue: 0,
    validValues: [0,1,2,3,4,5],
    perms: [Characteristic.Perms.READ, Characteristic.Perms.NOTIFY]
  });
  this.eventOnlyCharacteristic = true; //Manual addition.
  this.value = this.getDefaultValue();
};

inherits(Characteristic.ProgrammableSwitchEvent, Characteristic);

Characteristic.ProgrammableSwitchEvent.UUID = '00000073-0000-1000-8000-0026BB765291';

// The value property of ProgrammableSwitchEvent must be one of the following:
Characteristic.ProgrammableSwitchEvent.SINGLE_PRESS = 0;
Characteristic.ProgrammableSwitchEvent.DOUBLE_PRESS = 1;
Characteristic.ProgrammableSwitchEvent.LONG_PRESS = 2;
Characteristic.ProgrammableSwitchEvent.TRIPLE_PRESS = 3;        // New
Characteristic.ProgrammableSwitchEvent.QUADRUPLE_PRESS = 4;     // New
Characteristic.ProgrammableSwitchEvent.QUINTUPLE_PRESS = 5;     // New
```

Here is the result

![IMG_4333](https://user-images.githubusercontent.com/34118343/56464973-bd587c00-641e-11e9-980c-c0c9bcd2ffd6.JPG)

It works just fine but how can I fix the unknown name of new events added?

**Comment by ebaauw** [comment]
You cannot.

**Comment by tai1235** [comment]
@ebaauw is there any other ways to add new values to a characteristic rather than Apple defined ones

**Comment by ebaauw** [comment]
No, Apple’s Home app only handles standard (i.e. Apple defined) services and characteristics.  Typically it will accept an override of the properties for minimum and maximum value (e.g. for _Current Temperature_ to display (outside) temperatures below zero, and in your example), but there’s no way to add _Actions_ names for the new values.  I think this is the reason that Xioami’s HomeKit certified Aqara switches only provide single, double, and long press.

**Comment by tai1235** [comment]
Thank you very much @ebaauw. I'll close this for now
