### ISSUE TITLE
.on('set') event - what called it?

### ISSUE THREAD

**Issue by n0rt0nthec4t** [KhaosT/HAP-NodeJS#667]
The example I have is an array of objects, in this case, valves. Aside from some other details, each object in the the array has the service object for the valve

ie: tempZone is one object

 tempZone.__ValveService.getCharacteristic(Characteristic.Active).on('set', this.setActiveIrrigationZone.bind(this));

In the function that gets called on an active change event, is it possible to know what service object called teh on set event so I can loop though the array of objects and do a match to what triggered the on set?

Hope that makes sense,,

**Comment by NorthernMan54** [comment]
Thinking about your question for a moment, wouldn’t the ‘this’ object contain the context your looking for?  The this inside your function.

**Comment by ebaauw** [comment]
No, the context is (in) the `tempzone.__ValveService`.  You need to pass (a reference to) it to `setActiveIrrigationZone()`

**Comment by n0rt0nthec4t** [comment]
> No, the context is (in) the `tempzone.__ValveService`. You need to pass (a reference to) it to `setActiveIrrigationZone()`

How would you structure the on set binding and the. function declaration ?

**Comment by ebaauw** [comment]
Change the declaration to `function (context, state, callback)` and then change the `on(‘set’, ...)` to
```javascript
tempzone.__ValveService.on(‘set’, (value, callback) => {
  this.setIrrigationActive(tempzone.__ValveService, value, callback)
})
```

**Comment by n0rt0nthec4t** [comment]
Awesome, thanks!
