### ISSUE TITLE
Does this solution support Siri on Apple watch?

### ISSUE THREAD

**Issue by smika01** [KhaosT/HAP-NodeJS#67]
Hi, 
this solution works good with Siri on my Iphone but with the apple watch it seams not to work. 
Can HAP-NodeJS work together with Siri on the apple watch?
Thanks for your work!

**Comment by KhaosT** [comment]
Currently Siri on Apple Watch doesn't support controlling HomeKit accessories. It's an Apple bug so please file a radar with Apple about using Siri on Apple Watch with HomeKit accessories if you find this feature is necessary.

**Comment by maddox** [comment]
Just to add to this, I had an issue as well when I put iOS 9 on my iPad. Previously, I hadn't actually had HomeKitDemo installed on it though.

I installed iOS 9 on the iPad. Then installed HomeKitDemo. Opened HomeKitDemo, and gave it permission to see my devices, and they're all red.

**Comment by KhaosT** [comment]
@maddox Wrong issue?

**Comment by maddox** [comment]
Yup :cry:

**Comment by smika01** [comment]
Hi,
what about the watchOS 2.0 beta? It seams it will support HomeKit may be also with Siri. Did you have any chance to test this?

**Comment by KhaosT** [comment]
@smika01 right now watchOS 2.0 seed 1 still defers HomeKit command to iPhone (via Handoff), hope they will modify server to fix that in next release.

**Comment by smika01** [comment]
Thanks for the info. Hope as well and wait for next release.
