### ISSUE TITLE
Characteristic.TargetHeaterCoolerState state 3=OFF is not mapped

### ISSUE THREAD

**Issue by maisun** [KhaosT/HAP-NodeJS#682]
Hi,

The HeaterCooler accessory uses the Characteristic.TargetHeaterCoolerState, as I understand there should be 4 values:
AUTO=0
HEAT=1
COOL=2
OFF=3

Looking into the code it looks like OFF=3 is not mapped, any reason behind it? I'm trying to disabled the OFF button in HomeKit but couldn't find a way. It looks to me like if I allow value 0=AUTO, then OFF is also displayed. If I only allow HEAT=1 and COOL=2, then OFF is hidden. Could the missing mapping cause this?

Characteristic.call(this, 'Target Heater Cooler State', '000000B2-0000-1000-8000-0026BB765291');
this.setProps({
format: Characteristic.Formats.UINT8,
maxValue: 2,
minValue: 0,
validValues: [0,1,2],
perms: [Characteristic.Perms.READ, Characteristic.Perms.WRITE, Characteristic.Perms.NOTIFY]
});
this.value = this.getDefaultValue();
};

inherits(Characteristic.TargetHeaterCoolerState, Characteristic);

Characteristic.TargetHeaterCoolerState.UUID = '000000B2-0000-1000-8000-0026BB765291';

// The value property of TargetHeaterCoolerState must be one of the following:
Characteristic.TargetHeaterCoolerState.AUTO = 0;
Characteristic.TargetHeaterCoolerState.HEAT = 1;
Characteristic.TargetHeaterCoolerState.COOL = 2;

**Comment by tobekas** [comment]
OFF is not part of TargetHeaterCoolerState. 
Although it is shown in the Home App, or is internally linked to Characteristic.Active.
You can verify this behavior exactly with the Apple Homekit Accessory Simulator...

see: https://github.com/nfarina/homebridge/issues/2239

**Comment by tobekas** [comment]
His is the same for some other newer Services like Fanv2, Valve, AirPurifier, ...

You should not make people nervous as long as your other issue is clarified.

**Comment by maisun** [comment]
> His is the same for some other newer Services like Fanv2, Valve, AirPurifier, ...
> 
> You should not make people nervous as long as your other issue is clarified.

I think you're right, I can only disallow OFF by the following but I cannot hide the switch, it works differently from Thermostat which I can hide the OFF button completely:
        primaryService.getCharacteristic(this.Characteristic.Active).setProps({
            maxValue: 1,
            minValue: 1,
            validValues: [1]
        });
