### ISSUE TITLE
iOS 9 breaks things

### ISSUE THREAD

**Issue by mikegapinski** [KhaosT/HAP-NodeJS#69]
Just an early update on the new beta, you are not able to use any HAP accessories after switching off wifi and turning it back on. iCloud Remote access is also not a go. Devices need to be removed and added once more. Not sure if it's a beta problem or Apple changed the protocol and we are screwed up. Test on your devices guys :)

**Comment by KhaosT** [comment]
I wasn't able to reproduce the issue as I haven't encounter any problem from iOS 8.4 to iOS 9.0b1... And since "remove then add" works for you, I assume there is nothing wrong on this project side.

**Comment by maddox** [comment]
Just to add to this, I had an issue as well when I put iOS 9 on my iPad. Previously, I hadn't actually had HomeKitDemo installed on it though.

I installed iOS 9 on the iPad. Then installed HomeKitDemo. Opened HomeKitDemo, and gave it permission to see my devices, and they're all red.

I removed a device. At first it wouldn't find it when I tried to "add" it back. But eventually it showed up and it added back green. So we might just need to do add everything back again.

**Comment by KhaosT** [comment]
@maddox before you remove all the "old" devices, can you try to close the node server and then open device console, then start the server again? Just want to check if homed is complaining anything about the accessory.

**Comment by maddox** [comment]
Everything is red still. Even the new one I added that was green. :( 

I'm not sure if this is an iPad target issue, but when I try to browse the red device and go to the device Accessory Information, the app crashes. Again, this is the first time I've had the iOS app on an iPad, so maybe this was an existing crasher.

**Comment by maddox** [comment]
Ok, it's iOS 9, so there's LOTSSSSSSS OF LOGGGING going on. See if you can find anything relevant in here:

https://gist.github.com/maddox/5d538f577508eaed29c5

**Comment by KhaosT** [comment]
@maddox Huh... nothing useful there... Guess I will check the CoreHAP and see if they made any change that breaks the thing.

**Comment by KhaosT** [comment]
@maddox and that crash is caused by a private api call... I updated the repo (or you can try Apple's official one from [here](https://developer.apple.com/sample-code/wwdc/2015/)) with Swift 2.0 and fixed that crash.

**Comment by maddox** [comment]
Ah! I didn't check to see if there were any commits on HomeKitDemo, my bad. I'll go pull for my iOS 9 stuff.

**Comment by mikegapinski** [comment]
I will need to try with HomeKitDemo, I was using third party apps. The annoying thing is that I have to remove and add all devices any time I switch wifi on. I will try to get logs over the weekend, I came back to 8.4

**Comment by KhaosT** [comment]
Commit 19a4bee7d82674ac0051706687def1e3570c2b68 should fix the issue. You'll need to remove all the accessories from iOS, and then remove all the files under ./persist
After that everything should works. If you have multiple users, you'll have to use shared home (add user to one single HMHome)
Also, if you removed the accessory from iOS, you'll also need to remove the associated key file so that the accessory will be discoverable again. (I'm too busy to create an elegant way handle this... pull request is welcomed ^^)
--
Details
It seems that iOS 9 starts enforcing the requirement that one accessory can only be paired directly with one iCloud account. After pairing, the accessory needs to update a flag to indicate that the accessory has been paired. Otherwise iOS will reject connecting the accessory.

**Comment by mikegapinski** [comment]
I checked your patch, it discovers devices fine now. It only tells me that the services on this accessory have changed on wifi connection. Not a big deal. Did you try the new remote access features on iOS9? They might need an AppleTV to work, or just not implemented in Beta1. Will see :) Thanks for the patch

**Comment by legotheboss** [comment]
The Apple TV and iCloud sync is active. I tried to activate HAP over my data network and was able to relay the command over the existing Apple TV in my local network

**Comment by KhaosT** [comment]
@legotheboss It's nice to know. Are you running iOS beta on your Apple TV?

**Comment by legotheboss** [comment]
@KhaosT yes I installed it when it was available... I can't find any betas for Apple TV on the new website...
