### ISSUE TITLE
Thermostat Set Points

### ISSUE THREAD

**Issue by d0n4v4nb3ck3r** [KhaosT/HAP-NodeJS#697]
Is there anyway to make it so that a thermostat can do these set points? Instead of being able to just set 1 temp? Didn’t find anything in the code

**Comment by d0n4v4nb3ck3r** [comment]
![3EF08136-8795-4FC5-99F5-9CEC7B46BA31](https://user-images.githubusercontent.com/9875439/63235433-fce17a00-c1fe-11e9-9528-5a95e16eb006.png)

**Comment by d0n4v4nb3ck3r** [comment]
@KhaosT

**Comment by Supereg** [comment]
You mean setting a temperature range in which the target temperature should be?
When that's the question then no. The HomeKit protocol doesn't support this out of the box.
This would need custom characteristics and a custom app.

**Comment by d0n4v4nb3ck3r** [comment]
HomeKit has the functionally to set the heat to heat to a certain temperature and then set cooling to a certain temperature so that it stays with that rang.

**Comment by mihailescu2m** [comment]
use HeaterCooler service
