### ISSUE TITLE
How do you set multiple speeds on the fan controller

### ISSUE THREAD

**Issue by legotheboss** [KhaosT/HAP-NodeJS#70]
I am confused on how to edit and implement the fan controller with various speeds... How could you do this?

**Comment by KhaosT** [comment]
Under the fan service, create a characteristic with type ROTATION_SPEED_CTYPE and implement things under that.

**Comment by legotheboss** [comment]
How would I do this? I understand how to make the new characteristic, but don't understand how to implement multiple speeds...

**Comment by KhaosT** [comment]
@legotheboss just change the value type to Int or percentage.
BTW I don't think Siri supports Fan right now...

**Comment by legotheboss** [comment]
@KhaosT oh then that won't work. Guess I'll have to use the light controller to toggle the fan mode

**Comment by legotheboss** [comment]
@KhaosT can you show me an example file of how I could execute this? I am extremely confused and would greatly appreciate it. This is literally my first project in Node.JS

**Comment by KhaosT** [comment]
@legotheboss something like [this](https://gist.github.com/KhaosT/cd92012e5b854bfb13b5)

**Comment by legotheboss** [comment]
@KhaosT  could you show me how to execute a line of code when the fan turns on and a different line of code when the fan turns off

**Comment by KhaosT** [comment]
Check [here](https://gist.github.com/KhaosT/01e8a07b8bbe5e19f30e#file-outlet_accessory-js-L80), if you still don't know what to do, I'd suggest you to ask on stackoverflow since it's a question about JavaScript instead of the repo.

**Comment by legotheboss** [comment]
Ok thanks

**Comment by ericklil** [comment]
@legotheboss did you get the fan speed control working?

**Comment by legotheboss** [comment]
@ericklil Yes, I got it working. Take a look [here](https://github.com/legotheboss/YouTube-files/blob/master/Fan_accessory.js).

**Comment by Hekami** [comment]
@legotheboss 
i am trying your code.But in your code no GPIO pin is defined.Please help me in that.
