### ISSUE TITLE
npm install fails on PI2 (node-gyp rebuild  Segmentation fault)

### ISSUE THREAD

**Issue by LordS4me** [KhaosT/HAP-NodeJS#71]
Since I format my Pi, I can't get HAP works anymore.

I follow the instruction for node's version :
node -v v0.10.36
npm -v 1.4.28

This is my npm install results 

    root@helium:~/HAP-NodeJS# npm install
    npm info it worked if it ends with ok
    npm info using npm@1.4.28
    npm info using node@v0.10.36
    npm info preinstall HAP-NodeJS@0.0.1
    npm info trying registry request attempt 1 at 12:08:36
    npm http GET https://registry.npmjs.org/mdns
    npm http 304 https://registry.npmjs.org/mdns
    npm info install mdns@2.2.9 into /root/HAP-NodeJS
    npm info install curve25519@1.0.0 into /root/HAP-NodeJS
    npm info install srp@0.2.0 into /root/HAP-NodeJS
    npm info install ed25519@0.0.2 into /root/HAP-NodeJS
    npm info installOne mdns@2.2.9
    npm info installOne curve25519@1.0.0
    npm info installOne srp@0.2.0
    npm info installOne ed25519@0.0.2
    npm info preinstall curve25519@1.0.0
    npm info trying registry request attempt 1 at 12:08:41
    npm http GET https://registry.npmjs.org/bindings
    npm info trying registry request attempt 1 at 12:08:41
    npm http GET https://registry.npmjs.org/nan
    npm info preinstall srp@0.2.0
    npm http 304 https://registry.npmjs.org/nan
    npm http 304 https://registry.npmjs.org/bindings
    npm info trying registry request attempt 1 at 12:08:41
    npm http GET https://registry.npmjs.org/bignum
    npm info install nan@1.8.4 into /root/HAP-NodeJS/node_modules/curve25519
    npm info install bindings@1.2.1 into /root/HAP-NodeJS/node_modules/curve25519
    npm info installOne nan@1.8.4
    npm info installOne bindings@1.2.1
    npm http 304 https://registry.npmjs.org/bignum
    npm info install bignum@0.9.2 into /root/HAP-NodeJS/node_modules/srp
    npm info installOne bignum@0.9.2
    npm info preinstall bindings@1.2.1
    npm info build /root/HAP-NodeJS/node_modules/curve25519/node_modules/bindings
    npm info linkStuff bindings@1.2.1
    npm info install bindings@1.2.1
    npm info postinstall bindings@1.2.1
    npm info preinstall bignum@0.9.2
    npm info install nan@1.6.2 into /root/HAP-NodeJS/node_modules/srp/node_modules/bignum
    npm info installOne nan@1.6.2
    npm info preinstall nan@1.8.4
    npm info build /root/HAP-NodeJS/node_modules/curve25519/node_modules/nan
    npm info linkStuff nan@1.8.4
    npm info install nan@1.8.4
    npm info postinstall nan@1.8.4
    npm info build /root/HAP-NodeJS/node_modules/curve25519
    npm info linkStuff curve25519@1.0.0
    npm info install curve25519@1.0.0
    
    > curve25519@1.0.0 install /root/HAP-NodeJS/node_modules/curve25519
    > node-gyp rebuild
    
    Segmentation fault
    
    module.js:340
        throw err;
              ^
    Error: Cannot find module '/node_modules/node-gyp/bin/node-gyp.js'
        at Function.Module._resolveFilename (module.js:338:15)
        at Function.Module._load (module.js:280:25)
        at Function.Module.runMain (module.js:497:10)
        at startup (node.js:119:16)
        at node.js:929:3
    npm info preinstall mdns@2.2.9
    npm info preinstall ed25519@0.0.2
    npm info curve25519@1.0.0 Failed to exec install script
    npm info install bindings@1.2.1 into /root/HAP-NodeJS/node_modules/mdns
    npm info install nan@1.8.4 into /root/HAP-NodeJS/node_modules/mdns
    npm info installOne bindings@1.2.1
    npm info installOne nan@1.8.4
    npm info install bindings@1.2.1 into /root/HAP-NodeJS/node_modules/ed25519
    npm info install nan@1.8.4 into /root/HAP-NodeJS/node_modules/ed25519
    npm info installOne bindings@1.2.1
    npm info installOne nan@1.8.4
    npm info preinstall bindings@1.2.1
    npm info build /root/HAP-NodeJS/node_modules/mdns/node_modules/bindings
    npm info linkStuff bindings@1.2.1
    npm info install bindings@1.2.1
    npm info postinstall bindings@1.2.1
    npm info preinstall nan@1.6.2
    npm info build /root/HAP-NodeJS/node_modules/srp/node_modules/bignum/node_modules/nan
    npm info linkStuff nan@1.6.2
    npm info preinstall bindings@1.2.1
    npm info install nan@1.6.2
    npm info postinstall nan@1.6.2
    npm info build /root/HAP-NodeJS/node_modules/ed25519/node_modules/bindings
    npm info linkStuff bindings@1.2.1
    npm info build /root/HAP-NodeJS/node_modules/srp/node_modules/bignum
    npm info linkStuff bignum@0.9.2
    npm info install bindings@1.2.1
    npm info install bignum@0.9.2
    
    > bignum@0.9.2 install /root/HAP-NodeJS/node_modules/srp/node_modules/bignum
    > node-gyp configure build
    
    Segmentation fault
    
    module.js:340
        throw err;
              ^
    Error: Cannot find module '/node_modules/node-gyp/bin/node-gyp.js'
        at Function.Module._resolveFilename (module.js:338:15)
        at Function.Module._load (module.js:280:25)
        at Function.Module.runMain (module.js:497:10)
        at startup (node.js:119:16)
        at node.js:929:3
    npm info postinstall bindings@1.2.1
    npm info preinstall nan@1.8.4
    npm info build /root/HAP-NodeJS/node_modules/mdns/node_modules/nan
    npm info linkStuff nan@1.8.4
    npm info install nan@1.8.4
    npm info postinstall nan@1.8.4
    npm info build /root/HAP-NodeJS/node_modules/mdns
    npm info linkStuff mdns@2.2.9
    npm info install mdns@2.2.9
    npm info bignum@0.9.2 Failed to exec install script
    
    > mdns@2.2.9 install /root/HAP-NodeJS/node_modules/mdns
    > node-gyp rebuild
    
    Segmentation fault
    
    module.js:340
        throw err;
              ^
    Error: Cannot find module '/node_modules/node-gyp/bin/node-gyp.js'
        at Function.Module._resolveFilename (module.js:338:15)
        at Function.Module._load (module.js:280:25)
        at Function.Module.runMain (module.js:497:10)
        at startup (node.js:119:16)
        at node.js:929:3
    npm info preinstall nan@1.8.4
    npm info build /root/HAP-NodeJS/node_modules/ed25519/node_modules/nan
    npm info linkStuff nan@1.8.4
    npm info install nan@1.8.4
    npm info postinstall nan@1.8.4
    npm info build /root/HAP-NodeJS/node_modules/ed25519
    npm info linkStuff ed25519@0.0.2
    npm info install ed25519@0.0.2
    npm info mdns@2.2.9 Failed to exec install script
    
    > ed25519@0.0.2 install /root/HAP-NodeJS/node_modules/ed25519
    > node-gyp rebuild
    
    Segmentation fault
    
    module.js:340
        throw err;
              ^
    Error: Cannot find module '/node_modules/node-gyp/bin/node-gyp.js'
        at Function.Module._resolveFilename (module.js:338:15)
        at Function.Module._load (module.js:280:25)
        at Function.Module.runMain (module.js:497:10)
        at startup (node.js:119:16)
        at node.js:929:3
    
    npm info ed25519@0.0.2 Failed to exec install script
    npm ERR! curve25519@1.0.0 install: `node-gyp rebuild`
    npm ERR! Exit status 8
    npm ERR!
    npm ERR! Failed at the curve25519@1.0.0 install script.
    npm ERR! This is most likely a problem with the curve25519 package,
    npm ERR! not with npm itself.
    npm ERR! Tell the author that this fails on your system:
    npm ERR!     node-gyp rebuild
    npm ERR! You can get their info via:
    npm ERR!     npm owner ls curve25519
    npm ERR! There is likely additional logging output above.
    npm ERR! System Linux 3.18.11-v7+
    npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install"
    npm ERR! cwd /root/HAP-NodeJS
    npm ERR! node -v v0.10.36
    npm ERR! npm -v 1.4.28
    npm ERR! code ELIFECYCLE
    npm info preuninstall curve25519@1.0.0
    npm info uninstall curve25519@1.0.0
    npm info postuninstall curve25519@1.0.0
    npm info preuninstall bignum@0.9.2
    npm info uninstall bignum@0.9.2
    npm info postuninstall bignum@0.9.2
    npm info preuninstall srp@0.2.0
    npm info uninstall srp@0.2.0
    npm info postuninstall srp@0.2.0
    npm info preuninstall mdns@2.2.9
    npm info uninstall mdns@2.2.9
    npm info postuninstall mdns@2.2.9
    npm info preuninstall ed25519@0.0.2
    npm info uninstall ed25519@0.0.2
    npm info postuninstall ed25519@0.0.2
    npm ERR! not ok code 0

Thanks for any help !

**Comment by KhaosT** [comment]
Please try node 0.12 with latest npm.
