### ISSUE TITLE
iOS 13 Doorbell

### ISSUE THREAD

**Issue by netRunner0** [KhaosT/HAP-NodeJS#716]
in ios 12, when you call the intercom, the buttons for opening the lock and turning on the lights were available if they were in the same room.

At 13 this does not work (no buttons). Any ideas?

**Comment by Supereg** [comment]
Is this behavior consistent? Does your notification show a snapshot image?
For me iOS 13 now even shows all devices in the same room as the doorbell like the following:

![IMG_2409](https://user-images.githubusercontent.com/9783857/65958397-94b5c300-e44f-11e9-8f99-4566f341fe77.png)

**Comment by netRunner0** [comment]
Which plugin are you using?
I see the photo and everything, although the castle and the light in one room

**Comment by Supereg** [comment]
> Which plugin are you using?

custom made

> I see the photo and everything, although the castle and the light in one room

So the snapshot is getting displayed? But the controls do not (although they are in the same room)?
Are you using any specific plugin for this?

**Comment by netRunner0** [comment]
@Supereg please close)

**Comment by Supereg** [comment]
I'm not able to close your issue, you can close it yourself though 🤔

**Comment by Final-Hawk** [comment]
Could i get your custom plugin code? Thanks
