### ISSUE TITLE
nothing on started

### ISSUE THREAD

**Issue by tocks53** [KhaosT/HAP-NodeJS#72]
Hello, i use ubuntu 64 bit and when i start HAP-NodeJS. there are noting

beber@beber-Portable:~$ cd HAP-NodeJS-master/
beber@beber-Portable:~/HAP-NodeJS-master$ sudo npm install
[sudo] password for beber: 
 
> curve25519@1.0.0 install /home/beber/HAP-NodeJS-master/node_modules/curve25519
> node-gyp rebuild

make: Entering directory '/home/beber/HAP-NodeJS-master/node_modules/curve25519/build'
  CXX(target) Release/obj.target/curve/node_curve.o
../node_curve.cc: In function ‘v8::Handle<v8::Value> DoCurve(const v8::Arguments&)’:
../node_curve.cc:28:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
  SOLINK_MODULE(target) Release/obj.target/curve.node
  SOLINK_MODULE(target) Release/obj.target/curve.node: Finished
  COPY Release/curve.node
make: Leaving directory '/home/beber/HAP-NodeJS-master/node_modules/curve25519/build'

> mdns@2.2.9 install /home/beber/HAP-NodeJS-master/node_modules/mdns
> node-gyp rebuild

make: Entering directory '/home/beber/HAP-NodeJS-master/node_modules/mdns/build'
  CXX(target) Release/obj.target/dns_sd_bindings/src/dns_sd.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/dns_service_browse.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/dns_service_enumerate_domains.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/dns_service_get_addr_info.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/dns_service_process_result.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/dns_service_ref.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/dns_service_ref_deallocate.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/dns_service_ref_sock_fd.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/dns_service_register.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/dns_service_resolve.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/mdns_utils.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/network_interface.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/socket_watcher.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/txt_record_ref.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/txt_record_create.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/txt_record_deallocate.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/txt_record_set_value.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/txt_record_get_length.o
  CXX(target) Release/obj.target/dns_sd_bindings/src/txt_record_buffer_to_object.o
  SOLINK_MODULE(target) Release/obj.target/dns_sd_bindings.node
  SOLINK_MODULE(target) Release/obj.target/dns_sd_bindings.node: Finished
  COPY Release/dns_sd_bindings.node
make: Leaving directory '/home/beber/HAP-NodeJS-master/node_modules/mdns/build'

> bignum@0.9.2 install /home/beber/HAP-NodeJS-master/node_modules/srp/node_modules/bignum
> node-gyp configure build

make: Entering directory '/home/beber/HAP-NodeJS-master/node_modules/srp/node_modules/bignum/build'
  CXX(target) Release/obj.target/bignum/bignum.o
  SOLINK_MODULE(target) Release/obj.target/bignum.node
  SOLINK_MODULE(target) Release/obj.target/bignum.node: Finished
  COPY Release/bignum.node
make: Leaving directory '/home/beber/HAP-NodeJS-master/node_modules/srp/node_modules/bignum/build'

> ed25519@0.0.2 install /home/beber/HAP-NodeJS-master/node_modules/ed25519
> node-gyp rebuild

make: Entering directory '/home/beber/HAP-NodeJS-master/node_modules/ed25519/build'
  CC(target) Release/obj.target/ed25519/src/ed25519/keypair.o
  CC(target) Release/obj.target/ed25519/src/ed25519/sign.o
  CC(target) Release/obj.target/ed25519/src/ed25519/open.o
  CC(target) Release/obj.target/ed25519/src/ed25519/crypto_verify_32.o
  CC(target) Release/obj.target/ed25519/src/ed25519/ge_double_scalarmult.o
  CC(target) Release/obj.target/ed25519/src/ed25519/ge_frombytes.o
  CC(target) Release/obj.target/ed25519/src/ed25519/ge_scalarmult_base.o
  CC(target) Release/obj.target/ed25519/src/ed25519/ge_precomp_0.o
  CC(target) Release/obj.target/ed25519/src/ed25519/ge_p2_0.o
  CC(target) Release/obj.target/ed25519/src/ed25519/ge_p2_dbl.o
  CC(target) Release/obj.target/ed25519/src/ed25519/ge_p3_0.o
  CC(target) Release/obj.target/ed25519/src/ed25519/ge_p3_dbl.o
  CC(target) Release/obj.target/ed25519/src/ed25519/ge_p3_to_p2.o
  CC(target) Release/obj.target/ed25519/src/ed25519/ge_p3_to_cached.o
  CC(target) Release/obj.target/ed25519/src/ed25519/ge_p3_tobytes.o
  CC(target) Release/obj.target/ed25519/src/ed25519/ge_madd.o
  CC(target) Release/obj.target/ed25519/src/ed25519/ge_add.o
  CC(target) Release/obj.target/ed25519/src/ed25519/ge_msub.o
  CC(target) Release/obj.target/ed25519/src/ed25519/ge_sub.o
  CC(target) Release/obj.target/ed25519/src/ed25519/ge_p1p1_to_p3.o
  CC(target) Release/obj.target/ed25519/src/ed25519/ge_p1p1_to_p2.o
  CC(target) Release/obj.target/ed25519/src/ed25519/ge_tobytes.o
  CC(target) Release/obj.target/ed25519/src/ed25519/fe_0.o
  CC(target) Release/obj.target/ed25519/src/ed25519/fe_1.o
  CC(target) Release/obj.target/ed25519/src/ed25519/fe_cmov.o
  CC(target) Release/obj.target/ed25519/src/ed25519/fe_copy.o
  CC(target) Release/obj.target/ed25519/src/ed25519/fe_neg.o
  CC(target) Release/obj.target/ed25519/src/ed25519/fe_add.o
  CC(target) Release/obj.target/ed25519/src/ed25519/fe_sub.o
  CC(target) Release/obj.target/ed25519/src/ed25519/fe_mul.o
  CC(target) Release/obj.target/ed25519/src/ed25519/fe_sq.o
  CC(target) Release/obj.target/ed25519/src/ed25519/fe_sq2.o
  CC(target) Release/obj.target/ed25519/src/ed25519/fe_invert.o
  CC(target) Release/obj.target/ed25519/src/ed25519/fe_tobytes.o
  CC(target) Release/obj.target/ed25519/src/ed25519/fe_isnegative.o
  CC(target) Release/obj.target/ed25519/src/ed25519/fe_isnonzero.o
  CC(target) Release/obj.target/ed25519/src/ed25519/fe_frombytes.o
  CC(target) Release/obj.target/ed25519/src/ed25519/fe_pow22523.o
  CC(target) Release/obj.target/ed25519/src/ed25519/sc_reduce.o
  CC(target) Release/obj.target/ed25519/src/ed25519/sc_muladd.o
  CXX(target) Release/obj.target/ed25519/src/ed25519.o
  SOLINK_MODULE(target) Release/obj.target/ed25519.node
  SOLINK_MODULE(target) Release/obj.target/ed25519.node: Finished
  COPY Release/ed25519.node
make: Leaving directory '/home/beber/HAP-NodeJS-master/node_modules/ed25519/build'
node-persist@0.0.3 node_modules/node-persist
├── mkdirp@0.3.5
└── q@1.1.2

curve25519@1.0.0 node_modules/curve25519
├── bindings@1.2.1
└── nan@1.8.4

mdns@2.2.9 node_modules/mdns
├── bindings@1.2.1
└── nan@1.8.4

srp@0.2.0 node_modules/srp
└── bignum@0.9.2 (nan@1.6.2)

ed25519@0.0.2 node_modules/ed25519
├── bindings@1.2.1
└── nan@1.8.4
beber@beber-Portable:~/HAP-NodeJS-master$ node
node       node-gyp   nodejs     nodeusers  
beber@beber-Portable:~/HAP-NodeJS-master$ node
node       node-gyp   nodejs     nodeusers  
beber@beber-Portable:~/HAP-NodeJS-master$ node BridgedCore.js 
beber@beber-Portable:~/HAP-NodeJS-master$ ls
accessories                    chacha20poly1305.js  node_modules  TCPServer.js
AccessoryController.js         Characteristic.js    package.json  Thermostat_Logical.js
Accessory.js                   Core.js              README.md     TLV-Handler.js
Advertiser.js                  Encryption.js        Server.js
BridgedAccessoryController.js  hkdf.js              Service.js
BridgedCore.js                 index.js             Session.js

**Comment by tocks53** [comment]
when i start with nodejs i have this :

eber@beber-Portable:~/HAP-NodeJS-master$ sudo nodejs BridgedCore.js 
*** WARNING *** The program 'nodejs' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=nodejs>
*** WARNING *** The program 'nodejs' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=nodejs&f=DNSServiceRegister>

/home/beber/HAP-NodeJS-master/node_modules/ed25519/node_modules/bindings/bindings.js:83
        throw e
              ^
Error: Symbol ed25519_module not found.
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at bindings (/home/beber/HAP-NodeJS-master/node_modules/ed25519/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/home/beber/HAP-NodeJS-master/node_modules/ed25519/index.js:1:99)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
beber@beber-Portable:~/HAP-NodeJS-master$ ls

**Comment by KhaosT** [comment]
What's your node version? Please try 0.12.x instead of 0.10.x

**Comment by legotheboss** [comment]
I had the same issue and solved via using Node 12.x
