### ISSUE TITLE
Temperature in decimal format

### ISSUE THREAD

**Issue by kajaba** [KhaosT/HAP-NodeJS#721]
Hello 
I have a problem with decimal format in temperature characteristic. I’m trying to set, for example, value 38.5 and all I can get in the HomeKit app is 39

> sensor
> .addService(Service.TemperatureSensor)!
> .getCharacteristic(Characteristic.CurrentTemperature)!
> .on(CharacteristicEventTypes.GET, (callback: NodeCallback<CharacteristicValue>) => {
>     // return our current value
>     callback(null, 38.5);
>   });

Am I doing something wrong?

Thank you very much for helping

**Comment by codyc1515** [comment]
Appears to be an iOS 13 thing, not sure if it’s a bug or not. Have you tried asking Siri to set it with a decimal?

**Comment by kajaba** [comment]
I think that I had these issues also in previous versions of iOS. 
I could ask Siri what is the temperature, but in the code I am setting the temperature manually and somewhere between node Hap server and iOS homekit app (maybe the app has this bug) is this value rounded to whole number (int)

**Comment by jvmahon** [comment]
Just a guess, but try adding
    .setProps({ minStep:0.1})

To your TargetTemperature and CurrentTemperature characteristics.

**Comment by kajaba** [comment]
I think that CurrentTemperature characterist is well configured:
`export class CurrentTemperature extends Characteristic {

  static readonly UUID: string = '00000011-0000-1000-8000-0026BB765291';

  constructor() {
    super('Current Temperature', CurrentTemperature.UUID);
    this.setProps({
      format: Formats.FLOAT,
      unit: Units.CELSIUS,
      maxValue: 100,
      minValue: 0,
      minStep: 0.1,
      perms: [Perms.READ, Perms.NOTIFY]
    });
    this.value = this.getDefaultValue();
  }
}
`

**Comment by SystemKeeper** [comment]
I stumbled across the same issue and I think its because of an explicit integer conversion at https://github.com/KhaosT/HAP-NodeJS/blob/e87f7743c8f42d5f210a6fabf15591567c665b64/src/lib/Characteristic.ts#L528
Looking at older revisions (before moving to TS) it looked like this:
https://github.com/KhaosT/HAP-NodeJS/blob/c11776dc4a145381228ecfadb47dd583977e367d/lib/Characteristic.js#L285

Any idea why this was added? After removing the parseInt() I can set temperatur to 22.5 (22.3 will be displayed as 22.5, but guess thats not a problem of this repo!?)

**Comment by Supereg** [comment]
fixed on current master branch, issue can be closed

**Comment by mhin76** [comment]
> I stumbled across the same issue and I think its because of an explicit integer conversion at
> 
> https://github.com/KhaosT/HAP-NodeJS/blob/e87f7743c8f42d5f210a6fabf15591567c665b64/src/lib/Characteristic.ts#L528
> 
> 
> Looking at older revisions (before moving to TS) it looked like this:
> https://github.com/KhaosT/HAP-NodeJS/blob/c11776dc4a145381228ecfadb47dd583977e367d/lib/Characteristic.js#L285
> 
> Any idea why this was added? After removing the parseInt() I can set temperatur to 22.5 (22.3 will be displayed as 22.5, but guess thats not a problem of this repo!?)

you just solved a mystery I tried to figure out for month!!! Thanks a lot! Now it shows with decimals in iOS home and EVE!!! much appreciate your input!
