### ISSUE TITLE
No decimals in temperatures

### ISSUE THREAD

**Issue by joachimvenaas** [KhaosT/HAP-NodeJS#724]
Hello,

I have used this repo for several years now, made a couple of accessories (AC unit, outlet controlled oven, a couple of wireless temp. sensors). Everytime in Apples Home app, EVE and other apps it always shows ,0 of my temps, even if it says it has a decimal in the console. Anyone have some tips and tricks to help me here?

I have some Philips Hue sensors as well, and those shows decimal values.

**Comment by Shaquu** [comment]
@joachimvenaas did you found solution?

**Comment by joachimvenaas** [comment]
@Shaquu yes. The minStep value was 1
