### ISSUE TITLE
Possible ios13

### ISSUE THREAD

**Issue by triplemikedotcom** [KhaosT/HAP-NodeJS#726]
I would like to preface by saying I don't think there is any issue with the code and most likely just my setup. I have been searching high and low for anyone with a similar issue, but from all of my searching it's just me. Hopefully this will be easy to identify for someone more familiar with the code and how it all works.

I have been running HAP-NodeJS for years now without any issue, and thank you to everyone who made that possible, but after upgrading all of my Apple devices to ios13 I have been getting "No Response" from all of my custom accessories, about 80 in total. When I run in DEBUG mode it looks like the server is just too busy to accept any new connections.

Hopefully this sounds familiar to someone as I am completely stumped, and out of my depth as to what has changed, or what could be causing this. 

From some threads I have read, it was suggested to remove my home from the home app, and re-add all of the accessories, which I have done. It seemed to work for a little while, (approx 15 min) and then back to the same problem, where the server is unreachable due to constant new connections and pair-verify HAP Requests.

Since I never did have any issues prior to the update to ios13, I did not have the need to run debug mode, so I am unfamiliar with what a normal debug would look like.

But here is a short example of my current not-working DEBUG:

EventedHTTPServer [::ffff:192.168.1.127] New connection from client +38ms
EventedHTTPServer [::ffff:192.168.1.127] HTTP server listening on port 43359 +6ms
over and over and then...

EventedHTTPServer [::ffff:192.168.1.127] HTTP connection was closed +5ms
EventedHTTPServer [::ffff:192.168.1.127] HTTP server was closed +4ms
over and over and then...

EventedHTTPServer [::ffff:192.168.1.110] HTTP Response is finished +705ms
EventedHTTPServer [::ffff:192.168.1.119] HTTP request: /pair-verify +5ms
HAPServer [EE:1A:2E:CB:EA:C1] HAP Request: POST /pair-verify +4ms
HAPServer [EE:1A:2E:CB:EA:C1] Pair verify step 1/2 +17ms
over and over..

Any insight will be greatly appreciated.

**Comment by n0rt0nthec4t** [comment]
Funny enough, I've been seeing similar with my own custom accessories on iOS 13.1.3..

**Comment by triplemikedotcom** [comment]
I have found that if I turn off everything ios in my home the server eventually "catches up" and then I am able to start each ios device back up and they work as normal for a period of time and then back to the same issue... I am also using ios13.1.3

**Comment by Supereg** [comment]
Okay, firstly I would not assume that this is an issue with iOS 13, maybe or something in combination. But in order to help you I probably need some more data.

What version of hap-nodejs are you running. Just plain hap-nodejs or are you using for example homebridge?

With your supplied snippet I can't really get much information out of it. A complete log output would be great, where everything is contained. The time when everything works to the point where *something* happens and then nothing works anymore. And then upload the contents of the log output as a file or so.

**Comment by triplemikedotcom** [comment]
It had a pretty good run yesterday. It ran for hours so the log file is massive.

It is hard for me to judge but I think the problem starts around line#206422 
and approx line#254344 I turn of ios devices and it begins to recover and by the end of the log it is "working" again. 

Not 100% sure if I am answering version question properly but I am running plain HAP-NodeJS npm-v5.3.0 and node-v8.5.0-linux-armv6l. 

I also think you are correct that the pair verify step doesn't succeed.

Again, thank you for looking into this. 

[mqttbox.log](https://github.com/KhaosT/HAP-NodeJS/files/3769792/mqttbox.log)

**Comment by Supereg** [comment]
Okay so on first sight it seems that *something* causes the home hub (or whatever device) to be disconnected. Then when the hub tries to reconnect, pair-verify step 1 gets sent and received. It also seems that the response to step 1 gets sent correctly. However something happens that the hub won't send pair-verify step 2 🤔

Could you elaborate what your iDevice setup looks like. What devices are in the network and try to connect and what do you have as HomeKit Hub (Apple TV/HomePod/iPad). And I guess all devices run the latest iOS 13.1.3?
Just to be sure, you have the latest version running of HAP-NodeJS?

Any any guesses how this issue could possibly be reproduced? 😅 

Also it would be great if you could try to capture the log output a second time. However this time with only one accessory enabled, as it gets pretty hard to read if the same request get spammed into the console for multiple accessories. Maybe you could try to run a test instance in parallel with the example light accessory (or something simple like that) running. This makes it easier for you to still have all of your custom accessories running and we can also check that this issue has nothing to do with your current setup. That would be great if you could manage that.

**Comment by triplemikedotcom** [comment]
I think you may be hitting the nail on the head that I am not running the latest version of HAP-NodeJS. I have an, "if it ain't broke don't fix it" motto for updating.

I am going to hit you with some real noob questions now if you don't mind: 
What is the best way to find version and update HAP-NodeJS? 
With everything being typescript now if I update won't I have to re-code my accessories? 

If this is the case I don't have any real issue starting from scratch with the latest version, and re-coding my accessories. Unless I am just completely misunderstanding and there is an easy way to get things up to date.

**Comment by Supereg** [comment]
> What is the best way to find version and update HAP-NodeJS?

If you haven't installed HAP-NodeJS via npm and just cloned it via git (the way this project encourages it) you can just check the latest commit in your local repository:
```
git rev-parse HEAD
```
This will print some seemingly random numbers and characters and is referred to as commit id.
This id would be enough for me to check how outdated your version is.
Opening https://github.com/KhaosT/HAP-NodeJS/commit/<id> while replacing `<id>` with the commit id outputted by the command above opens the commit on GitHub. Or you could search the [Git history](https://github.com/KhaosT/HAP-NodeJS/commits/master) by hand for the give commit id.

> With everything being typescript now if I update won't I have to re-code my accessories?

There should be no need to migrate your existing accessories to typescript. However you will need to adjust some things. Some important information can be found here in this [Migration guide](https://github.com/hassankhan/HAP-NodeJS/blob/code-quality-and-docs/MIGRATION.md) by @hassankhan, which should be merge sometime soon. Additionally you would need to edit the way you start HAP-NodeJS by using the method in the current README or referring to this [README](https://github.com/hassankhan/HAP-NodeJS/blob/code-quality-and-docs/README.md#setting-up-the-project). The second one has probably a way way better startup time, however you would need to execute `npm run build` after each update.


But maybe create a backup of your HAP-NodeJS installation if you attempt to update, so you have something to roll back to if anything doesn't work.

**Comment by Supereg** [comment]
Did you solve your problem?

**Comment by triplemikedotcom** [comment]
I migrated to home assistant. Thanks for the help though.
