### ISSUE TITLE
Contributing to the wiki

### ISSUE THREAD

**Issue by Supereg** [KhaosT/HAP-NodeJS#728]
Currently pretty much every page in the wiki is outdated as hell. Mainly installation instructions, connection setup instructions and some notes in the camera page.

Is there anyway for us to overhaul and contribute to the wiki? AFAIK you can only toggle between "collaborators" or "everybody" for write permission in the GitHub repo settings.

It seems there isn't really a process like Pull Requests for GitHub wikis, but I'm not quite sure 🤔 

Any ideas @KhaosT?

**Comment by Supereg** [comment]
don't want to be pushy, but @KhaosT?

**Comment by NorthernMan54** [comment]
@Supereg I was able to edit pages.

I just added an extra CR to the Home page.  The EDIT button is on right side of the page.  Or am I missing something

**Comment by KhaosT** [comment]
I thought everyone can edit it, is that not the case?

**Comment by Supereg** [comment]
Honestly I didn't expect the wiki to be writeable to everyone and thus also didn't test it myself.
Thanks for the help :)
