### ISSUE TITLE
Code does not comply with 5.6.1 Service and Characteristic Types of the HAP spec

### ISSUE THREAD

**Issue by codyc1515** [KhaosT/HAP-NodeJS#740]
I would fix this, but am not sure how to. In practise, I don't think this breaks anything but it means that we are not compliant with the spec. Relevant extract from the public spec:

### 5.6.1 Service and Characteristic Types
When Apple-defined UUIDs are encoded as JSON strings, a short form must be used by including only the first 8 characters with leading zeros removed. When converting short form UUIDs back to full UUIDs, the process is reversed by prefixing the string with 0 or more '0' characters to expand it to 8 characters then "-0000-1000-8000-0026BB765291" is appended to form the full 36-character UUID.

For example, the public.hap.service.accessory-information full UUID is "0000003E-0000-1000-8000-0026BB765291". When encoded as a JSON string, the first 8 characters are "0000003E" and with leading zeros removed it becomes "3E". Converting back to a full UUID would prefix "3E" with six '0' characters to get "0000003E" then append "-0000-1000-8000-0026BB765291" to form a full UUID of "0000003E-0000-1000-8000-0026BB765291". Other examples:

**Comment by Supereg** [comment]
Is probably to save bandwidth. As the uuids are reassembled on the other side there is probably no change in functionality when changing this.
It is nothing with top priority but we should definitely consider implementing this.
We should ensure though, that third party uuids are still supported by HAP-NodeJS.
Thanks for uncovering this.

**Comment by codyc1515** [comment]
Waiting for #747 to close.
