### ISSUE TITLE
Control Samsung Smart TV

### ISSUE THREAD

**Issue by matthijsotterloo** [KhaosT/HAP-NodeJS#75]
How can I make an accesory to control my Samsung Smart TV?
Can't find out how to do it??? Would be really grateful if someone can help me :D

**Comment by mikegapinski** [comment]
it's not possible with HomeKit

**Comment by matthijsotterloo** [comment]
Why not? There are API's like this https://github.com/natalan/samsung-remote
It must be possible to implement it

**Comment by KhaosT** [comment]
@matthijsotterloo Yep, it's possible, just use that library and replace the appropriate characteristic onUpdate function in accessory.js

**Comment by matthijsotterloo** [comment]
@KhaosT Can you write the code for me? I don't really know how to do it :dancer:
