### ISSUE TITLE
TypeScript Typings and Engine Version Conflict

### ISSUE THREAD

**Issue by RLovelett** [KhaosT/HAP-NodeJS#761]
First of all _THANK YOU_ for converting to TypeScript. 👏  /cc: @hassankhan

With that in mind, I think that there is now a subtle dependency bug in the `package.json` declaration. Possibly even in the documentation/`README.md`.

The `package.json` declares the [`engines`](https://docs.npmjs.com/files/package.json#engines) runtime to be anything _after_ Node 4.3.2 (e.g., `"node": ">=4.3.2"`). This conflicts with the later Node.js typings dependency of `"@types/node": "^12.6.8"`.

Simply put the major version and minor version tagged in the semver string of `@types/node` corresponds to Node's version. For example, [`@types/node` v8](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/node/v8/index.d.ts#L1) and [`@types/node` v12](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/e901b4ff62b35981e5b6d1a4aac3009f6764b358/types/node/index.d.ts#L1).

Such that if someone were to have a dependency on `@types/node` v10 _and_ HAP-NodeJS v0.5.3 they would run into compilation errors about missing types.

<details><summary>Expand: Example with Errors</summary>
<p>

```json
{
  ...
  "devDependencies": {
    "@types/node": "^10.17.9",
    "typescript": "^3.7.3"
  },
  "dependencies": {
    "hap-nodejs": "^0.5.3"
  }
}
```

```text
node_modules/hap-nodejs/dist/lib/Camera.d.ts:2:10 - error TS2305: Module '"child_process"' has no exported member 'ChildProcessWithoutNullStreams'.

2 import { ChildProcessWithoutNullStreams } from 'child_process';
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/hap-nodejs/dist/lib/util/hkdf.d.ts:2:10 - error TS2305: Module '"crypto"' has no exported member 'BinaryLike'.

2 import { BinaryLike } from 'crypto';
           ~~~~~~~~~~

node_modules/hap-nodejs/dist/lib/util/uuid.d.ts:2:10 - error TS2305: Module '"crypto"' has no exported member 'BinaryLike'.

2 import { BinaryLike } from 'crypto';
           ~~~~~~~~~~
```

</p>
</details>

## Suggestions

To fix these discrepancies there seem to be at least two solutions:

1. Roll back `@types/node` to the oldest supported LTS release and update the `engines` section of `package.json` to reflect accordingly. Note: At the time of this message is v8 [though it's end-of-life is ~20 days away](https://github.com/nodejs/Release) so v10 might be better.

2. Leave the typing definition on v12 as it is the current LTS release and update the `engines` section of `package.json` to reflect accordingly.

No doubt there are other suggestions but these seem like the two most pragmatic ones to me. I'm happy to help make these changes. I just want to know what people are amenable to before I submit the changes.

**Comment by Supereg** [comment]
Just to throw it in, I would endorse moving to >=v10.4.0. Bigints are supported there and we would finally have a (native) way of handling 64-bit integers for protocol stuff and reading/writing them from/to buffers 🙃

However I know that most people (running Pis with Raspbian stretch) have currently v8 installed(?).
So at least it would be a good step to move to v8, away from v4.

**Comment by hassankhan** [comment]
Totally agree with @Supereg, would loved to have done it in my PR but was unsure of how much a backlash it would cause with users on older setups.

**Comment by RLovelett** [comment]
> However I know that most people (running Pis with Raspbian stretch) have currently v8 installed(?).
So at least it would be a good step to move to v8, away from v4.

I think that's probably fair. As far as I can tell, [Stretch comes with 4.8.2](https://packages.debian.org/stretch/nodejs). Though if you enable [`stretch-backports` you get 8.11.1](https://packages.debian.org/stretch-backports/nodejs). It's interesting to me that Debian is going to support either of those two versions (v4 or v8) since Node itself is no longer providing patches or security to either. That would imply that Debian is going to do that on their own. I digress.

[Rasbian does seem to be using Buster](https://www.raspberrypi.org/downloads/raspbian/) and that [comes with 10.15.2](https://packages.debian.org/buster/nodejs). Not to mention [NVM](https://github.com/nvm-sh/nvm) (which is what I use on Rasbian) so that you can basically get whatever version you want irrespective of the distribution.

I think my suggestion would be to move to v10. It is the oldest currently supported Node LTS version.

**Comment by Supereg** [comment]
I would propose moving to v10(.4.0) and include instructions to update node to the latest v10 using nvm or whatever(?). Don't know how smooth an upgrade process would be then.
We should be aware of the fact that we mostly deal with people who potential do not know anything about node npm and just want to expand their HomeKit experience.

An opinion from @KhaosT would be great

**Comment by Supereg** [comment]
any news about this?

**Comment by RLovelett** [comment]
As far as I know, no person with authority has weighed in.

I don’t know who the decider is here. Is it @KhaosT? Or does anyone else have authority to merge?

**Comment by KhaosT** [comment]
Sorry about the lack of involvement 😅

I'm down bumping the node requirement to v10 since the library already don't support most of linux distro bundled node anyway. The requirement for v4.x was there because that was a common version back when the last time major changes happened to this library. Node certainly released a lot of major versions since then 😉

Feel free to submit a PR and I'll merge that 🙏

**Comment by RLovelett** [comment]
Submitted pull request #777.
