### ISSUE TITLE
Releases are no longer tagged in git/on GitHub

### ISSUE THREAD

**Issue by meyer** [KhaosT/HAP-NodeJS#762]
I was digging through the releases tab here on GitHub and noticed that v0.4.50 was the last release to be tagged. Was that an intentional change?

**Comment by Shaquu** [comment]
I guess it's omitted because @KhaosT decided that it's useless or he just forgot.
Except the tags there are no releases added too. And these I would like to be here actually as it is a clean way to show changelog and you get notification on Github about new release.

**Comment by KhaosT** [comment]
`npm version x` used to automatically tag things... not sure why it no longer does that. If it provides value, I can do that manually in the future I guess...

**Comment by Supereg** [comment]
What npm version are you using? Since for me everything is fine and I my releases are tagged as usual 🤔
Your sure that you explicitly including the tags in your git push lol?

**Comment by KhaosT** [comment]
@Supereg you're right... I forgot to push the tags 🙈

**Comment by KhaosT** [comment]
Now those tags should be available. In terms of change logs... It's kinda tricky? Normally I'd hope people can just diff two releases and see what are the changes if they really care about that...

**Comment by Shaquu** [comment]
@KhaosT well in most libraries you got release on github and full change log here so I guess people use it :) 
Another thing is that it should require me to read changed code but sometimes commits descriptions are not too good.

**Comment by meyer** [comment]
@KhaosT rad, thank you! for diffing i generally use git tags—that’s actually how i first realised the tags were missing. Example URL: https://github.com/KhaosT/HAP-NodeJS/compare/v0.5.0..v0.5.4
