### ISSUE TITLE
error while npm install

### ISSUE THREAD

**Issue by RBEGamer** [KhaosT/HAP-NodeJS#77]
i can't run the command nom install successfully  the error message is :

make: Leaving directory '/home/pi/homebridge/lib/HAP-NodeJS/node_modules/ed25519/build'
npm ERR! Linux 3.18.0-20-rpi2
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! node v0.12.4
npm ERR! npm  v2.10.1
npm ERR! code ELIFECYCLE

npm ERR! mdns@2.2.9 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the mdns@2.2.9 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the mdns package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls mdns
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/pi/homebridge/lib/HAP-NodeJS/npm-debug.log

gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Linux 3.18.0-20-rpi2
gyp ERR! command "node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/pi/HAP-NodeJS/node_modules/mdns
gyp ERR! node -v v0.12.4
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok 
npm ERR! Linux 3.18.0-20-rpi2
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! node v0.12.4
npm ERR! npm  v2.10.1
npm ERR! code ELIFECYCLE

npm ERR! mdns@2.2.9 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the mdns@2.2.9 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the mdns package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls mdns
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/pi/HAP-NodeJS/npm-debug.log

its on Ubuntu 12 on RPI 2

**Comment by legotheboss** [comment]
try using debian, that is the proven one for RPi...

**Comment by FlyingTom** [comment]
Hi,

I've just received my RPI 2, with Raspbian installed, and I got the same kind of issue when I run "npm install". It seems to be linked to MDNS ...

**Comment by legotheboss** [comment]
@FlyingTom I suggest you install node-gyp without the -g option. I solved it that way on my RPi. 

    sudo npm install node-gyp

Make sure you run this command inside the HAP-NodeJS directory.

**Comment by FlyingTom** [comment]
@legotheboss Thanks but unfortunately it dos not solve the issue...
Here the error I got when I run "npm install" :

> mdns@2.2.9 install /home/pi/HAP-NodeJS/node_modules/mdns
> node-gyp rebuild

make: Entering directory '/home/pi/HAP-NodeJS/node_modules/mdns/build'
  CXX(target) Release/obj.target/dns_sd_bindings/src/dns_sd.o
In file included from ../src/dns_sd.cpp:1:0:
../src/mdns.hpp:32:20: fatal error: dns_sd.h: No such file or directory
compilation terminated.
dns_sd_bindings.target.mk:133: recipe for target 'Release/obj.target/dns_sd_bindings/src/dns_sd.o' failed
make: *** [Release/obj.target/dns_sd_bindings/src/dns_sd.o] Error 1
make: Leaving directory '/home/pi/HAP-NodeJS/node_modules/mdns/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Linux 3.18.7-v7+
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/pi/HAP-NodeJS/node_modules/mdns
gyp ERR! node -v v0.12.4
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok 

> bignum@0.9.2 install /home/pi/HAP-NodeJS/node_modules/srp/node_modules/bignum
> node-gyp configure build

make: Entering directory '/home/pi/HAP-NodeJS/node_modules/srp/node_modules/bignum/build'
  CXX(target) Release/obj.target/bignum/bignum.o
  SOLINK_MODULE(target) Release/obj.target/bignum.node
  SOLINK_MODULE(target) Release/obj.target/bignum.node: Finished
  COPY Release/bignum.node
make: Leaving directory '/home/pi/HAP-NodeJS/node_modules/srp/node_modules/bignum/build'
npm ERR! Linux 3.18.7-v7+
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.4
npm ERR! npm  v2.10.1
npm ERR! code ELIFECYCLE

npm ERR! mdns@2.2.9 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the mdns@2.2.9 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the mdns package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls mdns
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/pi/HAP-NodeJS/npm-debug.log

**Comment by FlyingTom** [comment]
I've fixed the issue by installing a missing package:
sudo apt-get install libavahi-compat-libdnssd-dev

Now I'm able to build the project, but when I start it, I've have the following warnings:
~/HAP-NodeJS $ node BridgedCore.js 
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
HAP-NodeJS starting...
TCP server accepting connection on port: 51826
HAP Server is listening

**Comment by nfarina** [comment]
These particular warnings are "normal" and can be safely ignored. It looks like it's working otherwise?

**Comment by FlyingTom** [comment]
Yes it's working :)

**Comment by cnliri1** [comment]
@FlyingTom .Already installed libavahi-compat-libdnssd-dev but still have the same issue.any suggestion?

make: Entering directory '/home/pi/HAP-NodeJS/node_modules/mdns/build'
CXX(target) Release/obj.target/dns_sd_bindings/src/dns_sd.o
In file included from ../src/dns_sd.cpp:1:0:
../src/mdns.hpp:32:20: fatal error: dns_sd.h: No such file or directory
compilation terminated.

**Comment by chmieludaniel** [comment]
@cnliri1 I am getting the same error, although I installed the deps, any update on that?

**Comment by WebberLai** [comment]
I have the same error message when I try to install mdns

I try 
`npm install node-gyp (without -g )`

not work

`sudo apt-get install libavahi-compat-libdnssd-dev` 

not work

how did you fix this issue ???

**Comment by dariusz** [comment]
i tried:

`sudo apt-get install libavahi-compat-libdnssd-dev`

followed by an explicit:

`sudo npm i -g mdns`

.. and that worked.  mdns is at 2.4.0 as of writing.

**Comment by NorthernMan54** [comment]
@dariusz as of this spring, the mdns dependancy was removed from hap-nodejs.  So on a recent install this would have no impact.
