### ISSUE TITLE
PM2.5 Density Characteristic

### ISSUE THREAD

**Issue by roscoe81** [KhaosT/HAP-NodeJS#775]
Is there any particular reason why "super('PM2.5 Density', PM2_5Density.UUID)" is used in line 1741 of HomeKit.ts, instead of "super('PM2_5 Density', PM2_5Density.UUID"? It appears to be an anomaly compared to all other characteristic naming conventions in HAP-NodeJS and it's triggering a problem with homebridge-mqtt.

**Comment by KhaosT** [comment]
Because the first part is a description, which is `PM2.5`. What is homebridge-mqtt trying to do with this information?

**Comment by roscoe81** [comment]
Thanks for the feedback. The homebridge-mqtt package now has a workaround.
