### ISSUE TITLE
0.4 to 0.5 Upgrade instructions?!

### ISSUE THREAD

**Issue by Apollon77** [KhaosT/HAP-NodeJS#794]
Hi, 

Is 0.4 and 0.5 fully api compatible or what needs to be taken care of when upgrading? Are there any summarized details available?

**Comment by KhaosT** [comment]
It should be fully compatible ^^

**Comment by Apollon77** [comment]
Ok, then I will try and give feedback.

**Comment by Apollon77** [comment]
Thank you for your fast answer
