### ISSUE TITLE
Thermostat ranges in F???

### ISSUE THREAD

**Issue by n0rt0nthec4t** [KhaosT/HAP-NodeJS#795]
One of my accessories developed using the thermostat service, how does one make the ranges appear as "F" rather than "C".

It seems the TargetTemperature/CoolingThreshold/HeatingThreshold etc characteristics are only limited to a max of 38 C, even if change the allowed ranges.

Sure an earlier version of iOS (12??) when you changed the DisplayedTemperatureUnits, HomeKit automatically converted these numbers to between C and F.. At least in iOS 13 (13.3 and 13.4B), doesn't do this.,

**Comment by ebaauw** [comment]
That would be a bug in the Home app.  HAP only deals with °C and it's up to the HomeKit app to convert this to °F.  Did you try another HomeKit app?

The characteristic is called _TemperatureDisplayUnits_.  Did you double-check your code?
https://github.com/KhaosT/HAP-NodeJS/blob/52abfb360f8d65a7ec73ded685db5b8a58d0c2b7/src/lib/gen/HomeKit.ts#L2910

**Comment by n0rt0nthec4t** [comment]
Seems to be the same in EveHome also. Changing the display units to F changes the current temp, but not the ranges. oh well. wondered if anyone had come across this also
