### ISSUE TITLE
version of node-persist vulnerable

### ISSUE THREAD

**Issue by volschin** [KhaosT/HAP-NodeJS#797]
Please fix.
https://app.snyk.io/test/npm/node-persist/0.0.11

Option could be by forking the old version and fixing the dependency to mkdirp.

**Comment by Supereg** [comment]
Does anybody got an analysis if this is actually critical to hap-nodejs/homebridge? I mean plugin developers already have code execution 😅

**Comment by volschin** [comment]
It seems its outdated, its not shown as vulnerable anymore.
