### ISSUE TITLE
Start Verify M1/M3

### ISSUE THREAD

**Issue by connyg** [KhaosT/HAP-NodeJS#8]
I have now 3 devices running, a lamp "window" (Licht Fenster), a lamp "cabinet" (Licht Schrankwand) and a power switch device "espresso machine" (Espressomaschine).
All react to Siri commands, the lamps on "Licht" plus "Fenster" or "Schrankwand", the espresso machine in fact on "Espresso Maschine", very good. Quite nice to say "all devices off" and the two lamps and the espresso machine get switched off one after the other. Fun!

In the first try the window light wouldn't pair, I see that every time a pairing fails if the "Verify M5" is not performed. Then the device is orphaned and doesn't show up in the discovery nor in the device list. I needed to reset HomeKit config, uninstall/reinstall the app, restart the phone etc. to get back to normal.
So the pairing process seems to be a bit fragile, currently can't see any factor influencing the failing of the pairing.

One thing that's disturbing now is that the HAP-NodeJS server would come up with "Start Verify M1" and "Start Verify M3" messages from time to time which take a few 10 seconds to complete. 
During that time the HAP server is little responsive, it would take quite long until a command to a device would be executed or sometimes not at all, Siri saying the device could not be reached.
Attached a part of the log below, don't know if this helps.

HTTP response: 200
{"returnCode": true}
HTTP response: 200
{"returnCode": true}
Change: true
executed accessory: Espressomaschine, and characteristic: power switch, with value: true.
HTTP response: 200
{"returnCode": true}
Change: false
executed accessory: Espressomaschine, and characteristic: power switch, with value: false.
HTTP response: 200
{"returnCode": true}
Change: false
executed accessory: Licht Schrankwand, and characteristic: light service, with value: false.
Change: false
executed accessory: Licht Fenster, and characteristic: light service, with value: false.
Change: false
executed accessory: Espressomaschine, and characteristic: power switch, with value: false.
HTTP response: 200
{"returnCode": true}
HTTP response: 200
{"returnCode": true}
HTTP response: 200
{"returnCode": true}
Server Disconnected
Client Disconnected
Change: true
executed accessory: Licht Schrankwand, and characteristic: light service, with value: true.
Change: true
executed accessory: Licht Fenster, and characteristic: light service, with value: true.
Change: true
executed accessory: Espressomaschine, and characteristic: power switch, with value: true.
HTTP response: 200
{"returnCode": true}
HTTP response: 200
{"returnCode": true}
HTTP response: 200
{"returnCode": true}
New Session 64982
Server Connection Established 39102
Start Verify M1
Start Verify M3
Verify Success
Change: false
executed accessory: Espressomaschine, and characteristic: power switch, with value: false.
HTTP response: 200
{"returnCode": true}
Change: false
executed accessory: Licht Schrankwand, and characteristic: light service, with value: false.
Change: false
executed accessory: Licht Fenster, and characteristic: light service, with value: false.
HTTP response: 200
{"returnCode": true}
HTTP response: 200
{"returnCode": true}
Change: true
executed accessory: Licht Schrankwand, and characteristic: light service, with value: true.
Change: true
executed accessory: Licht Fenster, and characteristic: light service, with value: true.
HTTP response: 200
{"returnCode": true}
HTTP response: 200
{"returnCode": true}
Server Disconnected
Client Disconnected
Server Disconnected
Client Disconnected
New Session 64986
New Session 64987
Server Connection Established 59086
Server Connection Established 34817
Start Verify M1
Start Verify M1
Start Verify M3
Verify Success
Start Verify M3
Verify Success
Server Disconnected
Server Disconnected
Client Disconnected
Client Disconnected
New Session 64991
Server Connection Established 39110
Start Verify M1
New Session 49506
Server Connection Established 59089
Start Verify M1
Start Verify M3
Verify Success
Start Verify M3
Verify Success
Server Disconnected
Server Disconnected
Client Disconnected
Client Disconnected
Server Disconnected
Server Disconnected
Client Disconnected
Client Disconnected
New Session 64992
New Session 64993
Server Connection Established 59091
Server Connection Established 34822
Start Verify M1
Start Verify M1
Start Verify M3
Verify Success
New Session 49510
New Session 49511
Start Verify M3
Verify Success
Server Connection Established 39115
Server Connection Established 34824
Start Verify M1
Start Verify M1
Start Verify M3
Verify Success
Start Verify M3
Verify Success
Server Disconnected
Server Disconnected
Client Disconnected
Client Disconnected
New Session 64997
Server Connection Established 39117
Start Verify M1
Start Verify M3
Verify Success
New Session 49518
Server Connection Established 59096
Start Verify M1
Start Verify M3
Verify Success
Server Disconnected
Client Disconnected
Server Disconnected
Client Disconnected
New Session 65001
Server Connection Established 59097
Start Verify M1
New Session 65002
Server Connection Established 34828
Start Verify M1
Start Verify M3
Verify Success
Start Verify M3
Verify Success
Server Disconnected
Server Disconnected
Client Disconnected
Client Disconnected

**Comment by KhaosT** [comment]
Commit 042203768f should fix this issue :)
