### ISSUE TITLE
Irrigation system service and active characteristic -question

### ISSUE THREAD

**Issue by n0rt0nthec4t** [KhaosT/HAP-NodeJS#803]
Have an irrigation system service with linked valves with bound callbacks to the irrigation system service active characteristic and one for the valve service active characteristic

If I say “hey Siri, turn on/off my irrigation system”, the irrigation system active callback gets triggered Nd I can do things based upon that

If I have the irrigation system in the “off” or inactive state, and I turn a valve to on via HomeKit, the irrigation system active callback gets triggered first, then the valve active callback

What I like to work out, is if my irrigation system callback was triggered by “hey siri”, rather than via the valve getting activated

Thoughts?

**Comment by ebaauw** [comment]
HomeKit probably sends a single message to HAP-NodeJS containing both _Active_ characteristics.  HAP-NodeJS breaks this up into an event per characteristic.  You would need to delay handling the first event (in the irrigation `.on('set')`), by say 20ms, to see if the second event (in the valve `.on('set')`) arrives.  I do something similar in Homebridge Hue, to combine the changes to characteristics of the same light into a single API request to the Hue bridge.  Quite tricky, though.  Make sure to call the `callback` functions passed to the `set` handlers, or the HomeKit app becomes unresponsive.

**Comment by n0rt0nthec4t** [comment]
Ok. gave me some ideas.. Below is what I came up with. Still not sure if just using callback(null) if ii'm not actually going to set the value requested by HomeKit. 
__processActiveCharacteristic(context, value, callback, type) {
        // Allows to process two consecutive active characteristic changes
        // workaround for using hey siri to turn on/off system and valves triggering the same
        this.__activeCheck.push({"context": context, "value": value, "callback": callback, "type": type, "takeaction": false });

        if (this.__activeCheckTimer == null) {
            this.__activeCheckTimer = setTimeout(function() {
                this.__activeCheck.forEach((activeCheck, index) => {
                    // Filter out an active system event followed by a active valve event
                    if (activeCheck.type == "system" && typeof this.__activeCheck[index + 1] == "object" && this.__activeCheck[index + 1].type == "valve") {
                        activeCheck.takeaction = false;  // no acton on this event
                    } else {
                        activeCheck.takeaction = true;  // Take acton on this event
                    }

                    // Process callbacks
                    if ((activeCheck.type == "system" || activeCheck.type == "switch") && activeCheck.takeaction == true) {
                        this.setIrrigationSystemState(activeCheck.value, activeCheck.callback);
                    } else if ((activeCheck.type == "system" || activeCheck.type == "switch") && activeCheck.takeaction == false) {
                        activeCheck.callback(null); // process homekit callback without taking action
                    }
                    if (activeCheck.type == "valve" && activeCheck.takeaction == true) {
                        this.setZoneActive(activeCheck.context, activeCheck.value, activeCheck.callback);
                    } else if (activeCheck.type == "valve" && activeCheck.takeaction == false) {
                        activeCheck.callback(null); // process homekit callback without taking action
                    }
                });

                this.__activeCheck = [];
                this.__activeCheckTimer = null;
            }.bind(this), 100);
        }
    },

**Comment by ebaauw** [comment]
You need to call the callback, or the HomeKit app will remain unresponsive, and Siri will probably timeout, claiming that the accessory doesn’t respond.  Passing `null` indicates success, passing an `Error` causes HomeKit to mark the service in error and Siri to complain the s/he couldn’t do the thing you asked.  I prefer to pass `null` and update the characteristic value a couple of 100 ms later (or on the next poll cycle) instead of passing an `Error`.
