### ISSUE TITLE
Exception when wrong Pin is entered.

### ISSUE THREAD

**Issue by rayzorben** [KhaosT/HAP-NodeJS#88]
Is there a way to have it gracefully handle a bad pin? Right now it just throws an exception and stops execution. Would be nice to have it remove the device from persist and recreate it in this case to make it available for discovery again.

**Comment by maddox** [comment]
Yeah this would be nice. Crashing the app because of fat fingering on the keyboard is rough.

**Comment by rayzorben** [comment]
I hacked a quick workaround, I am not sure if I am returning the correct buffer, or what state it leaves it in. But I was able to type in a bad pin, have it report a 'general error #d'oh" and still allow me to re-add it with the correct pin. In Server.js line 274 at the call to `this.srpServer.checkM1(M1);`

    try {
        this.srpServer.checkM1(M1);
    } catch (error) {
        console.log(err);
        response.write(Buffer([0x07,0x01,0x04]));
        response.end();
        return;
    }
