### ISSUE TITLE
Two messages for non-switch types.

### ISSUE THREAD

**Issue by rayzorben** [KhaosT/HAP-NodeJS#89]
I don't know if this is an Insteon+ issue (the app I am using for testing).

When I create the cTypes, for a fan for example, if I do not put the POWER_STATE_CTYPE then the device fails to add saying that it does not conform to HomeKit specification.

If I put the POWER_STATE_CTYPE and the ROTATION_SPEED_CTYPE then I get two messages when i try to change the fan speed - a POWER_STATE message AND a ROTATION_SPEED message.

Is this expected, and do I simply need to account and somehow ignore one of the two messages - in the case of the fan, I could simply return from the onUpdate method. Just want to know if this is what is recommended.

**Comment by KhaosT** [comment]
It's an issue with Insteon+ app. They made lots of strange decisions on how to update accessory when a change of state happened on the iOS side... (For example: lightbulb, if you turn off the light, they will also write color and brightness chars...)
