### ISSUE TITLE
Allowing HomeKit apps to get device status

### ISSUE THREAD

**Issue by rayzorben** [KhaosT/HAP-NodeJS#90]
Just wanted clarification - by using a HomeKit Bridge such as this, from what I understand there is no way for the application to query the device status. So when I close my app, if my light is on, and then I reopen the app, it has no way of knowing the status of the light. Similarly when I use the switch for my lightbulb to turn it off/on there is no way of having it notify the app that the status has changed?

**Comment by maddox** [comment]
It actually does, as of 40de0e9a32eeff2986495faf78a8018d339cd52b. But the way it's implemented, sort of makes it hard to add your own integrations if you need HAP-NodeJS to query for your devices' status.

Work is happening on #86 to help make that a little better.
