### ISSUE TITLE
onRead not being called.

### ISSUE THREAD

**Issue by rayzorben** [KhaosT/HAP-NodeJS#91]
Added an onRead to my device, and implemented it. I do have a physical device to test with. I have tried light bulbs and ceiling fans, and I simply never see the onRead method being called. I am using Insteon+ app, and also using Siri to test.

**Comment by maddox** [comment]
Could you post what your device code looks like? You can post a gist or the code right inside the thread.

**Comment by rayzorben** [comment]
I am using HomeBridge, but you can see the code in the pull request at https://github.com/nfarina/homebridge/pull/37/files

**Comment by maddox** [comment]
@rayzorben I commented on the actually pull request.

**Comment by snowdd1** [comment]
Please close, as this has been resolved by @rayzorben in https://github.com/nfarina/homebridge/issues/37 . Thanks.
