### ISSUE TITLE
Documentation for accessory attributes?

### ISSUE THREAD

**Issue by stephenyeargin** [KhaosT/HAP-NodeJS#92]
Being fully aware that the DMCA take-down notice occurred, is there a resource that explains in creative metaphors or allegories that may communicate what these attributes actually do (or do not do)? Specifically of interest is the `supportEvents` one.

```
            cType: types.BRIGHTNESS_CTYPE,
            perms: ["pw","pr","ev"],
            format: "int",
            initialValue:  0,
            supportEvents: true,
            supportBonjour: false,
            manfDescription: "<Data>",
            designedMinValue: 0,
            designedMaxValue: 100,
            designedMinStep: 1,
```

**Comment by KhaosT** [comment]
Inside Apple's HomeKit Accessory Simulator (.//Contents/Frameworks/HAPAccessoryKit.framework/Versions/A/Resources/default.metadata.plist) there is a metadata file which includes all the Apple defined services/characteristics and value ranges, type.
