### ISSUE TITLE
no prompt for pin

### ISSUE THREAD

**Issue by salimyzadeh** [KhaosT/HAP-NodeJS#93]
I have installed Domoticz on my pi and am able to access it from the web and have created a dummy device and test lights on the site
latest commit of homekit is also installed on the pi and the config file is set up to point to local address and port 8080

I can see the devices in the insteon+ app however after selecting the device, I never get a pop up to enter the pin and eventually the device times out and i get the following printed to the console

[Domoticz] There was a problem connecting to Domoticz.
An Error Occured on HAP side connection, { [Error: connect ETIMEDOUT] code: 'ETIMEDOUT', errno: 'ETIMEDOUT', syscall: 'connect' }
Server Disconnected

I then tried to run directly through HAP-NodeJS and removed the persist directory and reset the phone configuration but get the same error. I can see the sample devices in the insteon+ app and after tapping "Add anyway," I never get a prompt for the pin
the console shows the following:
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
Parsing accessory: Fan_accessory.js
Parsing accessory: GarageDoorOpener_accessory.js
Parsing accessory: Light_accessory.js
Parsing accessory: Lock_accessory.js
Parsing accessory: Thermostat_accessory.js
HAP-NodeJS starting...
Cannot find secret key, creating One...
TCP server accepting connection on port: 51826
HAP Server is listening
Cannot find secret key, creating One...
TCP server accepting connection on port: 51828
HAP Server is listening
Cannot find secret key, creating One...
TCP server accepting connection on port: 51832
HAP Server is listening
Cannot find secret key, creating One...
TCP server accepting connection on port: 51838
HAP Server is listening
Cannot find secret key, creating One...
TCP server accepting connection on port: 51846
HAP Server is listening
New Session 49202
Client Disconnected
An Error Occured on HAP side connection, { [Error: connect ETIMEDOUT] code: 'ETIMEDOUT', errno: 'ETIMEDOUT', syscall: 'connect' }
Server Disconnected

**Comment by legotheboss** [comment]
@salimyzadeh use the app suggested in the wiki, not the Insteon app.

**Comment by salimyzadeh** [comment]
after starting from scratch i now have everything working
looks like best way to install node is:
apt-get update
apt-get install git-core libnss-mdns libavahi-compat-libdnssd-dev -y
wget http://node-arm.herokuapp.com/node_latest_armhf.deb
dpkg -i node_latest_armhf.deb

thanks
