### ISSUE TITLE
WINDOW_COVERING

### ISSUE THREAD

**Issue by h-teske** [KhaosT/HAP-NodeJS#98]
In the accessory types I saw a variable for window covering (WINDOW_COVERING_TARGET_POSITION_CTYPE). 

Does anybody have an example how to use this to control window blinds? I'd love to not only open & close the blinds but also set them to a specific level (e.g. 50%)

Many thanks in advance!

**Comment by hplato** [comment]
I'm also really interested in this, in fact the blind control is the reason I'm trying to get this whole thing working!

**Comment by KhaosT** [comment]
Just create a new characteristic with this type and in the future it should work with iOS 9 :)

**Comment by hplato** [comment]
So I tried, but get an object that doesn't appear to be controlled (as least from the insteon+ app I'm using for testing). Any ideas?

getServices: function() {
    var that = this;
    return [{
      sType: types.ACCESSORY_INFORMATION_STYPE,
      characteristics: [{
        cType: types.NAME_CTYPE,
        onUpdate: null,
        perms: ["pr"],
        format: "string",
        initialValue: this.name,
        supportEvents: false,
        supportBonjour: false,
        manfDescription: "Name of the accessory",
        designedMaxLength: 255
      },{
        cType: types.MANUFACTURER_CTYPE,
        onUpdate: null,
        perms: ["pr"],
        format: "string",
        initialValue: "Http",
        supportEvents: false,
        supportBonjour: false,
        manfDescription: "Manufacturer",
        designedMaxLength: 255
      },{
        cType: types.MODEL_CTYPE,
        onUpdate: null,
        perms: ["pr"],
        format: "string",
        initialValue: "Rev-1",
        supportEvents: false,
        supportBonjour: false,
        manfDescription: "Model",
        designedMaxLength: 255
      },{
        cType: types.SERIAL_NUMBER_CTYPE,
        onUpdate: null,
        perms: ["pr"],
        format: "string",
        initialValue: "A1S2NASF88EW",
        supportEvents: false,
        supportBonjour: false,
        manfDescription: "SN",
        designedMaxLength: 255
      },{
        cType: types.IDENTIFY_CTYPE,
        onUpdate: null,
        perms: ["pw"],
        format: "bool",
        initialValue: false,
        supportEvents: false,
        supportBonjour: false,
        manfDescription: "Identify Accessory",
        designedMaxLength: 1
      }]
    },{
      sType: types.WINDOW_COVERING_STYPE,
      characteristics: [{
        cType: types.NAME_CTYPE,
        onUpdate: null,
        perms: ["pr"],
        format: "string",
        initialValue: this.name,
        supportEvents: true,
        supportBonjour: false,
        manfDescription: "Name of service",
        designedMaxLength: 255
      },{
        cType: types.WINDOW_COVERING_TARGET_POSITION_CTYPE,
        onUpdate: function(value) { console.log("value="+value); },
        perms: ["pw","pr","ev"],
        format: "int",
        initialValue: 0,
        supportEvents: false,
        supportBonjour: false,
        manfDescription: "Change the position",
        designedMaxLength:1 
      }]
    }];
  }

**Comment by bezzers** [comment]
I believe this will only work once we have ios9.

**Comment by bgottsch** [comment]
@hplato I have iOS 9 and tried this code. It doesn't work because it's incomplete. You have to put all the required characteristics for the Window Covering service. I don't know if it will work with iOS 8, but for iOS 9 this is my implementation and it works with the HMCatalog App provided by Apple:

```
// HomeKit types required
var types = require("./types.js")
var exports = module.exports = {};

var name = "Micro Blind"
var serviceName = "Blind"
var username = "1A:2B:3C:4D:5E:FP"
var manufacturer = "Insteon"
var model = "Micro Blind"
var serialNum = "A1S2NABB88EW"
var pincode = "031-45-154"

exports.accessory = {
  displayName: name,
  username: username,
  pincode: pincode,
  services: [{
	sType: types.ACCESSORY_INFORMATION_STYPE,
	characteristics: [{
		cType: types.NAME_CTYPE,
		onUpdate: null,
		perms: ["pr"],
		format: "string",
		initialValue: name,
		supportEvents: false,
		supportBonjour: false,
		manfDescription: "Name",
		designedMaxLength: 255
	},{
		cType: types.MANUFACTURER_CTYPE,
		onUpdate: null,
		perms: ["pr"],
		format: "string",
		initialValue: manufacturer,
		supportEvents: false,
		supportBonjour: false,
		manfDescription: "Manufacturer",
		designedMaxLength: 255
	},{
		cType: types.MODEL_CTYPE,
		onUpdate: null,
		perms: ["pr"],
		format: "string",
		initialValue: model,
		supportEvents: false,
		supportBonjour: false,
		manfDescription: "Model",
		designedMaxLength: 255
	},{
		cType: types.SERIAL_NUMBER_CTYPE,
		onUpdate: null,
		perms: ["pr"],
		format: "string",
		initialValue: serialNum,
		supportEvents: false,
		supportBonjour: false,
		manfDescription: "Serial Number",
		designedMaxLength: 255
	},{
		cType: types.IDENTIFY_CTYPE,
		onUpdate: null,
		perms: ["pw"],
		format: "bool",
		initialValue: false,
		supportEvents: false,
		supportBonjour: false,
		manfDescription: "Identify Accessory",
		designedMaxLength: 1
    }]
    },{
    sType: types.WINDOW_COVERING_STYPE,
    characteristics: [{
    	cType: types.NAME_CTYPE,
        onUpdate: null,
        perms: ["pr"],
        format: "string",
        initialValue: serviceName,
        supportEvents: false,
        supportBonjour: false,
        manfDescription: "Service Name",
        designedMaxLength: 255   
    },{
    	cType: types.WINDOW_COVERING_CURRENT_POSITION_CTYPE,
    	onUpdate: null,
    	perms: ["pr"],
    	format: "int",
      	initialValue: false,
      	supportEvents: false,
      	supportBonjour: false,
      	manfDescription: "Window cover current position",
      	designedMinValue: 0,
      	designedMaxValue: 100,
      	unit: "%"
    },{
    	cType: types.WINDOW_COVERING_TARGET_POSITION_CTYPE,
    	onUpdate: function(value) { console.log(name + "- Change:", value); },
    	perms: ["pw","pr","ev"],
    	format: "int",
      	initialValue: false,
      	supportEvents: false,
      	supportBonjour: false,
      	manfDescription: "Window cover target position",
      	designedMinValue: 0,
      	designedMaxValue: 100,
      	designedMinStep: 1,
      	unit: "%"
    },{
    	cType: types.WINDOW_COVERING_OPERATION_STATE_CTYPE,
    	onUpdate: null,
    	perms: ["pr"],
    	format: "int",
      	initialValue: false,
      	supportEvents: false,
      	supportBonjour: false,
      	manfDescription: "Window cover operation state",
      	designedMinValue: 0,
      	designedMaxValue: 100,
      	unit: "%"
    }]
  }]	
}
```

**Comment by cflurin** [comment]
@bgottsch: are you able to use the control  [-|+] on your iOS 9 device?

I tried with the HM Simulator and IOS 8.4.1 and this works using EVE App.
But with homebridge the control is grayed out.
Here is the example: FhemWindowCovering  https://github.com/cflurin/homebridge-shims

**Comment by bgottsch** [comment]
@cflurin I did not test on a version lower than iOS 9 so I don't know if it's compatible. Try to create a new accessory from my code just to see if it works with a version lower than 9. If it doesn't work, than the problem might be with iOS 8.

And yes, I am able to control the targetPosition characteristic from my iOS device in the HMCatalog App

**Comment by cflurin** [comment]
Okey thanks, I'll wait until next week (iOS 9).
